### ISSUE TITLE
`python super_universe` `n_v1_var_used` missing semicolon

### ISSUE THREAD

**Issue by ken-lauer** [bmad-sim/bmad-ecosystem#1019]
https://github.com/bmad-sim/bmad-ecosystem/blob/c1ebe6a1b64c0ea2d71de0858e2f59fee26e4020/tao/code/tao_python_cmd.f90#L7202

It's missing the final trailing semicolon which delimits the field information from the value.
(PR incoming)

**Comment by DavidSagan** [comment]
Will be fixed in next PR merge shortly.
