### ISSUE TITLE
Tao `python var {var} slaves` format incorrect

### ISSUE THREAD

**Issue by ken-lauer** [bmad-sim/bmad-ecosystem#1022]
https://github.com/bmad-sim/bmad-ecosystem/blob/f15df5bd7c8c640e1c9fc863e653798abeaf1005/tao/code/tao_python_cmd.f90#L7403

As-is, this always requests the `slaves` option in `pytao`.
This should read: `python var {var} {slaves}` such that `slaves` is an optional parameter.

**Comment by DavidSagan** [comment]
Fixed.

**Comment by ken-lauer** [comment]
Will the changes be reflected in `tao/doc/python-interface-commands.json` as well?

**Comment by DavidSagan** [comment]
Will be with PR merge later today.
