### ISSUE TITLE
`python ele:photon` regression test example causes Fortran runtime error

### ISSUE THREAD

**Issue by ken-lauer** [bmad-sim/bmad-ecosystem#1026]
Bmad version: `20240626.0` (installed via conda)

```
$ git log --oneline  |head -n 1
a97ab293b Minor doc correction. (#1024)

$ tao -init regression_tests/python_test/tao.init_photon
[MESSAGE | 2024-JUN-27 09:52:59] tao_init:
    OpenMP active with number of threads: 12
[MESSAGE | 2024-JUN-27 09:52:59] bmad_parser:
    Lattice parse time(min): 0.00

Tao> python ele:photon 1@0>>1|model base
At line 3556 of file /Users/runner/miniforge3/conda-bld/bmad_1719472715899/work/tao/code/tao_python_cmd.f90
Fortran runtime error: Index '-999' of dimension 1 of array 'surface_grid_type_name' below lower bound of 0
```

Source code line:
https://github.com/bmad-sim/bmad-ecosystem/blob/a97ab293bea0b0db9bdfd64ff26c26afabafcf55/tao/code/tao_python_cmd.f90?plain=1#L3556

Example:
https://github.com/bmad-sim/bmad-ecosystem/blob/a97ab293bea0b0db9bdfd64ff26c26afabafcf55/tao/code/tao_python_cmd.f90?plain=1#L3533-L3538

**Comment by DavidSagan** [comment]
Fixed.

**Comment by ken-lauer** [comment]
Thanks to the fix it no longer segfaults - but is the type annotation correct here?

The output is:
```
grid#type;LOGIC;F;Not_set
```

`LOGIC` should give `T` and `F` values and not one of `'Segmented', 'H_Misalign', 'Displacement', 'Not_set'`, right?

**Comment by DavidSagan** [comment]
Yes this should be ENUM. The fix will be in the next PR merge soon.
