### ISSUE TITLE
segment fault from util_program/generalized_gradient_fit

### ISSUE THREAD

**Issue by jinhyukchoi** [bmad-sim/bmad-ecosystem#1028]
I'm using the Intel Mac.
Commenting-out line 457 of gg_fit_mod.f90 (`zero_vec = 0`) resolved the memory issue.
It looks like, because `zero_vec` is assigned before it is allocated.
I'm not sure the simple commenting-out can be the correct solution.
Could you please check it?
Thanks.

**Comment by DavidSagan** [comment]
@jinhyukchoi The fix was moving the set of zero_vec to after the allocation. The revised code has been put in the repo. Thanks for reporting this.
