### ISSUE TITLE
mad8 to bmad translator bugs

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1030]
Jorg pointed out two things yesterday in the ESR meeting:
1. Any time "energy" is seen, its value is multiplied by 10^9. This is only correct when defining a BEAM, but incorrect where someone uses the word "energy" as a variable in the lattice file
2. Things that cannot be translated should just be ignored, rather than bombing the translation script

**Comment by DavidSagan** [comment]
@mattsignorelli 
1. I don't understand this. Can you give me an example?
2. Things that are not recognized are just passed through and should not bomb the translation script. Can you give me an example here?

**Comment by DavidSagan** [comment]
Fixed.
