### ISSUE TITLE
ltt%split_bends_for_stochastic_rad = T gives different emittance when ramping compared to ltt%split_bends_for_stochastic_rad = F

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#1040]
[ramp_example.zip](https://github.com/user-attachments/files/16089393/ramp_example.zip)

**Comment by DavidSagan** [comment]
@henrylovelace3 Is the emittance different when not ramping and just using the lattice at the end of the ramp?

**Comment by henrylovelace3** [comment]
Slightly, the equilibrium emittance hovers around 25 nm. The natural emittance is 21 nm.

**Comment by DavidSagan** [comment]
Problem is that split_bends_for_stochastic_rad = T was never meant to be used with ramping. I will put in checking to prevent this from happening. The checking will be in the next release.
