### ISSUE TITLE
`python beam` `track_beam_in_universe` marked as settable (`can_vary=T`)

### ISSUE THREAD

**Issue by ken-lauer** [bmad-sim/bmad-ecosystem#1045]
## Context

`python beam` `track_beam_in_universe` is marked as `can_vary`:
https://github.com/bmad-sim/bmad-ecosystem/blob/6d08b6712edb37164579a6ac1e9a7335368563ad/tao/code/tao_python_cmd.f90?plain=1#L330

However, `set beam track_beam_in_universe = True` fails with:

```
ERROR detected: [ERROR | 2024-JUL-08 13:28:16] tao_set_beam_cmd:
      PARAMETER NOT RECOGNIZED: track_beam_in_univer
      [DID YOU WANT "SET BEAM_INIT" INSTEAD OF "SET BEAM"?]
```

**Comment by DavidSagan** [comment]
Fixed.
