### ISSUE TITLE
request a minor correction in elegant_to_bmad

### ISSUE THREAD

**Issue by jinhyukchoi** [bmad-sim/bmad-ecosystem#1053]
util_programs/elegant_to_bmad.py converts elegant's **malign** to bmad's **gkicker**. Here the attributes, **dx**, **dy**, ... are converted to **x_offset**, **y_offset**, ..., but they should be converted to **x_kick**, **y_kick**, ... .

**Comment by DavidSagan** [comment]
Fixed.
