### ISSUE TITLE
Potential bug with Bmad BBU program. Bmad BBU fails at high-Q values (Q>10^5).

### ISSUE THREAD

**Issue by sadik82** [bmad-sim/bmad-ecosystem#1054]
I am benchmarking Bmad BBU program against analytical model and my own MATLAB based BBU tracking code. I used the example given in the Bmad "oneturn_lat.bmad". I am comparing the threshold current of the three models. I estimated threshold current (Ith) for a range of quality factors Q and plotting "Ith vs Q". The Q ranges from 10^3 to 10^7. Three model agree well in the range Q = 10^3 - 10^5. In the range Q = 10^5 - 10^7, the analytical and MATLAB BBU code agree with each other, but Bmad starts to disagree. As Q increases, the Ith decrease in Bmad is much less compared to other two models (almost stop decreases).
![1_Analytical_vs_Bmad_vs_MATLAB_VaryQL_RQBmad1e6](https://github.com/bmad-sim/bmad-ecosystem/assets/42129421/dae10aca-ca83-4639-ba1e-d9ee1babde5b)

**Comment by DavidSagan** [comment]
@sadik82 I suspect there might be a round-off problem in the code. In any case, please attach your input files so I can test.

**Comment by sadik82** [comment]
I have attached input files.
[bbu_benchmark.zip](https://github.com/user-attachments/files/16195656/bbu_benchmark.zip)


Lattice file: oneturn_lat_v5.bmad
HOM input file: vhoms_Bmad_cavity_1.TXT
To do QL scan, edit "vhoms_Bmad_cavity_1.TXT".

Need to change the line 13 in "test_run.py"
Code can be run by: ./test_run.py 1 1 output_dir1

**Comment by DavidSagan** [comment]
@sadik82 Did you test that the setting for simulation_turns_max was high enough at the larger Qs to give accurate results?

**Comment by sadik82** [comment]
> @sadik82 Did you test that the setting for simulation_turns_max was high enough at the larger Qs to give accurate results?

@DavidSagan I set it to 30:
 'simulation_turns_max': 30,

**Comment by DavidSagan** [comment]
That sounds very low. Do you get better results if you set this much higher?

**Comment by sadik82** [comment]
@DavidSagan Yes, I did  get much better results. I tried with much higher 'simulation_turns_max':
'simulation_turns_max': 300
'simulation_turns_max': 3000

These yielded results that are very close to the analytical and MATLAB tracking models. 

Thanks a lot.

**Comment by DavidSagan** [comment]
I am assuming that there are no further issues here.

**Comment by sadik82** [comment]
Yes.
