### ISSUE TITLE
Strange behavior in optimization with multiple universes

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1064]
I am using multiple universes in order to calculate numerical derivatives for higher order chromaticity. I have a setup file that changes pz in each universe and then in the init file the tunes of these lattices are entered into a numerical derivative. If I do not use the setup file, all of these derivatives should be zero, they are not. It also appears that the optimizer does not know what to do with these. It is possible they do not get updated.
[multi_uni_opt.zip](https://github.com/user-attachments/files/16241358/multi_uni_opt.zip)

**Comment by jeu8** [comment]
This worked a while ago when I tried it. I initially had done this in march of this year

**Comment by DavidSagan** [comment]
@jeu8 I am getting the error:
```
ERROR IN bmad_parser: UNABLE TO OPEN FILE: /nfs/acc/user/dcs16/linux_lib/test_unger/wigg1.cartesian_map
     THIS FROM THE LOGICAL FILE NAME: wigg1.cartesian_map
      IN FILE: /nfs/acc/user/dcs16/linux_lib/test_unger/cooler_new_wig_fixed_phase_reduced_beta.bmad
      AT OR BEFORE LINE: 100
```

Also we should zoom so you can explain this problem in more detail.

**Comment by jeu8** [comment]
here are the missing files
[wiggler.zip](https://github.com/user-attachments/files/16258468/wiggler.zip)

**Comment by jeu8** [comment]
The missing files are up. I would be free for a zoom wednesday morning

**Comment by DavidSagan** [comment]
I looked at that datum 5@fourth[1] and the nonzero value was due to round-off.

**Comment by DavidSagan** [comment]
`show der` only showing universe 1?

**Comment by DavidSagan** [comment]
And fixed showing only universe 1 (will be in next PR merge).
