### ISSUE TITLE
`python floor_plan` does not work with `-noplot`

### ISSUE THREAD

**Issue by ken-lauer** [bmad-sim/bmad-ecosystem#1068]
A follow-up to https://github.com/bmad-sim/bmad-ecosystem/issues/1057 (in particular, [this comment](https://github.com/bmad-sim/bmad-ecosystem/issues/1057#issuecomment-2231178872)).

`python floor_plan` does not currently work with `-noplot`. This is important for applications which interact with tao using with `-external_plotting`. To see this, use the simple regression test `init` files:

```
$ tao -init $ACC_ROOT_DIR/regression_tests/python_test/tao.init_wall -external_plotting -noplot
Tao> place -no_buffer r12 floor_plan

Tao> python floor_plan r12.g
[ERROR | 2024-JUL-16 08:03:43] tao_python_cmd:
    "python floor_plan r12.g": Floor plan drawing not yet setup for this graph.
```

Noting that the `-no_buffer` is required while in `-external_plotting` mode. It's not technically required to reproduce this issue, though (`tao -init $ACC_ROOT_DIR/regression_tests/python_test/tao.init_wall -noplot` and `python floor_plan r12.g` will suffice)

@DavidSagan indicated that this is a bug, since this method should work for all supported plot types. The required change will be to have Tao calculate the floor plan [plotting setup](https://github.com/bmad-sim/bmad-ecosystem/issues/1057#issuecomment-2231904873), even in `-noplot` mode. I haven't determined why just the floor plan plot initialization is skipped, but I hope it won't be difficult to find.

**Comment by DavidSagan** [comment]
I put in a fix.
