### ISSUE TITLE
Tao crashes when using cut command to close the lattice

### ISSUE THREAD

**Issue by ndwang** [bmad-sim/bmad-ecosystem#1073]
I'm trying to put in quadrupole misalignment in a ring and correct the orbit. Tao crashes with message `** On entry to DGEBAL parameter number  3 had an illegal value` after using cut command to close the lattice.
Steps to reproduce the crash:
1. tao -lat close.bmad
2. cut
3. set ele quadrupole::* x_offset = 1e-4*ran_gauss(3)
4. run (You can end the optimization after a few steps. No need to wait for it to finish)
5. cut

[cut_crash.zip](https://github.com/user-attachments/files/16314793/cut_crash.zip)

**Comment by DavidSagan** [comment]
Fixed. Problem was the optimizer taking a gigantic step and Bmad not detecting the issue.
