### ISSUE TITLE
`python spin_resonance` `n0` type incorrect (`REAL` -> `REAL_ARR`)

### ISSUE THREAD

**Issue by ken-lauer** [bmad-sim/bmad-ecosystem#1077]
https://github.com/bmad-sim/bmad-ecosystem/blob/009c19fcd2cf9bd70889c43b14cff41870693f48/tao/code/tao_python_cmd.f90#L7165

* Marked as `REAL` (scalar)
* It has 3 floating point values, indicating it should be `REAL_ARR` instead

**Comment by DavidSagan** [comment]
Fixed. Thanks for reporting this.
