### ISSUE TITLE
Aperture_type and Aperture_at of superimposed elements not in sync

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#1080]
A pipe has aperture_type set to elliptical and aperture_at set to continuous.
When a quad is superimposed onto the pipe, the aperture_type is shown to be rectangular.
When a hkicker or vkicker (with non-zero length) is superimposed onto the quad, the aperture_at is shown to be no_aperture.

Hopefully this is a visual bug which does not affect actual beam tracking...   

To test, please proceed with the attached zip folder.
Thanks.

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/bc4b9335-5d87-4041-8b75-f9ea203af138">

[aperture_test.zip](https://github.com/user-attachments/files/16381973/aperture_test.zip)

**Comment by weiyuanlou** [comment]
[aperture_test.zip](https://github.com/user-attachments/files/16382047/aperture_test.zip)

**Comment by DavidSagan** [comment]
Now the aperture_at and aperture_type will be set to `lord_defined`.
