### ISSUE TITLE
Unexpected behavior when changing tracking_method of a multipass cavity

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#1082]
A lattice is made with one "multi-pass cavity" which has two passes.
When setting the "tracking_method" of the cavity lord to 'range_kutta', the tracking_method of the two multi-pass slaves do NOT change respectively. The same thing happens when attempting to set tracking_method of one of the slaves; only the lord sees the change. 

Hopefully this is a visual bug which does not affect the actual tracking...

To test, use the attached zip file.

Thanks.

<img width="678" alt="image" src="https://github.com/user-attachments/assets/0cca2475-8afd-4827-a55e-05bba5b4d5c9">

[cavity_test.zip](https://github.com/user-attachments/files/16383935/cavity_test.zip)

**Comment by DavidSagan** [comment]
Fixed.
