### ISSUE TITLE
show track doesn't show collision point between particle and strong beam slice in beambeam element

### ISSUE THREAD

**Issue by RevanEoot** [bmad-sim/bmad-ecosystem#1090]
The "show track" command does not show the collision point between the tracked particle and the slice of the strong beam. Instead, it just shows the phase space coordinates of the particle as unchanged (see attached image). It would also be helpful if show track could display the longitudinal velocity of the particle.

<img width="1076" alt="image" src="https://github.com/user-attachments/assets/e5bdf5d8-f033-4595-8be0-5a1cdc5b22e7">

Lattice file used:
[lat.bmad.zip](https://github.com/user-attachments/files/16400934/lat.bmad.zip)

**Comment by DavidSagan** [comment]
Delay due to Bmad Workshop. I will get to this soon.

**Comment by DavidSagan** [comment]
@RevanEoot To see the the track through the beambeam element use the `-element` option (see the Tao manual for details). I will work on adding the longitudinal velocity.
