### ISSUE TITLE
Tao Show Command Order Problem

### ISSUE THREAD

**Issue by noahjosephwilson** [bmad-sim/bmad-ecosystem#1092]
When the attribute flag is written in this way it produces a different output than expected. This is with the fodoAF0.bmad lattice in the directory bmad-ecosystem/bmad-doc/tutorial_ring_design/lattices/1_FODO/a_Arc: 

`show lat −attrib k1 quadrupole ::*`

**Comment by DavidSagan** [comment]
@noahjosephwilson Very strange. I am not able to reproduce so unfortunately I cannot fix.
