### ISSUE TITLE
Tao: Default n_curve_pts should default to maximum based on number of pixels in plot page

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1101]

**Comment by DavidSagan** [comment]
Thought: Time the plotting calculation and if it takes too much time print a message (say 2 seconds). Do this only once except if the time is very long (say 10 seconds), do it every time. Also have a switch to turn this message off.

**Comment by DavidSagan** [comment]
It is not the number of pixels that matter it is the highest frequency in the curves (think Nyquist criterion). In any case, I put in a plot timer with a default setting of 5 seconds and if plotting exceeds this a message is printed alerting the user to possibly reduce the number of curve points. I also increased the default number of plot points to 4001. This value can be reconsidered after we gain some experience with the new setup.
