### ISSUE TITLE
LTT: beam_init Fortran runtime error: Cannot match namelist object name %file_name

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1105]
Run long_term_tracking with attached

[bug2.zip](https://github.com/user-attachments/files/16445276/bug2.zip)

**Comment by mattsignorelli** [comment]
Looks like this was changed to position_file but no update in the manual? Also shouldn't there be something to maintain backwards compatibility?

**Comment by DavidSagan** [comment]
LTT will now generate an appropriate error message.
