### ISSUE TITLE
"mrad" is a bad name for the units of px, py pz in `show ele` output

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#1109]
Suggestion: Use `milli` instead.

**Comment by mattsignorelli** [comment]
Why is this bad?

**Comment by DavidSagan** [comment]
It suggests that px, py and pz are angles which they are not.

**Comment by mattsignorelli** [comment]
Makes sense. I'm not sure `milli` is informative enough though?

**Comment by DavidSagan** [comment]
Suggestions for a better name? EG "10^-3" ?

**Comment by DavidSagan** [comment]
Settled on "1E-3"
