### ISSUE TITLE
long_term_tracking segfaults with ramping on

### ISSUE THREAD

**Issue by ndwang** [bmad-sim/bmad-ecosystem#1120]
@WillBergan and I discovered a segfault when running long_term_tracking with the lattice and initialization file in bmad-doc/tutorial_ring_design/lattices/15_SpinTracking/solution. The seg fault only occurs if `ltt%ramping_on = T` and `ltt%ram_update_each_particle = T`.

I ran it through Totalview. The issue is that, when lattice_bookkeeper parses the lattice, it calls ltt_track1_preprocess and attempts to apply rampers, but ltt_com%tracking_lat is not set up yet at that point.

**Comment by DavidSagan** [comment]
@WillBergan @ndwang Correct. I put in a line in the code to detect this. I also altered the code logic so that `ltt%ramp_update_each_particle` is only looked at for BEAM tracking. That is, you do not have to remember setting it for SINGLE or any other modes.
