### ISSUE TITLE
Tao: Silence Mode Flip Warnings During Optimization

### ISSUE THREAD

**Issue by electronsandstuff** [bmad-sim/bmad-ecosystem#1125]
I was asked to post here from the Bmad slack channel:

When running an optimization on a lattice with coupling, I get a large number of mode flip warnings which block out the information being reported from the optimizer. It would be nice to silence them after the first warning or have some sort of flag to turn them off.

![image](https://github.com/user-attachments/assets/9962486a-4eb8-4efb-912d-aa90eb095372)

**Comment by DavidSagan** [comment]
@electronsandstuff Can you provide an example I can use for testing? Thanks.

**Comment by electronsandstuff** [comment]
Sure thing. This example should do it if you execute `run` after loading.

[bmad_mode_flip_optimization.zip](https://github.com/user-attachments/files/16641405/bmad_mode_flip_optimization.zip)

**Comment by DavidSagan** [comment]
Fixed.
