### ISSUE TITLE
Add spin kick to phase trombones

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1134]
Phase trombones currently do nothing to the spin. This can be an issue when spin tracking, where for every x'' there should be an equivalent (1+a*gamma)*x'' (assuming fully perpendicular fields to first order)

**Comment by DavidSagan** [comment]
@mattsignorelli Is `x"` something the user sets?

**Comment by mattsignorelli** [comment]
No, that comes from the transfer matrix

We should meet to discuss the details because we will have to make some assumptions about the spin/orbital dynamics. we have to basically get the spin dynamics from a generic orbital transfer matrix

**Comment by DavidSagan** [comment]
@mattsignorelli I have implemented spin tracking with can be turned on by setting
```
mm: match, spin_tracking_model = transverse_fields, ...
```
Please check one point to verify that everything is OK.

**Comment by DavidSagan** [comment]
@mattsignorelli I will close this for now. Please reopen if you find a problem.
