### ISSUE TITLE
"show spin" in Tao produces 0 ST Polarization for all cases

### ISSUE THREAD

**Issue by ErisW** [bmad-sim/bmad-ecosystem#1137]
I am currently using the latest distribution (20240809-0) and have noticed an issue with the "show spin" functionality. When I run any of my previously working cases, it consistently shows 0 ST polarization using the latest distribution. The attached picture is the result using the clean FCC lattice.
![Screenshot 2024-08-12 204151](https://github.com/user-attachments/assets/3e8ed686-76d3-4c60-a83f-73b02cea9b45)
and the lattice file attached for examination. 
[lat_knob.zip](https://github.com/user-attachments/files/16591166/lat_knob.zip)

Thank you so much!

**Comment by DavidSagan** [comment]
Fixed.
