### ISSUE TITLE
Tao Giving Non-Informative Error Message

### ISSUE THREAD

**Issue by noahjosephwilson** [bmad-sim/bmad-ecosystem#1139]
This is the error that I get when I run Tao on my lattice file: (rayenv) $ tao -lat simple_ring.bmad -noplot
[MESSAGE | 2024-AUG-13 16:31:24] tao_init:
    OpenMP active with number of threads: 32
[ERROR | 2024-AUG-13 16:31:24] super_gaussj:
    SINGULAR MATRIX! (2)
[ERROR | 2024-AUG-13 16:31:24] super_mrqmin:
    Note: Generally a singular matrix means that one or more datum values are
    not affected by any variation of any variable.
[ERROR | 2024-AUG-13 16:31:24] super_gaussj:
    SINGULAR MATRIX! (2)
[ERROR | 2024-AUG-13 16:31:24] super_mrqmin:
    Note: Generally a singular matrix means that one or more datum values are
    not affected by any variation of any variable.
[ERROR | 2024-AUG-13 16:31:24] super_gaussj:
    SINGULAR MATRIX! (2)
[ERROR | 2024-AUG-13 16:31:24] super_mrqmin:
    Note: Generally a singular matrix means that one or more datum values are
    not affected by any variation of any variable.
[ERROR | 2024-AUG-13 16:31:24] closed_orbit_calc:
    SINGULAR MATRIX ENCOUNTERED!
    TRACKING BRANCH: 0:LAT
[ERROR | 2024-AUG-13 16:31:24] super_gaussj:
    SINGULAR MATRIX! (2)
[ERROR | 2024-AUG-13 16:31:24] super_mrqmin:
    Note: Generally a singular matrix means that one or more datum values are
    not affected by any variation of any variable.
[ERROR | 2024-AUG-13 16:31:24] super_gaussj:
    SINGULAR MATRIX! (2)
[ERROR | 2024-AUG-13 16:31:24] super_mrqmin:
    Note: Generally a singular matrix means that one or more datum values are
    not affected by any variation of any variable.
[ERROR | 2024-AUG-13 16:31:24] super_gaussj:
    SINGULAR MATRIX! (2)
[ERROR | 2024-AUG-13 16:31:24] super_mrqmin:
    Note: Generally a singular matrix means that one or more datum values are
    not affected by any variation of any variable.
[ERROR | 2024-AUG-13 16:31:24] closed_orbit_calc:
    SINGULAR MATRIX ENCOUNTERED!
    TRACKING BRANCH: 0:LAT

This is the lattice file: 

[simple_ring.zip](https://github.com/user-attachments/files/16605064/simple_ring.zip)

**Comment by DavidSagan** [comment]
I put in a fix.
