### ISSUE TITLE
tao data evaluation mis-computers vector functions in expressions

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#1143]
Unpack this example: [240814a.zip](https://github.com/user-attachments/files/16619329/240814a.zip) and run `tao -init 240814a.init`. It will output the `orbit.x` and `orbit.center` data. Then it will execute `show value` to print the two expressions that are in the `orbit.center` datum. As you can see, the values are different. Note how `orbit.center[1]` appears to pull the value from `orbit.x[1]` and `orbit.center[2]` apperas to pull the value from `orbit.x[2]`. The intent is that it would evaluate the maximum, etc. over the `orbit.x` array.

As I was writing this, I realized that I could use `orbit.x[:]` in the `orbit.center` expressions, and indeed, that did work. But the behavior in the example is not particularly obvious, and if it's desirable, it probably points to the need for a "clever things that tao will do in expression data" paragraph/section/chapter of the manual...

**Comment by DavidSagan** [comment]
This is a bug. I will work on it...

**Comment by DavidSagan** [comment]
Fixed.
