### ISSUE TITLE
BAD "quiet" COMMAND ARGUMENT: all

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#1147]
The Tao manual says that `all` is a valid option, but now we have:

```

Tao> set global quiet = all
[ERROR | 2024-AUG-15 11:14:20] tao_quiet_set:
    BAD "quiet" COMMAND ARGUMENT: all
```

<img width="852" alt="image" src="https://github.com/user-attachments/assets/d1fb250d-2aef-4a36-b07a-e056a03a4f62">

**Comment by DavidSagan** [comment]
Fixed.
