### ISSUE TITLE
Document that symbolic_number is not actually a namelist

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#1149]
When I read the documentation for `symbolic_number` in the Initialization chapter, I was a bit confused by your example since it didn't make sense as a namelist. But then I read the code and saw that it wasn't really a namelist, and you were parsing for `symbol = expression`. It might be good to clarify that point. And that putting division in your expression is fine as long as you don't do something creative like splitting the expression across lines and ending one line with `/` for division...

**Comment by DavidSagan** [comment]
OK I have reworded the section. If there is still something that is unclear please suggest a correction.
