### ISSUE TITLE
Tao regression/unit tests needed

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1162]
A test suite for Tao is necessary.

Even just one single lattice where all the correct values are stored and compared during each test run would go a long way with preventing new bugs from creeping in. E.g., take the ESR lattice and store the correct output for `show lat * -at beta_a@f20.16 ....` etc for as many lattice functions as possible, and the test should compare that against the known values.

Same for `show uni`, `show spin`, `show chrom`, etc...

**Comment by DavidSagan** [comment]
This will be a bit of work but it is needed.

**Comment by mattsignorelli** [comment]
If we set up some pytest CI we could use PyTao

**Comment by ken-lauer** [comment]
I have intentions of getting pytao's test suite itself running on new commits and releases for this repository (`bmad-sim/bmad-ecosystem`) to help with Tao's `pipe` (=`python`) command regressions/changes. It could also help to address this issue, I think.

**Comment by DavidSagan** [comment]
Ken has done the work to integrate PyTao tests with CI (much thanks!) and regression_tests/tao_test has been setup to test Tao's `show` command and this will be expanded as needed in the future.

**Comment by ken-lauer** [comment]
@mattsignorelli now that #1377 is in, any thoughts on extending the snapshot test (with more examples or other element data keys beyond `ele.a.beta` and `ele.b.beta`) or adding what you proposed at the top regarding `show` results? I may be able to help with the implementation if you can offer some suggestions

(Also nudging @ChristopherMayes for suggestions)

**Comment by mattsignorelli** [comment]
@ken-lauer I'm not familiar with how the test suite works. For me, the spin polarization calculation and element-by-element `spin_dn_dpz.x/y/z` has broken quite frequently, so having tests for those in would be good. I can provide a lattice if it helps

**Comment by ken-lauer** [comment]
Familiarity with the test suite itself isn't required. If you can list things to check between bmad versions/commits, I can at least offer sample implementations.

A lattice for the spin polarization check would be helpful.

**Comment by DavidSagan** [comment]
Please keep in mind: With thousands of tests it is important that the computation time of any given test be kept  at a minimum (think seconds).

**Comment by mattsignorelli** [comment]
Great, I've attached a lattice for the spin polarization check. It can also be used for the following checks. Things to check that immediately come to mind are
- All of the output for `spin_polarization`
- `show lattice -pipe -at spin_dn_dpz.x@e23.16 -at spin_dn_dpz.y@e23.16 -at spin_dn_dpz.z@e23.16`
- All output for `show uni`
- All output for `show chrom`
- All output for `show emit`

[esr-BAGELed.bmad.zip](https://github.com/user-attachments/files/18676722/esr-BAGELed.bmad.zip)

**Comment by ken-lauer** [comment]
Do you think you could provide a smaller lattice or a representative slice? Noting @DavidSagan 's request about keeping the test runtime short, loading that lattice and running those commands takes 1min46s on my machine.

**Comment by mattsignorelli** [comment]
Unfortunately I do not have such a lattice. And I do feel it is important to have these tests in a lattice with spin rotators, radiation, and nonzero closed orbit (though, since PTC is used, I don't expect much a speedup even without these)

Why do the tests runtime need to be short?

**Comment by DavidSagan** [comment]
The runtime needs to be short since I am often juggling different fixes which overlap code wise and waiting for tests to finish just wastes time. Also if there is a regression failure a test that is fast greatly reduces the time it takes to diagnose things. 

The key to speeding up the test is to use a small lattice. I don't think it is important to have a spin rotator since regression tests only measure changes in the results. No problem about keeping radiation and nonzero closed orbit.

**Comment by DavidSagan** [comment]
also reducing the taylor order to 2 helps.
