### ISSUE TITLE
Insufficient plot points for the beta functions plot

### ISSUE THREAD

**Issue by StevenTepikian** [bmad-sim/bmad-ecosystem#1164]
There are insufficient plot points for plotting the beta functions. This is when running tao -lat ir6-18GeV.bmad
The file is here: 
[ir6-18GeV.zip](https://github.com/user-attachments/files/16733080/ir6-18GeV.zip)

The resulting picture:
![Screenshot from 2024-08-23 15-46-14](https://github.com/user-attachments/assets/172c515c-adeb-4bb8-885c-02589c82d873)

**Comment by henrylovelace3** [comment]
@StevenTepikian You can use the command 
_set plot * n_curve_pts = 5000_
where * is the plot_region and the number of points is up to you.

**Comment by DavidSagan** [comment]
@StevenTepikian @henrylovelace3 I have increased the default value of n_curve_pts to 4001 from 401. Be aware that this can slow down graphing significantly depending upon the circumstances and if this becomes a problem I might change the default again.
