### ISSUE TITLE
Standalone DA program issue with ramping on

### ISSUE THREAD

**Issue by DariaKuzovkov** [bmad-sim/bmad-ecosystem#1169]
I have an lattice that I use for DA calculations with the standalone program. Everything seems to run fine until I turn ramping on, and then I get en error saying "SIGSEGV, segmentation fault occurred". I attached the files that are causing me trouble.
[DA_files.zip](https://github.com/user-attachments/files/16753223/DA_files.zip)

**Comment by DavidSagan** [comment]
@DariaKuzovkov How do I reproduce the error?

**Comment by DariaKuzovkov** [comment]
I run the dynamic_aperture DA.init command on a NoMachine computer with ramping = T in my Da.init file, which produces that error.

**Comment by DavidSagan** [comment]
Fixed. Problem was bookkeeping when there was ramping with radiation was off.
