### ISSUE TITLE
write madx command in tao misses part of lattice

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1170]
I am trying to convert a lattice to madx, but run into an issue where the last few hundred elements get dropped. other than that it appears to be working. This also happens when using the bmad_to_mad_sad_elegant program. I have my specific file attached
[madx conversion.zip](https://github.com/user-attachments/files/16767599/madx.conversion.zip)

**Comment by DavidSagan** [comment]
@jeu8 I will work on this. In any case, due to the wiggler elements you have,  the conversion program is going to do a very poor job of converting the wigglers. We can talk about this if you want.

**Comment by DavidSagan** [comment]
The code has been fixed.

**Comment by jeu8** [comment]
At the moment I am just giving a 3rd order map for the wiggler since I am trying to supply the lattice for madx and elegant use. I will also note that this bug appears to also happen when writing out an elegant lattice

**Comment by DavidSagan** [comment]
This should have fixed the translation to elegant. If not, please open an issue.
