### ISSUE TITLE
bmad to elegant translation missing match elements

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1178]
the translation from bmad to elegant is missing match elements, converts to a zero  length drift

**Comment by DavidSagan** [comment]
@jeu8 Please attach the Bmad file to use for testing.

**Comment by jeu8** [comment]
this is what I was using
[match.zip](https://github.com/user-attachments/files/16874376/match.zip)

**Comment by DavidSagan** [comment]
I put in a fix. Please test.
