### ISSUE TITLE
Adding Ability to Ramp Particle Energy

### ISSUE THREAD

**Issue by JosephPeterDevlin** [bmad-sim/bmad-ecosystem#1180]
As in long_term_tracking we can ramp the reference energy, it would be nice to also have the ability to ramp the energy of a particle directly at the same time. I would also like to be able to ramp the energy of a beam of particles, but I don't need the ability to use a different ramping function for each particle.

**Comment by DavidSagan** [comment]
@JosephPeterDevlin So if I understand this, you want to be able to have, with RF off, particle pz not vary when the reference energy (or momentum) is varied. Yes?

**Comment by JosephPeterDevlin** [comment]
@DavidSagan Right.

**Comment by DavidSagan** [comment]
Done. The LTT manual has been updated and the new parameter is `ltt%ramp_particle_energy_without_rf`.
