### ISSUE TITLE
LTT Can't Read beam.init

### ISSUE THREAD

**Issue by JosephPeterDevlin** [bmad-sim/bmad-ecosystem#1183]
In the newest release of Bmad (I'm using Conda), LTT can't read my beam.init file. Here is the error:

At line 222 of file /Users/runner/miniforge3/conda-bld/bmad_1725698858820/work/bsim/modules/lt_tracking_mod.f90 (unit = 1, file = 'long_term_tracking.init')
Fortran runtime error: Cannot match namelist object name beam.init

Error termination. Backtrace:
#0  0x1017f7cf7
#1  0x1017f8b07
#2  0x1017f942f
#3  0x101ad550b
#4  0x101adf9ab
#5  0x100132fe7
#6  0x100118ccf
#7  0x10064493f

Here are the input files: [Ramping.zip](https://github.com/user-attachments/files/16923604/Ramping.zip)

**Comment by DavidSagan** [comment]
@JosephPeterDevlin If you use quotation marks `"beam.init"` does the error go away?

**Comment by JosephPeterDevlin** [comment]
@DavidSagan Yes, thanks. I transferred the files from the CLASSE computer, where I didn't need the quotation marks.

**Comment by DavidSagan** [comment]
Yes different the ifort compiler is more picky.
