### ISSUE TITLE
Allow momenta in spin_stroboscope?

### ISSUE THREAD

**Issue by JosephPeterDevlin** [bmad-sim/bmad-ecosystem#1184]
Currently, spin_stroboscope only allows one to specify the (x,y,z) orbital position, taking all the momenta to be 0. This program should be able to calculate the invariant spin field at arbitrary phase space points, so we should be allowed to input (px,py,pz) as well.

**Comment by DavidSagan** [comment]
`orbit_start`, `orbit_stop`, and `n_points` are now 6-vectors.
