### ISSUE TITLE
patch element translation to madx gives problems

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1186]
I have a couple patch elements that each show up several times in my lattice. each only has a y_pitch attribute. The translation renames them to have a __y at the end in the element declaration, but only changes one of them in the line declarations.
[patch translation.zip](https://github.com/user-attachments/files/16952581/patch.translation.zip)

**Comment by DavidSagan** [comment]
Sorry for the delay but this was fixed awhile back but I did not respond to the issue.
