### ISSUE TITLE
New Tao datums: `show spin -spin_tune` monomial coefficients

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#1188]
Currently, Tao has the spin_tune_ptc.[N] datums which are the purely _pz_ expansion. There are also the "srdt" monomial coefficients but those are only 3rd- and 4th-order (do not include 1st- and 2nd- order).

It would be very helpful to have the amplitude-dependent spin tune coefficients from `show spin -spin_tune` as optimization datums as well, since these are extremely practical for higher-order spin resonance optimization.

Thanks

**Comment by DavidSagan** [comment]
New datum type: `spin_map_ptc.NNNNNN` where `NNNNNN` is a 6 digit inteter.
