### ISSUE TITLE
`spin_stroboscope` floating point exception - Totalview

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#1190]
Running normal version of spin_stroboscope produces zeroed-out output files _sanity_check.dat_ and _spin_track.dat_ and _spin_stroboscope.dat_

Totalview debugger shows a floating point exception in line 869 of `spin_stroboscope.f90` when running the debug version of spin_stroboscope.

[stroboscope_test.zip](https://github.com/user-attachments/files/16984909/stroboscope_test.zip)

**Comment by DavidSagan** [comment]
Fixed.

**Comment by eiad-hamwi** [comment]
@DavidSagan using the debug version `spin_stroboscope` in /nfs/acc/libs/Linux_x86_64_intel/nightly/debug/bin/ outputs & prints the spin data correctly, whereas using the production version of `spin_stroboscope` does not properly output spin tracking data.

You can see this by using the same input files attached above on the CLASSE intel fortran-compiled nightly distribution.
