### ISSUE TITLE
Tao's "read" command does not operate as described in manual 

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1195]
The manual says that the "read" command only effects the the model lattice. In my case, I am reading in a set of variables that were output from a previous optimization. The plot of the design lattice changes when this is done. It also changes in a contradictory way. I have a closed lattice but I do not get the periodic solution.

[read command.zip](https://github.com/user-attachments/files/17016702/read.command.zip)

**Comment by DavidSagan** [comment]
Looks like a plotting bug since `show lat -orbit -design` does not change. I will work on it.

**Comment by DavidSagan** [comment]
@jeu8 Fixed. Actually bug was due to bookkeeping connected to the overlay controlling Cartesian map parameters.
