### ISSUE TITLE
sho lat error in latest pull from github.

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#1204]
Tao> sho lat -s 20.0:40.0
NO ":" FOUND FOR RANGE SELECTION

**Comment by DavidSagan** [comment]
@MichaelEhrlichman I don't see this error using either ifort and gfortran. Can you reproduce this on other computers?

**Comment by DavidSagan** [comment]
I found and fixed the problem. Funny how this bug did show up before now.
