### ISSUE TITLE
Flag for open lattice in DA and ltt programs

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1210]
It is sometimes useful to be able track through a lattice where a closed orbit cannot be found in the DA and ltt programs. A flag allowing these programs to track through an open lattice would work

**Comment by DavidSagan** [comment]
Currently, LTT will accept open lattices and so no change is needed for this program.

**Comment by DavidSagan** [comment]
@jeu8 And the same is true for DA. One thing to remember is that the beginning betas have to be set.
