### ISSUE TITLE
Correct typos in §25.3, Hamiltonian, of the manual

### ISSUE THREAD

**Issue by dtabell** [bmad-sim/bmad-ecosystem#1217]
Eq (25.7): The normalized vector potential should read $q\bf{A}/P_0  = \bf{A}/(B\rho)_0$ (_no_ $c$).

Eq (25.8): The kinetic momentum terms in $p_x$ and $p_y$ both lack a factor of $\gamma$.

Eq (25.11): Delete the factor $(1 + g x)$ from the middle term on the RHS.
Similarly, delete the terms containing $g$ from (25.12) and (25.13).

**Comment by DavidSagan** [comment]
Fixed.
