### ISSUE TITLE
Lcavity and rf_frequency parameter

### ISSUE THREAD

**Issue by kdeitrick** [bmad-sim/bmad-ecosystem#1221]
A lcavity element is defined with rf_frequency = 591e6. 

When the field map is defined using a h5 file (freq_bug.bmad), "sho val ele::la.cav[rf_frequency]" returns 5.9117827970010006E+08

When the field map is defined using a text file (freq_bug02.bmad), "sho val ele::la.cav[rf_frequency]" returns 5.9100000000000000E+08

The text file field map was generated by writing the lattice and setting the appropriate format - I inherited the h5 fieldmap a few years ago.

[lcav_freq.zip](https://github.com/user-attachments/files/17297718/lcav_freq.zip)

**Comment by DavidSagan** [comment]
Indeed the h5 file was storing the rf_frequency and reinstating it. I have changed the code to prevent this.
