### ISSUE TITLE
tao not converging on a closed orbit for a lattice containing a foil and an RF cavity

### ISSUE THREAD

**Issue by pavel1murat** [bmad-sim/bmad-ecosystem#1230]
a .bmad file (renamed into .txt to make github happy) is attached. -- thanks a lot for looking into this issue!

racetrack_v06_bmad.txt](https://github.com/user-attachments/files/17336341/racetrack_v06_bmad.txt)

**Comment by DavidSagan** [comment]
Problem is the RF voltage is in eV (not MeV) so that set voltage is way too low. And for a stable closed orbit the voltage should be well above what is lost in the foil.
