### ISSUE TITLE
LongTermTracking not updating particle status in position files

### ISSUE THREAD

**Issue by DariaKuzovkov** [bmad-sim/bmad-ecosystem#1231]
When I track a bunch of particles through a lattice with long_term_tracking and some of the particles die, the program records that in the average files but not in individual position files. For instance, if I have a bunch of 100 particles and one dies at turn 7, the number of alive particles goes down. However, if I pull up a positions file for turn 7, all the particles are still listed as "Alive."
[lattice_and_example_files.zip](https://github.com/user-attachments/files/17345532/lattice_and_example_files.zip)

**Comment by DavidSagan** [comment]
There is a switch `ltt%only_live_particles_out` which if `True` (the default) will prevent printing of dead particles in position files.
