### ISSUE TITLE
Output for touschek_background program is unclear

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1251]
The touschek_background program has several output files that do not have a description in the manual. The output does have labeled columns, however I seem to not understand what they are saying or am getting contradictory results.

The main place this is seen is that I have the raw_rates.out file has a large rate (2.2427E+017 N/bunch/sec) but my particle loss files all say 0 particle loss. specifically the lines labeled "N deposited at slice per bunch". 

If this is a misunderstanding of the output, it might be good to have a brief description of these files in the manual.

**Comment by DavidSagan** [comment]
@MichaelEhrlichman Can you take a look at this? Thanks.

**Comment by MichaelEhrlichman** [comment]
@jeu8 I've updated the documentation.  IT might take a day to end up on the website.  Let me know if you still have questions. 

https://github.com/bmad-sim/bmad-ecosystem/pull/1306

**Comment by DavidSagan** [comment]
The web doc has been updated. @jeu8 Please take a look and close the issue if complete.

**Comment by jeu8** [comment]
looks good
