### ISSUE TITLE
documentation needed for aperture_by_tracking output

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1252]
The aperture_by_tracking program has documentation in the fortran file, but this mostly focuses on the input. The output files do not have a description, but the columns are labeled fairly clearly in all of the output files except for pz_aperture_by_s.out. Based on the description of the program and file name it is not too hard to work out what they should be, although I get numbers that are much smaller than expected so I am unsure about the units being used.

None of the files have units listed, but this mainly causes a problem in pz_aperture_by_s.out

**Comment by DavidSagan** [comment]
@MichaelEhrlichman Can you take a look at this? Thanks.

**Comment by DavidSagan** [comment]
@jeu8 If this solves your problem, can you close the issue? Thanks.

**Comment by jeu8** [comment]
Looks good
