### ISSUE TITLE
ENH: Add `ele:wall_radius` to `Tao> pipe` command

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#1258]
Currently Tao has `pipe ele:chamber_wall` that calls `calc_wall_radius`

Could we add a `pipe` command to call this calc directly, so that the user can query the wall at any `s` position and angle?

**Comment by DavidSagan** [comment]
@ChristopherMayes `calc_wall_radius` does not give  the wall for arbitrary `s`. The closest match to this is `wall3d_d_radius` but note that the `origin` may not be (0, 0). See the doc for `wall3d_d_radius` for details. What do you want to do?

**Comment by ChristopherMayes** [comment]
Previously I used `wall3d_d_radius ` in https://github.com/bmad-sim/bmad-ecosystem/blob/b1c0a33d265ecfbc4391e365fd5c2dc6d33f817d/bsim/wall_generator/wall_generator.f90#L188

So, having some ability to call that within Tao would be useful.

**Comment by DavidSagan** [comment]
OK. But just remember that in the general case wall3d_d_radius may not use (0,0) as the origin of the radius calc.

**Comment by ChristopherMayes** [comment]
In the end, I need to get what Bmad actually thinks the wall radius is at an arbitrary `s` and angle `theta`.

**Comment by DavidSagan** [comment]
Yes this gives the wall radius but the radius is not necessarily the distance from the origin to the wall.

**Comment by ChristopherMayes** [comment]
I would like the distance from the reference coordinate system to the wall.

**Comment by DavidSagan** [comment]
The problem is that the wall point identified by wall3d_d_radius is not in general at the angle specified in the argument passed to wall3d_d_radius with respect to the (0, 0) origin.

**Comment by DavidSagan** [comment]
I can have the pipe command return the origin of the computation and things can be handled on the Python side.

**Comment by DavidSagan** [comment]
@ChristopherMayes @ken-lauer Added `pipe wall3d_radius` command. Note: PyTao tests are now failing but I don't know how to fix this.

**Comment by DavidSagan** [comment]
@ChristopherMayes @ken-lauer Actually it turns out the problem was on my side and everything is fixed.
