### ISSUE TITLE
Tao: Lattice disagrees with `write` lattice

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1261]
WIth the attached lattice, in tao:
```
set ele * X = 0
scale
```

See the orbit plot. then
```
write bmad -form one_file out.bmad
exit
```

Open `out.bmad` in Tao and see the difference in the orbit plot.
[esr.bmad.zip](https://github.com/user-attachments/files/17622731/esr.bmad.zip)

**Comment by DavidSagan** [comment]
I see the same plots

![Screenshot 2024-11-06 at 2 03 03 PM](https://github.com/user-attachments/assets/5a8298d2-3d88-412b-b69e-9107f845e951)

**Comment by mattsignorelli** [comment]
Did you run `set ele * X = 0`? That is supposed to make the orbit almost zero..

**Comment by DavidSagan** [comment]
Sorry I forgot that. Checking now...

**Comment by DavidSagan** [comment]
Looks like the shifts you are seeing are due to the closed orbit finder tolerances. Try using tighter tolerances:
```
bmad_com[rel_tol_tracking] = 1e-10
bmad_com[abs_tol_tracking] = 1e-14
```

**Comment by DavidSagan** [comment]
Note: Repeated use of the `cut` command will also show shifts due to the closed orbit finder tolerances.

**Comment by mattsignorelli** [comment]
Shouldn't the tolerances be larger by default then? 1e-10 seems too low, 1e-12 seems more appropriate

**Comment by DavidSagan** [comment]
Unfortunately in some situations (generally involving Runge Kutta) a tighter tolerance prevents the closed orbit finder from finding a solution. And increasing the tolerance on RK (which could potentially solve this closed orbit problem) runs into problems with some field maps that violate Maxwell's equations to some degree.

**Comment by mattsignorelli** [comment]
I would say that having an error which tells the user to reduce the tolerance to find a closed orbit (which mostly people using RK would run into and should expect to run into) is better than having a case where two significantly different closed orbits are obtained for what is supposed to be the same exact lattice, and no error can be given to tell the user to reduce the tolerance
