### ISSUE TITLE
`show spin` gives all NaNs

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1262]
[esr-emitb-tapered.bmad.zip](https://github.com/user-attachments/files/17623074/esr-emitb-tapered.bmad.zip)

**Comment by mattsignorelli** [comment]
In fact I don't get NaNs with commit 7c63c744fa3f2084b7b4e3aba50afe6bc01f93d6 , so it must be some later bug that appeared...

**Comment by DavidSagan** [comment]
@mattsignorelli I don't see this. It might be due to what has been checked in before. Can you check if you still see this?

**Comment by mattsignorelli** [comment]
this seems fixed now but it is still slow #1265
