### ISSUE TITLE
Bmad -> elegant converter bugs

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1263]
From Boris P.:

> With regards to the bugs in the converter, the main one I found,  were the missing definitions of EDGE multipoles. I believe it’s just improper handling of multiple instances of “_”.
> 
> For instance, straight out of the converter the element EDGE1_002__1 is never defined, while the EDGE1_002__1__1 element is defined just fine.
> 
> Both elements are used in the lattice. This happens for similarly-named elements in another ~1100 occurrences in this lattice.
> 
>  
> My brute-force fix, in the attached bash script, was to copy the definitions from the generated *.mad8 file, and modify them according to elegant conventions, i.e.
> 
> "multipole, K1L ="  -> "multipole, order=1, KNL =".
> 
>  
> Separately, for any of the bmad ESR lattices I had to deal with so far, I found that I need to replace
> 
> “edrift” -> “drift”
> 
> “kquad” -> “quad”,
> 
> to have a closed orbit.

 
[esr(2).bmad.zip](https://github.com/user-attachments/files/17623521/esr.2.bmad.zip)

**Comment by DavidSagan** [comment]
Fixed multipole issue. the edrift vs drift and kquad vs quad issue is not one of translation. edrift and kquad are indeed the correct element types to translate to.
