### ISSUE TITLE
Incorrect singular matrix error

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1264]
with the attached lattice
```
set ele rf0* voltage=1e6
```

The singular matrix error should not be printed
[esr-main-18GeV-1IP.bmad.zip](https://github.com/user-attachments/files/17624028/esr-main-18GeV-1IP.bmad.zip)

**Comment by mattsignorelli** [comment]
Also, after you've done the above, try exiting and doing it again. The digested file causes the above step to not even work.

**Comment by DavidSagan** [comment]
Fixed.
