### ISSUE TITLE
`show spin` much slower even with sprint 

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1265]
This is using https://github.com/bmad-sim/bmad-ecosystem/commit/7c63c744fa3f2084b7b4e3aba50afe6bc01f93d6

**Comment by mattsignorelli** [comment]
Calculating the datum `spin.depolarization_rate` still seems fast with sprint tracking so maybe show spin is always using PTC?

**Comment by DavidSagan** [comment]
With the latest code, `show spin` is now a factor of two faster with sprint.

**Comment by mattsignorelli** [comment]
What was the problem? I noticed using `python spin_pol` gave the exact same results but was not nearly as slow

**Comment by DavidSagan** [comment]
Bookkeeping to switch between sprint and PTC maps was bad.

**Comment by mattsignorelli** [comment]
How is that related to the speed? I'm not referring to switching between the two here, just in general. What was `show spin` doing that `python spin_pol` was not doing?

**Comment by DavidSagan** [comment]
Turns out `show spin` was doing an unnecessary call that was taking time. This has been fixed.
