### ISSUE TITLE
dn/ddelta calculation fixes

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1267]
As I described in person, when we calculate the DK integral the "delta" parameter used must be wrt the closed orbit $p_0$, NOT some reference $p_0$. Also, with radiation damping, $p_0$ will vary around the ring, so care must be taken. Alternatively but less-accurately in this case, the $\langle p_0  \rangle$ of the closed orbit around the ring could be used. 

It's possible this is already implemented correctly but we must check

**Comment by DavidSagan** [comment]
The calculation does use the closed orbit.
