### ISSUE TITLE
Generalize injected bunch charge fill_pattern for BBU

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#1272]
Currently in BBU simulation, the injected bunch charge can vary only in a "linearly ramp-up and ramp-down fashion" ( see figure below ).
Instead, we want a more generalized bunch patterning.
For example, the user could specify `current_vary%fill_pattern = [0.1, 0.3, 1.0, 0.5]`, in which the values are weights to the nominal bunch charge.

The nominal bunch charge can still be determined by `bbu_param%bunch_freq` multiplied by `bbu param%current`.

Having `current_vary%variation_on = .true.` would require the user to provide the `current_vary%fill_pattern`, and all the other existing parameters under `current_vary` could become obsolete. 

For details on name
https://www.classe.cornell.edu/bmad/other_manuals.html

![image](https://github.com/user-attachments/assets/0d4d5c3c-f2ce-4e87-89a0-ba550dffa71c)

**Comment by DavidSagan** [comment]
@weiyuanlou I noticed that the manual description of bbu_param parameters leaves off many of the parameters. Just one example is ele_track_end. Since part of this process will be manual cleanup on my end. I will wait until you have updated the manual.

**Comment by weiyuanlou** [comment]
ok let me update the manual.
I found all the manuals other `bmad-ecosystem/bmad-doc/other_manuals`, but where do we find their Latex source files?

**Comment by DavidSagan** [comment]
in bsim/bbu/doc

**Comment by weiyuanlou** [comment]
ok it looks like we have two versions of BBU manual.
The manual ( in Latex ) under `bsim/bbu/doc` had been updated in Aug 12 2023 ( see image below ), which includes description of all the leftover parameters like `ele_track_end`.

The manual under `bmad-ecosystem/bmad-doc/other_manuals` is of Nov 14 2021, and has not been recompiled using the Latex  file. 

![image](https://github.com/user-attachments/assets/a2e5c5e5-3613-4915-81b0-481b8743e297)

**Comment by DavidSagan** [comment]
OK I will take a look...

**Comment by DavidSagan** [comment]
@weiyuanlou Code and manual have been modified but no tests have been run yet. Please run some test cases.
