### ISSUE TITLE
CANNOT INJECT INTO BRANCH: 1 FROM: BR

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#1277]
[fork-error.zip](https://github.com/user-attachments/files/17680923/fork-error.zip)
Receiving error when forking a bunch beam. 

just type in tao command line beamon and the error will appear. 

[ERROR | 2024-NOV-08 10:48:26] tao_inject_beam:
    CANNOT INJECT INTO BRANCH: 1 FROM: BR                                       IN UNIVERSE: 1

**Comment by DavidSagan** [comment]
@henrylovelace3 I'm not seeing this error. Can you try running on a different platform?

**Comment by henrylovelace3** [comment]
@DavidSagan 

I compiled the latest distribution using ifort. When I use "beamon" and set the default branch to 1, I see the following message
Tao: alias beamon set global track_type = beam

Tao: alias beamoff set global track_type = single

Tao> beamon

Tao> set default branch = 1

Tao> place r11 bunch_z_pz 
[WARNING] tao_graph_phase_space_setup:
    NO BEAM AT ELEMENT: 
    CANNOT DO PHASE_SPACE PLOTTING FOR CURVE: bunch_z_pz.g.c
[WARNING] tao_graph_phase_space_setup:
    NO BEAM AT ELEMENT: 
    CANNOT DO PHASE_SPACE PLOTTING FOR CURVE: bunch_z_pz.g.c
[ERROR | 2024-NOV-11 09:43:04] tao_scale_graph:
    CANNOT SCALE GRAPH bunch_z_pz.g SINCE NO DATA IS WITHIN THE GRAPH X-AXIS RANGE.
    USE x_scale TO FIRST SCALE THE X-AXIS.

**Comment by DavidSagan** [comment]
Fixed The `place  r11 bunch_z_pz` problem. I'm assuming the first problem is not reproducible so I am closing this issue.
