### ISSUE TITLE
tao: error while loading shared libraries: ../../production/lib/libpgplot.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#1286]
Error when compiling with PGPLOT enabled
02:06 PM->lovelace:bmad_dist_20241109-0 tao
tao: error while loading shared libraries: ../../production/lib/libpgplot.so: cannot open shared object file: No such file or directory

:from dist_pref:
export DIST_F90_REQUEST="ifort"
export ACC_PLOT_PACKAGE="pgplot"
export ACC_PLOT_DISPLAY_TYPE="X"
export ACC_ENABLE_SHARED="N"
export ACC_ENABLE_SHARED_ONLY="Y"

**Comment by DavidSagan** [comment]
@henrylovelace3 If you got to the pgplot library what is the result of the `mk` command?

**Comment by jsberg-bnl** [comment]
This is a Linux system presumably. What does `objdump -x $(which tao) | grep 'R.*PATH'` output? When you _built_ Bmad, what did you set `DIST_BASE_DIR` to? If I had to guess, I would speculate that you set it to a relative path rather than an absolute one.

**Comment by henrylovelace3** [comment]
@jsberg-bnl 

I have the following:
10:45 PM->lovelace:bmad_dist_20241118-0 objdump -x $(which tao) | grep 'R.*PATH'
  RUNPATH              /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib

where the DIST_BASE_DIR=/home/lovelace/BMAD_DIST/bmad_dist_20241118-0


I export the environment using

export DIST_SETUP_QUIET Y
export DIST_BASE_DIR="$HOME/BMAD_DIST/bmad_dist_20241118-0"
source ${DIST_BASE_DIR}/util/dist_source_me

**Comment by jsberg-bnl** [comment]
What's the output of `readelf -d $(which tao)`?

**Comment by jsberg-bnl** [comment]
And `ldd $(which tao)`

**Comment by jsberg-bnl** [comment]
And (after you've sourced `dist_source_me`), the output of `echo $LD_LIBRARY_PATH`

**Comment by henrylovelace3** [comment]
@jsberg-bnl 
See below:

01:57 PM->lovelace:bmad_dist_20241118-0 echo $LD_LIBRARY_PATH
/opt/intel/oneapi/vpl/2023.1.0/lib:/opt/intel/oneapi/tbb/2021.13/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.13/opt/mpi/libfabric/lib:/opt/intel/oneapi/mpi/2021.13/lib:/opt/intel/oneapi/mkl/2024.2/lib:/opt/intel/oneapi/itac/2022.1/slib:/opt/intel/oneapi/ippcp/2021.12/lib/:/opt/intel/oneapi/ipp/2021.12/lib:/opt/intel/oneapi/dpl/2022.6/lib:/opt/intel/oneapi/dnnl/2024.2/lib:/opt/intel/oneapi/debugger/2024.2/opt/debugger/lib:/opt/intel/oneapi/dal/2024.5/lib:/opt/intel/oneapi/compiler/2024.2/opt/compiler/lib:/opt/intel/oneapi/compiler/2024.2/lib:/opt/intel/oneapi/ccl/2021.13/lib/:/home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib:/home/lovelace/BMAD_DIST/bmad_dist_20241118-0/debug/lib:/opt/intel/oneapi/intelpython/python3.9/lib/libfabric:/opt/intel/oneapi/vpl/2023.1.0/lib:/opt/intel/oneapi/tbb/2021.13/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.13/opt/mpi/libfabric/lib:/opt/intel/oneapi/mpi/2021.13/lib:/opt/intel/oneapi/mkl/2024.2/lib:/opt/intel/oneapi/itac/2022.1/slib:/opt/intel/oneapi/ippcp/2021.12/lib/:/opt/intel/oneapi/ipp/2021.12/lib:/opt/intel/oneapi/dpl/2022.6/lib:/opt/intel/oneapi/dnnl/2024.2/lib:/opt/intel/oneapi/debugger/2024.2/opt/debugger/lib:/opt/intel/oneapi/dal/2024.5/lib:/opt/intel/oneapi/compiler/2024.2/opt/compiler/lib:/opt/intel/oneapi/compiler/2024.2/lib:/opt/intel/oneapi/ccl/2021.13/lib/

**Comment by jsberg-bnl** [comment]
Doesn't seem to be coming from `LD_LIBRARY_PATH`. What is the output of the commands in the earlier two comments?

**Comment by henrylovelace3** [comment]
@jsberg-bnl 

**02:15 PM->lovelace:bmad_dist_20241118-0 readelf -d $(which tao)**

Dynamic section at offset 0x1ff9d0 contains 66 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libtao.so]
 0x0000000000000001 (NEEDED)             Shared library: [libbmad.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsim_utils.so]
 0x0000000000000001 (NEEDED)             Shared library: [libplplotfortran.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libplplot.so.17]
 0x0000000000000001 (NEEDED)             Shared library: [libcsirocsa.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libqsastime.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libxrlf03.so.11]
 0x0000000000000001 (NEEDED)             Shared library: [libxrl.so.11]
 0x0000000000000001 (NEEDED)             Shared library: [libforest.so]
 0x0000000000000001 (NEEDED)             Shared library: [libfgsl.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgsl.so.27]
 0x0000000000000001 (NEEDED)             Shared library: [libgslcblas.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [liblapack95.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblapack.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libblas.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5hl_fortran.so.310]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5_hl.so.310]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5_fortran.so.310]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5.so.310]
 0x0000000000000001 (NEEDED)             Shared library: [libfftw3.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libfftw3_omp.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libcairo.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpango-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpangocairo-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgobject-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi_usempif08.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi_usempi_ignore_tkr.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi_mpifh.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libiomp5.so]
 0x0000000000000001 (NEEDED)             Shared library: [libreadline.so.7]
 0x0000000000000001 (NEEDED)             Shared library: [libgomp.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x000000000000001d (RUNPATH)            Library runpath: [/home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib]
 0x000000000000000c (INIT)               0x4156e8
 0x000000000000000d (FINI)               0x5027f8
 0x0000000000000019 (INIT_ARRAY)         0x7f9d68
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x7f9d78
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x4002d0
 0x000000006ffffef5 (GNU_HASH)           0x402800
 0x0000000000000005 (STRTAB)             0x40ccb0
 0x0000000000000006 (SYMTAB)             0x404e80
 0x000000000000000a (STRSZ)              27486 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x800000
 0x0000000000000002 (PLTRELSZ)           3696 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x414878
 0x0000000000000007 (RELA)               0x4143c8
 0x0000000000000008 (RELASZ)             1200 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x414298
 0x000000006fffffff (VERNEEDNUM)         6
 0x000000006ffffff0 (VERSYM)             0x41380e
 0x0000000000000000 (NULL)               0x0


**08:44 PM->lovelace:bmad_dist_20241118-0 ldd $(which tao)**
	linux-vdso.so.1 (0x00007fff89991000)
	libtao.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libtao.so (0x00007fe2a8481000)
	libbmad.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libbmad.so (0x00007fe2a770c000)
	libsim_utils.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libsim_utils.so (0x00007fe2a73ae000)
	libplplotfortran.so.0 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libplplotfortran.so.0 (0x00007fe2a7111000)
	libplplot.so.17 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libplplot.so.17 (0x00007fe2a6e99000)
	libcsirocsa.so.0 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libcsirocsa.so.0 (0x00007fe2a6c91000)
	libqsastime.so.0 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libqsastime.so.0 (0x00007fe2a6a8b000)
	libxrlf03.so.11 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libxrlf03.so.11 (0x00007fe2a6867000)
	libxrl.so.11 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libxrl.so.11 (0x00007fe2a5628000)
	libforest.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libforest.so (0x00007fe2a4bc1000)
	libfgsl.so.1 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libfgsl.so.1 (0x00007fe2a491a000)
	libgsl.so.27 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libgsl.so.27 (0x00007fe2a443c000)
	libgslcblas.so.0 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libgslcblas.so.0 (0x00007fe2a41fd000)
	liblapack95.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/liblapack95.so (0x00007fe2a3b88000)
	liblapack.so.3 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/liblapack.so.3 (0x00007fe2a30c9000)
	libblas.so.3 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libblas.so.3 (0x00007fe2a2e2d000)
	libhdf5hl_fortran.so.310 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libhdf5hl_fortran.so.310 (0x00007fe2a2c00000)
	libhdf5_hl.so.310 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libhdf5_hl.so.310 (0x00007fe2a29df000)
	libhdf5_fortran.so.310 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libhdf5_fortran.so.310 (0x00007fe2a275f000)
	libhdf5.so.310 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libhdf5.so.310 (0x00007fe2a2178000)
	libfftw3.so.3 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libfftw3.so.3 (0x00007fe2a1e76000)
	libfftw3_omp.so.3 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libfftw3_omp.so.3 (0x00007fe2a1c6f000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00007fe2a194e000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00007fe2a1707000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00007fe2a14f8000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007fe2a12a5000)
	libmpi_usempif08.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libmpi_usempif08.so.40 (0x00007fe2a1048000)
	libmpi_usempi_ignore_tkr.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libmpi_usempi_ignore_tkr.so.40 (0x00007fe2a0e34000)
	libmpi_mpifh.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libmpi_mpifh.so.40 (0x00007fe2a0bca000)
	libmpi.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libmpi.so.40 (0x00007fe2a088a000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007fe2a0547000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe2a0327000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe29ff92000)
	libiomp5.so => /opt/intel/oneapi/compiler/2024.2/lib/libiomp5.so (0x00007fe29fbaa000)
	libreadline.so.7 => /lib64/libreadline.so.7 (0x00007fe29f95b000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007fe29f723000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe29f3a1000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe29efdc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe2a8bf8000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe29edc4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fe29ebc0000)
	libifport.so.5 => /opt/intel/oneapi/compiler/2024.2/lib/libifport.so.5 (0x00007fe2a8dd8000)
	libifcoremt.so.5 => /opt/intel/oneapi/compiler/2024.2/lib/libifcoremt.so.5 (0x00007fe2a8c6c000)
	libimf.so => /opt/intel/oneapi/compiler/2024.2/lib/libimf.so (0x00007fe29e7b4000)
	libsvml.so => /opt/intel/oneapi/compiler/2024.2/lib/libsvml.so (0x00007fe29d170000)
	libintlc.so.5 => /opt/intel/oneapi/compiler/2024.2/lib/libintlc.so.5 (0x00007fe29d10f000)
	libirc.so => /opt/intel/oneapi/compiler/2024.2/lib/libirc.so (0x00007fe29d0ae000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007fe29cd95000)
	libSM.so.6 => /lib64/libSM.so.6 (0x00007fe29cb8c000)
	libICE.so.6 => /lib64/libICE.so.6 (0x00007fe29c96f000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007fe29c75c000)
	libirng.so => /opt/intel/oneapi/compiler/2024.2/lib/libirng.so (0x00007fe29c663000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00007fe29c3bb000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007fe29c176000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007fe29beba000)
	libpng16.so.16 => /lib64/libpng16.so.16 (0x00007fe29bc85000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00007fe29ba81000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007fe29b858000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00007fe29b64a000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007fe29b43f000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fe29b228000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fe29b020000)
	libthai.so.0 => /lib64/libthai.so.0 (0x00007fe29ae16000)
	libfribidi.so.0 => /lib64/libfribidi.so.0 (0x00007fe29abfa000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00007fe29a9e3000)
	libgnutls.so.30 => /lib64/libgnutls.so.30 (0x00007fe29a5f2000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fe29a381000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007fe29a178000)
	libopen-rte.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libopen-rte.so.40 (0x00007fe299ec2000)
	libopen-pal.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libopen-pal.so.40 (0x00007fe299bc2000)
	libutil.so => /lib64/libutil.so (0x00007fe2999be000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007fe299791000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fe299589000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fe29934e000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fe29913d000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007fe298f39000)
	libdatrie.so.1 => /lib64/libdatrie.so.1 (0x00007fe298d31000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00007fe298a8b000)
	libp11-kit.so.0 => /lib64/libp11-kit.so.0 (0x00007fe298761000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007fe298543000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007fe2981c2000)
	libtasn1.so.6 => /lib64/libtasn1.so.6 (0x00007fe297faf000)
	libnettle.so.6 => /lib64/libnettle.so.6 (0x00007fe297d75000)
	libhogweed.so.4 => /lib64/libhogweed.so.4 (0x00007fe297b44000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fe2978ac000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00007fe297680000)

**Comment by jsberg-bnl** [comment]
This was for a plplot build. I'm looking for the error in the pgplot build that you referred to earlier.

**Comment by henrylovelace3** [comment]
@jsberg-bnl 
    Sorry about that, juggling multiple builds:
    
    10:51 AM->lovelace:bmad_dist_20241118-0 echo $LD_LIBRARY_PATH
/opt/intel/oneapi/vpl/2023.1.0/lib:/opt/intel/oneapi/tbb/2021.13/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.13/opt/mpi/libfabric/lib:/opt/intel/oneapi/mpi/2021.13/lib:/opt/intel/oneapi/mkl/2024.2/lib:/opt/intel/oneapi/itac/2022.1/slib:/opt/intel/oneapi/ippcp/2021.12/lib/:/opt/intel/oneapi/ipp/2021.12/lib:/opt/intel/oneapi/dpl/2022.6/lib:/opt/intel/oneapi/dnnl/2024.2/lib:/opt/intel/oneapi/debugger/2024.2/opt/debugger/lib:/opt/intel/oneapi/dal/2024.5/lib:/opt/intel/oneapi/compiler/2024.2/opt/compiler/lib:/opt/intel/oneapi/compiler/2024.2/lib:/opt/intel/oneapi/ccl/2021.13/lib/:/home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib:/home/lovelace/BMAD_DIST/bmad_dist_20241118-0/debug/lib:/opt/intel/oneapi/intelpython/python3.9/lib/libfabric:/opt/intel/oneapi/vpl/2023.1.0/lib:/opt/intel/oneapi/tbb/2021.13/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.13/opt/mpi/libfabric/lib:/opt/intel/oneapi/mpi/2021.13/lib:/opt/intel/oneapi/mkl/2024.2/lib:/opt/intel/oneapi/itac/2022.1/slib:/opt/intel/oneapi/ippcp/2021.12/lib/:/opt/intel/oneapi/ipp/2021.12/lib:/opt/intel/oneapi/dpl/2022.6/lib:/opt/intel/oneapi/dnnl/2024.2/lib:/opt/intel/oneapi/debugger/2024.2/opt/debugger/lib:/opt/intel/oneapi/dal/2024.5/lib:/opt/intel/oneapi/compiler/2024.2/opt/compiler/lib:/opt/intel/oneapi/compiler/2024.2/lib:/opt/intel/oneapi/ccl/2021.13/lib/
10:51 AM->lovelace:bmad_dist_20241118-0 readelf -d $(which tao)

Dynamic section at offset 0x20fa50 contains 59 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libtao.so]
 0x0000000000000001 (NEEDED)             Shared library: [libbmad.so]
 0x0000000000000001 (NEEDED)             Shared library: [libsim_utils.so]
 0x0000000000000001 (NEEDED)             Shared library: [../../production/lib/libpgplot.so]
 0x0000000000000001 (NEEDED)             Shared library: [libxrlf03.so.11]
 0x0000000000000001 (NEEDED)             Shared library: [libxrl.so.11]
 0x0000000000000001 (NEEDED)             Shared library: [libforest.so]
 0x0000000000000001 (NEEDED)             Shared library: [libfgsl.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libgsl.so.27]
 0x0000000000000001 (NEEDED)             Shared library: [libgslcblas.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [liblapack95.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblapack.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libblas.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5hl_fortran.so.310]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5_hl.so.310]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5_fortran.so.310]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5.so.310]
 0x0000000000000001 (NEEDED)             Shared library: [libfftw3.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libfftw3_omp.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi_usempif08.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi_usempi_ignore_tkr.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi_mpifh.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libmpi.so.40]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libiomp5.so]
 0x0000000000000001 (NEEDED)             Shared library: [libreadline.so.7]
 0x0000000000000001 (NEEDED)             Shared library: [libgomp.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x000000000000001d (RUNPATH)            Library runpath: [/home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib]
 0x000000000000000c (INIT)               0x415ac0
 0x000000000000000d (FINI)               0x50a438
 0x0000000000000019 (INIT_ARRAY)         0x809b28
 0x000000000000001b (INIT_ARRAYSZ)       16 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x809b38
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x4002d0
 0x000000006ffffef5 (GNU_HASH)           0x402858
 0x0000000000000005 (STRTAB)             0x40cf70
 0x0000000000000006 (SYMTAB)             0x404f30
 0x000000000000000a (STRSZ)              27725 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x810000
 0x0000000000000002 (PLTRELSZ)           3696 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x414c50
 0x0000000000000007 (RELA)               0x4147a0
 0x0000000000000008 (RELASZ)             1200 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x414670
 0x000000006fffffff (VERNEEDNUM)         6
 0x000000006ffffff0 (VERSYM)             0x413bbe
 0x0000000000000000 (NULL)               0x0
10:52 AM->lovelace:bmad_dist_20241118-0 ldd $(which tao)
	linux-vdso.so.1 (0x00007ffcbbf2f000)
	libtao.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libtao.so (0x00007f105ed51000)
	libbmad.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libbmad.so (0x00007f105dfdc000)
	libsim_utils.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libsim_utils.so (0x00007f105dc7d000)
	../../production/lib/libpgplot.so => not found
	libxrlf03.so.11 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libxrlf03.so.11 (0x00007f105da59000)
	libxrl.so.11 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libxrl.so.11 (0x00007f105c81a000)
	libforest.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libforest.so (0x00007f105bdb3000)
	libfgsl.so.1 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libfgsl.so.1 (0x00007f105bb0c000)
	libgsl.so.27 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libgsl.so.27 (0x00007f105b62e000)
	libgslcblas.so.0 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libgslcblas.so.0 (0x00007f105b3ef000)
	liblapack95.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/liblapack95.so (0x00007f105ad7a000)
	liblapack.so.3 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/liblapack.so.3 (0x00007f105a2bb000)
	libblas.so.3 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libblas.so.3 (0x00007f105a01f000)
	libhdf5hl_fortran.so.310 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libhdf5hl_fortran.so.310 (0x00007f1059df2000)
	libhdf5_hl.so.310 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libhdf5_hl.so.310 (0x00007f1059bd1000)
	libhdf5_fortran.so.310 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libhdf5_fortran.so.310 (0x00007f1059951000)
	libhdf5.so.310 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libhdf5.so.310 (0x00007f105936a000)
	libfftw3.so.3 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libfftw3.so.3 (0x00007f1059068000)
	libfftw3_omp.so.3 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libfftw3_omp.so.3 (0x00007f1058e61000)
	libmpi_usempif08.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libmpi_usempif08.so.40 (0x00007f1058c04000)
	libmpi_usempi_ignore_tkr.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libmpi_usempi_ignore_tkr.so.40 (0x00007f10589f0000)
	libmpi_mpifh.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libmpi_mpifh.so.40 (0x00007f1058786000)
	libmpi.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libmpi.so.40 (0x00007f1058446000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f1058103000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f1057d6e000)
	libiomp5.so => /opt/intel/oneapi/compiler/2024.2/lib/libiomp5.so (0x00007f1057986000)
	libreadline.so.7 => /lib64/libreadline.so.7 (0x00007f1057737000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f10574ff000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f105717d000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1056f5d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1056b98000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f105f4c8000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1056980000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f105677c000)
	../../production/lib/libpgplot.so => not found
	libifport.so.5 => /opt/intel/oneapi/compiler/2024.2/lib/libifport.so.5 (0x00007f105f6aa000)
	libifcoremt.so.5 => /opt/intel/oneapi/compiler/2024.2/lib/libifcoremt.so.5 (0x00007f105f53e000)
	libimf.so => /opt/intel/oneapi/compiler/2024.2/lib/libimf.so (0x00007f1056370000)
	libsvml.so => /opt/intel/oneapi/compiler/2024.2/lib/libsvml.so (0x00007f1054d2c000)
	libintlc.so.5 => /opt/intel/oneapi/compiler/2024.2/lib/libintlc.so.5 (0x00007f1054ccb000)
	libpgplot.so => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/sim_utils/../production/lib/libpgplot.so (0x00007f105483e000)
	libirc.so => /opt/intel/oneapi/compiler/2024.2/lib/libirc.so (0x00007f10547dd000)
	libirng.so => /opt/intel/oneapi/compiler/2024.2/lib/libirng.so (0x00007f10546e4000)
	libopen-rte.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libopen-rte.so.40 (0x00007f105442e000)
	libopen-pal.so.40 => /home/lovelace/BMAD_DIST/bmad_dist_20241118-0/production/lib/libopen-pal.so.40 (0x00007f105412e000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f1053f26000)
	libutil.so => /lib64/libutil.so (0x00007f1053d22000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f1053b0b000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f10538e2000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f10536b5000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f10534b1000)

**Comment by jsberg-bnl** [comment]
OK, looks like pgplot got put on the link command line in a funky way. Let me investigate...

**Comment by jsberg-bnl** [comment]
Problem is that no SONAME is set on `libpgplot.so` when it is built, the link puts the full path to pgplot on the command line, and so that full path gets encoded into the executable. And someone set `DIST_BASE_DIR` to a relative directory when they did the build... Will make a PR into https://github.com/bmad-sim/bmad-external-packages.

**Comment by DavidSagan** [comment]
@jsberg-bnl Much thanks for diagnosing this and I await the PR.
