### ISSUE TITLE
`graph%x%min` and `graph%x%max` setting does not work

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1289]
**Describe the bug**
Setting the graphs `x%min` and `x%max` in `tao_plot.init` does not work.

**Minimal Working Example**
Call `tao -lat arc.bmad` with the provided files.

**To Reproduce**
See plot page

**Expected behavior**
Should be changing x scale

**Compiler and Operating system**
gfortran, MacOS
[Archive.zip](https://github.com/user-attachments/files/17753960/Archive.zip)

**Comment by DavidSagan** [comment]
Fixed.
