### ISSUE TITLE
BUG: Tao refuses to start when the reference particle is lost

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#1297]
**Describe the bug**
If the reference particle is lost, Tao quits immediately. This is frustrating because the problem could be fixed within Tao.

**To Reproduce**

`lat.bmad`:
```
beginning[beta_a] = 10
beginning[beta_b] = 10
beginning[e_tot] = 5e6

parameter[geometry] = open
parameter[absolute_time_tracking] = T

cav: lcavity, L = 1, voltage = 10e6, rf_frequency=1e9, phi0 = 0.2

linac: line[multipass] = (cav)

p1: pipe, L = 0

lat: line = (linac, p1, linac)

use, lat
```

```
tao -lat lat.bmad
[MESSAGE | 2024-NOV-15 14:21:19] tao_init:
    OpenMP active with number of threads: 10
[FATAL | 2024-NOV-15 14:21:19] ele_compute_ref_energy_and_time:
    PARTICLE LOST IN TRACKING: CAV\2
    CANNOT COMPUTE REFERENCE TIME & ENERGY.
[ERROR | 2024-NOV-15 14:21:19] lat_compute_ref_energy_and_time:
    CANNOT COMPUTE REFERENCE ENERGY FOR: CAV\2
    REFERENCE ENERGY NOT COMPUTED FOR REST OF LATTICE
[FATAL | 2024-NOV-15 14:21:19] tao_init_lattice:
    PARSER ERROR DETECTED FOR UNIVERSE: 1
    EXITING...
```

**Expected behavior**
Tao should start. Note that if we set `p1[L] = 1` in the lattice, start tao, and then set it to zero, tao still runs:

```
Tao> set ele p1 L = 0
[FATAL | 2024-NOV-15 14:22:36] ele_compute_ref_energy_and_time:
    PARTICLE LOST IN TRACKING: CAV\2
    CANNOT COMPUTE REFERENCE TIME & ENERGY.
[ERROR | 2024-NOV-15 14:22:36] lat_compute_ref_energy_and_time:
    CANNOT COMPUTE REFERENCE ENERGY FOR: CAV\2
    REFERENCE ENERGY NOT COMPUTED FOR REST OF LATTICE
tao_single_track: particle lost in single particle tracking at branch>>element 0>>3: CAV\2  [s =     2.00]
[FATAL | 2024-NOV-15 14:22:36] ele_compute_ref_energy_and_time:
    PARTICLE LOST IN TRACKING: CAV\2
    CANNOT COMPUTE REFERENCE TIME & ENERGY.

Tao> 
```

**Compiler and Operating system**
gcc14 with macOS 15.1

**Comment by DavidSagan** [comment]
@ChristopherMayes The problem is that when the reference energy cannot be computed initially, the reference energy is not set and this will cause a lot of divide by zero  and segmentation fault issues later which will bomb the program anyway. The reason why Tao survives when you set `p1[L] = 0` after starting Tao is due to the old reference energy numbers still being in place. I don't see a good way to get around this.

**Comment by ChristopherMayes** [comment]
@DavidSagan did you do something about this?

**Comment by DavidSagan** [comment]
No. I don't know a good way to handle this.

**Comment by ChristopherMayes** [comment]
Could we keep this then as an open issue? It's not solved.

**Comment by DavidSagan** [comment]
I use the issues to organize what I need to do so having stuff like this remain open wastes my time. Instead I have created a new label `Unresolved` which can be used for searching and in fact is a better solution since this makes finding unresolved issues easier.

**Comment by ken-lauer** [comment]
You might consider organizing issues into projects:
* https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects
* https://github.com/bmad-sim/bmad-ecosystem/projects

**Comment by DavidSagan** [comment]
Yes definitely a good thought.
