### ISSUE TITLE
Calls to sprint_spin_taylor_map should always pass in reference orbit

### ISSUE THREAD

**Issue by JosephPeterDevlin** [bmad-sim/bmad-ecosystem#1302]
Currently, start_orb is not being passed in as the reference orbit for sprint_spin_taylor_map in track1_spin_taylor.f90. Additionally, it should be checked that the reference orbit is being handled properly in spin_concat_linear_maps.f90 and the subroutine ele_to_taylor.

**Comment by DavidSagan** [comment]
OK try it now...
