### ISSUE TITLE
`pipe wall3d_radius` type names should indicate arrays and not scalars

### ISSUE THREAD

**Issue by ken-lauer** [bmad-sim/bmad-ecosystem#1308]
**Describe the bug**

For `pipe wall3d_radius`, pytao expects array-valued floats to have a type of `REAL_ARR` and not simply `REAL`. These two lines should be `REAL_ARR` instead:

https://github.com/bmad-sim/bmad-ecosystem/blob/b33b6bd8ed75d81d0b55e9d11381a43aedc538e7/tao/code/tao_pipe_cmd.f90#L7881-L7882

**Minimal Working Example**

```
Tao> reinit tao -clear -init '$ACC_ROOT_DIR/regression_tests/pipe_test/tao.init_wall3d' -noplot
Tao> pipe wall3d_radius 1@0 0.0 0.0
wall_radius;REAL;F;  2.90909090909091E+00
origin;REAL;F;  1.00000000000000E+00;  2.00000000000000E+00;  0.00000000000000E+00
perpendicular;REAL;F;  9.09090909090909E-01; -1.00000000000000E+00;  0.00000000000000E+00
```

**Comment by DavidSagan** [comment]
Fixed.
