### ISSUE TITLE
`P_dk` discontinuous jump when passing over half-integer spin tune

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1314]
**Describe the bug**
![Screenshot 2024-11-20 at 4 14 43 PM](https://github.com/user-attachments/assets/8fe63162-37c5-4b60-b252-37e25c31b3dc)

When the spin tune passes over the half integer, there is a discontinuous jump in P_dk. I do not see this with older versions (6-7-8 months ago or so it's been a while) for this same lattice.

**Minimal Working Example**
`show spin` is now very slow even with SPRINT tracking #1265 . Nonetheless I calculate this scan using `python spin_polarization` which fortunately is fast still. So I would `set ele 0 e_tot` to values around a*gamma = 40.5 and see the jump. Or you could use [Tao.jl](https://github.com/bmad-sim/Tao.jl) and run the documented `pol_scan` function.

**Comment by mattsignorelli** [comment]
[esr-main-unique-1IP-CS-1.bmad.zip](https://github.com/user-attachments/files/17837035/esr-main-unique-1IP-CS-1.bmad.zip)
Here's the lattice

**Comment by mattsignorelli** [comment]
OK i determined the problem. It is the sign of the ST + kinetic term after passing over the half integer closed orbit spin tune.

With the new attached lattice below if you do `set ele 0 e_tot = 1.784627E+10`, then `show spin` you get:
```
a_anomalous_moment * gamma = 40.5
E_tot = 1.78463E+10
Spin Tune    0.499967rad/2pi
bmad_com%spin_tracking_on                = T

spin_tune:      4.9998805E-01
Polarization Limit ST:                     0.87646802
Polarization Limit DK:                     0.66687436
Polarization Limits DK (a,b,c-modes):      0.86540169  0.83726019  0.66405758
Polarization Limits DK (bc,ac,ab-modes):   0.66013140  0.67032360  0.82797114
Polarization Time BKS (minutes, turns):         36.3  1.7019E+08
Depolarization Time (minutes, turns):            127  5.9355E+08
Depolarization Time (a-mode) (minutes, turns):        2914  1.3671E+10
Depolarization Time (b-mode) (minutes, turns):         781  3.6636E+09
Depolarization Time (c-mode) (minutes, turns):         124  5.8065E+08
Depolarization Time (b&c modes) (minutes, turns):         121  5.6670E+08
Depolarization Time (a&c modes) (minutes, turns):         129  6.0657E+08
Depolarization Time (a&b modes) (minutes, turns):         627  2.9424E+09
Integral g^3 * b_hat * n_0:             9.1087E-05
Integral g^3 * b_hat * dn/ddelta:       1.9097E-06
Integral g^3 (1 - 2(n * s_hat)/9):      9.6002E-05
Integral g^3 * 11 (dn/ddelta)^2 / 9:    2.7527E-05
```

Then if you do `set ele 0 e_tot = 1.784628E+10` and a `show spin` you get

```
a_anomalous_moment * gamma = 40.5
E_tot = 1.78463E+10
Spin Tune    0.499989rad/2pi
bmad_com%spin_tracking_on                = T

spin_tune:      4.9998953E-01
Polarization Limit ST:                     0.87646802
Polarization Limit DK:                     0.69543787
Polarization Limits DK (a,b,c-modes):      0.86598035  0.83785800  0.69154433
Polarization Limits DK (bc,ac,ab-modes):   0.68794586  0.69853677  0.82911627
Polarization Time BKS (minutes, turns):         36.3  1.7019E+08
Depolarization Time (minutes, turns):            127  5.9356E+08
Depolarization Time (a-mode) (minutes, turns):        2914  1.3671E+10
Depolarization Time (b-mode) (minutes, turns):         781  3.6636E+09
Depolarization Time (c-mode) (minutes, turns):         124  5.8066E+08
Depolarization Time (b&c modes) (minutes, turns):         121  5.6670E+08
Depolarization Time (a&c modes) (minutes, turns):         129  6.0658E+08
Depolarization Time (a&b modes) (minutes, turns):         627  2.9424E+09
Integral g^3 * b_hat * n_0:            -9.1087E-05
Integral g^3 * b_hat * dn/ddelta:       1.9096E-06
Integral g^3 (1 - 2(n * s_hat)/9):      9.6002E-05
Integral g^3 * 11 (dn/ddelta)^2 / 9:    2.7527E-05
```

Look at the integrals at the bottom specifically, the sign has flipped for the `Integral g^3 * b_hat * n_0` (Sokolov Ternov) but NOT for `Integral g^3 * b_hat * dn/ddelta` (kinetic polarization). Doing a `show spin -ign` for the above two energies to ignore the kinetic term gives equivalent results.

New lattice
[esr-BAGELed.bmad.zip](https://github.com/user-attachments/files/17962526/esr-BAGELed.bmad.zip)

**Comment by DavidSagan** [comment]
Fixed.
