### ISSUE TITLE
`pipe space_charge_com` `diagnostic_output_file` quoted

### ISSUE THREAD

**Issue by ken-lauer** [bmad-sim/bmad-ecosystem#1317]
**Describe the bug**
`pipe space_charge_com` has a key of `diagnostic_output_file` with a value that is quoted:

https://github.com/bmad-sim/bmad-ecosystem/blob/6048d2ef8419517256ddca50cc394bace7a4b3ef/tao/code/tao_pipe_cmd.f90#L6814

**To Reproduce**

```bash
$ tao -init $ACC_ROOT_DIR/bmad-doc/tao_examples/erl/tao.init
Tao> pipe space_charge_com
...
diagnostic_output_file;STR;T;""
```

**Expected behavior**

To be consistent with all other `STR` values in `pipe` commands, the quotes should be removed.

**Comment by DavidSagan** [comment]
Fixed.
