### ISSUE TITLE
long_term_tracking crashing with extraction output

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1329]
I am using the extraction tracking in long_term_tracking to get more first turn data while tracking. This crashes the program when data is being written. The tracking appears to finish. 

I am not using this for extraction tracking, so it is possible there is something it is looking for but cannot find. The error does not give any specific information. 

[extraction tracking.zip](https://github.com/user-attachments/files/17920836/extraction.tracking.zip)

**Comment by DavidSagan** [comment]
@jeu8 Can you show the error message? What happens if you run with the debug exe?

**Comment by jeu8** [comment]
the debug exe gives the same error:

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libifcore.so.5     00007F0AD97A8936  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00007F0ADB459630  Unknown               Unknown  Unknown
long_term_trackin  00000000008EE2BE  beam_mod_mp_track         285  beam_mod.f90
long_term_trackin  000000000042E928  lt_tracking_mod_m        1243  lt_tracking_mod.f90
long_term_trackin  00000000004055F6  MAIN__                     35  long_term_tracking.f90
long_term_trackin  000000000040510E  Unknown               Unknown  Unknown
libc-2.17.so       00007F0AD7804555  __libc_start_main     Unknown  Unknown
long_term_trackin  0000000000405019  Unknown               Unknown  Unknown

**Comment by DavidSagan** [comment]
Is this on a lab computer? If not, can you reproduce this error on a lab computer?

**Comment by jeu8** [comment]
This is on a lab computer

**Comment by DavidSagan** [comment]
Fixed.
