### ISSUE TITLE
`show spin` values *sometimes* changes with spin tracking method change

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1333]
This is very strange, incorrect behavior. Using the lattice attached, do `show spin`. Note the values, P_dk will. be around 50%

Now do `set ele * spin_tracking_method = sprint` , then do `show spin`. Unrelated, but it will still be slow per #1265  . Alternatively you can do `python spin_polarization` which for some reason is much faster.

Note the new values, P_dk about 40%,   a 10% difference in P_dk for sprint vs non sprint tracking. That feels a bit large, but could be correct because of all the quadrupoles (I compared with a commit from last February and had the same thing)

Now do `set ele * spin_tracking_method = tracking` to go back to the initial spin tracking method. Do `show spin` again and see that it did not go back to 50%, instead staying at 40%. same for `python spin_polarization` (which is equivalent but much faster)

[bug.bmad.zip](https://github.com/user-attachments/files/17963373/bug.bmad.zip)

**Comment by DavidSagan** [comment]
Fixed
