### ISSUE TITLE
Setting `plot_page%curve_legend%row_spacing` does not do anything

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#1334]
See attached files where I set the `row_spacing` to very large values and there are no differences in the plot

[Archive.zip](https://github.com/user-attachments/files/17970210/Archive.zip)

**Comment by DavidSagan** [comment]
What should be set is `default_graph%curve_legend%...`. But there was a problem in the code and documentation which is now fixed.
