### ISSUE TITLE
Unstable optics when using tune_scan

### ISSUE THREAD

**Issue by vdmkshkn** [bmad-sim/bmad-ecosystem#1343]
When running the tune_scan program I have unstable optics on the entire Qx-Qy area under study. 
At some points the program sees resonance, but cannot calculate the Twiss parameters at all other points.

```
[ERROR | 2024-DEC-06 08:30:07] twiss_from_mat6:
    BAD 1-TURN MATRIX: UNSTABLE A-MODE
    TWISS PARAMETERS NOT COMPUTED
```

At the same time, the Tao and long_term_tracking program behave perfectly and predictably. 
And this only happens with my lattice.
For a long time I thought that the problem was in my init file, since my colleagues from other institutes did not have such a problem.
The behavior is similar when RF is enabled.
[tune_scan_vepp4m.zip](https://github.com/user-attachments/files/18031791/tune_scan_vepp4m.zip)

**Comment by DavidSagan** [comment]
A mistake in the code meant that these messages were being printed (since the program was trying to set one of the tunes to the half integer). This will be corrected in the next release. Other than printing the spurious messages the program looks like it is running fine.
