### ISSUE TITLE
rad_int.i1 data type appears to not updating

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#1348]
while optimizing in Tao, it appears the rad_int.i1 data type does update. I have a lattice an open lattice with a few FODO cells and an init file with the initial dispersion and bend strength as variables. Both of these should have an effect, but when the optimizer is run, it does not change and says it is independent of the variables.

[I1_opt.zip](https://github.com/user-attachments/files/18159056/I1_opt.zip)

**Comment by DavidSagan** [comment]
Fixed.
