### ISSUE TITLE
OpenMPI build script error

### ISSUE THREAD

**Issue by mattgibbs** [bmad-sim/bmad-ecosystem#140]
In openmpi/acc_build_openmpi, there's a bug that prevents a pre-built version of OpenMPI from being used.  The script refers to the variables `major` and `minor` to check if the already-built version is compatible, but these variables aren't defined.  This is because the 'VERSION' file is only sourced as a sub-command for defining the `PACKAGE_VERSION`.  Taking `source ./VERSION` out of the sub-command and making it its own line seems to fix the problem.

**Comment by DavidSagan** [comment]
@mattgibbs Just to make sure there are no mistakes, can you attach the corrected version of acc_build_open_mpi which works for you so that it can be tested?  Thanks.

**Comment by mattgibbs** [comment]
Sure!  Here's my hacked-up version.
[acc_build_openmpi.txt](https://github.com/DavidSagan/Bmad/files/2797743/acc_build_openmpi.txt)

**Comment by attiliodefalco** [comment]
This issue was addressed in issue bmad-sim/bmad-ecosystem#141. and can be closed.  ~Attilio
