### ISSUE TITLE
multipole_ele_to_ab called repeatedly

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#145]
multipole_ele_to_ab calls take up a significant amount  of time (25% of the entire program time in one simulation) during tracking. If the multipole values in an element do not change, there would be a significant time savings if caching of the a/b values along with n_pole_max is implemented.

The major problem is making sure that if there are any changes to element parameters, cached values are not saved.

Proposal: 
1) Only use caching if  bmad_com%auto_bookkeeper = False. 
2) Store the cache in ele%cache which is a pointer.
```
 type ele_multipole_cache_struct
     logical valid
     real(rp) a_pole(0:n_pole_maxx), b_pole(0:n_pole_maxx)
     integer ix_pole_mag_max
     integer include_kicks   ! Store value of multipole_ele_to_ab arg. no$ include_kicks$, include_kicks_except_k1$
     real(rp) a_pole_elec(0:n_pole_maxx), b_pole_elec(0:n_pole_maxx)
     integer ix_pole_elec_max
 end type
```
3) Cache is reset (%valid -> False) if set_flags_for_changed_real_attribute is called.
4) Cache values are updated if value of %include_kicks is different
5) Check that bend exact multipoles are properly handled.

**Comment by ChristopherMayes** [comment]
[csr_beam_tracking2.txt](https://github.com/DavidSagan/Bmad/files/5145508/csr_beam_tracking2.txt)

This is better. The old one took 70 s.

**Comment by DavidSagan** [comment]
Fixed.
