### ISSUE TITLE
build failure of 2022_0830-0, debug build

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#158]
When I do `util/dist_build_production` followed by `util/dist_build_debug`, the debug build fails (the production build succeeded). Log files: [2022_0830-0-log.zip](https://github.com/DavidSagan/Bmad/files/9461789/2022_0830-0-log.zip). The only change to `util/dist_prefs` is `ACC_ENABLE_SHARED=Y`

**Comment by DavidSagan** [comment]
@jsberg-bnl Can you report this to Attilio?  -- Thanks

**Comment by DavidSagan** [comment]
Attilio has been notified.
