### ISSUE TITLE
`track_a_crab_cavity` jacobian matrix calculation missing derivative terms

### ISSUE THREAD

**Issue by jp-ga** [bmad-sim/bmad-ecosystem#159]
There are missing derivative terms in `track_a_crab_cavity` jacobian matrix calculation arising from $p_z$ dependence in $\beta$. The missing terms are: 

1. additional derivative terms in lines 73 and 74 arising from $p_z$ dependence in $\phi( t_{\mathrm{r.f.}}( z, \beta(p_z) ) )$
2. derivatives of z with respect to all the other coordinates are missing. They are non-trivial since there is $p_z$ dependence in the betas of the following transformation: $z_f = z_i * \frac{\beta_{old}}{\beta_{new}}$

**Comment by DavidSagan** [comment]
Fix by jp-ga now in Bmad. Thanks!
