### ISSUE TITLE
Add python command to grab any tao datum at an arbitrary s

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#184]
Feature request:
It would be good to be able to grab any datum in python that is available at an arbitrary s (essentially any datum allowing an s_offset). One of two options would be useful:
- datum_at_s, where a specific datum is given
- everything_at_s, which would output a dictionary of all available datum. This may be more efficient if you want multiple things at a given s.

**Comment by DavidSagan** [comment]
@jsberg-bnl Is the `@s_offset` syntax sufficient for this?

**Comment by jsberg-bnl** [comment]
Yes, that should be, thanks. And very useful from the tao command line, in expressions for data, etc.. Though something like `python everything_at_s` might be nice and more efficient in python if you want a bunch of things at the same place, though I would think everything_at_offset would be better (`python everything_at_offset ele offset`) since that avoids the search for which element is at `s` (and most of the time I know the element rather than its s position anyhow).

**Comment by DavidSagan** [comment]
How about twiss and orbit at ele+offset?

**Comment by jsberg-bnl** [comment]
Yes, that's good too. I tend to think in the Fortran world, where once you've gone through the trouble calling `twiss_and_track_intra_ele`, everything else is pretty much free, but it's probably much more expensive pushing it through to python...

**Comment by jsberg-bnl** [comment]
`@s_offset` works for a number, but not for an expression (OK, maybe I'm asking a bit much of it...):
```
Tao> sho val lat::floor_orbit.x[q2pr@0.5]
    -1.0734873082662855E+00

Tao> sho val lat::floor_orbit.x[q2pr@0.5*ele::q2pr[l]]
[ERROR | 2021-NOV-24 16:40:10] tao_evaluate_lat_or_beam_data:
    MANGLED CONSTRUCT: lat::floor_orbit.x[q2pr@0.5*ele::q2pr[l]]
[ERROR | 2021-NOV-24 16:40:10] tao_evaluate_expression:
    ERROR IN EXPRESSION: lat::floor_orbit.x[q2pr@0.5*ele::q2pr[l]]
    CANNOT EVALUATE: lat::floor_orbit.x[q2pr@0.5*ele::q2pr[l]]
```

**Comment by jsberg-bnl** [comment]
Even `@number` is useful in python; expressions are more for command-line tao.

**Comment by DavidSagan** [comment]
Actually it does work for expressions but I'm guessing that an offset expression with "[]" in it is confusing the expression evaluator. I will look into it...

**Comment by DavidSagan** [comment]
@jsberg-bnl Problem with using "@" to separate s-position is that with a python command if you have a syntax which is something like 
  {ix_uni}@{ele}@s_offset
Then "1@1" is ambiguous. Could use "$".  Or use a different python syntax. What do you think?

**Comment by DavidSagan** [comment]
Other possible characters to delimit the s_offset are "%" and "?". "%" is used with name wildcards so I'm not too crazy about using that symbol here. Another possibility is to use two characters like "->"

This is what using these symbols could look like:

show value lat::orbit.x[10?ele::10[L]]
python 1@q10w?3.4

show value lat::orbit.x[10%ele::10[L]]
python 1@q10w%3.4

show value lat::orbit.x[10$ele::10[L]]
python 1@q10w$3.4

show value lat::orbit.x[10->ele::10[L]]
python 1@q10w->3.4

**Comment by DavidSagan** [comment]
OK I made the executive decision to go for "->"

**Comment by DavidSagan** [comment]
@jsberg-bnl Try it now...
