### ISSUE TITLE
Feature suggestion: extend ->s_offset syntax to include beg/cen/end

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#188]
What would you think of extending the `->s_offset` syntax to include the beginning/center/end reference point? It would look like

```
lat::datum[ele->loc{+,-}s_offset]
```
where `loc` is `beg[inning]`, `cen[ter]`, or `end` (brackets indicate optional additional characters). If `{+,-}s_offset` is missing, take it to be zero, and if `loc{+,-}` is missing, then the (annoying but consistent) default of `end` is used.

One thing to watch out for here if you the obvious thing: if someone writes `cen-a+b`, is that interpreted as the location `0.5*L-a+b` within the element or `0.5*L-(a+b)`? The latter is what you would get if you just load everything after `loc{+,-}` into the s_offset slot, but the former is probably the expected behavior, but less trivial to code.

My reason for the request is that what I want to do virtually all the time is either `lat::datum[ele->beg+s_offset]` or `lat::datum[ele->cen]`. Of course all of this is soluble with fairly simple expressions if this is difficult to implement.

**Comment by DavidSagan** [comment]
You can use "ele-1" to get the beginning of the element. I will think about how to reference the center.

**Comment by DavidSagan** [comment]
How about `L` representing the element length so that `ele->-L/2` references the center?

**Comment by DavidSagan** [comment]
@jsberg-bnl  Since it was easy to program, the defaulting of parameters like "L" that do not have an explicit element reference, to be parameters of the evaluation element is now implemented.

**Comment by jsberg-bnl** [comment]
I'm finding two issues with this at this point:
1. Using `L` in the expression doesn't seem to be working in svn
2. It seems like if the chosen offset overruns the element, to use the next element down the line. I'm not sure this is the best behavior for `s_offset` (does it always behave like that, even when evaluating a datum?). I would have wanted it to always stay within the element. My problem example was with an element immediately preceded by a patch:
```
Tao> sho val lat::floor.z[q2pf]-0.5*ele::q2pf[l]*cos(lat::floor.theta[q2pf])-lat::floor.z[q2pf->-0.5*ele::q2pf[l]]
     0.0000000000000000E+00

Tao> sho val lat::floor.z[q2pf]-ele::q2pf[l]*cos(lat::floor.theta[q2pf])-lat::floor.z[q2pf->-ele::q2pf[l]]
    -1.1290086712634206E-04

Tao> sho val lat::floor.z[q2pf-2]-lat::floor.z[q2pf->-ele::q2pf[l]]
     0.0000000000000000E+00
```
The first calculation shows it does the right thing for the middle of the element. The next calculation shows it doesn't do what I expected for the beginning of the element. The third calculation shows why: apparently it decided that my s_offset overran q2pf, so it moved on to the next element upstream (zero-length patch), then continued to the element before that.
