### ISSUE TITLE
Elements with # in their name in attribute expressions for show lattice

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#190]
Say I do the following:
```show lattice -attribute s-ele::cqs05y11#1[s]```
where `cqs05y11#1` is an actual tracking element name (resulting from an element split by a superposition). `#` is replaced by the element number for each line and this fails. The fix would be to only do the replacement of `#` when it is not part of a word, but that would require you to parse before doing the replacement, which might be easier said than done.
This is not critical, it can be worked around, it's a convenience issue.

**Comment by DavidSagan** [comment]
Could do something like "\\#" would mean do not substitute. Would that do?

**Comment by jsberg-bnl** [comment]
That would be great (in fact I tried it just in case it might work...)

**Comment by DavidSagan** [comment]
@jsberg-bnl OK it has been implemented.
