### ISSUE TITLE
set symbol unhappy with white space between symbol and =

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#192]
```
Tao> set sym ke = 10e6
[ERROR | 2021-DEC-20 10:26:29] tao_command:
    SYNTAX PROBLEM. "=" NOT IN CORRECT PLACE.

Tao> set sym ke= 10e6

Tao>
```

**Comment by DavidSagan** [comment]
Problem was that "ke" looks like "key" and there is a "set key" command which is confusing Tao. I have put in a fix

**Comment by jsberg-bnl** [comment]
Latest svn doesn't seem to fix this.

**Comment by DavidSagan** [comment]
Strange. The fix works for me.

**Comment by jsberg-bnl** [comment]
Ack! My mistake, I thought I was running the svn version but actually wasn't. Sorry...
