### ISSUE TITLE
"show value lat::chrom.a" gives outdated values until "show universe" is executed

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#197]
If I load a lattice, make modifications, then `show value lat::chrom.a`, the value returned seems to be from the design lattice. Once I execute `show universe`, then `sho value lat::chrom.a` gives the correct value for the model lattice.

**Comment by DavidSagan** [comment]
@jsberg-bnl Bookkeeping problem is fixed.

**Comment by jsberg-bnl** [comment]
svn is still showing the same behavior.

**Comment by jsberg-bnl** [comment]
Ack! My error, thought I was running svn but I was running the release. It's fixed, sorry, thanks.
