### ISSUE TITLE
Documentation: to set the reference particle species, you need to say "set branch particle = ..."

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#198]
The documentation for `set branch` implies that you can look at the output of `show branch` to know what to set. `show branch` lists the reference particle species under `ref_particle`, but if you try `set branch ref_particle = ...` it fails; you need to say `set branch particle = `. The correct syntax should be documented somewhere (unless I just didn't find it...).

**Comment by DavidSagan** [comment]
Manual updated.
