### ISSUE TITLE
Pattern matching problem: var::*y|model

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#199]
There seems to be a pattern matching issue with `*` as part of a pattern. If I have some variables ending in `y`, then `sho var *y` seems to work fine. `sho val var::*|model` works fine. But `sho val var::*y|model` fails with 
```
Tao> sho val var::*y|model
[ERROR | 2022-FEB-04 10:23:06] tao_find_var:
    VARIABLE NAME IS BLANK
[ERROR | 2022-FEB-04 10:23:06] tao_evaluate_expression:
    ERROR IN EXPRESSION: var::*y|model
    CANNOT EVALUATE: var::
```

**Comment by DavidSagan** [comment]
Fixed. Yes it was a pattern matching issue.

**Comment by jsberg-bnl** [comment]
Working correctly, thanks!
