### ISSUE TITLE
Tao hardcoded version

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#2]
The Tao code has a hardcoded version. This should somehow be linked to a tag or release.

https://github.com/bmad-sim/bmad-ecosystem/blob/e16884769705976d2128fb95441a50c5f599985e/tao/version/tao_version_mod.f90#L9

**Comment by DavidSagan** [comment]
Fixed.

**Comment by DavidSagan** [comment]
PR #500
