### ISSUE TITLE
Offset/rotate bend with mat6_calc_method=symp_lie_ptc fails

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#202]
See attached example: [220314a.txt](https://github.com/DavidSagan/Bmad/files/8248766/220314a.txt); I get a bunch of messages like
```
[ERROR | 2022-MAR-14 18:00:36] s:
    singular matrix
```
`tracking_method=symp_lie_ptc` by itself seems fine. If I set the offset/rotation to zero it's fine.

**Comment by jsberg-bnl** [comment]
And no error on the debug build

**Comment by DavidSagan** [comment]
Interesting I am able to reproduce with debug gcc but not production. And ifort does not show a problem. I will work on it...

**Comment by jsberg-bnl** [comment]
Actually, it turns out the error is also present in my debug build, it's just less chatty about it. It manifests in NaNs for the twiss functions/matrix.

**Comment by jsberg-bnl** [comment]
Looks like the problem is only for bends.

**Comment by jsberg-bnl** [comment]
I think I've fixed the bug: in ptc_midalign_fibre, o_chord is not initialized for an sbend when the offsets are nonzero; here's the patch for that:
```
Index: bmad/interface/ptc_interface_mod.f90
===================================================================
--- bmad/interface/ptc_interface_mod.f90        (revision 51989)
+++ bmad/interface/ptc_interface_mod.f90        (working copy)
@@ -3850,6 +3850,7 @@

     dr = [ele%value(x_offset_tot$), ele%value(y_offset_tot$), ele%value(z_offset_tot$)]
     if (any(dr /= 0)) then
+      o_chord = ptc_fibre%mag%p%f%o
       o_arc = o_chord + sagitta * ptc_fibre%mag%p%f%mid(1,1:3)
       basis = orient
       x = 0
```
At least I think that's right, I haven't thought through carefully what it's supposed to be doing.

**Comment by DavidSagan** [comment]
Good catch! The fix is in the SVN repository.
