### ISSUE TITLE
memory leak of magnet_frame in misalign_girder, possibly other places

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#203]
In `misalign_girder` (`forest/code/Sma_multiparticle.f90`), there is a pair `call alloca(f)` and `call kill(f)`. The issue is that `kill(f)` (really `dealloc_f` in `Sd_frame.f90`) deallocates the pointer structures within `f`, but does not deallocate `f` itself. There are similar problems in other calls to that function; but there are also places the caller manually does the `deallocate(f)`. I'm assuming that the caller is supposed to be responsible for doing the deallocate, but I suppose that's a question to Etienne.

**Comment by DavidSagan** [comment]
Etienne fixed this.
