### ISSUE TITLE
Problems with fixed-step-runge-kutta tracking

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#209]
There seem to be at least one, maybe multiple, issue(s) with tracking_method=fixed_step_runge_kutta. There seems to be an issue with patches, maybe reversed em_field elements, and maybe superimposed elements having num_steps=0 for some reason? Start by packing this example: [hsr-ir6-9fb900a.zip](https://github.com/DavidSagan/Bmad/files/8374045/hsr-ir6-9fb900a.zip). Then
```
set ele * tracking_method = fixed_step_runge_kutta
```
I get the following complaint on one of the patches (not the first!):
```
[ERROR | 2022-MAR-29 14:27:19] odeint_bmad:
    STEP SIZE IS TOO SMALL OR TOO MANY STEPS WHILE TRACKING THROUGH: PB_B1APF
    AT (X,Y,Z) POSITION FROM ENTRANCE:    0.0369611   0.0000000   0.0000000
    TYPICALLY THIS IS DUE TO THE FIELD NOT OBEYING MAXWELL'S EQUATIONS.
    [OFTEN TIMES THE FIELD IS NOT EVEN BE CONTINUOUS IN THIS CASE!]
    THE PARTICLE WILL BE MARKED AS LOST.
tao_single_track: particle lost in single particle tracking at branch>>element 0>>120: PB_B1APF  [s =   -22.08]
```
Next, try
```
set default universe=1
set ele * tracking_method = fixed_step_runge_kutta
```
I now get complaints like this:
```
[ERROR | 2022-MAR-29 14:29:07] odeint_bmad:
    STEP SIZE IS TOO SMALL OR TOO MANY STEPS WHILE TRACKING THROUGH: YO5_TV5\YO5_OCT5\YO5_DEC5\YO5_QS5
    AT (X,Y,Z) POSITION FROM ENTRANCE:    0.0000000   0.00000002000.5000000
    TYPICALLY THIS IS DUE TO THE FIELD NOT OBEYING MAXWELL'S EQUATIONS.
    [OFTEN TIMES THE FIELD IS NOT EVEN BE CONTINUOUS IN THIS CASE!]
    THE PARTICLE WILL BE MARKED AS LOST.
```
Note that all elements are reversed in this universe. Also note that those superimposed elements have num_steps=0 for some reason.
But in universe 3 (no reverse elements, fewer patches), everything seems to be fine.
```
set default universe=3
set ele * tracking_method = fixed_step_runge_kutta
```

**Comment by DavidSagan** [comment]
Fixed step RK in a patch does not make sense so that is one thing that needs to be fixed....

**Comment by jsberg-bnl** [comment]
I still seem to have problems if I set the tracking method to bmad_standard for the patches, however.

**Comment by DavidSagan** [comment]
I put in a fix for everything.

**Comment by jsberg-bnl** [comment]
Working now, thanks!
