### ISSUE TITLE
Scalar-to-array syntax for "set lat_layout ele_shape(..."

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#213]
I wanted to disable labels on all elements in a lattice layout, so I tried
```
set lat_layout ele_shape(1:30)%label = 'none'
```
which didn't work (only sets the first element). It seems that 
```
set lat_layout ele_shape(15:16)%label = 'none' 'none'
```
does work, but it would be convenient if the scalar-to-array syntax in the first did (this sort of things seems to work elsewhere in tao).

**Comment by DavidSagan** [comment]
Try:
> set lat_layout ele_shape(1:30)%label = 30*'none'

See the Tao manual discussion of namelist input (beginning of initialization chapter) for more details. I will modify the Tao manual doc on the "set lat_layout" command to explicitly discuss this.

**Comment by jsberg-bnl** [comment]
Unfortunately that sets the label for the first shape to `30*'none'` and leaves the other shapes untouched.

**Comment by jsberg-bnl** [comment]
```
Tao> set lat_layout ele_shape(1:30)%label = 30*'none'

Tao> sho plot -lat_layout

Element Shapes:
                                                                                       Shape   Type    Shape  Multi  Line_
                  Ele_Name                            Shape           Color             Size  Label     Draw  Shape  Width
                  ------------------------------      ----------      -------           ----  -------  -----  -----  -----
ele_shape(1) =    "fork::*"                           "circle"        "red"              0.1  "30*'non    T     F      1
ele_shape(2) =    "crystal::*"                        "circle"        "red"              0.1  "name"      T     F      1
```

**Comment by jsberg-bnl** [comment]
By the way, the following in tao.init also failed to do anything:
```
&lat_layout_drawing
 include_default_shapes = t
 ele_shape(1:10)%label = 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none'
 ele_shape(11:20)%label = 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none'
 ele_shape(21:30)%label = 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none' 'none'
/
```
In hindsight, this is not too surprising, but the example in 10.13.9 in the manual implies that it would do something (note the `include_default_shapes = t` in the example)

**Comment by DavidSagan** [comment]
The problem with the set command was due to a bug in Tao (only affected string parameters). This has been fixed. 

The issue of setting the label in the lat_layout_drawing is that "ele_shape" refers to the non-default shapes only so if you defined non-default shapes you would see an effect. There is no mechanism to set the default shapes from within the lat_layout_drawing.

**Comment by jsberg-bnl** [comment]
That didn't quite work (built from svn):
```
Tao> set lat_layout ele_shape(1:30)%label = 'none'

Tao> set lat_layout ele_shape(1:30)%label = 30*'none'
[ERROR | 2022-APR-21 12:14:24] tao_set_drawing_cmd:
    BAD COMPONENT OR NUMBER
```

**Comment by DavidSagan** [comment]
Looks like a problem with gfortran. Ifort works fine. There have been problems in the past with gfortran and namelist arrays so this is not too surprising.

**Comment by DavidSagan** [comment]
Looks like there is nothing else to be done so I will close the issue.

**Comment by jsberg-bnl** [comment]
That makes sense; you're probably using list-directed formatting which probably uses the same code in gfortran as namelist formatting, and thus is equally broken.

**Comment by DavidSagan** [comment]
Correct.
