### ISSUE TITLE
Setting a precise number of divisions in a plot

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#214]
According to the quick plot documentation, if I want to set a precise number of major divisions, I should set `major_div_nominal` to zero or negative, and `major_div` to the value that I want. The problem is:
```
Tao> set graph beta.g x%major_div_nominal=0
[ERROR | 2022-APR-21 12:08:16] tao_set_integer_value:
    x VALUE TOO SMALL.
```

**Comment by DavidSagan** [comment]
Fixed.

**Comment by jsberg-bnl** [comment]
So, it now accepts the syntax, but you get odd behavior when you then try to set `x%major_div`:
```
Tao> set graph beta.g x%major_div_nominal=0

Tao> sho graph beta.g
...
x%major_div                      = 4
x%major_div_nominal              = 0
...
Tao> set graph beta.g x%major_div=6

Tao> sho graph beta.g
...
x%major_div                      = 4
x%major_div_nominal              = 6
```

**Comment by DavidSagan** [comment]
Fixed. Tao was being helpful in also setting major_div_nominal when you set major_div but Tao should not have set major_div_nominal if it was not positive.

**Comment by jsberg-bnl** [comment]
All working, thanks!
