### ISSUE TITLE
Allow "set universe" to take a list of universes with the usual notation

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#215]
A feature request if possible without too much effoet: it would be nice to be able to say `set universe 1,10:20 on`, along with the other `set universe` options (`recalculate`, etc.).

**Comment by DavidSagan** [comment]
Updated code so that `set uni [1,10:20] on` will work.

**Comment by jsberg-bnl** [comment]
Works great, thanks!
