### ISSUE TITLE
In tao, call exits when an error occurs

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#218]
See issue bmad-sim/bmad-ecosystem#217. The reason I used two command files rather than one is that if I combined them, the command file stops executing after the `read lattice` command. I'm assuming this is because that command had errors? Is that the correct behavior? If so it should be documented.

**Comment by DavidSagan** [comment]
Yes the errors caused the command file abort. Looking at the code I find that there are a number of places where there should be an abort on error. I will work on this...

**Comment by DavidSagan** [comment]
Now the info message on a command file abort is more informative.
