### ISSUE TITLE
Something goes wrong getting chromaticity through the python command

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#219]
Seems I have to use `show value lat::chrom.a` before trying to get it with `python evaluate lat::chrom.a`:
```
Tao> python evaluate lat::chrom.a
[ERROR | 2022-MAY-09 19:18:05] tao_evaluate_expression:
    ERROR IN EXPRESSION: lat::chrom.a
    CANNOT EVALUATE: lat::chrom.a
[ERROR | 2022-MAY-09 19:18:05] tao_python_cmd:
    "python evaluate lat::chrom.a": Invalid expression
INVALID
Tao> sho val lat::chrom.a
    -9.8050099202069418E+01
Tao> python evaluate lat::chrom.a
1; -9.80500992020694E+01
```

**Comment by DavidSagan** [comment]
I'm not seeing this error with both ifort and gfortran. Can you reproduce on a lab machine?

**Comment by jsberg-bnl** [comment]
Yes, I see it on CLASSE systems; I've put an example in `/cdat/tem/jsberg/220510a`; just run tao then execute the commands as above.

**Comment by DavidSagan** [comment]
Looks like the problem depends upon an open lattice being switched to closed ...

**Comment by DavidSagan** [comment]
Fixed. Was a bookkeeping issue.
