### ISSUE TITLE
Invalid "set ptc_com" command in tao sends tao off into an endless loop

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#222]
`set ptc_com taylor_order_ptc=5` causes tao to print out an infinite number of these:
```
[ERROR | 2022-MAY-20 09:25:45] tao_next_switch:
    UNKNOWN SWITCH: ptc_com
```
This points to the related problem that I'm not sure how to set ptc_com parameters in tao.

**Comment by DavidSagan** [comment]
`set ptc_com` is now fixed. 

Another issue is that taylor_order_ptc is not supposed to be directly set. Rather set bmad_com[taylor_order]. To make sure there is no confusion, taylor_order_ptc (and some other parameters that should not be set by the user) have been moved to their own structure called ptc_private.
