### ISSUE TITLE
Have tao indicate which universe caused an error

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#228]
It would be really helpful if when an error occurs, there were some indication of what universe caused the error. I suppose it's easier said than done, since somehow universe information needs to get pushed into Bmad's error reporting mechanism. 

If that's difficult to implement, one possible option would be a chatty debug option to have it print "universe #" as tao processes each universe; that would produce a ton of output, but you could turn it on from the command line when you need to debug.

**Comment by DavidSagan** [comment]
This is something that is solved on a case-by-case basis. So if any error message is unclear for any reason please open an issue for that error message.

**Comment by jsberg-bnl** [comment]
OK, will do. The particular set of messages confusing me at the time were bmad_parser(2) errors; it was sometimes difficult to determine which universe generated them.

**Comment by DavidSagan** [comment]
It helps a lot having an example to work with...
