### ISSUE TITLE
Compact output of overlay expressions

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#229]
This is a minor annoyance, so feel free to ignore it or put it off. Right now, if I want to know what the expression for an overlay lord is, the only thing I know of that gives it to me is `show element`, which gives me an entire page of output. It would be nice to be able to get just the overlay info: the "Slaves" table from `show element` would be fine. Something like `show overlay lord [slave]`, where if `slave` were present (possibly as an pattern), it would only show entries corresponding to the given slave(s) (for cases where there are a lot of slaves). This is basically for "tao as a desktop calculator for lattices" functionality, e.g., I want to know what some coefficient in an expression is so I can copy it into the command line I'm typing, while minimizing things scrolling off the screen. Again, it's just a minor annoyance, so not a high priority.

**Comment by DavidSagan** [comment]
I'll think about it but for now there is a non-public show command that will do what you want:
  `show internal -control <ele_name>`

**Comment by jsberg-bnl** [comment]
The `show internal -control` command only gives the lord/slave relationships, it doesn't show the attributes controlled and their associated expressions.

**Comment by DavidSagan** [comment]
OK try it now...

**Comment by jsberg-bnl** [comment]
Yes, much better, thanks. A couple minor issues: first, there's a column labeling issue in the output (in the Lords table, the 5th column should be "Lord"):
```
Tao> sho internal -control yi3_qd4_i
For element: (3509)  YI3_QD4_I
Slaves: Type       %ic  %cntrl  back   Slave                    Param               Expression
  Overlay_Lord      52      52     1   YI3_QD4 (0>>2798)        B1_GRADIENT         -0.027149189411764706/1.811949*i
Lords:  Type       %ic  %cntrl  back   Slave                    Param               Expression
  Overlay_Lord     432     424     2   YI3_QD6_PS (0>>3731)     I                   -i
  Overlay_Lord     433     434     2   YI3_QF7_PS (0>>3734)     I                   -i
  Overlay_Lord     434     508    13   Y_QMAIN_PS (0>>3759)     I                   -i
```
Second (some people are always asking for more...), for debugging overlays having the expression value can be a timesaver, ideally given in the Lords table. In the output of `show element`, you have that in the slave table:
```
Slaves: [Attrib_Value = Expression_Val summed over all Overlays controlling the attribute.]
 Ele_Loc   Ele_Name    Attribute         Attrib_Value  Expression_Val     Expression
    3497   YI3_QD2_I   I                  -5.3297E+03     -3.7871E+01     -i
    3509   YI3_QD4_I   I                  -5.4214E+03     -3.7871E+01     -i
    3533   YI3_QD6_I   I                  -5.4214E+03     -3.7871E+01     -i
    3491   YI3_QF1_I   I                   5.3675E+03      3.7871E+01     -i
    3503   YI3_QF3_I   I                   5.2689E+03      3.7871E+01     -i
    3521   YI3_QF5_I   I                   5.4214E+03      3.7871E+01     -i
```
It would be more useful in the lords table for a slave since you'd be looking at the slave to understand where its value is coming from.

**Comment by jsberg-bnl** [comment]
Also, you may need a digested format version bump; I had to remove the digested file to avoid a segfault (example in `/cdat/tem/jsberg/220610a` if you want to see it happen)

**Comment by DavidSagan** [comment]
segfault was actually indicative of a problem in the code not related to digested files. This has been fixed.

**Comment by DavidSagan** [comment]
And I made the change to the output format.

**Comment by jsberg-bnl** [comment]
Very nice, thanks! That output will be really useful for sorting what is going on with complex overlays. If you want to save a bit of horizontal space, you could drop the attrib_value column from the Lords table, since that's easily accessible with a `show value`.
