### ISSUE TITLE
Justification with custom format in show lattice

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#230]
A _really_ minor documentation issue for people who try to do clever things with `show lattice -custom ...`: in the documentation, it claims that numbers are right justified. That's only sort of true. Yes, a Fortran format will right justify the number within the width of the format specification if it is a fixed-width format specification. However, the string that's output by the Fortran format is then left justified in a column of the specified (column 3) width. So if you make the number for the column width larger than the width that the format typesets, it will not be right justified (e.g., writing `'f10.3' 11` for the second and third items in `custom_show_list`, or using a zero field width in the Fortran format).

**Comment by DavidSagan** [comment]
I can make the code conform to the doc or the doc conform with the code. What do you like?

**Comment by jsberg-bnl** [comment]
I would just fix the doc, since what is there works if you know what it is doing. Maybe with a brief digression on Fortran formats and a recommendation to match the Fortran format field width to the specified field width if you want rational behavior. Here's a random try:

Each value is formatted using the specified Fortran format descriptor (second entry for the column) and left justified in a field with a width equal given by the third entry for the column. However, a number formatted by Fortran will be right justified in a field of the width specified in the format descriptor. Thus, we recommend hat the width specified in the Fortran format descriptor matches the width given in the third entry for the column, as shown in the example. Column headers for numeric entries are right justified in their fields to match this expected behavior.

And a text (maybe as a footnote) like:
Some examples of Fortran format descriptions for floating point numbers: `f10.3` means to output the number in a field of width 10 with three digits after the decimal place (ordinary, not scientific notation); `es15.6` means to output the number in scientific notation, in a field of width 15, with 6 digits after the decimal place.

**Comment by DavidSagan** [comment]
One thought I just had is to simplify things and simply remove the width field.

**Comment by jsberg-bnl** [comment]
That would be fine, but it feels moderately tricky to get right if you try to parse the format. If you want to make it fool-proof you would need to make one pass, format everything, take the maximum `len_trim`, and set the field width to that.

**Comment by DavidSagan** [comment]
Tao already does this.

**Comment by DavidSagan** [comment]
OK now the width field is taken from the format width. Old custom files should still work though and in this case the width as set in the file will be respected.
