### ISSUE TITLE
Random variables have key_bound set to true 

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#231]
So far I've only seen this in the complex example located on CLASSE, `/cdat/tem/jsberg/220613a`. A random set of variables are having their `key_bound` member set to true. The easy way to see that it is random is to run both the production and debug versions of devel on the CLASSE example. Everything else I've ever run seems to default the `key_bound` member to false.

**Comment by jsberg-bnl** [comment]
At least part of the problem appears to be in `tao_init_variables`, when you have variables that clone, the transfer of `default_key_bound` to `default_key_b` doesn't occur for all of the cloned universes, but only the last one.

**Comment by jsberg-bnl** [comment]
Maybe also that `re_allocate_logical` does not use `transfer_logical`

**Comment by jsberg-bnl** [comment]
The following patch seems to fix it: `default_key_b` should not have been indexed by `n` (the count multiplied by the number of universes for clones), but by the number of `tao_var` namelists (`n_nml`):
```
Index: sim_utils/misc/re_allocate_mod.f90
===================================================================
--- sim_utils/misc/re_allocate_mod.f90  (revision 52545)
+++ sim_utils/misc/re_allocate_mod.f90  (working copy)
@@ -620,7 +620,7 @@
 logical, allocatable :: logic(:), temp_logic(:)

 integer, intent(in) :: n
-integer n_save, n_old
+integer i, n_save, n_old

 logical, optional :: exact
 logical, optional :: init_val
@@ -635,7 +635,9 @@
   allocate (logic(n))
   if (present(init_val)) logic = init_val
   n_save = min(n, n_old)
-  logic(1:n_save) = temp_logic(1:n_save)
+  do i=1,n_save
+     call transfer_logical(temp_logic(i),logic(i))
+  enddo
   deallocate (temp_logic)
 else
   allocate (logic(n))
Index: tao/code/tao_init_variables_mod.f90
===================================================================
--- tao/code/tao_init_variables_mod.f90 (revision 52545)
+++ tao/code/tao_init_variables_mod.f90 (working copy)
@@ -114,12 +114,12 @@
   else
     n = n + size(s%u)
   endif
-  if (n >= size(default_key_b)) then
+  if (n_nml >= size(default_key_b)) then
     call re_allocate (default_key_b, 2*size(default_key_b))
     call re_allocate (default_key_d, 2*size(default_key_d))
   endif
-  call transfer_logical (default_key_bound, default_key_b(n))
-  default_key_d(n) = default_key_delta
+  call transfer_logical (default_key_bound, default_key_b(n_nml))
+  default_key_d(n_nml) = default_key_delta
 enddo

 call tao_allocate_v1_var (n, .false.)
```

**Comment by DavidSagan** [comment]
I think `n` is correct. I put in a fix. Please test.

**Comment by jsberg-bnl** [comment]
I think my patch is correct, actually. Yours avoids the error in the original example, but only because nothing is key bound by default. Here's an example that fails with your patch: [220614a.zip](https://github.com/DavidSagan/Bmad/files/8899832/220614a.zip). In the first universe, only the first two quads (from the `q1` variables) should be key bound, but the quads controlled by the `q2` variables are key bound as well. Also, you'll notice that the `key_delta` values for the `q2` variables are wrong as well. My patch above gets that example correct.
What's going on is that in the loop that follows, `default_key_b` and `default_key_d` are indexed by which namelist you've read: `n_v1` is only incremented once for each namelist read. The exit condition `n_v1 > n_list` will never occur when there is a nontrivial cloned variable, the exit condition will be the failure of the namelist read further down. In the loop we're both patching, `n_nml` indexes the namelist that's being read, whereas `n` effectively indexes a double loop of the namelists and universes, with the universe being the most rapid variation.

**Comment by jsberg-bnl** [comment]
And I would have made a simpler example earlier, except I didn't understand enough of the underlying problem to make one until I had actually studied the code enough to come up with a fix.

**Comment by jsberg-bnl** [comment]
Now that I think about it, that first loop doesn't actually accomplish anything useful with the `default_key_b` and `default_key_d` business. You could handle `default_key_delta` and `default_key_bound` in the second loop just by taking the values from the namelist and drop `default_key_b` and `default_key_d`. Then the first loop would only be counting for the `tao_allocate_v1_var` call.

**Comment by DavidSagan** [comment]
Can you send me a patched tao_init_variables_mod.f90 file and I will make it official?

**Comment by jsberg-bnl** [comment]
A version working with both my examples is in this Zip file (Github apparently won't let me attach Fortran directly): [220614-tao_init_variables_mod.zip](https://github.com/DavidSagan/Bmad/files/8903081/220614-tao_init_variables_mod.zip). I basically put all the `default_key_bound` and `default_key_delta` logic into the second loop, eliminating the need to manage it in the first loop.

**Comment by DavidSagan** [comment]
Patch now official. Thanks Scott!
