### ISSUE TITLE
Solenoid Tracking subsection of manual

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#234]
I go diagonally through a solenoid, and was surprised to notice that Bmad actually gets the exact answer (the drift with the square root) with `bmad_standard` tracking when `ks` is 0, and that it even continues to be close to that when `ks` is small and nonzero. But the manual claims that you do an approximation without the square root, so you're doing better than what the manual claims.

**Comment by DavidSagan** [comment]
I assume that you are talking about Section 24.20. Yes I need to update the manual. It turns out to be fairly easy to not make the sqrt approximation.

**Comment by jsberg-bnl** [comment]
Yup, that's it.

**Comment by DavidSagan** [comment]
And the manual has been modified.

**Comment by DavidSagan** [comment]
And, as always, thanks for reporting this.
