### ISSUE TITLE
show spin crashes Tao on ESR lattice with Sprint spin tracking.

### ISSUE THREAD

**Issue by JacobAsimow** [bmad-sim/bmad-ecosystem#236]
When running `show spin` on the attached file (converted to .txt for Github uploading), Tao gives the following error:

![image](https://user-images.githubusercontent.com/109096391/178310274-e03ee02a-180d-4dc1-9581-2ced8f6895b6.png)

The command runs fine when commenting out line 650 `*::*[spin_tracking_method] = sprint`

[esr_sprint.txt](https://github.com/DavidSagan/Bmad/files/9085854/esr_sprint.txt)

**Comment by JacobAsimow** [comment]
Resolved: element HQ2EF_7 is missing a k1 value.

**Comment by DavidSagan** [comment]
Not having a k1 value just means the k1 value defaults to zero. Therefore the bug has not been resolved. Working on it...

**Comment by DavidSagan** [comment]
Sprint calc had a divide-by-zero problem when k1 was zero. I put in a fix.
