### ISSUE TITLE
Garbage error messages with global%lattice_calc_on=f in tao.init and data that require lattice calculation

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#237]
The user should never do this, but Bmad shouldn't write an uninitialized variable to the terminal either. Example: 
[220712a.zip](https://github.com/DavidSagan/Bmad/files/9093247/220712a.zip)
And here's the output:
![image](https://user-images.githubusercontent.com/24276120/178498339-634a8fe2-ca1c-44a3-b6b1-f95f31f0bb72.png)

**Comment by DavidSagan** [comment]
Fixed. Thanks for reporting. There is nothing in the input files that is off here.
