### ISSUE TITLE
Extra options for ref_coords attribute of patch

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#243]
A couple more options for the `ref_coords` attribute of `patch` might be convenient, mostly to satisfy users who like having `l` corresponding to the length of the actual orbit:
- `t_offset`: in this case the `t_offset` value is used to compute the change in `l`. Anyone daft enough to simultaneously set `e_tot_set` or its equivalents will have to be satisfied with whatever energy (before/after/average) you choose to do that calculation with.
- `user`: make `l` an independent parameter and let me set it. The "trust me I know what I'm doing" flag.

Not a high priority, really just there to help make things like people are expecting them. Feel free to pick better names for the attribute values.

**Comment by jsberg-bnl** [comment]
And as I think about this, I'm realizing that the question arises as to what it means if you have a nonzero `t_offset` and a nonzero `l`; the issue arises because you go around the ring and either patches or orbit offsets cause the length of the "design" orbit to be different from `l`; usually you want to restore `l` to the actual orbit length and make the `z` variable zero. So if `ref_coords=t_offset` and `t_offset` was set to restore `z` to zero on the design orbit, then `l` would correspond to the length of the design orbit in the most common situation. `ref_coords=user` would adjust the reference time by and amount corresponding `l`, and then would add an additional `t_offset` if that happened to be specified.

**Comment by DavidSagan** [comment]
The description of `ref_coords` in the Bmad manual was incorrect. The purpose of `ref_coords` is to set the orientation of the reference coordinates. Not to set the element length. I have corrected the manual. I have also removed the `no_end` setting for `ref_coords` as this does not make sense. This leaves open the issue of setting the length. A new element parameter like `user_sets_length` = T/F could be introduced.

**Comment by jsberg-bnl** [comment]
Actually, I think the description of `ref_coords` is right, or at least was at one point; the `no_end` case came from me and was the reason you introduced `ref_coords`, as I wanted the option of just setting `L=0`. And I have lattices that use that feature, but it's probably only me so I can fix the cases where it appears.

**Comment by jsberg-bnl** [comment]
The description in the manual is correct, the code is in `bmad/low_level/patch_length.f90`

**Comment by DavidSagan** [comment]
The latest version of `patch_length.f90` has had `no_end` removed. The issue with `no_end` is that  the reference coords inside the patch are undefined. As I said, a new element parameter like `user_sets_length` = T/F could be introduced if you want.

**Comment by DavidSagan** [comment]
`user_sets_length` has now been implemented for patch elements.

**Comment by jsberg-bnl** [comment]
Could you make it so `ref_coords=no_end` gives a warning rather than an error? New versions of Bmad are crashing on EIC lattice releases...

**Comment by jsberg-bnl** [comment]
Also, there's a bug in `user_sets_length`: a nonzero length changes `ref_time` (correct), leaves the particle time unchanged (correct), but also leaves `orbit.z` unchanged (wrong):
```
Tao> sho val ele::pl_crab6w[l]
    -1.6891202708078710E-03
Tao> sho val (ele::pl_crab6w[ref_time]-ele::pl_crab6w-1[ref_time])*c_light*ele::pl_crab6w[p0c]/ele::pl_crab6w[e_tot]
    -1.6891202708066873E-03
Tao> sho val (lat::time[pl_crab6w]-lat::time[pl_crab6w-1])*c_light*ele::pl_crab6w[p0c]/ele::pl_crab6w[e_tot]
     0.0000000000000000E+00
Tao> sho val lat::orbit.z[pl_crab6w]-lat::orbit.z[pl_crab6w-1]
     0.0000000000000000E+00
```

**Comment by DavidSagan** [comment]
@jsberg-bnl Why is `ref_coords=no_end` showing up in EIC lattices?

**Comment by jsberg-bnl** [comment]
There are patches in a number of places in the EIC lattices. I used `ref_coords=no_end` for two reasons: first, to make the length output consistent with mad-x, and second, from my experience with CBETA (which had lots of patches), I found an enforced l=0 to be a bit more predictable (in some sense you could argue that either way is predictable in the sense of deterministic, but it's predictable in the sense of knowing what length will be assigned).

**Comment by jsberg-bnl** [comment]
Anyhow, I'm removing the `ref_coords=no_end` settings, but having old lattices crash on newer Bmad versions is a problem.

**Comment by DavidSagan** [comment]
The ref_time computation should be good now.

**Comment by DavidSagan** [comment]
And "ref_coords = no_end" downgraded to warning.

**Comment by jsberg-bnl** [comment]
Tested, works great, thanks! A release would be helpful to close the window where my released EIC lattices crash.

**Comment by DavidSagan** [comment]
A new Distribution is building now...
