### ISSUE TITLE
Documentation: beta functions for nonzero pz

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#261]
In the documentation, it would be good to make clear how beta functions are handled for nonzero pz. Before calculating the beta functions, the transfer matrix is scaled so that the beta functions you get are what you would have had with the actual magnetic fields if you adjusted the reference momentum. The documentation implies that it just picks the beta functions off from the matrix elements (or at least I didn't find where it says otherwise).

**Comment by DavidSagan** [comment]
The Twiss calculation now no longer does a reference momentum correction.
