### ISSUE TITLE
chrom.a datum not valid for some reason

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#265]
See attached: [arc4.zip](https://github.com/DavidSagan/Bmad/files/9739254/arc4.zip)
First `set branch 3@0 geometry=closed`. The datum 3@all (which just evaluates `chrom.a` and `chrom.b` on universe 3) cannot be used for some reason.

**Comment by DavidSagan** [comment]
Fixed.
