### ISSUE TITLE
Potentially incorrect calculation of kmat(5,6) for soft_bend_edge_kick

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#267]
Hi Dave, please take a look at the soft_bend_edge_kick routine in bmad/modules/fringe_mod.f90 . Based on the calculation for orb%vec(5) and applying partial differentiation with respect to pz, Chris and I believe that the calculation for kmat(5,6)  should be (c1 * px + c2 * y**2/2 - c3 * y**4/4) / rel_p**2 * (-2) , which disagrees with your current formula. (We noticed that c1, c2, and c3 all depend on pz in the same way.)  Could you confirm this? thanks.

**Comment by ChristopherMayes** [comment]
I confirmed that `fringe_mod.f90`, line 948 should be 
```fortran
kmat(5,6) = -2*(c1 * px + c2 * y**2/2 - c3 * y**4/4) / (rel_p**2)
```
which then agrees with PyTorch's Jacobian.

**Comment by DavidSagan** [comment]
Chris will put in the fix.

**Comment by ChristopherMayes** [comment]
```
svn commit -m "Fix kmat(5,6) in soft_bend_edge_kick"
Sending        modules/fringe_mod.f90
Transmitting file data .done
Committing transaction...
Committed revision 53331.
```
