### ISSUE TITLE
Dipole Hard Edge Fringe Map: Discrepancy between Bmad Manual and code

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#268]
Hi Dave:

     This discussion is for sbend with "fringe_type" set to "hard_edge_only".

     Eq. 17.9 in Bad manual shows the entrance fringe map, which corresponds to line 306 to 308 in bmad/modules/fringe_mod.f90, which I paste here:

 306   dz = e_factor**2 * 0.5_rp * (v(3)**2 * fg_factor + v(1)**3 * (4.0_rp * k1_tane - gt * gt2) / 6.0_rp + &
 307             0.5_rp * v(1)*v(3)**2 * (-4.0_rp * k1_tane + gt * gs2) + 2.0_rp * (v(1)**2*v(2) - v(1)*v(3)*v(4)) * gt2 + &
 308             v(2)*v(3)**2 * (g_tot + gt2))

Below are my questions:

(A) The second last term the manual has (x^2*px - 2x*y*py) , but in the code the factor of 2 is missing. 
       The same disagreement occurs in the exit fringe too.

(B). The final term in the manual has a MINUS sign, but the code has a PLUS sign ( this disagreement is only for the entrance fringe ).

(C) Since "fint_gap" is set to ZERO for "hard_edge_only", I do not understand why we keep all the terms with "finite_gap" in the munual and the code.  These terms currently exist in the mapping for py and z. 

(D) Is K1 in formula 17.9 the same as the k1 of the sbend in 1/m^2?

**Comment by DavidSagan** [comment]
A/B) Eq 17.9 is the generator. This is different from the fringe kick which is derived via 17.11. The generator is not calculated by the code. Compare the code to equations 17.12 and 17.3

C) Yes.

**Comment by weiyuanlou** [comment]
Sorry I'm more confused now. 
Doesn't the transport for Z in Eq. 17.12 depend on the generator in 17.9 ?
If the code doe not calculate the generator, how does it calculate the z transport?

**Comment by DavidSagan** [comment]
The generator is used to derive the transport equations. The generator is not used explicitly in transporting particles. The transport equations are used to transport particles.

**Comment by DavidSagan** [comment]
Hwang fringe should not be called "hard edge".

**Comment by DavidSagan** [comment]
@weiyuanlou Update: I am working on this when I find free time. So far I have pretty well got the code sorted out. The higher_order_fringe_type has been retired (its use generates a warning that it is no longer used) and I am working on the documentation.

**Comment by DavidSagan** [comment]
@weiyuanlou Finally I believe I have things straightened out in terms of the equations. I am closing this issue and am working on further documentation issues (Issue bmad-sim/bmad-ecosystem#252).
