### ISSUE TITLE
No energy loss when going off-axis through a quadrupole with radiation_damping_on=t

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#269]
Run `tao` on this lattice: [221015.txt](https://github.com/DavidSagan/Bmad/files/9791642/221015.txt). There is no energy loss even though the electron goes off axis through the quadrupole. If the quadrupole is replaced with a dipole, you see energy loss.

**Comment by DavidSagan** [comment]
Fixed.
