### ISSUE TITLE
Generalized gradient approximation for grid_field maps

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#272]
It would be useful to implement a generalized gradient approximation for grid_field field maps in order to calculate higher-order taylor maps of these elements using PTC tracking.

Furthermore, implementing a simple scaling functionality for the overall field strength would be convenient for a basic parametrization of the lattice element in question.

**Comment by DavidSagan** [comment]
The syntax for a grid_field scale is something like `Q1[grid_field(1)%field_scale]` where, in this case, `Q1` is the name of the element and it is assumed that there is only a single field grid.

**Comment by DavidSagan** [comment]
I talked to Etienne and he will implement GG in PTC. I will work on the Bmad end. His estimate is 1 month but I suspect that it will be closer to 2 before things are working.

**Comment by eiad-hamwi** [comment]
That's great to know, I just saw that in the manual after posting the issue!

But I'm excited to hear that about PTC, and I'm glad you and Etienne feel like it will be useful for many people as well. Thanks again!

**Comment by DavidSagan** [comment]
- [x] Code Bmad side: Superposition tracking needs work
- [x] Tao python ele:gen_grad_field needs finishing.
- [x] PTC side and interface
- [x] Test
- [x] DOC
- [x] Regression tests (parse_test)
- [x] Field table to gen grad coefs program
- [x] Gen grad lattice element to field table program
- [x] Remove references to taylor_field from documentation (bmad and tao).

**Comment by DavidSagan** [comment]
Finished.
