### ISSUE TITLE
Cannot plot orbit.charge: DATA DOES NOT HAVE A WELL DEFINED S-POSITION

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#275]
`orbit.charge` is a datum that at well-defined elements, but the attached example gives the following:

```
Tao: place r11 bpm_orbit
[ERROR | 2022-OCT-29 13:39:38] tao_curve_data_setup:
    DATA DOES NOT HAVE A WELL DEFINED S-POSITION FOR PLOT CURVE: orbit.charge
    SOLUTION: PLOT BY DATUM INDEX INSTEAD OF S-POSITION.
```

[error.zip](https://github.com/DavidSagan/Bmad/files/9894561/error.zip)

**Comment by DavidSagan** [comment]
Problem is error message is bogus. I will fix this. The real problem is that you want the curve component = 'model'.

**Comment by DavidSagan** [comment]
Fixed.
