### ISSUE TITLE
Support of initial value for closed_orbit_calc in subroutine rad_damp_and_stoc_mats inside modules/rad_6d_mod.f90

### ISSUE THREAD

**Issue by z-duan** [bmad-sim/bmad-ecosystem#277]
Hi, for some cases, Bmad solver cannot locate the closed orbit, either in 4d or 6d searches, there is a subroutine init_coord that helps to set up initial value for the closed orbit solver. However, in subroutine rad_damp_and_stoc_mats inside modules/rad_6d_mod.f90, this usage of initial value is not yet supported.  To facilitate this, I had to do the following:

1. add "use coord_mod" at the beginning of the file
2. add call reallocate_coord (closed_orb, branch%lat) inside subroutine rad_damp_and_stoc_mats
3. add call init_coord (closed_orb(0), branch%lat%particle_start, branch%ele(0), downstream_end$, closed_orb(0)%species)    before   call closed_orbit_calc(branch%lat, closed_orb, 4, +1, branch%ix_branch, err_flag).

This solution helps to avoid the error messages I met when calling "tao -lat lattice.bmad" that reports closed orbit calculations did not converge.  

![screenshot_2022-11-03_at_11 45 47_am](https://user-images.githubusercontent.com/21173404/199856718-c55781b0-0944-4f12-90c1-05a526f21292.png)

**Comment by ChristopherMayes** [comment]
@z-duan could you attach the lattice that causes this?

**Comment by z-duan** [comment]
[agamma_103.50.bmad.zip](https://github.com/DavidSagan/Bmad/files/9943820/agamma_103.50.bmad.zip)
You can check this lattice. Thanks!

**Comment by DavidSagan** [comment]
@z-duan @ChristopherMayes I can reproduce this error message. Problem is that the tracking_method is symp_lie_ptc while the mat6_calc_method is bmad_standard (the default) and the (small)  differences between the two are causing the closed orbit algorithm from converging. The solution is to set mat6_calc_method to symp_lie_ptc or the tracking_method to bmad_standard. Using symp_lie_ptc is *very* slow and not recommended. Notice that the new "auto" method for mat6_calc_method should help to prevent this issue.
