### ISSUE TITLE
Tao not displaying Sigma values

### ISSUE THREAD

**Issue by ags232** [bmad-sim/bmad-ecosystem#279]
About a week ago I could easily view the Sigma values at the end of a sextupole in my lattice, simply through the show ele command:

![Twiss_Parameters_w_Sigma](https://user-images.githubusercontent.com/47345293/200031843-62a08109-32d1-473b-b82d-d8c6dc25d8bd.png)

But for some reason, the same command on the same lattice now does not produce the sigma values as part of the twiss parameters:

![Twiss_Parameters_no_Sigma](https://user-images.githubusercontent.com/47345293/200032397-d2cbe955-1eab-4097-b515-a1de64dcd7fb.png)

**Comment by DavidSagan** [comment]
@ags232 Please include lattice

**Comment by DavidSagan** [comment]
@ags232 The sigma is only printed if it is non-zero and the sigma is only non-zero if there was an emittance calculated.
