### ISSUE TITLE
STARTING ORBIT NOT PROPERLY INITIALIZED!

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#282]
This throws many `NEEDS AN INIT_COORD CALL?` errors (zip attached). 

```
tao

...
Tao: beamon
[ERROR | 2022-NOV-06 14:26:21] track1:
    STARTING ORBIT NOT PROPERLY INITIALIZED! [NEEDS AN INIT_COORD CALL?]
[ERROR | 2022-NOV-06 14:26:21] track1:
```

[error.zip](https://github.com/DavidSagan/Bmad/files/9946979/error.zip)

**Comment by DavidSagan** [comment]
Round off error was confusing the track1 routine. Fixed.
