### ISSUE TITLE
Another STARTING ORBIT NOT PROPERLY INITIALIZED! [NEEDS AN INIT_COORD CALL?]

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#283]
(see attached zip)
```
tao
...
[ERROR | 2022-NOV-06 23:08:43] track1:
    STARTING ORBIT NOT PROPERLY INITIALIZED! [NEEDS AN INIT_COORD CALL?]
```

[error.zip](https://github.com/DavidSagan/Bmad/files/9948949/error.zip)

**Comment by DavidSagan** [comment]
Fixed. Problem due to logic for detecting change in the beam starting conditions assumed that the beam was starting from the beginning of the lattice branch.
