### ISSUE TITLE
One_turn_map giving the same value for all universes

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#284]
I am using the one turn map calc and getting the same results for each universe. In addition to the same momentum compaction being calculated for each universe, universe 2 has a negative momentum compaction. From madx, the gamma transition looks like this:

03:16 PM->lovelace:madx_file fstring GAMMATR
./twiss.out_Au21-100GeV::gammat1:@ GAMMATR          %le          23.7164959
./twiss.out_Au21-100GeV::gammat2:@ GAMMATR          %le         23.83071035 !Universe 2
./twiss.out_Au21-100GeV::gammat4:@ GAMMATR          %le         22.83062566
./twiss.out_Au21-100GeV::gammat5:@ GAMMATR          %le         23.14808213

Looking at the one turn map calc:

Tao> show value 1/sqrt(*@lat::momentum_compaction_ptc.1[end])
    1:    2.3148081996426288E+01
    2:    2.3148081996426288E+01
    3:    2.3148081996426288E+01
    4:    2.3148081996426288E+01

the values look suspiciously identical.

**Comment by DavidSagan** [comment]
@henrylovelace3 Please attach lattice.

**Comment by henrylovelace3** [comment]
[examp.zip](https://github.com/DavidSagan/Bmad/files/9974746/examp.zip)
Here you go.

**Comment by DavidSagan** [comment]
@henrylovelace3 One thing I notice is that the tao.init file has:
>     design_lattice(1:4)%one_turn_map_calc = t
This only sets universe bmad-sim/bmad-ecosystem#4. What you want is:
>     design_lattice(1:4)%one_turn_map_calc = 4*t
I will keep investigating...

**Comment by DavidSagan** [comment]
@henrylovelace3 This has now been fixed.
