### ISSUE TITLE
spin_res not plotting over energy range

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#285]
I scripted a custom plot in the `tao.init` file of `spin_res.b1` vs `e_tot`. Whenever I try to display this plot, Tao lingers indefinitely. I was able to confirm that Tao can calculate `spin_res.b1` as a datum for a given value of reference energy `e_tot`, but the plotting function is having trouble for some reason.

[rhic_resonances.zip](https://github.com/DavidSagan/Bmad/files/9967694/rhic_resonances.zip)

**Comment by DavidSagan** [comment]
@eiad-hamwi Looks like the problem is the number of plot points and the time to calculate each plot point (about 10 sec/pt). To set the number of points for a plot set plot%n_curve_pts .

Also graph%x_min/max should be plot%x%min/max
