### ISSUE TITLE
Difference in tunes even though presumably same lattice

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#288]
Assuming I'm not missing anything, both of these procedures should give (atleast nearly) the same lattice, but the fractional vertical tunes differ by 0.03. With the attached lattice, call in Tao

set tune 48.12 43.07 -mask 2125:2140,2169:2186,57:74,103:118
write bmad -form one_file esr-main-2.bmad

without exiting Tao, do

set bmad_com radiation_damping_on = T
taper
sho uni

You should see a vertical tune of about 43.10. Exit and start Tao with esr-main-2.bmad, and call

set bmad_com radiation_damping_on = T
taper
sho uni

Now you should see a vertical tune of 43.07, as desired previously

[esr-main.zip](https://github.com/DavidSagan/Bmad/files/10007609/esr-main.zip)

**Comment by DavidSagan** [comment]
This is because the tapering is done with respect to the base lattice which, in this case is the same as the design lattice and in the two cases the design lattices are different.
