### ISSUE TITLE
TAO throws error when asking for spin tracked through grid field

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#289]
When spin tracking through grid field, TAO gives an error message.

Tao> show spin
[FATAL | 2022-NOV-15 15:17:12] ele_to_fibre:
    PTC TRACKING IS NOT ABLE TO USE GRID_FIELDS. FOR ELEMENT: SNK03#1
forrtl: severe (174): SIGSEGV, segmentation fault occurred

**Comment by DavidSagan** [comment]
@henrylovelace3 
This represents a valid problem. But the code should be modified to not bomb. Please attach input files to reproduce this.

**Comment by DavidSagan** [comment]
@henrylovelace3 Closing this issue until lattice provided.

**Comment by henrylovelace3** [comment]
Sent you an email with an example lattice.
