### ISSUE TITLE
Error when using field_overlap when overlapping field maps

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#294]
field_overlap generates an error when used. Zip file contains field maps and tao.init where there are two universes. Universe 1, superimposed field map onto drift, universe 2 elements have the field map have field map attributes. File too large for github. Sent you an email. 
[ERROR | 2022-NOV-20 14:13:42] grid_field_interpolate:
    3D GRID_FIELD INTERPOLATION INDEX OUT OF BOUNDS: I3 = 741 (POSITION =     7.412000)
    FOR ELEMENT: PHSNK_MOD                                 (6)
    PARTICLE POSITION:    -0.000012    0.000238    7.412000
    SETTING FIELD TO ZERO
[ERROR | 2022-NOV-20 14:13:42] grid_field_interpolate:
    3D GRID_FIELD INTERPOLATION INDEX OUT OF BOUNDS: I3 = 741 (POSITION =     7.412000)
    FOR ELEMENT: PHSNK_MOD                                 (6)
    PARTICLE POSITION:    -0.000012    0.000258    7.412000
    SETTING FIELD TO ZERO

**Comment by DavidSagan** [comment]
@henrylovelace3 Bookkeeping fixed.
