### ISSUE TITLE
Zero emittance beam causes Seg Fault

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#296]
Created a working a simple drift example w/fft_3d SC.  The initial beam has zero emittance, average momentum of 10 MeV/c and is tracked for 5 m.  The input files for this example are included in the attached zip file.  These include:

1. tao.init 
2. tao_plot.init -- used for initializing plotting
3. initial_tao_particles.h5 -- initial input particle file with zero emittance beam
4. drift.bmad -- lattice file with a 5 m drift
5. commands.tao -- list of commands use to run the example in tao

It is the beam tracking on command which causes the seg fault:
<img width="593" alt="Screenshot 2022-11-22 at 2 53 14 PM" src="https://user-images.githubusercontent.com/36416205/203408813-091e9ba5-e98d-4a78-95f0-0b8d5b6dbdb6.png">

[driftsc.zip](https://github.com/DavidSagan/Bmad/files/10070640/driftsc.zip)

**Comment by DavidSagan** [comment]
@ChristopherMayes Problem is line 226 in deposit_particles routine in open_spacecharge_mod.f90:
`dzi=1.d0/dz`
and dz is zero. Can you look at this? Thanks.

**Comment by ChristopherMayes** [comment]
@ndwang Could you take a look?

**Comment by DavidSagan** [comment]
Ningdong has put in a fix.
