### ISSUE TITLE
TAO set universe * dynamic_aperture_calc off not setting the dyn calc off

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#299]
This can be checked with any closed lattice. 
   58: **set dynamic_aperture pz(1) = 0.0**
   59: **set uni * dy on**
   60: **set uni * dy off**
   61: **change ele quad::* k1 .00001**
  ......
[test.zip](https://github.com/DavidSagan/Bmad/files/10109015/test.zip)

**Comment by DavidSagan** [comment]
Fixed.
