### ISSUE TITLE
Single particle tracking z-mode beta function

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#30]
Does BMAD keep track of longitudinal moments in single particle mode? Something like the longitudinal 'twiss parameters' ? In multi-particle mode bmad calculates a z beta function, but there isn't something similar for one particle tracking.

**Comment by DavidSagan** [comment]
@ChristopherMayes 

In single particle tracking Bmad does not keep track of any moments, longitudinal or transverse.
