### ISSUE TITLE
spin tracking error in long_term_tracking program

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#300]
### In the RHIC lattice files below, there is a very strong intrinsic spin resonance at `Gγ = 422.18`.
[ramping.zip](https://github.com/DavidSagan/Bmad/files/10117274/ramping.zip)
\
\
\
\
If I perform long term tracking at constant energy with `Gγ = 422.16` I get the following result:
![image](https://user-images.githubusercontent.com/66403062/204637287-4b7f8a9a-7f24-4691-8048-9d4ec20767ce.png)
\
\
\
\
Then I perform long term tracking at constant energy with `Gγ = 422.17` and we can see the widening of the opening angle for the invariant spin field:
![image](https://user-images.githubusercontent.com/66403062/204637459-63b15747-23a9-4c28-a3f7-3d4d107769ae.png)
\
\
\
\
\
Finally, the confusion pops out when I try to ramp the energy between those two values, and find no indication of the spin-tracking being updated along the process.
![image](https://user-images.githubusercontent.com/66403062/204638470-85cfb280-41fc-4522-a8db-fd748bce9f76.png)

**Comment by DavidSagan** [comment]
@eiad-hamwi In Tao when I set ramp_e time to the equivalent of 400 turns (specifically: 1.28e-5*400), G*gamma goes from 422.172 to 422.176 which is off from your graphs. Also when ramping with the long_term_tracking program the particle energy can lag changes in the reference energy. Can you check this?

**Comment by eiad-hamwi** [comment]
RF Cavities need to be turned on for particle energy to update.
