### ISSUE TITLE
Error with PTC tracking for Generalized Gradient Snakes

### ISSUE THREAD

**Issue by wlin6927** [bmad-sim/bmad-ecosystem#301]
I am trying to try two snakes (cold snake called csnk, and warm snake called wsnk) for the AGS using generalized gradient maps and PTC.

All the input files, csnk.bmad and csnk_gg.bmad for cold snake, wsnk.bmad and wsnk_gg.bmad for warm snake, are located at /home/wl674/ags_ring/snakes_madx on the CLASSE system. I use the nightly release for Bmad and Tao.

For the cold snake (tao -lat csnk.bmad), at first it hangs in the terminal so I had to stop the process, then when I rerun the same command I get an error that says `*** Error in /nfs/acc/libs/Linux_x86_64_intel/nightly/production/bin/tao: corrupted size vs. prev_size: 0x00000000067eef90 ***` as shown in csnk_error.txt
[csnk_error.txt](https://github.com/DavidSagan/Bmad/files/10135758/csnk_error.txt)

For the warm snake (tao -lat wsnk.bmad), it just hangs after giving the error that says `ERROR IN DAALL, MAX NUMBER OF DA VECTORS EXHAUSTED,4                            ipause=mypause(0)` as shown in wsnk_error.txt
[wsnk_error.txt](https://github.com/DavidSagan/Bmad/files/10135795/wsnk_error.txt)

**Comment by DavidSagan** [comment]
@wlin6927 The first issue looks like it is due to plotting (Tao trying to calculate the orbit at many interior points). I will work on it...

**Comment by DavidSagan** [comment]
@wlin6927 The plotting is now fixed. Etienne is working on the spin tracking which is only 2nd order at present. Also now you can set `num_steps` for an element (previously the number of steps was strickly determined by the number of z-plane slices for the generalized gradients.
