### ISSUE TITLE
Error for long term tracking

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#302]
Just recompiled this morning. Running tracking with files on the lab computer at say /home/mgs255/mgs255/master/22_summer/esr5_6/beam-beam/nobb_qs/1st_order/qs44/esr-main-qs44.bmad

Map generates fine and once the tracking starts 
[ABORT | 2022-DEC-02 09:46:57] mass_of:
    MASS NOT KNOWN FOR SPECIES: -999

Even though electron is defined in the Bmad file.

**Comment by DavidSagan** [comment]
@mattsignorelli I don't see this problem. Did you update the forest library?

**Comment by mattsignorelli** [comment]
@DavidSagan Yes. I just recompiled and reran and same issue:
dTime:    0.62 Now: 2022-DEC-02 11:11:01  13: Slave Starting...
dTime:    0.42 Now: 2022-DEC-02 11:11:01  0: Master: Writing initial data.
[ABORT | 2022-DEC-02 11:11:01] mass_of:
    MASS NOT KNOWN FOR SPECIES: -999

During the write part it seems

**Comment by DavidSagan** [comment]
@mattsignorelli Fixed.
