### ISSUE TITLE
Autoscaling/Autophasing of Lcavity appears incorrect

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#304]
I have a simple field map example with one rf cavity using a fieldmap:

```
BEGINNING[BETA_A]  = 10
BEGINNING[BETA_B]  = 10
parameter[geometry] = open
parameter[particle] = electron

beginning[e_tot] = 6e6

PC.LA.CAV01: lcavity, L = 0.5,
    rf_frequency = 197000000.0,
    field_calc = fieldmap, tracking_method = time_runge_kutta, mat6_calc_method=tracking,
    grid_field = call::$COOLER/bmad/fieldmaps/BNL_QWC_197MHz_fieldmesh_reversed.h5,
    wrap_superimpose = False,
    superimpose, ref=PC.LA.CRMOD.Pip01, ref_origin=beginning, ele_origin=center, offset = 0.75,
    phi0 = 0.0 
PC.LA.CAV01[voltage]=3e6
PC.LA.CAV01[autoscale_amplitude] = True
PC.LA.CAV01[autoscale_phase] = True
!PC.LA.CAV01[field_autoscale] = 2824325.8915627715

PC.LA.CRMOD.Pip01: pipe, L = 1.5

CAV: line = (PC.LA.CRMOD.Pip01)

use, CAV
```

I run Tao, turn on absolute_time_tracking using

`set bmad_com absolute_time_tracking = True`

 and plot the energy:

<img width="651" alt="Screenshot 2022-12-07 at 11 17 21 PM" src="https://user-images.githubusercontent.com/36416205/206355415-24814031-45e5-491a-bd2b-2d9195eca924.png">

However, I was expecting to see the energy go from 6 MeV to 9 MeV.  Attached is the working example.

[cavtest.zip](https://github.com/DavidSagan/Bmad/files/10182024/cavtest.zip)

**Comment by ColwynGulliford** [comment]
Note in the zipped example file absolute time tracking is set explicitly in the *bmad file.

**Comment by DavidSagan** [comment]
Fixed. Problem was Bmad was computing the wrong reference time in the situation where the cavity was superimposed with a pipe. Absolute time tracking was not involved.

**Comment by ColwynGulliford** [comment]
Here is my latest working example:
[cavtest.zip](https://github.com/DavidSagan/Bmad/files/10220617/cavtest.zip)

I am expecting the beam to gain 3 MeV from the cavity given:

```
parameter[geometry] = Open            

parameter[p0c]                      = 5.9782004042269E6
parameter[particle]                 = Electron
bmad_com[radiation_fluctuations_on] = T
bmad_com[absolute_time_tracking] = T

beginning[beta_a]    = 10
beginning[beta_b]    = 10


!-------------------------------------------------------

slave_drift_0_1: drift, l = 0.5
slave_drift_0_2: drift, l = 0.5
slave_drift_0_3: drift, l = 0.5
PC.LA.CRMOD.PIP01: Pipe, L = 1.5
PC.LA.CAV01: Lcavity, grid_field = call::pc.la.cav01.grid_field.h5, L = 0.5, RF_FREQUENCY = 1.97E8,
   VOLTAGE = 3E6, phi0 = 0.0,
   mat6_calc_method = Tracking, tracking_method = Time_Runge_Kutta, field_calc = FieldMap
PC.LA.CAV01[autoscale_amplitude] = True
PC.LA.CAV01[autoscale_phase] = True

!-------------------------------------------------------
! Overlays, groups, rampers, and superimpose

superimpose, element = PC.LA.CRMOD.PIP01, ref = slave_drift_0_1, offset = 0.5
superimpose, element = PC.LA.CAV01, ref = slave_drift_0_2, offset = 0

!-------------------------------------------------------
! Lattice lines


CAV: line = ( slave_drift_0_1, slave_drift_0_2, slave_drift_0_3)

use, CAV
```
<img width="666" alt="Screenshot 2022-12-13 at 12 45 48 PM" src="https://user-images.githubusercontent.com/36416205/207407134-f7cc26a2-71be-451e-9802-f368de0428f6.png">


But only see a fraction of that gain:
