### ISSUE TITLE
Make tao handle high resolution displays nicely

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#308]
There's an issue that under some circumstances, the X server on a high resolution display reports 96 dpi when in fact that resolution is much larger. This ends up creating a tiny window under default circumstances. You can bump up the window size with the geometry argument to tao, but the fonts are still tiny. So instead I'm proposing that instead we provide a mechanism to override the DPI reported by the lying X server. The easiest solution is to check for a BMAD_DPI environment variable, and override the DPI with its value if present. I've attached a patch (to `display_size_and_res.f90`) that does this: [bmad-dpi.txt](https://github.com/DavidSagan/Bmad/files/10238911/bmad-dpi.txt). I've tested it, it does the right thing for me, and it shouldn't bother anyone who doesn't set the environment variable.

**Comment by DavidSagan** [comment]
Done. To be consistent, the environment variable is named `ACC_DPI_RESOLUTION`.

**Comment by DavidSagan** [comment]
@ChristopherMayes You may be interested in this...
