### ISSUE TITLE
show spin -z_zero giving unexpected result

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#317]
If I understand correctly, doing 

show spin -z_zero * 

should give the exact same DK polarization as that printed for the "ab-modes DK polarization" in a "show spin". However this is not the case. Attached is a lattice file.

[esr-18GeV-1IP.zip](https://github.com/DavidSagan/Bmad/files/10412308/esr-18GeV-1IP.zip)

**Comment by DavidSagan** [comment]
Not true. The -z_zero option zeros the z, pz part of the transport matrix but that is different from the c-mode. For example, in places where there is horizontal dispersion the c-mode has a (x,px) component.
