### ISSUE TITLE
malloc memory corruption with show spin -z_zero

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#319]
Input files attached. Commands are

set ele * spin_tracking_method = sprint
sho spin -z_zero 5740:203 -ele 5740 203 -n_ 0 1 0
[mad8 (2).zip](https://github.com/DavidSagan/Bmad/files/10462580/mad8.2.zip)

**Comment by DavidSagan** [comment]
I get:

```
Tao> sho spin -z_zero 5740:203 -ele 5740 203 -n_ 0 1 0
[ERROR | 2023-JAN-19 21:02:54] lat_ele1_locator:
    ELEMENT LOCATION INDEX OUT OF RANGE: 5740

```

**Comment by mattsignorelli** [comment]
Sorry, these are the exact input files. Call tao with mad8.lat. I made one bmad file attached in initial post but it must have something to do with that
[mad8.zip](https://github.com/DavidSagan/Bmad/files/10462800/mad8.zip)

**Comment by DavidSagan** [comment]
I put in a fix.
