### ISSUE TITLE
Chromaticity Calculation not updating when looped

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#324]
Hi,
   The chromaticity calculation does not update when looped. The lattice contains a ramper element that makes the linear and nonlinear optics time dependent. Included in the zip file: lattice file, ramp file, and simple script to ramp lattice. Notice that the chromaticity column does not change. 
[error.zip](https://github.com/DavidSagan/Bmad/files/10483400/error.zip)

**Comment by DavidSagan** [comment]
Tao's set command not properly handling chrom updating. Fixed.

**Comment by henrylovelace3** [comment]
I just updated my Bmad version to 53994 @DavidSagan . The chromaticity values are not updating called in a loop. The loop:
do i = 0, 2343940, 10
   set ele lat time = [[i]] * lat::time[end]! + 5.44     
   set symbolic_num alpha_p =  (sum(ele::*dh%[eta.a]*ele::*dh%[ang])+sum(ele::*dh%%[eta.a]*ele::*dh%%[ang]))/lat::s_position[end]
   **set symbolic_num chroma = lat::chrom.a|model**
   **set symbolic_num chromb = lat::chrom.b|model**
   !set uni 1 recalc  
   show value 1/sqrt(alpha_p)
   show -append gt_table.txt string [[i]]  **`lat::chrom.a`** **`chromb`** !truncated from original file
enddo

is not printing to file updated chromaticity calculations. The knots in the ramp file show that the chromaticity is to increase with respect to time.

**Comment by DavidSagan** [comment]
Sorry I forgot a checkin. Try it now.

**Comment by henrylovelace3** [comment]
OK thanks
