### ISSUE TITLE
Tao> set global track_type=beam

### ISSUE THREAD

**Issue by JimCrittenden** [bmad-sim/bmad-ecosystem#330]
The command
Tao> set global track_type=beam
takes  a very long time to complete.

In an otherwise empty directory you can copy
/home/critten/bss/model/tao.init

and run tao to see this. Needs to be done on a classe machine to get the lattice file.

I saved a tao exe from 5 February 2021 which does not have this delay.
That exe file is /home/critten/bss/model/tao_exe

**Comment by DavidSagan** [comment]
There are two issues here. 

- [x] The bunch comb_ds_save parameter is defaulting to 0.01 meter which is not a good choice for long lattices. Thought: Use lattice_length/plot_page%n_curve_points.
- [x] The slice_slaves generated when tracking a bunch does not have the ele%multipole_cache structure allocated. This should be done during slice generation. [Moved to issue bmad-sim/bmad-ecosystem#336.]

@JimCrittenden For now you can set comb_ds_save to a large length to speedup the calculation.

**Comment by DavidSagan** [comment]
@JimCrittenden Fixed including "show beam" not showing the correct comb_ds_save value.
