### ISSUE TITLE
phase trombone causing issue in optimization and not updating phase

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#332]
I have an optimization which uses phase trombones which runs into closed orbit errors.

with only the phase trombones, the merit value does not change until it hits the closed orbit errors. The data I am optimizing should be effected by the phase. 

I also tried updating the dphi_a,b values manually using the "set element" command, and it had no effect on the tune. it did show the new dphi_a,b value if I did a "show element".

The files I used are at: /nfs/acc/temp/jeu8/esr_6.0

**Comment by DavidSagan** [comment]
Bug is fixed and fix is in the SVN repository.
