### ISSUE TITLE
Field calc seems wrong with crab_cavity

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#334]
The attached lattice shows opposite behavior when using runge_kutta versus bmad_standard.

```
tao -lat lat.bmad

Tao> sho ele end
Orbit:  Electron   State: Alive
         Position[mm] Momentum[mrad]  
  X:       1.50000095     1.00000013  
  Y:       0.00000000     0.00000000  
  Z:      -0.00075000     0.00000000  
```

Changing to `runge_kutta`:
```
set ele kcav tracking_method = runge_kutta
sho ele end
Orbit:  Electron   State: Alive
         Position[mm] Momentum[mrad]   
  X:      -1.50000082    -1.00000013   
  Y:       0.00000000     0.00000000   
  Z:      -0.00066667     0.00000000   
```

Furthermore, the `e_field` plot doesn't look correct at all:`place r13 e_field` is at the $10^{-8}$ level.

[error.zip](https://github.com/DavidSagan/Bmad/files/10541510/error.zip)

**Comment by DavidSagan** [comment]
Problem is the sign of the particle. Positrons behave as expected.

**Comment by DavidSagan** [comment]
I put in a fix for the particle sign. In terms of the e_field, you are tracking near the e_field zero so a small e_field is not surprising. You can check the e_field against the equations in the Bmad manual.

**Comment by ChristopherMayes** [comment]
@DavidSagan how does the particle get kicked if the field is this tiny?

**Comment by DavidSagan** [comment]
Look at the equations in the Bmad manual. It is the magnetic field.

**Comment by ChristopherMayes** [comment]
Ah okay, it makes sense now. Thanks!
