### ISSUE TITLE
Infinite loop when cesrv run in batch

### ISSUE THREAD

**Issue by JimCrittenden** [bmad-sim/bmad-ecosystem#342]
CesrV checks if a change in sextupole k2 is larger than 10 m^-3 if so
and closes the command file.  This is fine interactively, but in batch it
goes into an infinite loop.

Here is the batch script and what happens (with no_mpm):
#! /bin/bash -v
#$ -l mem_free=2.0G
#$ -m a
#$ -M jac243@cornell.edu
#$ -N opt_27059
#$ -o /home/critten/bss/analysis/gridlogs
#$ -e /home/critten/bss/analysis/gridlogs
#$ -q all.q
#$ -l arch=lx-amd64
source /nfs/acc/libs/cesr/cesr_online.bashrc
date
cd /home/critten/bss/analysis/
/home/critten/production/bin/cesrv_cl no_mpm -custom_calib custom_calibrations.cal call optimize_and_write_output_files_xoffsets.cesrv 27059 31 -30000  >& logs/opt_27059_cesrv.log

CesrV> ! set the sextupole cu
 _CesrV> chan sex 31 @-30000cu
 This change is rather large...
 Shall I make the change? Default is N    -> !
 ERROR: TO BE SAFE, I AM CLOSING THE COMMAND FILE.
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR SQUADING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR QTUNEING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR QSTUNING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR XQUNEING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR BETASING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR COUPLING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR HBUMPING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR VBUMPING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR HBSAVING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR VBSAVING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CHS HBUMPING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CHS CBUMPING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR HBINJING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR VBINJING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR VBLIMING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR WIGGLING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR ZENTHING
[ERROR | 02/13/23 12:23:07]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:07]vnumbr_c:  Node = CSR EMITTING
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = CSR QUAD CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = CSR QADD CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = XSA QUAD CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = XSA DIPQ CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = CSR HORZ CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = XSA HORZ CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = CSR VERT CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = XSA VERT CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = XSA PVERTING
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = XSA CANT CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = XSA CANT TRM
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = CSR SEXT CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = CSR OCTU CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = CSR SQEWQUAD
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = XSA PSKEWING
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = XSA PMAG CUR
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = CSR SQEWSEXT
[ERROR | 02/13/23 12:23:09]Mnet_sendRequest:  Not initialized.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Failed to send request.
[ERROR | 02/13/23 12:23:09]vnumbr_c:  Node = CHS BPM EPCS
Shall I make the change? Default is N    ->   Choices are Y    or N   
Shall I make the change? Default is N    ->   Choices are Y    or N   
Shall I make the change? Default is N    ->   Choices are Y    or N   
Shall I make the change? Default is N    ->   Choices are Y    or N   
Shall I make the change? Default is N    ->   Choices are Y    or N

**Comment by DavidSagan** [comment]
@JimCrittenden I'm perplexed why a batch job should be different from a non-batch job. I'm not able to debug batch jobs very well so can you try to find an example where running non-batch shows the problem? Thanks.

**Comment by JimCrittenden** [comment]
Yes, I did run it interactively and there is no problem at all.

It just exits the command file and stops.

It's not good, because it wrote Gbs of output file before I noticed.
It could fill a disk.

And I have only a temporary fix, which is to set the sextupole to zero
before setting it. Then the change is smaller. But it depends on dk2_dcu,
which can be practically anything. I guess the cu choice could also be
anything, e.g. by accident. But it could be (and maybe is) protected by the cu limits.

Also, there is no problem with setting it to anything as long as it doesn't get
loaded.

-- Jim

==========================================
James Crittenden                        Tel. (607) 255-4882
Wilson Synchrotron Laboratory
Cornell University
Ithaca, New York 14853-8001
________________________________

**Comment by DavidSagan** [comment]
I put in what might be a fix.

**Comment by JimCrittenden** [comment]
The batch job is still in an infinite loop, just a different one:

_CesrV> ! set the sextupole cu
 _CesrV> ! Protect against too-large change. Otherwise infinite loop in batch.
 _CesrV> ! github issue submitted 13feb2023
 _CesrV> !chan sex 31 @0cu
 _CesrV> chan sex 31 @-30000cu
 This change is rather large...
 Shall I make the change? Default is N    -> !
 ERROR: TO BE SAFE, I AM CLOSING THE COMMAND FILE.
 No change made.
[31m[ERROR | 02/16/23 13:27:31]Mnet_sendRequest:  Not initialized.[0m
[31m[ERROR | 02/16/23 13:27:31]vnumbr_c:  Failed to send request.[0m
[31m[ERROR | 02/16/23 13:27:31]vnumbr_c:  Node = CSR SQUADING[0m
[31m[ERROR | 02/16/23 13:27:31]Mnet_sendRequest:  Not initialized.[0m

...

[31m[ERROR | 02/16/23 13:27:33]vnumbr_c:  Failed to send request.[0m
[31m[ERROR | 02/16/23 13:27:33]vnumbr_c:  Node = CHS BPM EPCS[0m
CesrV>  ERROR: UNRECOGNIZED COMMAND: 
        TYPE "HELP" FOR HELP OR SEE THE WEB DOCUMENTATION
CesrV>  ERROR: UNRECOGNIZED COMMAND: 
        TYPE "HELP" FOR HELP OR SEE THE WEB DOCUMENTATION
CesrV>  ERROR: UNRECOGNIZED COMMAND: 
        TYPE "HELP" FOR HELP OR SEE THE WEB DOCUMENTATION
CesrV>  ERROR: UNRECOGNIZED COMMAND: 

**Comment by DavidSagan** [comment]
@JimCrittenden Now there is logic%exit_on_input_error . Set this to True and this should avoid the problem.

**Comment by JimCrittenden** [comment]
I think it works as you intended:

CesrV>  ERROR: UNRECOGNIZED COMMAND: 
        TYPE "HELP" FOR HELP OR SEE THE WEB DOCUMENTATION
 LOGIC%EXIT_ON_INPUT_ERROR = T SO CESRV WILL STOP.

-- Jim

==========================================
James Crittenden                        Tel. (607) 255-4882
Wilson Synchrotron Laboratory
Cornell University
Ithaca, New York 14853-8001
________________________________
