### ISSUE TITLE
Slow beam tracking through a DRIFT

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#344]
Tracking 100,000 particles through a drift takes 5 seconds, which seems slow.

Changing the lattice to have `lat: line = (100*d1)` also takes 5 seconds (no change).

```
export OMP_NUM_THREADS=1
time tao
[MESSAGE | 2023-FEB-16 10:33:54] tao_init:
    OpenMP active with number of threads: 1
[MESSAGE | 2023-FEB-16 10:33:54] bmad_parser:
    Lattice parse time(min): 0.00
Using startup file: tao.startup

Tao: set ele d1 L = 0

Tao: ! Fast:

Tao: set global track_type = beam

Tao: ! Slow:

Tao: set ele d1 L = 1

Tao: quit
[INFO 2023-FEB-16 10:34:00] tao_command:
    Stopping.
tao  5.87s user 0.17s system 99% cpu 6.048 total
```

[slow.zip](https://github.com/DavidSagan/Bmad/files/10759350/slow.zip)

**Comment by ChristopherMayes** [comment]
Some timing tests on Cori (NERSC), OMP_NUM_THREADS=1:

| Bmad version      | time (s) |
| ----------- | ----------- |
| 20230214.0  | 14       |
| 20230209.1  |    15        |
| 20230110.0  |   4  |
| 20221213.0 |  4 | 
| 20221115.0 |   4  |
| 20221018.2 | 4  | 
| 20221017.0 | SEGFAULT | 
| 20221013.0 | SEGFAULT |
| 20221011.0 | SEGFAULT |
| 20221009.0 | SEGFAULT |
| 20221004.0 | 0.4 | 
| 20220929.0 | 0.4 |
| 20220928.0 | 0.4 |

**Comment by DavidSagan** [comment]
Fixed. Zero length branch causing divide by zero problem.
