### ISSUE TITLE
Long term tracking action-angle calculation using 1-turn matrix

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#346]
Option to use the 1-turn transfer matrix instead of the sigma matrix for action-angle variable calculations (e.g. all action variables are zero for single particle tracking, but 1-turn matrix still can be used in linear approximation).

**Comment by DavidSagan** [comment]
Implemented ltt%action_angle_calc_uses_1turn_matrix (Default False. Set to True to use 1-turn matrix).

**Comment by mattsignorelli** [comment]
Hi David, this doesn't seem to be working, with all action-angle variables still being zero. 

One thing also I wanted to mention is that in the bookkeeping it should be the 1-turn matrix evaluated at ele_start defined in the LTT file

**Comment by DavidSagan** [comment]
Please post your test files. Also the 1-turn matrix is referenced to  ele_start.

**Comment by mattsignorelli** [comment]
[test2.zip](https://github.com/DavidSagan/Bmad/files/10863750/test2.zip)

Another idea when you have more time of course might be to allow action-angle input, instead of phase space, for the beam_init based on the 1-turn matrix - that's what I'm trying to do right now with the SODOM stuff

**Comment by DavidSagan** [comment]
@mattsignorelli The basic problem is that the RF is off so the N-matrix cannot be computed. One possibility is to just have the long_term_tracking program issue an error message and stop. Thoughts?
