### ISSUE TITLE
beambeam gives an error with odd number of slices

### ISSUE THREAD

**Issue by vsmorozov** [bmad-sim/bmad-ecosystem#348]
beambeam gives an intermittent error when the number of slices is odd, e.g., with 5 slices:
...
[FATAL | 2023-FEB-20 15:18:15] super_zbrent:
    ROOT NOT BRACKETED!,   6.6820E-07 at  -1.5500E-06 and   3.7676E-06 at   1.5500E-06
[FATAL | 2023-FEB-20 15:18:15] super_zbrent:
    ROOT NOT BRACKETED!,   3.8235E+80 at  -3.6724E-03 and   3.8235E+80 at   3.6724E-03
[FATAL | 2023-FEB-20 15:18:15] super_zbrent:
    ROOT NOT BRACKETED!,   7.6174E+80 at  -8.9724E-03 and   7.6174E+80 at   8.9724E-03
...

**Comment by DavidSagan** [comment]
@vsmorozov Can you upload your input files? Thanks.

**Comment by vsmorozov** [comment]
Minimum code reproducing the issue is attached. It gives the following error:

bbtest_odd_n_slices$ long_term_tracking long_term_tracking.init 
Initialization file: long_term_tracking.init
[FATAL | 2023-FEB-21 12:51:35] super_zbrent:
    ROOT NOT BRACKETED!,  -2.5408E-22 at  -0.0000E+00 and  -2.5408E-22 at   0.0000E+00
[FATAL | 2023-FEB-21 12:51:35] super_zbrent:
    ROOT NOT BRACKETED!,   3.7939E+80 at  -3.6708E-03 and   3.7939E+80 at   3.6708E-03
[FATAL | 2023-FEB-21 12:51:35] super_zbrent:
    ROOT NOT BRACKETED!,   7.5878E+80 at  -8.9709E-03 and   7.5878E+80 at   8.9709E-03
[ERROR | 2023-FEB-21 12:51:35] radiation_integrals:
    ORBIT IN UNINITALIZED STATE! RADIATION INTEGRALS NOT COMPUTED.
n_particle:                       10000
[FATAL | 2023-FEB-21 12:51:38] super_zbrent:
    ROOT NOT BRACKETED!,   9.7116E-09 at  -6.8067E-07 and   1.3708E-06 at   6.8067E-07
[FATAL | 2023-FEB-21 12:51:38] super_zbrent:
    ROOT NOT BRACKETED!,   2.4451E+80 at  -3.6715E-03 and   2.4451E+80 at   3.6715E-03
[FATAL | 2023-FEB-21 12:51:38] super_zbrent:
    ROOT NOT BRACKETED!,   6.2389E+80 at  -8.9715E-03 and   6.2389E+80 at   8.9715E-03
 Cumulative number dead on turn 49: 1
\# tracking_time = 0.1122

[beambeam_test.zip](https://github.com/DavidSagan/Bmad/files/10796301/beambeam_test.zip)

**Comment by DavidSagan** [comment]
@vsmorozov Fixed.
