### ISSUE TITLE
Long term tracking not correctly reading in spins from beam_init file

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#349]
All particle spins initialized to [0,1,0] regardless of individual particle spin definitions in beam init file. Defining the spin direction for the beam_init structure in the long_term_tracking.init file works, however all particles will then have the same spin. Input files are attached.
[test.zip](https://github.com/DavidSagan/Bmad/files/10843951/test.zip)

**Comment by mattsignorelli** [comment]
It looks like it might just be taking the spin of the first particle and assuming its the same for all particles, actually

**Comment by DavidSagan** [comment]
Fixed.
