### ISSUE TITLE
element-by-element resonance driving terms

### ISSUE THREAD

**Issue by bendmchou** [bmad-sim/bmad-ecosystem#350]
[z_read_m_u_m_t_real_coordinates.f90.zip](https://github.com/DavidSagan/Bmad/files/10852444/z_read_m_u_m_t_real_coordinates.f90.zip)
To implement element-by-element RDTs in Bmad. Useful references:

- [ ] Fig.8 of https://journals.aps.org/prab/pdf/10.1103/PhysRevSTAB.15.054002 RDTs from arc sextupole magnets of a light source (PEP-X)
- [ ] Figs.2, 3, 4, 7, 8, 11 of https://www.slac.stanford.edu/pubs/slacpubs/16000/slac-pub-16127.pdf RDTs from arc sextupole magnets and IR magnets of a collider
- [ ] Pages 17 - 29 of https://research.kek.jp/people/dmzhou/BeamPhysics/SingleParticleDynamics/RDT_SuperKEKB_dmzhou_20180215.pdf s-dependent RDTs calculated by PTC (An example code developed by E. Forest is attached).

**Comment by DavidSagan** [comment]
@bendmchou Sorry to take so long getting around to this. Looking at the code it is not clear how to extract the RDTs from the program. Do you know how to do this?

**Comment by bendmchou** [comment]
> @bendmchou Sorry to take so long getting around to this. Looking at the code it is not clear how to extract the RDTs from the program. Do you know how to do this?

Thanks for looking at it.
I roughly understood the logic of the code. 
If it's not clear to you also, maybe it's not safe to convert it into a robust subroutine for Bmad by ourself.

**Comment by DavidSagan** [comment]
I leave that decision up to you.

**Comment by bendmchou** [comment]
> I leave that decision up to you.

Let's postpone it. I need a good time slot to study the codes carefully.

**Comment by DavidSagan** [comment]
OK I will close for now. Please reopen if desired.
