### ISSUE TITLE
orbit.e_tot value is different from "python lat_list" and "show lat" commands

### ISSUE THREAD

**Issue by williamColocho** [bmad-sim/bmad-ecosystem#352]
The value from the "show lat ..." does change after command
set ele LC PHI0_ERR = 60/360
but the value from "python lat_list ..." does not change.

Tao> show lat END -attr orbit.e_tot
# Values shown are for the Exit End of each Element:
# Index  name key                      s       l orbit.e_tot
      7  END  Marker               2.400   0.000  2.1000E+09
# Index  name key                      s       l orbit.e_tot
# Values shown are for the Exit End of each Element:

Tao> python lat_list END orbit.e_tot
  1.10000130559111E+09

Lattice file:
$ cat cavity.bmad
beginning[beta_a] = 10.   ! m  a-mode beta function
    beginning[beta_b] = 10.   ! m  b-mode beta function
    beginning[p0c] = 1e8   ! eV

    parameter[geometry] = open      ! or closed
    parameter[particle] = electron

    q1: quad, l = 0.1, k1 = 0.14
    q2: quad, l = 0.1, b1_gradient = parameter[p0c] * q1[k1] / c_light
    lc: lcavity, l = 1, voltage = 10e8, rf_frequency = 1e9
    rf: rfcavity, l = 1, voltage = 10e8, phi0 = 0.25, rf_frequency = 1e9

    lat: line = (q1, q2, lc, q1, q2, rf)
    use, lat

**Comment by DavidSagan** [comment]
@williamColocho The python command was returning the reference energy which it should not have. The code has been fixed.
