### ISSUE TITLE
Optimization Not Using Variables/Data

### ISSUE THREAD

**Issue by ags232** [bmad-sim/bmad-ecosystem#353]
I am attempting to run an lattice design optimization. I am trying to optimize for zero Chromaticity by varying Sextupole strengths. However when I run "show var" or "show data", Tao shows that there are no variables or data being used for the optimization. Screenshot here:

![image(1)](https://user-images.githubusercontent.com/47345293/223195255-c4004632-2077-4ee5-a257-8c3806722503.png)

When I delete the veto var * line in my tao.startup file, Tao begins to use the variables defined in my init file for the optimization. But still I can't seem to figure out how to make Tao use the data that I defined as well. 

Attached: tao.init    tao.startup   lattice file

[init.txt.txt](https://github.com/DavidSagan/Bmad/files/10901197/init.txt.txt)
[startup.txt](https://github.com/DavidSagan/Bmad/files/10901198/startup.txt)
[lattice.txt](https://github.com/DavidSagan/Bmad/files/10901199/lattice.txt)

(I had to change them all to .txt files because GitHub doesn't support .init and .bmad files, but the names describes what the files are)

Thank you.

**Comment by DavidSagan** [comment]
@ags232 FYI: You can zip the files and so do not have to modify file names.

**Comment by DavidSagan** [comment]
@ags232 Looks like you posted duplicate files. Please post a zip file containing everything.

**Comment by ags232** [comment]
Sorry about that.

[tao_optimization.zip](https://github.com/DavidSagan/Bmad/files/10910756/tao_optimization.zip)

**Comment by DavidSagan** [comment]
On startup, Tao prints error messages about the datums:

```
[ERROR | 2023-MAR-07 10:52:45] tao_data_sanity_check:
    DATUM OF TYPE: chrom.a
    CANNOT HAVE AN ASSOCIATED ELEMENT: END
    FOR DATUM: chromaticity[1]
[ERROR | 2023-MAR-07 10:52:45] tao_data_sanity_check:
    DATUM OF TYPE: chrom.b
    CANNOT HAVE AN ASSOCIATED ELEMENT: END
    FOR DATUM: chromaticity[2]
[WARNING] tao_init_data:
    Note: All datums in: chromaticity
    are marked as non-existent
```
So modify the tao.init file to fix this and your problem goes away.
