### ISSUE TITLE
Tao "write bmad" command does not produce correct file names for field maps, and resulting tao.init causes Seg Fault

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#354]

**Comment by DavidSagan** [comment]
@ColwynGulliford Please provide example files.

**Comment by ColwynGulliford** [comment]
It's a little tricky since the command I use often to make examples has the problem.  I suspect a hardcoded string size limit is the problem when using absolute paths.  Working on the example.

**Comment by DavidSagan** [comment]
Just provide the original lattice file.

**Comment by ColwynGulliford** [comment]
For example, I just tried to recreate the problem in a self contained example and there is no issue.  In that case everything is using short relative paths, hence my suspicion.  I will try and get you something usable...

**Comment by ColwynGulliford** [comment]
I've narrowed it down to:

`write bmad /Users/colwyngulliford/GitHub/eic-cooler/studies/pc_in2pl/archive/0037d41b5d6ada8e8eb7b2bdaf648c5b/lat.bmad`

causes the problem, but 

`write bmad lat.bmad `

has no issue.

**Comment by DavidSagan** [comment]
Could you post your lat.bmad file?

**Comment by ColwynGulliford** [comment]
[mwe.tgz](https://github.com/DavidSagan/Bmad/files/10912197/mwe.tgz)

**Comment by ColwynGulliford** [comment]
That is the standalone set of files.  You may need to try write bmad to some really long path name to see the issue.

**Comment by DavidSagan** [comment]
@ColwynGulliford You need to modify the files so that I can run:
`ERROR IN bmad_parser: MALFORMED FILE NAME: $COOLER/bmad/fieldmaps/BNL_QWC_197MHz_fieldmesh.h5`

**Comment by ColwynGulliford** [comment]
In the folder provided, there is a subfolder called `output` that has a completely self contained set of example files.  It is the output from write bmad when it works, that is when called without a very long path name.  Can you use that as your example?

**Comment by ColwynGulliford** [comment]
Attaching just that part here:

[output.zip](https://github.com/DavidSagan/Bmad/files/10937929/output.zip)

**Comment by DavidSagan** [comment]
@ColwynGulliford 
I cannot reproduce the problem. I tried:

` write bmad ~/linux_lib/test_gulliford/adfdfadsfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfa/mwe/output/z.bmad`

If you want to diagnose the problem we would need to zoom and I can guide you in debugging this (essentially insert print statements into the code).

**Comment by ColwynGulliford** [comment]
The last thing easy thing I can think of to try first is to make the name of the field map files long too in the lattice file.  I assume Bmad expands things like:

$COOLER/bmad/fieldmaps/BNL_QWC_197MHz_fieldmesh.h5

On my machine the becomes: 

/Users/colwyngulliford/GitHub/eic-cooler/bmad/fieldmaps/BNL_QWC_197MHz_fieldmesh.h5

**Comment by ColwynGulliford** [comment]
Then try the long write bmad str.

**Comment by DavidSagan** [comment]
No that does not work either.

**Comment by DavidSagan** [comment]
I've tried several combinations and no luck.

**Comment by ColwynGulliford** [comment]
Strange!  I able to reproduce it regularly.  I'm running from a conda installation so not sure I can put in print statements.

<img width="845" alt="Screenshot 2023-03-10 at 10 18 47 AM" src="https://user-images.githubusercontent.com/36416205/224354090-09ea7968-74a2-4663-99d6-518a5d78d029.png">

It's an annoying bug, but not a show stopper.  Maybe find a time next week for zoom.

**Comment by DavidSagan** [comment]
Can you compile a Bmad Distribution?

**Comment by ColwynGulliford** [comment]
Yes, I have one compiled on a separate laptop. But don't have time today to look much further on this.

**Comment by DavidSagan** [comment]
The next step is to see if you can reproduce the problem with a Distribution.

**Comment by ColwynGulliford** [comment]
Ok, sounds good.  If I get a moment I'll try running the same thing on the other laptop and will report, not too busy for that.  Just meant I'm booked up and can't zoom today.

**Comment by ColwynGulliford** [comment]
I am able to reproduce the same problem using a tao built from source on my M2 laptop, as opposed to a Conda build:

Here is the directory before running:

```
(cooler) colwyngulliford@Colwyns-MBP-2 e017336f9631b088ce06d930b9bc04de % ls
PL.CRMOD00.MAR.END.h5		commands.tao			gpt.h5				results.yaml
PL.CRMOD01.MAR.END.h5		end.h5				initial_tao_particles.h5	tao.init
```

I then issue:
`(cooler) colwyngulliford@Colwyns-MBP-2 e017336f9631b088ce06d930b9bc04de % tao -init /Users/colwyngulliford/GitHub/eic-cooler/bmad/models/precooler/mg2pl/tao.init -noplot `

At the tao command prompt:

```
Tao> write bmad /Users/colwyngulliford/GitHub/eic-cooler/studies/pc_in2pl/archive/e017336f9631b088ce06d930b9bc04de/lat.bmad
[INFO] tao_write_cmd:
    Written: /Users/colwyngulliford/GitHub/eic-cooler/studies/pc_in2pl/archive/e017336f9631b088ce06d930b9bc04de/lat.bmad
```

Which results in incorrect file names:

```
(cooler) colwyngulliford@Colwyns-MBP-2 e017336f9631b088ce06d930b9bc04de % ls *gri
pl.crmod00.cav01.gri	pl.crmod00.cav02.gri	pl.crmod00.cav03.gri
```

I can debug further during the week.  Maybe zoom Monday?

**Comment by DavidSagan** [comment]
I finally was able to reproduce and fix.
