### ISSUE TITLE
tao issue with electric quads

### ISSUE THREAD

**Issue by vcilento** [bmad-sim/bmad-ecosystem#355]
A sample lattice description to explain the issue is attached (pEDM.txt). The quadruples are defined with the help of the parameter b1_elec_gradient. I noticed that we have some discrepancies in the lattice, in particular the horizontal and vertical tunes when we run using my computers (both Linux and Mac) and my supervisor's (latest version of the Mac). The reference tunes are Qx=2.42 and Qy=0.44. My supervisor is getting the right tunes, while I am getting the tunes that are slightly different (I see at the end of the Twiss table Qx=2.415 and Qy=0.417). If the electro-static quadrupoles are replaced by magnetic ones with appropriate strength, the problem disappears.
Note that the parameter “geometry” is set to “open” (transfer line). The reason is that the Twiss parameters (as well as the plots) computed after launching TAO are not correct for our electro-static rings.  
We cannot understand why we have this problem, I also tried to use the latest version of bmad but this is not changing the results. 
Do you have any idea why this could happen and what we can do to correct it?
Many thanks in advance. 
[pEDM.txt](https://github.com/DavidSagan/Bmad/files/10919506/pEDM.txt)

**Comment by DavidSagan** [comment]
@vcilento 
The first thing to do is to compare the closed orbit and transfer matrices through individual elements. What differences do you notice

**Comment by vcilento** [comment]
@DavidSagan 
I had to set the geometry to open and give the right Twiss starting values otherwise the closed orbit is not computed correctly (if I set the geometry to closed). This happens only when I use electric quads, while if I have electric bends and magnetic quads the closed geometry is computing all the right parameters. 
Concerning your question, I can see from tao directly the matrices for each parameter, do I have to check that one for the quads? should I set the geometry to closed?

**Comment by DavidSagan** [comment]
If the closed orbit is off that would shift the tunes and explain what you are seeing. Do you understand why the closed orbit is off?

**Comment by DavidSagan** [comment]
@vcilento 
According to the initial post, you see different results running Tao on different platforms. I cannot reproduce this so to diagnose the problem what is needed is for you to narrow down what is happening. I can help guide this. If it would help, a zoom session can be arranged.

**Comment by vcilento** [comment]
@DavidSagan 
yes sure we can arrange a zoom session. But if you try to run the pEDM I provide you, what values of tunes do you see?

**Comment by DavidSagan** [comment]
I get:

```
Tao> show uni
Universe: 1  Of: 1
Branch:   0  In range: [0, 0]
is_on:                    T
Lattice name:             "pEDM_ring"
Machine name:             ""
Used line(s) in lat file: "RING"
Lattice file name:        "/nfs/acc/user/dcs16/linux_lib/test_cilento/pEDM.txt"
Reference species:        Proton
Default tracking species: Ref_Particle (Proton)
a_anomalous_moment * gamma     2.23766556E+00
Reference energy:              1.17106409E+09
Reference momentum:            7.00740028E+08
Absolute_Time_Tracking:      F
Geometry:                    Closed
global%rf_on:                T
Elements used in tracking: From 1 through 353
There are no Lord elements
Lattice branch length:      500.000
Lattice branch transit time: 2.787231E-06
Lattice branch S-range:     [.000000, 500.000000]

                              A-Mode         |            B-Mode
                         Model       Design  |       Model       Design
                Q     2.419979     2.419979       0.440222     0.440222  ! Tune
            Chrom    -1.704086    -1.704086      -2.429286    -2.429286  ! dQ/(dE/E)
           J_damp     2.174118     2.174118       1.000000     1.000000  ! Damping Partition #
        Emittance -1.67908E-26 -1.67908E-26    5.12233E-26  5.12233E-26  ! Unnormalized
   Emit (photon vert opening angle ignored)    0.00000E+00  0.00000E+00
       Alpha_damp  2.59743E-19  2.59743E-19    1.19471E-19  1.19471E-19  ! Damping per turn
     Damping_time  1.07307E+13  1.07307E+13    2.33298E+13  2.33298E+13  ! Sec

                         Model       Design
          Z_tune:    0.0000000    0.0000000   ! The design value is calculated with RF on
         Sig_E/E: -1.00000E+00 -1.00000E+00
           Sig_z: -1.00000E+00 -1.00000E+00   ! Only calculated when RF is on
     Emittance_z: -1.00000E+00 -1.00000E+00   ! Only calculated when RF is on
     Energy Loss:  2.79816E-10  2.79816E-10   ! Energy_Loss (eV / Turn)
          J_damp: -2.91030E-02 -2.91030E-02   ! Longitudinal Damping Partition #
      Alpha_damp: -3.47696E-21 -3.47696E-21   ! Longitudinal Damping per turn
       damp_time: -8.01630E+14 -8.01630E+14   ! Longitudinal Damping time (sec)
         Alpha_p:  4.49628E-01  4.49628E-01   ! Momentum Compaction
           Eta_p: -1.92314E-01 -1.92314E-01   ! Slip factor
     gamma_trans:  1.49133E+00  1.49133E+00   ! Gamma at transition
       Spin Tune:  2.39352E-06  2.39352E-06   ! Spin Tune on Closed Orbit (Units of 2pi)
            <pz>:  6.47797E-31  6.47797E-31   ! Average closed orbit pz (momentum deviation)
```

**Comment by vcilento** [comment]
I get instead for the same lattice: 
Tao> show uni
Universe: 1  Of: 1
Branch:   0  In range: [0, 0]
is_on:                    T
Lattice name:             "pEDM_ring"
Machine name:             ""
Used line(s) in lat file: "RING"
Lattice file name:        "pEDM.bmad"
Reference species:        Proton
Default tracking species: Ref_Particle (Proton)
a_anomalous_moment * gamma     2.23766556E+00
Reference energy:              1.17106409E+09
Reference momentum:            7.00740028E+08
Absolute_Time_Tracking:      F
Geometry:                    Closed
global%rf_on:                F
Elements used in tracking: From 1 through 353
There are NO Lord elements
Lattice branch length:      500.000
Lattice branch transit time: 2.787231E-06
Lattice branch S-range:     [.000000, 500.000000]

                                X            |              Y
                         Model       Design  |       Model       Design
                Q     2.415609     2.415609       0.420016     0.420016  ! Tune
            Chrom    -1.695360    -1.695360      -2.490328    -2.490328  ! dQ/(dE/E)
           J_damp   -15.325549   -14.819595       1.000000     1.000000  ! Damping Partition #
        Emittance -8.71886E-18 -8.73033E-18    2.36421E-16  2.36469E-16  ! Photon vert opening angle
                                                                         !     is included in calc
       Alpha_damp -2.24958E-18 -2.17539E-18    1.46787E-19  1.46792E-19  ! Damping per turn
     Damping_time -1.23900E+12 -1.28125E+12    1.89883E+13  1.89877E+13  ! Sec
               I4  2.40933E+00  2.33474E+00   -4.69412E-39  7.69727E-38  ! Radiation Integral
               I5  6.06584E-02  5.87351E-02    4.78070E-75  1.08850E-73  ! Radiation Integral
      I6b/gamma^2                              4.54067E-01  4.54176E-01  ! Radiation Integral

                         Model       Design
          Z_tune:   -0.0000000   -0.0000000   ! The design value is calculated with RF on
         Sig_E/E:  6.70070E-10  6.79560E-10
         Sig_z:    1.00000E+30  1.00000E+30   ! Only calculated when RF is on
     Energy Loss:  3.43793E-10  3.43805E-10   ! Energy_Loss (eV / Turn)
          J_damp:  1.83255E+01  1.78196E+01   ! Longitudinal Damping Partition #
      Alpha_damp:  2.68994E-18  2.61577E-18   ! Longitudinal Damping per turn
       damp_time:  1.03617E+12  1.06555E+12   ! Longitudinal Damping time (sec)
         Alpha_p:  2.79514E-01  2.78695E-01   ! Momentum Compaction
           Eta_p: -3.62429E-01 -3.63248E-01   ! Slip factor
     gamma_trans:  1.89146E+00  1.89424E+00   ! Gamma at transition
              I0:  8.58983E+00  8.58985E+00   ! Radiation Integral
              I1:  1.39757E+02  1.39348E+02   ! Radiation Integral
              I2:  1.47580E-01  1.47586E-01   ! Radiation Integral
              I3:  3.73519E-03  3.73580E-03   ! Radiation Integral
       Spin Tune:  2.39352E-06  2.39352E-06   ! Spin Tune on Closed Orbit (Units of 2pi)
            <pz>:  5.72752E-31  5.72752E-31   ! Average closed orbit pz (momentum deviation)

**Comment by vcilento** [comment]
@DavidSagan 
Maybe we have a zoom session so you can help me to understand why I have different values in comparison to yours.

**Comment by DavidSagan** [comment]
Fix by Vera updating to latest Bmad
