### ISSUE TITLE
Odd behavior of dispersion of an off-momentum beam

### ISSUE THREAD

**Issue by vsmorozov** [bmad-sim/bmad-ecosystem#356]
A recent Bmad update where normalization of the transfer matrix was given up resulted in an odd dispersion behavior of an off-momentum beam. Compare dispersion behavior before (top) and after (bottom) the update. It cannot be explained by simple reference momentum renormalization, e.g. zero dispersion should remain zero regardless of normalization. The code used to generate the figures is attached.

![image](https://user-images.githubusercontent.com/45010171/223755675-1306dc67-93b6-4644-a114-060c8699f764.png)
![image](https://user-images.githubusercontent.com/45010171/223755857-d0baa082-e1d8-498e-b3d9-66016fa2d53d.png)

[230112_beam_merge_bmad.zip](https://github.com/DavidSagan/Bmad/files/10922096/230112_beam_merge_bmad.zip)

**Comment by DavidSagan** [comment]
To make the dispersions at the end all be zero the initial dispersion values must be appropriately set in the lattice files.
