### ISSUE TITLE
dg does not seem to work

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#357]
[dip-bend-example.zip](https://github.com/DavidSagan/Bmad/files/10926371/dip-bend-example.zip)
dg/db_field does not zero field when dg = -ele::d0[g].

**Comment by DavidSagan** [comment]
The field is indeed zero:

```
Element Name: D1
Key: Sbend
Sub Key: SBend
S_start, S:      0.000000,      1.148393

Attribute values:
    1  L                           =  1.1483928E+00 m
    6  G                           =  4.7493799E-03 1/m      43  B_FIELD                     = -6.3368853E-03 T
    7  DG                          = -4.7493799E-03 1/m      44  DB_FIELD                    =  6.3368853E-03 T
    8  G_TOT                       =  0.0000000E+00 1/m      28  B_FIELD_TOT                 =  0.0000000E+00 T
```

Particles are lost for the same reason why particles would get lost in a ring if all the dipole fields are turned off: Particles will go in a straight line and exit the curved beam pipe.

**Comment by henrylovelace3** [comment]
@DavidSagan ok thanks. I understand.
