### ISSUE TITLE
Linear chromaticity optimization disagreeing once file closed + reopened

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#358]
Open the lattice in the attached file and do:

"sho data chrom"
You'll see chrom.a and chrom.b about 10^-3
Run lm and it will immediately give a merit of 10^-20
Do "sho data chrom" again and you'll see chrom.a and chrom.b about 10^-11
Close the lattice file, add "call, file = "var1.out" to the end of the lattice file and reopen in Tao
"sho data chrom" will give chrom.a and chrom.b about 10^-3, not 10^-11 as it should be

[chrom.zip](https://github.com/DavidSagan/Bmad/files/10932738/chrom.zip)

**Comment by DavidSagan** [comment]
Fixed. Problem was when var1.dat file was generated it was missing a slave variable.
