### ISSUE TITLE
Long term tracking error in core emit calc

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#359]
3rd order map tracking mpi:

"...
Thread 8: Cumulative number dead on turn 412: 155
Thread 25: Cumulative number dead on turn 412: 155
dTime:    3.22 Now: 2023-MAR-09 11:12:57  0: Master: Track beam for stage: 412 (End turn: 412)
Thread 0: Cumulative number dead on turn 412: 78
dTime:    3.22 Now: 2023-MAR-09 11:12:57  0: Master: Writing data for stage 412
[WARNING] calc_emittances_and_twiss_from_sigma_matrix:
    Cannot normalize some eigenvectors.
    Note: This can happen if the emittance of a normal mode is very small or zero.
    This will throw off the emittance and other calculations.
 ERROR IN CORE EMIT CALC. PLEASE REPORT!"

Possibly related to large number of particle loss (5,000 particles total, almost each thread lost 155), but unsure.

**Comment by mattsignorelli** [comment]
Input files attached. I do "sh qtrack.sh" to run

[3rd_order_bug.zip](https://github.com/DavidSagan/Bmad/files/10934708/3rd_order_bug.zip)

**Comment by DavidSagan** [comment]
Fixed. Problem was error in emittance calc not properly flagged.
