### ISSUE TITLE
Long term tracking PTC cannot find closed orbit, but Bmad/Tao can

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#360]
Map tracking does not work because PTC cannot find the closed orbit for attached files, however Bmad can. 

[1st_order.zip](https://github.com/DavidSagan/Bmad/files/10935310/1st_order.zip)

**Comment by DavidSagan** [comment]
PTC sometimes has problems if the closed orbit is far from the origin. In this case, I shifted the RF phase setting phi0 = 0.09 which shifted the closed orbit z nearer to zero and then PTC could find the CO. 

One thing to note is that when using PTC you should always vary the number of slices (by adjusting the element attributes ds_step or num_steps) to make sure the simulation is accurate.
