### ISSUE TITLE
Strange Bookkeeping Error

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#362]
[bookkeeper-error.zip](https://github.com/DavidSagan/Bmad/files/10949178/bookkeeper-error.zip)
A series of errors occur when loading upon launch of tao, and when show universe command is used. 
![image](https://user-images.githubusercontent.com/30727946/224505726-9c2c3eb9-7869-4470-a338-d28ab107adfc.png)

![image](https://user-images.githubusercontent.com/30727946/224505713-a4da01e9-fd8b-4b5b-a3d3-f0daeaa7b560.png)

**Comment by DavidSagan** [comment]
Fixed.
