### ISSUE TITLE
Tao python command to show extra globals

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#363]
`python global` outputs the usual globals, but there are several other switches that show space charge, etc. 
Could we add this to python global or have some other way to get this info?

**Comment by DavidSagan** [comment]
@ChristopherMayes 
Can either add to `python global` or can make separate commands. On the Tao side there is no advantage of one over the other. From the Python point of view is there a preference? Note: If everything is put in `python global` I would want to change the parameter names to reflect which structure a parameter is in. For example, `opt_with_base` would become `global%opt_with_base`.

**Comment by ChristopherMayes** [comment]
I'd rather have things separated so they can be called when needed. It could be like `python global:space_charge` PyTao would make that into a method `Tao.global_space_charge()`

**Comment by DavidSagan** [comment]
Now have python commands:

- space_charge_com
- global:optimization
- global:opti_de
