### ISSUE TITLE
Reference momentum p0c doesn't change through lcavity fieldmap, can't plot beam energy using bunch_comb

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#366]
I'm trying to plot the mean bunch energy through a lattice using the bunch_comb.  The arguments I can pass using the bunch_comb command are:
<img width="823" alt="Screenshot 2023-03-13 at 8 26 08 PM" src="https://user-images.githubusercontent.com/36416205/224861057-5ede4daf-43ed-48b1-b0aa-265dc437eb1a.png">

Mean or centroid energy is not an option.

So to try and compute the energy, I do:
<img width="281" alt="Screenshot 2023-03-13 at 8 27 00 PM" src="https://user-images.githubusercontent.com/36416205/224861150-5386bd66-d0e8-41a1-ac67-0620ddd688a0.png">

I notice this reference energy doesn't seem to change through the fieldmap, but only at the end:
<img width="703" alt="Screenshot 2023-03-13 at 8 29 22 PM" src="https://user-images.githubusercontent.com/36416205/224861704-ff0a4d52-2137-4660-accf-cbbfe750248b.png">

Compare that to the orbit energy, which is smooth:

<img width="1083" alt="Screenshot 2023-03-13 at 8 30 44 PM" src="https://user-images.githubusercontent.com/36416205/224861913-4b33573a-8067-401d-a0f5-54b19902dda7.png">

How do I compute the centroid energy?

Also, I tried putting in the attached file of extra markers, but the addition of the markers causes particles to be lost and I get thousands of error messages.
[markers.bmad.txt](https://github.com/DavidSagan/Bmad/files/10962997/markers.bmad.txt)

**Comment by DavidSagan** [comment]
Centroid energy is p0c*(1+pz) and not p0c. p0c jumps at the beginning of and lcavity and is constant through the body.

**Comment by ColwynGulliford** [comment]
Yes, that is what I started with, however its clearly incorrect:

<img width="750" alt="Screenshot 2023-03-14 at 2 09 14 PM" src="https://user-images.githubusercontent.com/36416205/225098400-fbe04c58-d061-4a1e-9204-159f5fb5ece7.png">



I ran that with a 2 mm comb ds step, so I don't suspect this is due to sampling.

So I plotted p0c and it looked stepwise.

**Comment by ColwynGulliford** [comment]
Ningdong made it sound like when tracking with time, different particles could reach the end of elements and have different p0c for a given t.

**Comment by DavidSagan** [comment]
@ColwynGulliford Can you post your input files? Thanks. Right now the drifting to go between constant t and constant s does not work unless you use space charge tracking throughout.

**Comment by ColwynGulliford** [comment]
Attaching them here:
[mwe.tgz](https://github.com/DavidSagan/Bmad/files/10994344/mwe.tgz)

**Comment by DavidSagan** [comment]
One thing to do is track with space charge off and see what happens.

**Comment by ColwynGulliford** [comment]
Without space charge the behavior of p0c is different:

<img width="675" alt="Screenshot 2023-03-16 at 10 00 05 PM" src="https://user-images.githubusercontent.com/36416205/225792927-b1836a3b-7d08-44ee-9508-5019dfb73c70.png">

Now it seems to grow linearly in the cavity. The total Pz = p0c*(1 + pz) seems to track The p0c:
<img width="693" alt="Screenshot 2023-03-16 at 10 06 23 PM" src="https://user-images.githubusercontent.com/36416205/225793648-92bfb0f7-0472-4858-b662-06aac55b14f9.png">

**Comment by DavidSagan** [comment]
@ColwynGulliford I'm going to close this as this issue should be resolved when issue bmad-sim/bmad-ecosystem#331 is.

**Comment by ndwang** [comment]
I believe this issue is unrelated to space charge. I modified `multiparticle/beam_util.f90/calc_bunch_sigma_matrix_etc` so bunch_combs use Pz instead of pz. The bunch_comb curve looks reasonable and agrees with the no-sc case. That means the momentum/energy is tracked correctly.
![Capture](https://user-images.githubusercontent.com/45082410/228093617-0f1cd7d6-1e9e-47bd-9785-1f69f1873ff5.PNG)

The problem comes down to what is stored in bunch_combs. `centroid%vec(6) = avg(p%vec(6)*p%p0c + p%p0c - p0c_avg) / p0c_avg`, but `centroid%p0c` uses `bunch%particle(1)%p0c` and not `p0c_avg`. calc_bunch_sigma_matrix_etc L1772 is commented out - I confirmed that putting it back in causes an error in track1. I'm not sure why calc_bunch_sigma_matrix_etc is involved in single particle tracking, but the error comes from energy sanity check in `code/track1.f90 L136-154`.

A quick fix: We can use `bunch%particle(1)%p0c` in place of `p0c_avg` for all purposes. `centroid%p0c` doesn't make much sense, but users can extract the momentum and energy. But we may eventually want to figure out why calc_bunch_sigma_matrix_etc talks to single particle tracking.

**Comment by DavidSagan** [comment]
@ndwang At constant s p0c should be the same for all particles and if not then this is a bug. So if you can come up with a simple case where this is not so please post it.

**Comment by DavidSagan** [comment]
Note: As far as I can tell, centroid%p0c does not use bunch%particle(1)%p0c.

**Comment by ndwang** [comment]
> @ndwang At constant s p0c should be the same for all particles and if not then this is a bug. So if you can come up with a simple case where this is not so please post it.

With space charge, particles can be in different elements and therefore have different p0c. In this case, p0c_avg!=bunch%particle(1)%p0c in lcavities.

> Note: As far as I can tell, centroid%p0c does not use bunch%particle(1)%p0c.

beam_utils.f90 L1361

**Comment by DavidSagan** [comment]
OK confusion here. When you wrote "particle(1)" I thought you meant the first particle. The code uses particle(i) where `i` is the index of the first living particle.

In any case, yes the calc_bunch_params code needs to be modified to properly handle the constant time case. I will work on it.

**Comment by DavidSagan** [comment]
@ndwang @ColwynGulliford I put in a fix for when calc_bunch_params is called with time coords. When using s-coords, using the average p0c for centroid%p0c is problematical due to round off error in the case where centroid is used for tracking.

**Comment by ndwang** [comment]
> @ndwang @ColwynGulliford I put in a fix for when calc_bunch_params is called with time coords. When using s-coords, using the average p0c for centroid%p0c is problematical due to round off error in the case where centroid is used for tracking.

It is now fixed.
![image](https://user-images.githubusercontent.com/45082410/230227220-c9efdd68-4c2b-431c-bad9-b677367b18a4.png)
