### ISSUE TITLE
When using an lcavity with a field map with master_parameter=voltage_tot, e_tot is changed based on voltage_tot, not voltage

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#372]
Consider this example: [230407a.zip](https://github.com/DavidSagan/Bmad/files/11180647/230407a.zip). What _should_ happen is that `e_tot` should not be changing, since voltage=0. But instead it is changing. It's not obvious exactly what it is doing since pz is nonzero (but small) after the cavity.

**Comment by DavidSagan** [comment]
Fixed. Bug was due to voltage_tot bookkeeping (voltage_tot is used to scale the lcavity field) not being done properly.
