### ISSUE TITLE
Emittance growth due to SR direction-dependent

### ISSUE THREAD

**Issue by kdeitrick** [bmad-sim/bmad-ecosystem#373]
When tracking a round beam through a bend, the emittance growth is different if the dipole bends horizontally or vertically. In universe 1, the beam bends horizontally, and emittance grows horizontally, while vertical emittance remains unchanged. In universe 2, the dipole is rotated, so the round beam bends vertically and emittance grows in both planes and more energy is lost. The emittance is shown in the datum printed. 
[sr_direction.zip](https://github.com/DavidSagan/Bmad/files/11180803/sr_direction.zip)

**Comment by DavidSagan** [comment]
Fixed.
