### ISSUE TITLE
Long term tracking time always -1, no particles read in

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#374]
I think I noticed this a week or so ago but didn't have time to check if I made any mistakes. files are attached.

[sodom2.zip](https://github.com/DavidSagan/Bmad/files/11204977/sodom2.zip)

**Comment by DavidSagan** [comment]
Fixed. Problem was with so few particles the LTT program was doing too aggressive cleanup.
