### ISSUE TITLE
Segmentation Fault using Cavity Fieldmap

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#375]
Attached is the following lattice: 

beginning[beta_a] = 10
beginning[beta_b] = 10

parameter[particle] = electron
parameter[absolute_time_tracking] = T

beginning[e_tot] = 1e6
parameter[geometry] = open

*[tracking_method] = time_runge_kutta
*[mat6_calc_method] = tracking
*[space_charge_method] = fft_3d
!IN_GUN01[space_charge_method] = cathode_fft_3d

IN.CAV01: lcavity, L = 0.5640000000000005,
    rf_frequency = 1300000000.0,
    field_calc = fieldmap, tracking_method = time_runge_kutta, mat6_calc_method=tracking,
    grid_field = call::Cornell_icm_2cell_2D_1300MHz_1V_expanded_fieldmesh.h5,
    wrap_superimpose = False,
    superimpose, ref=beginning, ele_origin=center, offset = 2.086,
    phi0 = 0.04981882132401159
IN.CAV01[voltage]=2001007.833332885
IN.CAV01[autoscale_amplitude] = True
IN.CAV01[autoscale_phase] = True

IN.PIP01: pipe, L = 5
IN.MAR.BEG: marker
IN.MAR.END: marker

in: line = (IN.MAR.BEG, IN.PIP01, IN.MAR.END)

use, in
```

Running this using `tao -lat in.bmad` gives:

```
(cooler) Colwyns-MBP:mwe colwyngulliford$ tao -lat in.bmad
[MESSAGE | 2023-APR-14 07:05:02] tao_init:
    OpenMP active with number of threads: 8

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x1081562b6
bmad-sim/bmad-ecosystem#4  0x10815540d
bmad-sim/bmad-ecosystem#5  0x7ff801ffbc1c
bmad-sim/bmad-ecosystem#6  0x1064526e9
bmad-sim/bmad-ecosystem#7  0x106454a34
bmad-sim/bmad-ecosystem#8  0x1063cb653
bmad-sim/bmad-ecosystem#9  0x106383701
bmad-sim/bmad-ecosystem#10  0x105fad644
bmad-sim/bmad-ecosystem#11  0x105f7df8a
bmad-sim/bmad-ecosystem#12  0x106179447
bmad-sim/bmad-ecosystem#13  0x106895fc4
bmad-sim/bmad-ecosystem#14  0x7ff801ca030f
Segmentation fault: 11
```

I'm using conda version 20230411.0

**Comment by ColwynGulliford** [comment]
Looking at it, I was worried this was just due to the long fieldmap file name, but I shortened the name to "shortname.h5" and the problem persists.

**Comment by DavidSagan** [comment]
@ColwynGulliford Problem is expected index range for the third index is 1:1 but the hdf5 file has 0:0. I will put in a fix for this. Question: How was the hdf5 file generated?

**Comment by ColwynGulliford** [comment]
@DavidSagan Thanks! The hdf5 file was generated using openPMD-beamphyscs FieldMesh object, it is possible that it wasn't set correctly by that code.  @ChristopherMayes can you comment?

**Comment by DavidSagan** [comment]
I can correct on the Bmad side. There is no reason why Bmad should be picky about the third index which is not used for rotationally_symmetric_rz.

**Comment by ColwynGulliford** [comment]
Ok, good!  Thanks again.

**Comment by DavidSagan** [comment]
The fixed code is in the Repository.
