### ISSUE TITLE
use of %re in mais_ripken.f90

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#378]
`mais_ripken.f90` uses %re to get the real part of complex numbers. This feature only appears in Fortran 2008 and so is not supported in all compiles that otherwise compile Bmad (gcc8 is the issue in this case). `v%re` can be replaced with `real(v)`.

**Comment by DavidSagan** [comment]
Fixed. Also output is not meters instead of cm and output order slightly changed.
