### ISSUE TITLE
RF time calc will fail with two overlapping RF elements.

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#379]
Problem is that particle_rf_time cannot handle multiple super_lords with RF. This is a problem in time_runge_kutta and may be a problem elsewhere.

**Comment by ColwynGulliford** [comment]
I assume when you say two overlapping RF elements you don't mean simply two overlapping cavity fields?  I ran the example files I sent on the other issue with no overlapping fields and still see the issue:
<img width="637" alt="Screenshot 2023-04-20 at 3 13 18 PM" src="https://user-images.githubusercontent.com/36416205/233464820-ae76088e-f419-41ff-a8f0-9689aeb1e1c5.png">

**Comment by DavidSagan** [comment]
@ColwynGulliford I believe this is fixed. Please reply if not.
