### ISSUE TITLE
Wakefield pseudomode scale factors, L independent

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#38]
Some Wakefields, like the DC resistive wall with radius r, have the form:
W(z) = factor * W0( z/z0), where W0 is a pure function of z, and the material and radius only appear in the factor and z0. If we had a 'scale_factor' and a 'z_scale_factor' at the ele and/or wake struct level, the general W0 pseudo modes could be reused.

Also, in LCLS2 we implement resistive wall wakes at marker elements, with a scale factor that represents the effective length (sometimes very long). Could we have a switch that disables the ele L and uses the wake as-is?

**Comment by DavidSagan** [comment]
OK I put in new wake scaling parameters:
wake_amp_scale = real
wake_time_scale = real
sr_wake_scale_with_length = T/F

And updated the manual

— Cheers, David

On Aug 2, 2019, at 12:49 PM, Christopher Mayes <notifications@github.com<mailto:notifications@github.com>> wrote:


Some Wakefields, like the DC resistive wall with radius r, have the form:
W(z) = factor * W0( z/z0), where W0 is a pure function of z, and the material and radius only appear in the factor and z0. If we had a 'scale_factor' and a 'z_scale_factor' at the ele and/or wake struct level, the general W0 pseudo modes could be reused.

Also, in LCLS2 we implement resistive wall wakes at marker elements, with a scale factor that represents the effective length (sometimes very long). Could we have a switch that disables the ele L and uses the wake as-is?

**Comment by ChristopherMayes** [comment]
I’m getting kind of crazy results. Is this right?

 arg = ele%wake%wake_time_scale * (mode%phi - orbit%vec(5) * mode%k) 

Shouldn’t the time scale just multiply vec(5)?

**Comment by DavidSagan** [comment]
Correct. Fixed.  — Cheers, David


On Aug 6, 2019, at 7:45 PM, Christopher Mayes <notifications@github.com<mailto:notifications@github.com>> wrote:

I’m getting kind of crazy results. Is this right?

arg = ele%wake%wake_time_scale * (mode%phi - orbit%vec(5) * mode%k)

Shouldn’t the time scale just multiply vec(5)?

**Comment by ChristopherMayes** [comment]
Thanks. Another point of confusion is the the equation has exp(d*z), but d should actually be positive, because z should be negative.

**Comment by DavidSagan** [comment]
I put a sentence in the manual about this.

On Aug 6, 2019, at 11:08 PM, Christopher Mayes <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks. Another point of confusion is the the equation has exp(d*z), but d should actually be positive, because z should be negative.

**Comment by DavidSagan** [comment]
Left to do:

- []  Enable user to specify standard formulas, for example for resistive wake, in the lattice file.
- [x]  Generalize long-range wake syntax so that a given wake term has a phase and can have zero frequency.

**Comment by DavidSagan** [comment]
@ChristopherMayes Chris: I am closing this for now. If you want me to implement the possibility of the user selecting standardized wakes just let me know.
