### ISSUE TITLE
Removing ele_ref or ele_start from a datum

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#380]
For interactive modification of a datum, it would be convenient to be able to remove the ele_ref or ele_start. Ideally `set dat d2.d1[#]|ix_ele_ref = -1` would work, but that results in `ELEMENT INDEX OUT OF RANGE`. There doesn't seem to be a way to set it with `ele_ref_name` either.

**Comment by DavidSagan** [comment]
Done.
