### ISSUE TITLE
Once model value invalid, datum cannot be made valid again

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#381]
I haven't found a way to reliably reproduce this as yet, but the problem is that I have frequently been able to get a datum to become invalid, in every case I recall having the message
```Model value is invalid since: CANNOT EVALUATE DATUM AT OFFSET POSITION.```
Often it was because I tried to change `data_type` on the fly for something that had `eval_point=center`. The problem is that nothing that I do will ever make `exists` true again.

**Comment by jsberg-bnl** [comment]
Here's an example of it getting into this state. Note the negative value for `beta.b` in `%model`, but in the current state `beta.b` is perfectly fine:
```
Tao> sho dat ir6w.betay[4]

Universe: 1  of: 2
%ele_name          = "YO5_QD7"
%ele_start_name    = ""
%ele_ref_name      = ""
%data_type         = "beta.b"
%data_source       = "lat"
%ix_branch         = 0
%ix_ele            = 77
%ix_ele_start      = -1
%ix_ele_ref        = -1
%ix_ele_merit      = -1
%ix_dmodel         = -1
%ix_d1             = 4
%ix_data           = 21
%ix_bunch          = 0
%model             =  -9.87654312E+05
%design            =   1.97308867E+02
%meas              =   2.50000000E+02
%ref               =   0.00000000E+00
%base              =   1.97308867E+02
%error_rms         =   0.00000000E+00
%old               =   0.00000000E+00
%invalid           =   0.00000000E+00
%eval_point        = Center
%s_offset          =   0.00000000E+00
%s                 = UNDEFINED S-POSITION
%merit_type        = "target"
%merit             =   0.00000000E+00
%delta_merit       =   0.00000000E+00
%weight            =   1.00000000E-02
%exists            = F
%good_model        = F
%good_design       = T
%good_base         = T
%good_meas         = T
%good_ref          = F
%good_user         = T
%good_opt          = T
%good_plot         = T
%useit_plot        = F
%useit_opt         = F   ! useit_opt = False since exists = False
Model value is invalid since: CANNOT EVALUATE DATUM AT OFFSET POSITION.
Tao> sho val ele_mid::yo5_qd7[beta_b]
     2.9114917944865590E+02
```

**Comment by jsberg-bnl** [comment]
Oh, that's just your garbage value.

**Comment by jsberg-bnl** [comment]
I see the cause of for centered/offset elements at least: `tao_evaluate_datum_at_s` doesn't check `orb_at_s%state` before calling `tao_param_value_at_s`, the latter then sees `orbit%state` is not `alive$`, returns an error to `tao_evaluate_datum_at_s`, which then sets `bad_datum` leading to extermination.

While that would fix what seems to frequently happen to me, it would also be good to have a way to un-exterminate a datum.

**Comment by DavidSagan** [comment]
Now `set data` will try to toggle exists on. Also `set data ... |exists = True` should work.
