### ISSUE TITLE
Superimposing Markers in Injector Lattice Causes Loss of Reference Particle During Autophasing

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#383]
I have an injector lattice which uses RF field maps that are autoscaled/phased.  I would like to be able to plot a smooth curve for the orbit energy vs. s, so added many markers to do so.  Before adding markers the lattice runs fine:

Adding the makers:
(kyber) colwyngulliford@Colwyns-MBP-2 inv1 % tao -lat in.lat.bmad 
```
[MESSAGE | 2023-APR-24 14:02:51] tao_init:
    OpenMP active with number of threads: 12
[FATAL | 2023-APR-24 14:02:52] ele_compute_ref_energy_and_time:
    PARTICLE LOST IN TRACKING: IN.CAV05
    CANNOT COMPUTE REFERENCE TIME & ENERGY.
[FATAL | 2023-APR-24 14:02:52] tao_init_lattice:
    PARSER ERROR DETECTED FOR UNIVERSE: 1
    EXITING...
```

**Comment by DavidSagan** [comment]
Fixed.
