### ISSUE TITLE
Generalized gradient fit with offset field map

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#387]
The r0 parameter in GG init files is not centering the field map appropriately around axis for calculation of GG coefficients.

Attached is an example from RHIC's siberian snake.

[Centered and offset field maps](https://drive.google.com/file/d/14-p0bwwtVN24hp5IVI_491Ym7MWaIztE/view?usp=sharing)

**Comment by DavidSagan** [comment]
Fixed.

**Comment by DavidSagan** [comment]
Small note: r0 in offset file was not in cm.
