### ISSUE TITLE
Calculation of 2nd order Taylor terms affected by including markers

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#390]
Hi Dave, attached lattice is a short line with few sbends, quads, and sextuples.
You can do `sho Taylor -order 2` to see the tt.xxx terms.
However if you insert markers ( by un-commenting the 2nd last line in lat.bmad ) , then these terms differ.
For instance, the t566 term changes from -1.61 m to -1.60 m.

Is this supposed to happen with PTC calculation? Thanks.

[lat.zip](https://github.com/DavidSagan/Bmad/files/11481933/lat.zip)

**Comment by DavidSagan** [comment]
There will be variations in the map due to changes in step size when the markers are put in. The sextupoles are prime suspects. For example, uncut A1.SX01 uses 1 step of order 2. Try looking at the map through individual elements and vary the number of steps and the order.

**Comment by DavidSagan** [comment]
Since things have been quiet I will close for now. Please reopen if needed.
