### ISSUE TITLE
Corrector kick when using Bmad to Madx translator

### ISSUE THREAD

**Issue by wlin6927** [bmad-sim/bmad-ecosystem#393]
I tried the translator bmad_to_mad_sad_elegant to translate lattice from bmad to madx, where the correctors are defined as hkickers/vkickers with a function to calculate their kicks from PS currents. When I use the translator on a bmad file where I define the corrector current to be non-zero, the corrector in the translated file doesn't have the non-zero kick it should have.

Simple example with one corrector dhce2 between two drift sections attached (delete .txt to make the file format correct), madx file is generated by running `bmad_to_mad_sad_elegant -madx corrector.bmad` in terminal, the dhce2 element in it doesn't have kick defined. But if you run corrector.bmad there is a non-zero kick for dhce2.

[corrector.madx.txt](https://github.com/DavidSagan/Bmad/files/11548537/corrector.madx.txt)

[corrector.bmad.txt](https://github.com/DavidSagan/Bmad/files/11548515/corrector.bmad.txt)

**Comment by DavidSagan** [comment]
Fixed.
