### ISSUE TITLE
User defined x-ray source spectrum for simulations of EXAFS spectrometers

### ISSUE THREAD

**Issue by sstoupin** [bmad-sim/bmad-ecosystem#395]
A user defined source spectrum can be very helpful for testing x-ray crystal spectrometers measuring transmission EXAFS using divergent (~isotropic) polychromatic x-ray sources.  Only energy-dependent intensity, no angular dependence can be assumed. A uniform ~1keV-wide spectrum passing through a foil is modified by x-ray absorption of the foil which includes the absorption edge of interest and the fine structure (EXAFS). The shape of the spectrum can be defined using experimental data taken at a synchrotron as It/Io ratio (example attached, data from APS).  The energy resolution of synchrotron-measured EXAFS is typically good (~1eV) because data is collected sequentially using a tunable x-ray monochromator. Resolution of the crystal spectrometer is usually worse. Therefore, the spectral distribution represented by the synchrotron data can be used to test performance of the spectrometer via ray tracing. 
Such user defined spectrum (numerical input of synchrotron data) would be a very useful feature in Bmad in addition to the existing  Uniform and Gaussian spectral shapes. 
![image](https://github.com/DavidSagan/Bmad/assets/7483526/5ed2e33b-d3d1-4324-b744-720cc3b83643)
[Fe_metal_rt_03.txt](https://github.com/DavidSagan/Bmad/files/11550037/Fe_metal_rt_03.txt)

**Comment by DavidSagan** [comment]
Defined:
```
ele%photon%init_energy_prob   ! Does not have to be normalized.
ele%photon%integrated_init_energy_prob
ele%value(energy_curve_norm$)
energy_distribution = Gaussian, uniform, or curve
```

To Do:
- [x] Read in distribution and compute normalization and spline coefs: energy_probablity_curve = {e1 p1, e2 p2, ...}
- [x] Doc
- [x] Emit photons with distribution
- [x] plot distribution.

**Comment by DavidSagan** [comment]
Done.
