### ISSUE TITLE
tau crashes after 300 steps in optimization

### ISSUE THREAD

**Issue by dejantrbojevic** [bmad-sim/bmad-ecosystem#396]
[May22_2023.zip](https://github.com/DavidSagan/Bmad/files/11555461/May22_2023.zip)

  320    1.5510E+04  9.88-324
  321    1.5510E+04  0.00E+00
  322    1.5510E+04  0.00E+00
 
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
 
Backtrace for this error:
#0  0x103b1a893
bmad-sim/bmad-ecosystem#4  0x103b19b3b
bmad-sim/bmad-ecosystem#5  0x19350b4a3
bmad-sim/bmad-ecosystem#6  0x10083a5c3
Segmentation fault: 11

**Comment by DavidSagan** [comment]
@dejantrbojevic I put in a fix.
