### ISSUE TITLE
Tao veto var error

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#400]
Trying to veto only the first variable gives an error:
[ERROR | 2023-MAY-25 09:14:57] location_decode:
    NAME MATCHES TO MULTIPLE LOCATIONS: 1
[ERROR | 2023-MAY-25 09:14:57] tao_find_var:
    BAD VAR INDEX NUMBER(S): 1

However other variables can be vetoed no problem and have similar definitions
[vetovar.zip](https://github.com/DavidSagan/Bmad/files/11565239/vetovar.zip)

**Comment by DavidSagan** [comment]
I put in a fix.

**Comment by DavidSagan** [comment]
By the way, using indexes for specifying elements (in this case in the tao_var namelist) is to be avoided since any modification of the lattice will break things. Better to use something like "HQD_SS##N" where "N" is an integer to select among elements of like name.
