### ISSUE TITLE
Reading particles: hdf5_read_attribute_int_rank1:ATTRIBUTE IS NOT OF INTEGER TYPE: value

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#405]
Loading externally created particles is now giving me an error:

```
tao   
[MESSAGE | 2023-JUN-07 13:50:25] tao_init:
    OpenMP active with number of threads: 10
[MESSAGE | 2023-JUN-07 13:50:25] bmad_parser:
    Lattice parse time(min): 0.00
[ERROR | 2023-JUN-07 13:50:25] hdf5_read_attribute_int_rank1:
    ATTRIBUTE IS NOT OF INTEGER TYPE: value

Tao> 
```
[error.zip](https://github.com/DavidSagan/Bmad/files/11681843/error.zip)

**Comment by DavidSagan** [comment]
I modified the code to give a better error message. The error now reads:

[ERROR | 2023-JUN-07 21:12:10] hdf5_read_attribute_int_rank1:
    ATTRIBUTE IS NOT OF INTEGER TYPE: particleStatus
