### ISSUE TITLE
chrom.w not evaluating for open lattice

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#408]
[w_optimize.zip](https://github.com/DavidSagan/Bmad/files/11727597/w_optimize.zip)

**Comment by mattsignorelli** [comment]
[w_optimize1.zip](https://github.com/DavidSagan/Bmad/files/11727888/w_optimize1.zip)

**Comment by DavidSagan** [comment]
Extended Tao code to do this.
