### ISSUE TITLE
NaN from lmdif in tao

### ISSUE THREAD

**Issue by rbkibbee** [bmad-sim/bmad-ecosystem#411]
To reproduce:
run ! runs 50 with lm then stops
run lmdif !runs to 450 then produces NaN
[NaNerror.zip](https://github.com/DavidSagan/Bmad/files/11751728/NaNerror.zip)

**Comment by DavidSagan** [comment]
@rbkibbee This has been fixed in the repository and will propagate to the next Distribution.
