### ISSUE TITLE
Tao plot printing `Particle lost at s = ` when there is no loss

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#412]
This simple lattice with a custom phase plot prints `Particle lost` test on the plot, yet there is no particle loss.

All files are in the attached [error.zip](https://github.com/DavidSagan/Bmad/files/11763882/error.zip)

![plot](https://github.com/DavidSagan/Bmad/assets/31023527/828fa543-91e0-4411-8bd2-36750bbdcaef)

**Comment by DavidSagan** [comment]
Fixed.
