### ISSUE TITLE
Tracking Spacecharge beam causes "NaN" for lost particle pz 

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#414]
Attached is a minimal working example where several particles are lost during tracking w/SC on.  When examining the beam output at the at a screen about half through tracking and at the end, there are lost particles.  These report NaN for pz.

To run the example, please run Tao with the start up file "commands.tao"

**Comment by DavidSagan** [comment]
@ColwynGulliford After 20 min Tao is still tracking the beam so this is hard to diagnose. Could you check that the problem still exists? Also please see if you can shorten the computation time and please tell me exactly the commands to use to see the problem.

**Comment by DavidSagan** [comment]
@ColwynGulliford I am closing this for now and you can always reopen if you want.
