### ISSUE TITLE
Warning/particle loss due to radiation loss

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#415]
I'm running a 6 MeV beam through a low energy merger and short linac w/3d SC on.
In the merger I see:

```
Tao: set global track_type =  beam
[WARNING] track1_radiation:
    Particle is kaput due to radiation loss!
1 particle(s) lost at element 6: MG.PIP01B#1  Total lost: 1  of 10000
1 particle(s) lost at element 11: MG.BEN01  Total lost: 2  of 10000
1 particle(s) lost at element 12: MG.PIP02#1  Total lost: 3  of 10000
```

Note - I wonder if this is related to the issue I was seeing with NaN's in the beam data (previous Git issue).  I'm running the attached example using Bmad/Tao via conda:

`bmad  20230613.0`

**Comment by ChristopherMayes** [comment]
`tao -command "call commands.tao"` to run. 

The first time I ran it was fine. The second time:
```
Tao: set global track_type =  beam
[WARNING] track1_radiation:
    Particle is kaput due to radiation loss!
1 particle(s) lost at element 2: MG.PIP01A#1  Total lost: 1  of 10000
```

**Comment by DavidSagan** [comment]
@ColwynGulliford @ChristopherMayes Can you check if this is still a problem? Thanks.

**Comment by DavidSagan** [comment]
Since no response I am closing this issue.

**Comment by ColwynGulliford** [comment]
Hi Dave,

I have turned off radiation integrals in all my Bmad usage to avoid strange behavior.  Last I checked, which was a week ago or so, the radiation integrals seemed to kick particles to 1e1000 TeV.

**Comment by ColwynGulliford** [comment]
Here is example I produced two weeks ago:
![Screenshot 2023-08-13 at 4 58 16 AM](https://github.com/DavidSagan/Bmad/assets/36416205/a5219f7f-52ef-40f5-a95e-2748beb60ba1)

**Comment by ColwynGulliford** [comment]
When I turned the radiation integral off, I stopped seeing the mega energy particle
