### ISSUE TITLE
short range wakes with multiple bunches

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#416]
There is currently no way for the short range wake fields in Bmad to effect multiple bunches

**Comment by DavidSagan** [comment]
@jeu8 With the present code, the only option is to put both bunches into one bunch struct. Try this. I can modify the long_term_tracking program to make it easier for initializing multi-bunches into one. Another possibility if this proves too problematic is to modify the Bmad code to handle the situation. I am closing this issue but please keep in contact as things develop.
