### ISSUE TITLE
rad_int.i2 sometimes not recomputed when dg parameters change

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#417]
Unpack [esr-100-05-230601a.zip](https://github.com/DavidSagan/Bmad/files/11821094/esr-100-05-230601a.zip) and run `tao -lat esr-main-100-05.bmad`. This will output `show universe` and `show value lat::rad_int.i2` for two different `dg` values for the main dipoles in the ring. Note that the energy loss changes as expected, but `lat::rad_int.i2` does not. When I tried to create a simpler example, `lat::rad_int.i2` did change as expected, so there's something a bit complicated going on here.

**Comment by DavidSagan** [comment]
@jsberg-bnl What I get is:

lnx-f2-1:~/linux_lib/test_berg> tao -lat esr-main-100-05.bmad 
[MESSAGE | 2023-JUN-21 13:22:32] bmad_parser:
    Lattice parse time(min): 0.01
[ERROR | 2023-JUN-21 13:22:32] tao_init_data:
    MULTIPLE LATTICE ELEMENTS OF THE SAME NAME: HQF_5A
    FOR DATUM: alpha.a
    WILL MARK THIS DATUM AS NOT EXISTING
[ERROR | 2023-JUN-21 13:22:32] tao_init_data:
    MULTIPLE LATTICE ELEMENTS OF THE SAME NAME: HQF_6B
    FOR DATUM: alpha.a
    WILL MARK THIS DATUM AS NOT EXISTING

So I'm confused as to what to look at.

**Comment by jsberg-bnl** [comment]
Sorry, wrong zip file. Try [230621-rad_int.zip](https://github.com/DavidSagan/Bmad/files/11821666/230621-rad_int.zip)

**Comment by DavidSagan** [comment]
It is a logic bug where the rad ints are not getting recalculated. I will work on it...

**Comment by DavidSagan** [comment]
Fixed.

**Comment by jsberg-bnl** [comment]
This doesn't seem to be fixed when using pytao. When I use pytao and change the lattice `lat::rad_int.i2` doesn't change. Run this [230622-rad_int.txt](https://github.com/DavidSagan/Bmad/files/11835232/230622-rad_int.txt) Python script in the directory you unpacked above, it basically does the same thing that the tao startup script did.

**Comment by DavidSagan** [comment]
Fixed. This involved different code.
