### ISSUE TITLE
Value of C_q in the Bmad manual

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#419]
The last digit of C_q given in the Bmad manual (Synchrotron Radiation Integrals) looks wrong:
```
Tao> sho val -f es10.2 55*h_bar_planck*c_light/(32*sqrt(3)*m_electron)
     3.83E-13
```

**Comment by DavidSagan** [comment]
Manual fixed. Interestingly enough, inaccuracy traced back to me copying Sands ("The Physics of Electron Storage Rings").
