### ISSUE TITLE
Turning off space charge seems to turn off bunch_comb at ds_step

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#420]
When running tao with the `commands.tao` startup file included, if I toggle spacecharge on and off, it seems to change whether the beam stats using the comb are calculated:
![Screenshot 2023-06-22 at 12 06 01 PM](https://github.com/DavidSagan/Bmad/assets/36416205/76d69db3-9312-4846-975a-fdcec2370684)
![Screenshot 2023-06-22 at 12 05 48 PM (1)](https://github.com/DavidSagan/Bmad/assets/36416205/6085910d-4473-4574-840a-2c61869a9de3)

**Comment by ColwynGulliford** [comment]
Here I use the global space charge switch "`bmad_com:csr_and_space_charge_on`"

Here's the MWE.
[mwe.tgz](https://github.com/DavidSagan/Bmad/files/11837973/mwe.tgz)

**Comment by DavidSagan** [comment]
@ColwynGulliford: Lattice file mg2l1.lat.bmad is missing. Please make sure the problem can be seen with the files provided.

**Comment by ColwynGulliford** [comment]
@DavidSagan I changed `'mg2l1.lat.bmad'` with `'lat.bmad'` in `tao.init` and re-attaching:

[mwe.zip](https://github.com/DavidSagan/Bmad/files/11849991/mwe.zip)

**Comment by ColwynGulliford** [comment]
I tried rerunning the latest files and get:

(cooler) Colwyns-MBP:mwe colwyngulliford$ tao
```
[MESSAGE | 2023-JUN-23 11:42:13] tao_init:
    OpenMP active with number of threads: 8

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x10a5692b6
bmad-sim/bmad-ecosystem#4  0x10a56840d
bmad-sim/bmad-ecosystem#5  0x7ff81aebac1c
Segmentation fault: 11
```

**Comment by DavidSagan** [comment]
I just put in a fix for that.

**Comment by DavidSagan** [comment]
@ColwynGulliford How did you generate the plots and which plot is which?

**Comment by ColwynGulliford** [comment]
The plots are generated by getting the data from the comb using PyTao, so:

`sqrt( tao.bunch_comb('sigma.11') )`

**Comment by DavidSagan** [comment]
I put in a fix.
