### ISSUE TITLE
Dynamic_Aperture input issues

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#422]
This problem is in the stand alone Dynamic_Aperture program, I do not see this when running through Tao

I set min_angle=0 and max_angle=3.14159, however the program uses max_angle=0.1 and lists it as the input in the data file. 

I am also concerned that ramp files are not being properly used. I appear to get the same output with and without it.

The files I was using are located at nfs/acc/temp/jeu8/test

**Comment by DavidSagan** [comment]
@jeu8: Fixed both angle and ramp problems. Try it now. Note: Syntax of input file is a bit different now. I have updated the manual. However, the old syntax still works (and the files you pointed to work).
