### ISSUE TITLE
var1.out corrupted with no warning

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#423]
My REU student defined a variable with ele_name that had a space in the single quotes before the element name (see HQLS5_5)
	var(1:7)%ele_name = 'HQLS1_5', 'HQLS2_5', 'HQLS3_5', 'HQLS4_5', ' HQLS5_5', 'HQLS6_5', 'HQLS7_5'

Tao seemed to work perfectly fine but var1.out was corrupted

**Comment by DavidSagan** [comment]
Fixed.
