### ISSUE TITLE
Setting RF voltage after calling show uni doesn't work

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#425]
In attached file if I do
set ele CAVITY_591MHZ voltage = 28e6

before calling show uni, everything is fine. But if I call show uni before, it does not work

**Comment by mattsignorelli** [comment]
[hsr-275-10-2.zip](https://github.com/DavidSagan/Bmad/files/11909152/hsr-275-10-2.zip)

**Comment by DavidSagan** [comment]
Fixed.
