### ISSUE TITLE
build system: ACC_SET_GMAKE_JOBS appears to be applied twice

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#429]
During the build, if I set `ACC_GMAKE_JOBS=4`, I sometimes see many more than 4 compiler jobs running at the same time. I'm guessing that the `-j 4` option is effectively getting applied in two layers, or something along those lines? I see the behavior when building hdf5, maybe other places as well.

**Comment by DavidSagan** [comment]
@jsberg-bnl: Can you report this to Attilio via service-classe@cornell.edu ? Thanks
