### ISSUE TITLE
Long term tracking: odd behavior with RF off

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#433]
Turning RF off and doing single particle tracking with only an initial amplitude in y (defined in LTT file) gives after 1 turn a growing amplitude in x up to some value. The lattice is uncoupled.

x-px phase space after some number of turns:
![Screenshot 2023-07-07 174015](https://github.com/DavidSagan/Bmad/assets/113714234/73147edb-d7aa-401d-8c51-27dde1e06517)

If I set *[tracking_method] = linear, x-px looks like:
![Screenshot 2023-07-07 174123](https://github.com/DavidSagan/Bmad/assets/113714234/120344d8-9c1d-42f3-bce7-3ef0afb11387)

Files are at /home/mgs255/mgs255/test/issue-07-07-23/

**Comment by mattsignorelli** [comment]
I also noticed that the turn 0 coordinates in the output file are not equal to what I give in the .init file, with a nonzero initial x

**Comment by DavidSagan** [comment]
You have ltt%add_closed_orbit_to_init_position = T so this shifts the orbit. Also there are solenoids and solenoids have nonlinear coupling. One way to test is to vary the initial amplitude. If the horizontal motion scales quadratically or with a higher power this indicates the coupling is nonlinear.
