### ISSUE TITLE
Long_Term_Tracking MPI Crashed during Bmad Tracking

### ISSUE THREAD

**Issue by annaconnelly** [bmad-sim/bmad-ecosystem#435]
The average.dat.ave file was supposed to have 3000 turns and only went up to 2210 turns. I had the  .init file set so that a phase.dat file was produced after every turn, and phase.dat files were produced up to phase.dat.2301. 

 Here is the error output:
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 30, file /nfs/acc/user/aac236/Lattices/particle_tracking/phase.dat2302
Image              PC                Routine            Line        Source             
long_term_trackin  0000000001455D1F  Unknown               Unknown  Unknown
long_term_trackin  000000000146A584  Unknown               Unknown  Unknown
long_term_trackin  00000000004254F6  lt_tracking_modlt        1565  lt_tracking_mod.f90
long_term_trackin  0000000000424C54  lt_tracking_mod_m        1499  lt_tracking_mod.f90
long_term_trackin  000000000040F4A5  MAIN__                    289  long_term_tracking_mpi.f90
long_term_trackin  000000000040C95E  Unknown               Unknown  Unknown
libc-2.17.so       00007FC5761BB555  __libc_start_main     Unknown  Unknown
long_term_trackin  000000000040C861  Unknown               Unknown  Unknown

The files are located here: /home/aac236/CLASSE_shortcuts/acc_aac236/Bmad

**Comment by DavidSagan** [comment]
@annaconnelly I cannot reproduce this. Try the following: 
1) Try to run again and see if you get the same error.
2) Reduce the number of particles to 20 and see if you get the same error
3) Use the lattice /home/dcs16/linux_lib/test_connelly/small_ring.bmad with #particles = 1000.
4) If you get the error for steps 2 & 3 try using 20 particles with small_ring.bmad.
5) Try using the exe at /home/dcs16/bmad_distribution/bmad_dist/production/bin
