### ISSUE TITLE
After creating a datum with python data_d2_create, cannot assign to data_type

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#437]
Simple example: [230711a.zip](https://github.com/DavidSagan/Bmad/files/12021325/230711a.zip); run with `tao -lat lat.bmad`, note the failure of the `set data d.d[1]|data_type` command. Cannot assign to the `data_type` component of the datum. Workaround is to use `python datum_create`, but that's messy in that you need to know exactly how many times to type `^^`.

**Comment by DavidSagan** [comment]
Fixed.
