### ISSUE TITLE
Feature Request: calculate slice emittance of a beam

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#445]
Is there a way to get the slice emittance in tao?  I am thinking something like `sho beam end -s -0.0005:0.0005`  that would restrict the calculation of the sigma matrix and emittances to the middle 1 mm of the bunch.

Specifying slices in terms of n^th slice out of N where the user chooses n and N would probably work too.

**Comment by ChristopherMayes** [comment]
Note that is it often useful to slice the beam in regularly sized chucks of particles instead of simply binning in regularly spaced `z` bins.

**Comment by DavidSagan** [comment]
Done. See the updated documentation.

**Comment by MichaelEhrlichman** [comment]
Looks good.  Some basic tests return sensical numbers.
