### ISSUE TITLE
RF cavity problems when setting tracking_method = taylor

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#449]
If parameter[taylor_order] = 1, then a closed orbit cannot be found. If taylor_order is not set, then the plot of the orbit looks like the mirror of the plot of the dispersion, and z = -114m at the cavity.

tracking_method = linear works just fine.
[esr-18GeV.zip](https://github.com/DavidSagan/Bmad/files/12088675/esr-18GeV.zip)

**Comment by DavidSagan** [comment]
@mattsignorelli I put in a fix.

**Comment by mattsignorelli** [comment]
This is giving a particle a kick to pz when x,px,y,py,z,pz = 0 entering the magnet. Try with the files attached above
