### ISSUE TITLE
Long term tracking crashing at turn 300000

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#450]
This happened to all 8 of my trackings overnight. Once they hit turn ~300000, the program bombed. Here is the tail of out.txt:

dTime:  886.70 Now: 2023-JUL-19 01:47:41  31: Slave: Track beam for stage: 300001 (End turn: 300001)
dTime:  886.70 Now: 2023-JUL-19 01:47:41  7: Slave: Track beam for stage: 300001 (End turn: 300001)
dTime:  886.70 Now: 2023-JUL-19 01:47:41  17: Slave: Track beam for stage: 300001 (End turn: 300001)
dTime:  886.64 Now: 2023-JUL-19 01:47:41  0: Master: Track beam for stage: 300001 (End turn: 300001)
dTime:  886.64 Now: 2023-JUL-19 01:47:41  0: Master: Writing data for stage 300001
[FATAL | 2023-JUL-19 01:47:41] lunget:
    NO LOGICAL UNIT OPENABLE BETWEEN 30 AND 60!
 
 !-------------------------------------------------
 ERR_EXIT: WILL BOMB PROGRAM TO GIVE TRACEBACK...

and traceback:
forrtl: severe (71): integer divide by zero
Image              PC                Routine            Line        Source             
long_term_trackin  000000000145BD1D  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FB2B9331630  Unknown               Unknown  Unknown
long_term_trackin  00000000008B9B52  err_exit_                  38  err_exit.f90
long_term_trackin  000000000087C752  lunget_                    41  lunget.f90
long_term_trackin  000000000042784B  lt_tracking_mod_m        2170  lt_tracking_mod.f90
long_term_trackin  000000000040F4BE  MAIN__                    290  long_term_tracking_mpi.f90
long_term_trackin  000000000040C95E  Unknown               Unknown  Unknown
libc-2.17.so       00007FB2B68ED555  __libc_start_main     Unknown  Unknown
long_term_trackin  000000000040C861  Unknown               Unknown  Unknown

Files are at /home/mgs255/mgs255/test/issue-07-19-23/

**Comment by mattsignorelli** [comment]
I found it had the same error for another tracking with only one particle around turn 550000. I think it is related to the beam binary file writing

**Comment by DavidSagan** [comment]
@mattsignorelli I put in a fix. Please test.
