### ISSUE TITLE
Long term tracking single particle tracking spin decimal places

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#451]
For single particle tracking the single.dat output file should print more decimal places for the spin

**Comment by DavidSagan** [comment]
@mattsignorelli Can you give me line numbers for this?

**Comment by mattsignorelli** [comment]
Line 143 in lt_tracking_mod change ps_fmt

**Comment by mattsignorelli** [comment]
If it isn't too much work it would be convenient if it printed the time too

**Comment by DavidSagan** [comment]
Done.
