### ISSUE TITLE
dynamic aperture program crashing while making maps

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#453]
I am using the dynamic aperture program with first order maps and excluding different elements. When I exclude sbends it crashes. This could likely be due to a large number of sbends, but it is not clear from the error message.

the files are at /nfs/acc/temp/jeu8/test

**Comment by DavidSagan** [comment]
@jeu8 Fixed. Problem was the counting of sections when bends were excluded from maps.
