### ISSUE TITLE
tao crash when a variable wanders too far off

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#456]
Another user error when ends up crashing tao. Run `tao -noplot` on
[230725a.zip](https://github.com/DavidSagan/Bmad/files/12165530/230725a.zip). On the second `run lmdif`, it crashes, ending with
```
    CHARGE NOT KNOWN FOR SPECIES: -999
[ABORT | 2023-JUL-25 16:57:26] mass_of:
    MASS NOT KNOWN FOR SPECIES: -999
[ABORT | 2023-JUL-25 16:57:26] charge_of:
    CHARGE NOT KNOWN FOR SPECIES: -999
[ABORT | 2023-JUL-25 16:57:26] mass_of:
    MASS NOT KNOWN FOR SPECIES: -999
 ** On entry to DGEBAL parameter number  3 had an illegal value
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
```
The problem was that for the first `run lmdif` I had accidentally left one variable on for the optimization and it wandered off to some ungodly value. Now, why it wandered off is unclear since the derivative of all the data enabled for that optimization with respect to the variable in question (`th12`) was zero and it thus should have known better.

**Comment by DavidSagan** [comment]
Fixed.
