### ISSUE TITLE
If a datum has data_type=phase.a but no valid ele_name, tao crashes

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#458]
Run this example: [230728a.zip](https://github.com/DavidSagan/Bmad/files/12198234/230728a.zip), and tao will segfault, due to the `phase.a` datum and no associated `ele_name`. This caught me when I reassigned `data_type` for a datum that previously had an expression. Probably this is a broader issue, some values of `data_type` need to first check if there's a valid `ele_name`, and if not fail gracefully. `beta.a`, for instance, has no issues, just gives a message.

**Comment by DavidSagan** [comment]
Fixed.
