### ISSUE TITLE
lat::chrom_ptc.a.0 and lat::chrom_ptc.b.0 do not update when called from script

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#459]
[error.zip](https://github.com/DavidSagan/Bmad/files/12208504/error.zip)
The values for the fractional tunes do not update when called from script. 
Single command shown below
![image](https://github.com/DavidSagan/Bmad/assets/30727946/86a690a3-2faa-4584-a34e-8120e645b0be)

When script is run, the values of the fractional tunes do not update

**Comment by DavidSagan** [comment]
@henrylovelace3 Please attach input files.

**Comment by henrylovelace3** [comment]
The files should be in the error zip file attached.

**Comment by henrylovelace3** [comment]
Archive:  error.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
    23132  07-27-2023 14:48   rcs-06-05-23.bmad-test
     3380  07-28-2023 13:38   dynap/eddy-current-scan.tao
---------                     -------
    26512                     2 files

Just run tao and call dynap/eddy-current-scan.tao

**Comment by DavidSagan** [comment]
@henrylovelace3 I don't see an error.zip file attached anywhere.

**Comment by henrylovelace3** [comment]
[error.zip](https://github.com/DavidSagan/Bmad/files/12285657/error.zip)

Here is the zip file

**Comment by DavidSagan** [comment]
@henrylovelace3 My apologies. I somehow overlooked the first attachment.

**Comment by DavidSagan** [comment]
Finally found and fixed the bug. It was due to the bmad to ptc fibre updater code not being updated when there was a change in how PTC handled RF cavities.
