### ISSUE TITLE
Tao python spin_polarization shows spin_tune = 0 if spin tracking not set T in lat file

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#464]
If the lattice does not have "bmad_com[spin_tracking_on] = T" in the lattice file, then the spin_tune printed is 0 (but everything else is not zero) using this command:

python spin_polarization 1@0|model

lattice file attached
[esr.txt](https://github.com/DavidSagan/Bmad/files/12296045/esr.txt)

**Comment by DavidSagan** [comment]
Fixed.
