### ISSUE TITLE
Add dn_dpz, spin eigenvectors and amplitudes as element attributes in Tao

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#471]

**Comment by DavidSagan** [comment]
@mattsignorelli dn_dpz(:) array already exists. Which eigenvectors and amplitudes are you referring to?

**Comment by mattsignorelli** [comment]
The individual n_k’s and their A_k’sOn Aug 11, 2023, at 5:08 PM, David Sagan ***@***.***> wrote:﻿
@mattsignorelli dn_dpz(:) array already exists. Which eigenvectors and amplitudes are you referring to?

**Comment by DavidSagan** [comment]
I have created the tao_spin_ele_struct which these parameters. %orb_eigen_val, %orb_eigen_vec and %spin_eigen_vec are not currently set.
