### ISSUE TITLE
BBU tracking:  the injected bunches have generally large z orbit values

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#472]
Currently the injected bunches for BBU have z orbit separated by RF wavelength ( see the table of values at the bottom ).
Large z values translate to large orbit values if the downstream elements have non-zero RX5 transfer-matrix values ( which leads to beam loss ).
Non-zero RX5 transfer-matrix values usually (only?) occurs when hybridization includes cavities.
The current BBU program allows the users to hybridize cavities assuming the cavities have no HOM assigned, so this issue can occur.

One potential fix is to shift all z orbits ( by "mod" them with RF_wavelength ). Hopefully this would still make physical sense and is compatible with the program.

Thanks.

==========
The following table can be produced by un-commenting out line 484 in bbu_track_mod.f90.

ele_ix:   1 bunch_ix:   1  orbit: -1.257E-09 0.000E+00 -3.961E-09 0.000E+00 0.000E+00 0.000E+00
 ele_ix:   2 bunch_ix:   1  orbit: -7.106E-10 2.006E-10 -2.239E-09 6.319E-10 -1.330E-12 2.047E-10
 ele_ix:   1 bunch_ix:   2  orbit: 1.697E-08 0.000E+00 -3.720E-09 0.000E+00 -2.309E-01 0.000E+00
 ele_ix:   2 bunch_ix:   2  orbit: 9.594E-09 -2.708E-09 -2.103E-09 5.935E-10 -2.312E-01 2.129E-10
 ele_ix:   1 bunch_ix:   3  orbit: -4.703E-09 0.000E+00 1.020E-08 0.000E+00 -4.618E-01 0.000E+00
 ele_ix:   2 bunch_ix:   3  orbit: -2.658E-09 7.502E-10 5.768E-09 -1.628E-09 -4.623E-01 2.129E-10
 ele_ix:   1 bunch_ix:   4  orbit: -7.536E-10 0.000E+00 8.320E-11 0.000E+00 -6.927E-01 0.000E+00
 ele_ix:   2 bunch_ix:   4  orbit: -4.259E-10 1.202E-10 4.703E-11 -1.327E-11 -6.935E-01 2.129E-10

**Comment by DavidSagan** [comment]
@weiyuanlou I noticed that the manual description of bbu_param parameters leaves off many of the parameters. Just one example is `ele_track_end`. Since part of this process will be manual cleanup on my end. I will wait until you have updated the manual. Note: I have checked in to the repo my manual cleanup work up to this point in time.

**Comment by DavidSagan** [comment]
@weiyuanlou Should I close this? You can always get back to this when you are ready.
