### ISSUE TITLE
Lattice translation from Bmad to Elegant: missing parameters

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#473]
Currently 'bmad_to_mad_sad_elegant.f90' can translate a Bmad lattice to elegant.
Two potentially missing parameters were identified:

(1) The parameter N_SLICES for magnets (CSBEND/kquad/ksext/koct) in ELEGANT has an ( awfully ) small default value ( either 1 or 4 ).  This can strongly affect beam-tracking results. My suggestion is to translate the DS_STEP in bmad to N_SLICES in elegant  ( like N_SLICES  = floor ( element_length / DS_STEP ) ).

(2) lcavity in Bmad translates to RFCA in Elegant, but the default RFCA is 'traveling wave', not 'standing wave'. The flag 'STANDING_WAVE' in Elegant needs to be set based on what Bmad lcavity has.  ( This issue might occur to all other cavity types )

Thanks.

**Comment by DavidSagan** [comment]
@weiyuanlou A Bmad element has `num_steps`. Why not just directly translate that?

**Comment by weiyuanlou** [comment]
Oh yes, num_steps should work too. 
I was helping with translating from Elegant to Bmad, but not from Bmad to Elegant.
Could you put in the fix when free ( also for standing_wave ) ? Thanks.

**Comment by ChristopherMayes** [comment]
Also, for standing wave cavities, we should set `RFCA` elements to have:
- `standing_wave=1`
- `end1_focus=0`
- `end2_focu2=0`
- `body_focus_model="SRS"`

**Comment by DavidSagan** [comment]
@weiyuanlou n_slices is not set per element so I am mystified exactly what you are wanting with this.

**Comment by DavidSagan** [comment]
Modified cavity translation. @ChristopherMayes end1_focus and end2_focus default to zero so no need to explicitly set.

**Comment by ChristopherMayes** [comment]
Actually, I think we want those `end1_focus=1`, `end2_focus=1`

**Comment by DavidSagan** [comment]
Done.
