### ISSUE TITLE
data_type = 'beam' not valid for data type n_particle_loss

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#474]
[ERROR | 2023-AUG-14 19:39:03] tao_set_invalid:
    DATA_TYPE = "beam" NOT VALID FOR THIS DATA_TYPE: n_particle_loss

**Comment by MichaelEhrlichman** [comment]
Sort of a work around.  Replace start_ele_ix and end_ele_ix as appropriate.

`datum( 3) =  'expression: beam::n_particle_loss[start_ele_ix&end_ele_ix]'     '' '' ''   'target'   0.0  1e1`

**Comment by DavidSagan** [comment]
@MichaelEhrlichman Looking at the code I do not see how this error message could be generated. Please attach test files.

**Comment by MichaelEhrlichman** [comment]
Found a clue while putting together a test:

Adding `datum(3)%data_source = 'beam'` to the tao_d1_data prevents the error shown below.   The datum is:

```datum( 3) =  'n_particle_loss'     '' 'BEAM_START' 'YAGDL18_OTR'   'target'   0.0  1e1```

```
tao_set_invalid:
DATA_TYPE = "beam" NOT VALID FOR THIS DATA_TYPE: n_particle_loss
FOR DATUM: YAGDL18_OTR[3]
```

**Comment by MichaelEhrlichman** [comment]
Test case at Cornell demonstrating bug:

```
[mpe5@lnx201 77]$ pwd
/home/ehrlichm/for_dcs/77
[mpe5@lnx201 77]$ tao
[ERROR | 2023-AUG-15 20:36:50] tao_set_invalid:
    DATA_TYPE = "beam" NOT VALID FOR THIS DATA_TYPE: n_particle_loss
    FOR DATUM: BUG_REPORT[1]
```

**Comment by MichaelEhrlichman** [comment]
The logic seems clear.  If the data_type is n_particle loss, then data_source needs to be 'beam'.  In the code below from `tao_data_and_eval_mod.f90`, if the data_source is anything other than 'beam', is prints ` 'DATA_TYPE = "beam" NOT VALID FOR THIS DATA_TYPE: '`.

So the error message is simply incorrect.  Note that data_source defaults to 'lat', and is indeed 'lat' in my test case.

So I see two solutions:

1.  Fix the error message
2. Is there a way to make n_particle_loss data types default to data_source = 'beam'?  Does tao change the default data_source depending on data_type?

```
case ('n_particle_loss')
  if (data_source /= 'beam') goto 9000  ! Set error message and return
  if (ix_ele < 0) ix_ele = branch%n_ele_track
  datum_value = sum(bunch_params(ix_ref+1:ix_ele)%n_particle_lost_in_ele)
  valid_value = .true.

...

9000 continue
call tao_set_invalid (datum, 'DATA_TYPE = "beam" NOT VALID FOR THIS DATA_TYPE: ' // datum%data_type, why_invalid, .true.)
return
```

**Comment by DavidSagan** [comment]
Fixed error message and now n_particle_loss defaults to beam data_source
