### ISSUE TITLE
Dispersion effected by solenoid that is turned off

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#476]
I'm trying to migrate from using hardedge solenoids to the soft edge model in Bmad, as this model has a 1:1 correspondence with a model for solenoids in GPT.  I have a merger system that I want to close the dispersion for using solenoids between two bends, however the dispersion behaves oddly.  In particular, if I turn the solenoid off it still bends the dispersion function.  In the example below, I have a bend and then solenoid.  
<img width="1212" alt="Screenshot 2023-08-18 at 4 24 04 PM" src="https://github.com/DavidSagan/Bmad/assets/36416205/d427a057-7352-4c53-a8df-7517098d6162">

If I plot the b_fields, I can see that the solenoid field is zero:

<img width="658" alt="Screenshot 2023-08-18 at 4 23 23 PM" src="https://github.com/DavidSagan/Bmad/assets/36416205/e8050571-1bf9-46a7-b438-6326aacfd2f0">

It seems like the dispersion calc has a bug or the solenoid is still on?

Here is my lattice file:
[mg.test copy.bmad.txt](https://github.com/DavidSagan/Bmad/files/12384449/mg.test.copy.bmad.txt)

**Comment by DavidSagan** [comment]
@ColwynGulliford Fixed. This was a strange bookkeeping bug where the finite r_solenoid confused Bmad so Bmad thought it was dealing with a bend!

Also: To the extent that the field is not zero at the ends of the solenoid, there will be an edge kick.
