### ISSUE TITLE
starting orbit not initialized

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#477]
If tracking starts at the beginning of L0B#3 (yes, 3), then errors like the following come up for many following elements.  If tracking starts at the end of L0B#3, then the errors do not appear.

Test case:
```
[mpe5@lnx201 78]$ pwd
/home/ehrlichm/for_dcs/78
```
```
[ERROR | 2023-AUG-22 15:33:44] track1:
    STARTING ORBIT NOT PROPERLY INITIALIZED! [NEEDS AN INIT_COORD CALL?]
    TRACKING THROUGH ELEMENT: L0B#6 (58)
```

**Comment by DavidSagan** [comment]
Fixed element slicing bug.
