### ISSUE TITLE
r12 and r21 terms in track_this_lcavity subroutine.

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#479]
I am comparing Rosenzweig & Serafini equation 13 with Bmad's track_this_lcavity subroutine.  It appears to me that (in the standing wave case) the subroutine's calculation of kmat(1,2) is missing a factor of Cos(Dphi) and kmat(2,1) has an extra factor of Cos(Dphi).  I have checked Rosenzweig & Serafini's matrix multiplication exit dot body dot entrance and at least their matrix algebra is correct.
Setting eta=1 and applying some identities to make Equation 13 and the track_this_lcavity calculation look similar, I find the result below.  Do you know the reason for the discrepancy?

![image](https://github.com/DavidSagan/Bmad/assets/18479946/a192c3ce-8f85-4929-9e73-948b2fdb594e)

**Comment by DavidSagan** [comment]
The factors of cos[del_phi] are hidden in the Bmad code in gradient_max. That is: gradient = gradient_max * cos[del_phi]
