### ISSUE TITLE
Tao python command incorrect error

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#484]
I'm getting an error for:
Tao> python lat_list 1@0>>quadrupole::*|model ele.k1
[ERROR | 2023-AUG-31 14:37:11] tao_python_cmd:
    "python lat_list 1@0>>quadrupole::*|model ele.k1": Bad {who}: ele.k1
INVALID

When "help python lat_list"  says:
!     ele.{attribute} Where {attribute} is a Bmad syntax element attribute. (EG: ele.beta_a, ele.k1, etc.)

**Comment by DavidSagan** [comment]
Two issues:
1) Code bug fixed.
2) "quadrupole::" needs to be "quadrupole::*".
