### ISSUE TITLE
`write bmad` with e_gun not giving the same beginning e_tot

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#487]
Using `write bmad` and reloading shows different beginning e_tot.

```
tao -noplot -lat lat.bmad -command "sho value ele::beginning[e_tot];quit"

Tao: sho value ele::beginning[e_tot]
     9.1099898980239313E+05
```

```
tao -lat lat.bmad -noplot -command "write bmad;quit"
Tao: write bmad
[INFO] tao_write_cmd:
    Written: lat_1.bmad
```

```
tao -noplot -lat lat.bmad -command "sho value ele::beginning[e_tot];quit"

Tao: sho value ele::beginning[e_tot]
     9.1099898776161368E+05
```

Files are in my CLASSE error directory, `e_gun_beginning_write_bmad`

**Comment by DavidSagan** [comment]
Difference has to do with RK tracking tolerances. 
  real(rp) :: rel_tol_adaptive_tracking = 1d-8         ! Runge-Kutta tracking relative tolerance.
  real(rp) :: abs_tol_adaptive_tracking = 1d-10        ! Runge-Kutta tracking absolute tolerance.
Making these smaller makes the difference smaller.

**Comment by ChristopherMayes** [comment]
see bmad-sim/bmad-ecosystem#488

**Comment by DavidSagan** [comment]
This is due to the RK step size control. Either live with this or switch to the fixed setep size version.
