### ISSUE TITLE
Show spin gives all NaNs

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#491]
I'm using the latest tarball distribution /bmad_dist_2023_0905-0/ , attached are input files. It seems to work fine on the nightly release on the lab computer
[ring1_err.zip](https://github.com/DavidSagan/Bmad/files/12552602/ring1_err.zip)

**Comment by DavidSagan** [comment]
@mattsignorelli I am making a new tarball right now can you test this?

**Comment by mattsignorelli** [comment]
@DavidSagan I just tested this with the new 0907 tarball and it is still giving all NaNs

**Comment by mattsignorelli** [comment]
![image](https://github.com/DavidSagan/Bmad/assets/113714234/181c67ab-2861-4655-941a-6f608de68781)

**Comment by mattsignorelli** [comment]
^ same lattice I sent earlier but with different energy. Still seeing NaN

**Comment by DavidSagan** [comment]
Looks like bug shows up with gfortran and not ifort. Am working on it...

**Comment by DavidSagan** [comment]
@mattsignorelli Fixed in the latest distribution.
