### ISSUE TITLE
Taylor element spin attributes inaccessible through Tao

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#492]
Taylor elements have 3 different forms for expressing their orbital terms `(1,2,3,4,5,6)` in Bmad lattice files. From the Bmad manual:
```
{<out>: <coef>, <e1> <e2> <e3> <e4> <e5> <e6>}    ! Taylor term. First form.
{<out>: <coef> | <n1> <n2> ...}                   ! Taylor term. Second form.
tt<out><n1><n2>... = <Coef>                       ! Taylor term. Third form.
```
The spin-taylor terms `(S1,Sx,Sy,Sz)` on the other hand, cannot be expressing using the _Third form_, probably due to their labels' alphanumeric nature, as opposed to the purely-numeric nature of the orbital terms' labels.

Unfortunately, only the _third form_ is accessible through Tao, meaning it is impossible to change the spin-taylor terms within Tao.
Further, this makes it impossible to use spin-taylor components as variables for any sort of optimization in Tao.

**Comment by DavidSagan** [comment]
Bmad now accepts ttS<c><n1><n2>... = <Coef> syntax where <c> is one of "1", "x", "y", or "z".

**Comment by eiad-hamwi** [comment]
It looks like the code now works for applying spin taylor elements in the form `ttS<index><order>` 

However, it seems like I cannot apply a _constant_ spin taylor term, i.e. for a snake. 

So if I type in, say: 

```
set ele snake ttSx = 1
```

Tao says: “Invalid Attribute”

But it will take linear/higher-order terms, such as: 


```
set ele snake ttSx1 = 1
```

**Comment by DavidSagan** [comment]
@eiad-hamwi Fixed.
