### ISSUE TITLE
spin_dn_dpz buggy

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#493]
For closed geometries, the spin_dn_dpz_x,y,z are all 0 in a show ele. For open lattices, if I initially set it to zero, it stays zero all the way through even though it should not (see attached lattice).
[esr-ip12.txt](https://github.com/DavidSagan/Bmad/files/12587627/esr-ip12.txt)

**Comment by DavidSagan** [comment]
Fixed.
