### ISSUE TITLE
Sudden jump in coordinates when tracking through multipass sequence

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#495]
Test case at ~mpe5/for_dcs/79 at CLASSE.

Run `../production/bin/toss test_cerl_modea.lat` then look at `toss.dat`.  Notice that the orbit suddenly jumps at `LA.MERGE.BEN01\1`, resulting in particle loss.

`test_cerl_modea.lat` is from `bsim/aperture_by_s/test`.

The toss program simply tracks a closed orbit particle through the line using `track_all`.

**Comment by DavidSagan** [comment]
@MichaelEhrlichman This is due to the energy mismatch between LA.MERGE.BEN01 ref energy (1e7) and the ref energy at  LA.MERGE.BEN01\1 (1.5e7).
