### ISSUE TITLE
Show spin bug when using spin.depolarization_rate datum

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#497]
With attached files, run lm and then do show spin
[esr-main-unique.zip](https://github.com/bmad-sim/bmad-ecosystem/files/12661071/esr-main-unique.zip)

**Comment by mattsignorelli** [comment]
This is with the 09/10 tarball

**Comment by DavidSagan** [comment]
@mattsignorelli What should I see that is wrong?

**Comment by mattsignorelli** [comment]
I think this was related to the NaNs so it should be good now
