### ISSUE TITLE
Tao hanging when trying to enter single_mode

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#498]
[esr-main-unique (4).zip](https://github.com/bmad-sim/bmad-ecosystem/files/12662240/esr-main-unique.4.zip)

**Comment by mattsignorelli** [comment]
Whoops, forgot to include the spin.bmad file. It just includes parameter[geometry] = closed at the top

**Comment by DavidSagan** [comment]
Will change initial message when entering single mode to make things clearer.
