### ISSUE TITLE
Tao plot curves don't update correctly after optimization

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#505]
[ags_optimize_plot.zip](https://github.com/bmad-sim/bmad-ecosystem/files/12693945/ags_optimize_plot.zip)

Run `tao` in the previous folder.

This is the startup sequence:
1. Tao starts with snakes off (closed orbit = zero)
2. Initializes variables and datums for orbit optimization
3. Turns snakes on
4. Optimizes orbit to zero
5. Displays BPM orbit readouts (show lattice PUE*)

If you compare the BPM readouts with the orbit plot, you'll notice they are inconsistent.

**Comment by DavidSagan** [comment]
Fixed PR #514

**Comment by eiad-hamwi** [comment]
bump

This issue also happens when using symp_lie_ptc tracking on Cartesian_Maps.

I've attached a saved lattice file which is post-optimization. Take a look at the `show lat 90:300` orbit readout, and compare with the plot. 
[test_lat.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13180079/test_lat.zip)

Surprisingly, however, the beta functions and whatnot seem to correspond with the plot.

**Comment by eiad-hamwi** [comment]
Need to use larger `num_steps` in field decomposition, and more terms in generalized gradients.
