### ISSUE TITLE
Group element harmonic spin matching difficulty

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#511]
Trying to run lm with the attached files gives unable to find closed orbit, followed by "one or more datum values are not affected by any variation of any variable" which is not true. If you "veto var hkicker" it will run faster and also "set ele * spin_tracking_method = sprint"
[tao.zip](https://github.com/bmad-sim/bmad-ecosystem/files/12731047/tao.zip)

**Comment by DavidSagan** [comment]
@mattsignorelli I improved the error bookkeeping of the tao_spin_polarization_calc routine so try it now.
