### ISSUE TITLE
Track_bunch_to_s/t at element edges in space charge is slow

### ISSUE THREAD

**Issue by ndwang** [bmad-sim/bmad-ecosystem#513]
Currently, track1_bunch_space_charge tracks the bunch from the same s to the same t at the beginning of an element, and vice versa at the end. This turns out to be very slow and increases the runtime by 4x compared to drifting. Since these two operations are reversible, we should use drift between two elements with SC to speed things up. Ideally track to t/s is only needed where SC is turned on/off.

I included a test case. tao.init is configured to run tracking through a merger (MG) and a linac (PL). MG has SC on and PL has SC off. Startup file starts tracking 1k particles. It takes 8 minutes to finish with the current release.
[MG_PL_test.zip](https://github.com/bmad-sim/bmad-ecosystem/files/12732435/MG_PL_test.zip)

**Comment by DavidSagan** [comment]
@ndwang I put in a fix. Please test.
