### ISSUE TITLE
Show spin giving NaNs again 

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#515]
I git cloned the repository today on my own computer, compiled everything and again get all NaNs for a show spin. I do not see this on the nightly release on the lab computer. This does not occur if I include -noinit in the Tao call, so it appears related to the spin.depolarization_rate datum

**Comment by mattsignorelli** [comment]
Actually, I seem to be getting the NaNs even with -noinit

**Comment by DavidSagan** [comment]
@mattsignorelli Are you still seeing the problem?

**Comment by mattsignorelli** [comment]
Hi David, yes I am

**Comment by DavidSagan** [comment]
@mattsignorelli Can you attach the input files you are using? Thanks

**Comment by mattsignorelli** [comment]
[esr-1.zip](https://github.com/bmad-sim/bmad-ecosystem/files/12805277/esr-1.zip)

**Comment by mattsignorelli** [comment]
The depolarization rate appears to not be a NaN while the others are NaNs. So maybe tau_bks or P_bks is giving a NaN (one of the integrals included in P_dk)

**Comment by DavidSagan** [comment]
@mattsignorelli Found and fixed bug in tao_spin_polarization_calc which has been in there for about 1.5 years. Please check the latest code against prior calculations to make sure there are no significant changes.
