### ISSUE TITLE
Tao spin_res datum invalid

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#517]
The `spin_res.i.sum` and `spin_res.i.diff` data types are showing as invalid, for `i=a,b,c`

Running Tao in any Bmad lattice, type the following command for example:

`show value lat::spin_res.b.sum[0]`

The following error message shows up:
```
[ERROR | 2023-SEP-27 19:45:15] tao_set_invalid:
    DATA_TYPE = "spin_res.b.sum" IS NOT VALID
    FOR DATUM: spin_res.b.sum
```

Here's a sample lattice file, but that is irrelevant:
[fodo.zip](https://github.com/bmad-sim/bmad-ecosystem/files/12744114/fodo.zip)

**Comment by eiad-hamwi** [comment]
#371 is relevant. Tao Manual was updated to use this data type name.

**Comment by DavidSagan** [comment]
Fixed.
