### ISSUE TITLE
Tao spin_dn_dpz_x/y/z not showing in show ele/lat

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#519]
I would like to create an open lattice with some initial spin_dn_dpz with the attached closed lattice, but cannot get the values at the starting element with show ele/lat to do so (it only shows 0's for all spin_dn_dpz_x/y/z
[esr-main-unique.zip](https://github.com/bmad-sim/bmad-ecosystem/files/12751742/esr-main-unique.zip)

**Comment by DavidSagan** [comment]
@mattsignorelli  `show lat -spin` or `show lat -attrib spin_dn_dpz.x` does show non-zero values.

**Comment by mattsignorelli** [comment]
Hi David,

While show lat -spin does work, or also show lat -at spin_dn_dpz.x/y/z,
doing a 'show ele 0' gives:
[image: image.png]

Also I am getting a "BAD ATTRIBUTE FOR ELEMENT PARTICLE_START error when
trying to set particle_start[spin_dn_dpz_x] (tried with both .x and _x and
also spin_dn_x_dpz):
[image: image.png] [image: image.png]

Thanks,
Matt
