### ISSUE TITLE
particle loss in cartesian map wiggler

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#521]
I am having an issue with particle loss in a cartesian map wiggler due to a large orbit oscillation of greater than 1cm. There is likely currently a way to deal with this issue. I found the parameters parameter[aperture_limit_on] and parameter[max_aperture_limit] in the manual, but neither solved the problem after trying a few configurations in the lattice file.

Lattice file is at /nfs/acc/temp/jeu8/test

**Comment by DavidSagan** [comment]
@jeu8 Problem is that ds_step is not explicitly set and the default is too large. I will modify the code to generate a warning message about this.
