### ISSUE TITLE
MacOS XCode 15.0 HDF5 Link Problem

### ISSUE THREAD

**Issue by electronsandstuff** [bmad-sim/bmad-ecosystem#531]
I encounter a linker error in the HDF5 dependency when building on macOS with the latest release of XCode (15.0). 
```
...
ld: unknown options: -commons 
collect2: error: ld returned 1 exit status
gmake[1]: *** [Makefile:1534: H5detect] Error 1
gmake[1]: Leaving directory '/Users/chris/bmad-ecosystem/hdf5/debug/src'
gmake: *** [Makefile:729: install-recursive] Error 1

Error in building HDF5 VERSION HDF5-1.14.1-2 2023-07-12.
```

This seems to be a known problem (ie [this forum post](https://community.intel.com/t5/Intel-Fortran-Compiler/Mac-Xcode-15-0-unknown-options-commons/td-p/1526357)) and downgrading to version 14.3.1 fixes it. I saw related problems mentioned on the [wiki troubleshooting page](https://wiki.classe.cornell.edu/ACC/ACL/CodeTroubleshooting#Xcode_14.0_Bug_on_Mac_OS_402022_4509_4522_41).

There's probably not much to be done, but thought I would report it here to save other people time if they run into similar issues.

**Comment by DavidSagan** [comment]
@electronsandstuff: Reposted this on the troubleshooting page https://wiki.classe.cornell.edu/ACC/ACL/CodeTroubleshooting#A_42MacOS_XCode_15.0_HDF5_Link_Problem_402023_479_4730_41_42

Thanks for reporting this!
