### ISSUE TITLE
Contribution from wiggler is not added to the energy loss per turn

### ISSUE THREAD

**Issue by jinhyukchoi** [bmad-sim/bmad-ecosystem#533]
The contribution from the following wiggler element is not included in the energy loss per turn of tao summary.

M_LS: MARKER     ! marker at the center of the straight section
DWSIN: WIGGLER,L=3.51, B_MAX=1.8, n_PERIOD=39, superimpose, ref=M_LS, ele_origin=center

**Comment by DavidSagan** [comment]
@jinhyukchoi I see the problem and am working on a fix...

**Comment by DavidSagan** [comment]
@jinhyukchoi The code has been fixed.

**Comment by jinhyukchoi** [comment]
Sent from my iPhoneOn Oct 7, 2023, at 1:41 AM, David Sagan ***@***.***> wrote:﻿
@jinhyukchoi The code has been fixed.
