### ISSUE TITLE
Bmad to Elegant lattice conversion error: Gkicker 

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#537]
The recently added element in Bmad "Gkicker" can give a zeroth order kick to the particles ( i.e. magically displacing their orbit ).
The corresponding element in ELEGANT is MALIGN ( see https://ops.aps.anl.gov/manuals/elegant_latest/elegantsu171.html#x182-18300010.61 ). 
Could the conversion be added to the "bmad_to_mad_sad_elegant" program?

Thanks.

**Comment by DavidSagan** [comment]
@weiyuanlou Put in code for converting both directions. Do you have an elegant and/or Bmad files that you use for testing that I could get to use for regression testing? Something that had all types of elements would be great. Thanks.
