### ISSUE TITLE
Open lattice spin_dn_dpz still not working

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#538]
I am getting a "BAD ATTRIBUTE FOR ELEMENT PARTICLE_START error when trying to set particle_start[spin_dn_dpz_x] (tried with both .x and _x and also spin_dn_x_dpz):

![unnamed](https://github.com/bmad-sim/bmad-ecosystem/assets/113714234/2c597d08-46a7-4045-afc2-f8665ef38032)

Also, while show lat -spin does work, or also show lat -at spin_dn_dpz.x/y/z, doing a 'show ele 0' gives:
![unnamed](https://github.com/bmad-sim/bmad-ecosystem/assets/113714234/b2501f95-8ce8-44be-b236-775ed652cec0)

**Comment by DavidSagan** [comment]
@mattsignorelli Doc is wrong. I will correct. What you want is `beginning[...]` instead of `particvle_start[...]`.
