### ISSUE TITLE
Beam Tracking - multipole_ele_to_ab Caching

### ISSUE THREAD

**Issue by electronsandstuff** [bmad-sim/bmad-ecosystem#543]
For beam tracking with CSR, it looks like a ton of time (about 40% of the total runtime of the program for my application) is being spent calling `multipole_ele_to_ab`. I'm pretty sure it's getting run for every particle in the bunch. There is some caching code in there (in the image) to protect against this, but for whatever reason it doesn't seem to be working on my setup.

<img width="1062" alt="image" src="https://github.com/bmad-sim/bmad-ecosystem/assets/61094787/225f0f3e-0129-4a02-ad9d-257b1f21603f">

Here is the profiling on my input file. I can still see it on the minimal example I put at `/nfs/acc/temp/electronsandstuff/csr-radiation-profiling` on the CLASSE system (doing tests with 5mil particles now), but with fewer elements in the lattice it's more like 27% of runtime.
<img width="947" alt="image" src="https://github.com/bmad-sim/bmad-ecosystem/assets/61094787/1b942f85-8bc5-459e-a1b4-cef0d44924b6">

**Comment by DavidSagan** [comment]
I modified the code to better cache multipole values.

**Comment by DavidSagan** [comment]
Chris reports a 20-30% speedup
