### ISSUE TITLE
Syntax error with show spin

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#547]
After you fixed the first NaNs bug early yesterday morning, everything worked well yesterday. But using the nightly release this morning now on the lab computer, show spin gives a syntax error.  Possibly related to the latest commit "Better error handling in tao_spin_polarization_calc"? Example file attached
[esr-unique-2IP.txt](https://github.com/bmad-sim/bmad-ecosystem/files/12831495/esr-unique-2IP.txt)

**Comment by mattsignorelli** [comment]
[mgs255@lnx201 2IP]$ nightly
[mgs255@lnx201 2IP]$ $ACC_EXE/tao -lat esr-unique-2IP.bmad 

Tao> sho spin
forrtl: info (58): format syntax error at or near -2147483646)                  
forrtl: severe (62): syntax error in format, unit -5, file Internal Formatted Write or ENCODE
Image              PC                Routine            Line        Source             
libifcore.so.5     00007F61ABC30536  for__io_return        Unknown  Unknown
libifcore.so.5     00007F61ABC92A54  for_write_int_fmt     Unknown  Unknown
tao                0000000000C79FC9  real_to_string_           137  real_to_string.f90
tao                0000000000C7914B  real_str_                  37  real_str.f90
tao                0000000000682B81  tao_show_this_           4436  tao_show_this.f90
tao                0000000000641258  tao_show_cmd_              91  tao_show_cmd.f90
tao                000000000040D875  tao_command_              822  tao_command.f90
tao                000000000040761E  tao_top_level_             92  tao_top_level.f90
tao                000000000040751F  MAIN__                     15  tao_program.f90
tao                00000000004074BE  Unknown               Unknown  Unknown
libc-2.17.so       00007F61A9C9F555  __libc_start_main     Unknown  Unknown
tao                00000000004073C1  Unknown               Unknown  Unknown

**Comment by DavidSagan** [comment]
I put in a fix.
