### ISSUE TITLE
Data incorrectly independent of variables, and incorrect nonzero closed orbit

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#558]
With the attached files, open Tao with the setup.tao script - variables will be vkickers and hkickers, and the one used datum is emit.b. Run LM and Tao will incorrectly print "Data is independent of Variable...    Will not use this variable in optimization." for every variable, and the emittance will be unchanged. The variables will also be unchanged (sho var vkickers, sho var hkickers). However the closed orbit will be nonzero after running the optimization, even though no coils were turned on.

Then do "use data pol[1]" for a spin.depolarization_rate datum instead of the emit.b datum, and run lm again. The optimization will run, but the merit function will remain unchanged. After the optimization, the closed orbit will change again, yet "sho var vkickers" and "sho var hkickers" shows that the variables are all still zero.

[tao.zip](https://github.com/bmad-sim/bmad-ecosystem/files/12840606/tao.zip)

**Comment by DavidSagan** [comment]
Fixed. Problem was bookkeeping error in last code change.
