### ISSUE TITLE
closed_orbit_calc called on a open lattice in tao

### ISSUE THREAD

**Issue by ndwang** [bmad-sim/bmad-ecosystem#562]
I was running the latest release version of tao on a open lattice. Tao opens up fine, but when I turned on beam tracking, I received an error from closed_orbit_calc.
`[ERROR | 2023-OCT-13 13:59:41] closed_orbit_calc:
    PARTICLE LOST IN TRACKING!!
    ABORTING CLOSED ORBIT SEARCH.
    TRACKING BRANCH: 0:IN
[ERROR | 2023-OCT-13 13:59:41] rad_damp_and_stoc_mats:
    Closed orbit calculation failing.
    Emittance and other radiation related quantities will not be calculated.
`

If you need an example, you can find the lattice at /nfs/user/nw285/bmad_benchmarking/cooler_injector/v4/in.

**Comment by DavidSagan** [comment]
@ndwang Can you check that if the simulation is run with less particles you still get the error? Running with 10000 particles takes a long time...

**Comment by DavidSagan** [comment]
Never mind. The bug was already fixed but the fix is not in the `devel` release yet. Try `nightly`.
