### ISSUE TITLE
Tao hangs when placing spin_dn_dpz plot

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#564]
Try place r13 spin_dn_dpz with attached lattice
[esr-main-unique.txt](https://github.com/bmad-sim/bmad-ecosystem/files/12930113/esr-main-unique.txt)

**Comment by DavidSagan** [comment]
Problem is due to the spin polarization calc being called for each plot point. I am working on a fix...

**Comment by DavidSagan** [comment]
I put in a fix.
