### ISSUE TITLE
Implementation of a thick decapole in Bmad

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#565]
Currently in Bmad we have thick quadrupole, sextupole, and octuple. 
However these can not be implemented as multipoles or ab_multipoles with exact equivalence ( with all higher-order Taylor terms agreeing ), likely due to the fact that multipoles and ab_multipoles must have zero length.

Could we implement a thick decapole ( and perhaps also dodecapole and 14-pole ) in Bmad ?

Thanks.

**Comment by DavidSagan** [comment]
You can get the same thing by, for example, using a octupole with a non-zero b7.
