### ISSUE TITLE
Handle elements installed backwards

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#567]
Here's the use case: I build a lattice, and have an element which will eventually have a field map. The engineers are going to give me the field map in the direction opposite to the direction of the lattice file. So what I'd like to express is that "this element is installed rotated by 180 degrees" (note: not a reflection). I might also want to do this at the girder level. I attempted the following simple example:
```
q: quadrupole, l=1, x_pitch=pi
o: drift, l=1

l: line=(o,q,o)

l[geometry] = open
beginning[beta_a] = 1
beginning[beta_b] = 1
beginning[e_tot] = 5e9

use, l
```
and the behavior within `q` can best be described as "irrational." I'm guessing this has something to do with Bmad trying to track from the entrance face which is now at the downstream end of the line? Anyhow, the tao plot of the beta function goes crazy inside the element, and things like `show value lat::beta.b[q->-0.9*l]` give values that make no sense. I can see this getting complicated if I do this to a girder, since then I'm saying "track through these elements in the opposite order, each from back to front." 

Of course, the answer could just be to tell the user to fix the fieldmap, which is really not that hard. But at the very least it might be good if the 180 degree rotated element either behaved in a more sensible fashion or there were an error message that noted that you just tried to track starting at the wrong side of your element.

**Comment by DavidSagan** [comment]
@jsberg-bnl Every element has an "entrance" end and an "exit" end. With an unreversed element, Bmad always injects the particle at the entrance end which means the particle is not even headed towards the exit end. I will look into putting in some error checking for this. 

And yes, you need to reverse the map and take out the x_pitch set.

**Comment by DavidSagan** [comment]
I have put in some error checking on this.
