### ISSUE TITLE
MadX to Bmad translation

### ISSUE THREAD

**Issue by ErisW** [bmad-sim/bmad-ecosystem#571]
The Bmad and MadX produce the same closed orbit for untapered lattice, but once tapering is applied, the translation of the "KTAP" attribute in MadX to Bmad does not work properly, the orbits generated by two codes are completely inconsistent (check horrizontal orbits). How madx_to_bmad.py deals with KTAP makes perfect sense to me so I have no clue where the problem is. Thank you in advance!!

The attached .zip contains an example of FCC Z lattice, the tapered sequence in MadX (fcc_z_tapered.seq+test_tapered.mad) which is translated into Bmad (fcc_z_tapered.bmad). [bug_report.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13070887/bug_report.zip) 

Horizontal orbit in MadX
![madx](https://github.com/bmad-sim/bmad-ecosystem/assets/78316763/41c852ba-2ed9-4300-ad68-aa3310f56386)

in Bmad
![bmad](https://github.com/bmad-sim/bmad-ecosystem/assets/78316763/a12aebdb-cbe8-410f-998e-1ce8965949bc)

**Comment by DavidSagan** [comment]
@ErisW To diagnose, look at the transfer matrix with MAD and Bmad for a single quadrupole and a single bend. We can zoom if you need more detail.

**Comment by ErisW** [comment]
I've checked the Taylor map of single quadrupole and single bend where KTAP has a relatively larger value.  If it is accurate to 8 decimal places in Bmad, then the first-order Taylor map from Bmad of both ele types is the same as the one from MadX, except for R(1,2) and R(3,4), where a very small difference (at 7th decimal place) happens. In the untapered lattice, this discrepancy at (1,2) (3,4) also exists, but to the 8th decimal place, yet almost exactly the same closed orbit can be produced by untapered lattice, while tapered one cannot, so I'm wondering whether this is truly the source.                     

For higher order map, MadX uses Taylor maps like $z_j(s_2)=\sum R_{jk}z_k(s_1)+\sum_{k}\sum_{l}T_{jkl}z_k(s_1)z_l(s_1)$, I can get second order map T ($6\times 6\times 6$) from MadX but don't know how to get such higher-order tensor in Bmad. 

Looking forward to your opinions! Thank you!

**Comment by DavidSagan** [comment]
Next check: Tracking with an open geometry with the same initial position at the start of the lattice. How does the orbit with MAD compare with Bmad? at what point is there a significant difference?

**Comment by ErisW** [comment]
Sorry I was wrong, the discrepancy doesn't come from the translation of "KTAP". Even using untapered Z lattice, MadX and Bmad produce a ~1e-8m difference in closed orbit, and that difference is enlarged in ttbar lattice. The story is: I'm doing orbit correction for ttbar (182.5GeV) lat in MadX, everything went well. Then to calculate polarization, I need to translate them to Bmad, but Tao can't find C.O., even using tapered ttbar lat without any errors assigned (then I switched to Z lat for more testing)... Since this small discrepancy got magnified in ttbar, do you have any suggestions on how to help Tao find C.O.? For ttbar tapered lat without any error, I've tried to set it as an open geometry, and x explodes (suddenly becomes way larger) after a long rbend, then completely lost somewhere after that.

**Comment by DavidSagan** [comment]
@ErisW Perhaps this is best handled via Zoom. Do you have some time for this?

**Comment by ErisW** [comment]
Sure! How about Friday (27th) 10 a.m. ET (4 p.m. Swiss time)? Or 9 a.m. ET? I'll send you a zoom link via email. Thank you!

**Comment by DavidSagan** [comment]
10am ET it is so please send me a link

**Comment by ErisW** [comment]
test the lattice
[bmad_taper.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13190094/bmad_taper.zip)

**Comment by ErisW** [comment]
[madx_taper.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13190162/madx_taper.zip)

**Comment by DavidSagan** [comment]
@ErisW Fixed. Problem was translation of `lag` from MADX to Bmad needed a negative sign.
