### ISSUE TITLE
tune_scan program not finding tunes with group knobs

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#578]
I set a simple tune_scan file up, and gave a small tune range to be controlled with group knobs. I got many errors about not being able to find the right tune and eventually the program failed. 

Files at /nfs/acc/temp/jeu8/tune_scan_Jim

**Comment by DavidSagan** [comment]
[ts.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13125669/ts.zip)

**Comment by DavidSagan** [comment]
@jeu8 One thing is that Q_a1 and Q_b1 are not set in the init file. I am investigating further...

**Comment by DavidSagan** [comment]
I made some improvements to the program. Try the new code and open another issue if needed.
