### ISSUE TITLE
Lcavity tracking documentation typo ?

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#579]
Equation (24.70) on page 387 shows in the Bmad manual b_0 and b_{-1} being set to 1, and all others set to 0. However I am finding this to be inconsistent with what Tao gives. Here is why:

According to manual, m11 = sqrt(beta_1/beta_2)*cos(\alpha)
Attached lattice has m11 = 0.95546668
So alpha =acos(sqrt(beta_2/beta_1)*m11) = acos(sqrt(0.9993519036796968/0.9992271571945698) *0.95546668 ) = 0.299356970589515
Per Rosenzqweig and Serafini (RS) Eq.8, 
alpha = sqrt(eta/8) / cos(phi_0) * log(gamma_f/gamma_i)
->
sqrt(eta) = alpha*cos(phi_0)*sqrt(8) / log(gamma_f/gamma_i) = 9.6222399
But according to Eq. 4 in RS, with b_0 = 1 and b_{-1} = 1 with all others set to 0, sqrt(eta) = 1

Here is a link to RS: https://journals.aps.org/pre/pdf/10.1103/PhysRevE.49.1599

Lattice attached: 
[lcavity.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13127642/lcavity.txt)

**Comment by mattsignorelli** [comment]
I looked into this a bit more, and according to the code the documentation is correct (eta = 1)... I see the "discrepancy" is on line 392 of track_a_lcavity.f90, where the m11 element is defined.  So I think I am missing something about why there's this extra "-sqrt_2*sin_a*cos_phi* added to the RS m11 element. Accounting for this term I get the same as Bmad

**Comment by mattsignorelli** [comment]
Ok I figured this out... I was expecting to see only the body transfer matrix when I set fringe_type = none, but I still see the transfer matrix including fringe effects. Is that expected behavior?

**Comment by DavidSagan** [comment]
@mattsignorelli I don't think any consideration to being able to turn off the fringe field was given when the routine was coded. At this point in time I would rather not put in the time to change the code unless there was a sufficient reason.
