### ISSUE TITLE
Tao crashes when tracking cylindrical_map with symp_lie_ptc or taylor

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#581]
`Program received signal SIGBUS: Access to an undefined portion of a memory object.`

Run Tao in the following directory:
[cylinder_field.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13127813/cylinder_field.zip)

**Comment by DavidSagan** [comment]
Fixed.
