### ISSUE TITLE
show value truncates its expression

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#584]
type into tao:
```
show value 3.1415926536+sin(3.1415926536)+sin(3.1415926536)+sin(3.1415926536)+sin(3.1415926536)+sin(3.1415926536)
```
Output is:
```
[ERROR | 2023-OCT-25 13:43:51] tao_evaluate_expression:
    UNMATCHED "("
    IN EXPRESSION: 3.1415926536+sin(3.1415926536)+sin(3.1415926536)+sin(3.1415926536)+sin(3.1415926536)+sin(3.141592653
```
Cause is that for `show value`, `tao_next_switch` is called with `return_next_word=.true.`, loading the rest of the line into `switch` which is only 100 characters long. So either make `switch` longer or replace `switch` with one of your longer scratch variables (`line1`, etc.)

**Comment by DavidSagan** [comment]
Fixed.
