### ISSUE TITLE
Translation to Elegant not working when quadrupoles have B4 (decapole) or higher order multipoles

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#590]
When Bmad quadrupole has a multipole associated with it ( B4 of decapole for instance ), translation fails ( see message below ).
One ( perhaps simple but not general ) way is for Bmad to have an independent decapole element, which can be translated to the MULT element in elegant ( I personally only need decapole to work for now ).
Or the formula to convert the multipole moment associated with a Bmad's quad ( the multipole strength probably depends on the "field_master" and "scale_multipoles" parameter too ) to elegant's MULT needs to be figured out...

Thanks.

```
[WARNING] write_lattice_in_foreign_format:
    ! NOTE: ELEGANT TRANSLATION IN DEVELOPMENT. PLEASE CONTACT DAVID SAGAN IF YOU WANT TO USE!
[INFO] write_lattice_in_foreign_format:
    Note: In general, Bmad lattice elements can have attributes that cannot be translated.
          For example, higher order terms in a Taylor element.
          Please use caution when using a translated lattice.
```

**Comment by DavidSagan** [comment]
Bmad to Elegant translation now will translate a single pole higher order thick multipole to a MULT element.

**Comment by DavidSagan** [comment]
@weiyuanlou PS: Please test.

**Comment by weiyuanlou** [comment]
Sorry Dave, could you show me the Bmad definition of "single pole higher order thick multipole"? Is it the same as having a quad with B4, B5... etc ?

**Comment by DavidSagan** [comment]
A quad with a b5 but no other multipoles (including k1) would be an example.

**Comment by DavidSagan** [comment]
@weiyuanlou I just fixed a problem so please pull the latest code.

**Comment by weiyuanlou** [comment]
Hi Dave, I tested again and found a new bug in the translation. 
k1 of quad in Bmad should be translated directly to k1 of kquad in Elegant, but currently it's off by a factor of the length of the quad. 
Same thing happens to k2 of sextuple and k3 of octupole.

Feel free to discuss this with me on Bmad Slack. Thanks.
