### ISSUE TITLE
Write bmad and read lat var1.out after optimization not giving optimized values

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#591]
With attached files, run lm and then write bmad. Exit and reopen and the lattice is not optimized.

[setup.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13184027/setup.zip)

**Comment by mattsignorelli** [comment]
If you run lm again on the resutling lattice, there is suddenly a vertical orbit even though no vertical coils are on and coupling is essentially zero (place r13 cbar)

**Comment by mattsignorelli** [comment]
Another interesting find - if I do taper, instead of my orbit correction, I get a closed orbit very similar to that incorrect one I get when I open the file after optimization . So maybe finding a different wrong closed orbit?

**Comment by DavidSagan** [comment]
Problem is with the phase_trombone. I am working on a fix...

**Comment by mattsignorelli** [comment]
To solve: optimizations with phase trombones, how to handle transparency of Twiss parameters

**Comment by DavidSagan** [comment]
@mattsignorelli I have revamped the match element and added to Tao a logical `global%opt_match_auto_recalc`.
