### ISSUE TITLE
Setting field master = T changes the tune

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#592]
I need a lattice defined in terms of B-fields so I can get off energy closed orbits. But if I do

set ele * field_master = T

My tunes change immediately. It does not resolve with any order of setting scale_multipoles before/after or T/F
[esr1.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13184989/esr1.txt)

**Comment by DavidSagan** [comment]
@mattsignorelli This is not a lattice file.

**Comment by DavidSagan** [comment]
Problem are the multipoles. I am working on a fix.

**Comment by DavidSagan** [comment]
Fixed. Problem was due to input multipoles needed to be modified when toggling field_master and this bookkeeping was absent.
