### ISSUE TITLE
Bmad_standard tracking non-symplectically for bend with sextupole

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#597]
Attached is a single element lattice showing the violation:
[multibend.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13194311/multibend.zip)

Setting `ds_step = 1e-5` has almost no effect.

Using symp_lie_ptc as the tracking method alleviates this issue, but is slow.

**Comment by DavidSagan** [comment]
Part of the problem is that you need to use `exact_multipoles`. See the Bmad manual for details. On your example lattice the symplectic error went from 2e-6 to 8e-8. That is still a little more than I would like and will look into it.

**Comment by DavidSagan** [comment]
Note: The exact_multipole tracking looks to be behaving strangely. Please do not use until I have looked into this.

**Comment by eiad-hamwi** [comment]
Oh! I will avoid using `exact_multipoles` until your notice, but I will certainly read up on it.

**Comment by DavidSagan** [comment]
@eiad-hamwi I put in a fix so you can use exact_multipoles now. The symplectic error is still 8e-8 for your example.
