### ISSUE TITLE
RF Cavities in LongTermTracking

### ISSUE THREAD

**Issue by DariaKuzovkov** [bmad-sim/bmad-ecosystem#607]
When I run long_term_tracking without ramping with my current files and plot z and pz for one particle, I get an expected ellipse. However, when I turn ramping on in the lattice file, it seems like the rf cavities don't turn on for some reason.

[lattice.bmad.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13209756/lattice.bmad.txt)
[correction.var.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13209757/correction.var.txt)
[beam.init.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13209759/beam.init.txt)
[test.init.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13209760/test.init.txt)

**Comment by DavidSagan** [comment]
@DariaKuzovkov Are you using Mac?

**Comment by DariaKuzovkov** [comment]
Yes, I'm running everything in NoMachine on a Mac.

**Comment by DariaKuzovkov** [comment]
Since I am running it in NoMachine, it should be the same as running on the native linux machine, so I don't think that is the issue I am having.

**Comment by DavidSagan** [comment]
@DariaKuzovkov Looks like all attached files are the same. Best would be to zip all the files into one file.

**Comment by DavidSagan** [comment]
Everything looks like it is working. Only two of the RFcavity elements are being varied so you might not have as much change as you would expect.

**Comment by DavidSagan** [comment]
@DariaKuzovkov I'm closing this issue. If you still have questions we should zoom.
