### ISSUE TITLE
particle lost at end of custom wiggler

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#633]
I have a wiggler with a field that has a field that goes as sin(k*z), so the particle orbit should start with an initial px (in my case ~0.15rad). This produces an orbit that looks reasonable, however Tao is losing the particle near the end of the wiggler. This prevents me from getting the correct closed orbit and optics.
[cartesian_map_focus.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13342417/cartesian_map_focus.txt)

**Comment by DavidSagan** [comment]
@jeu8 I'm not seeing any particle loss. But the orbit at the end has px = 0.313 which is very large. One thing to keep in mind is that if the field is not zero at the ends, there is a "kick" at the ends to keep the motion symplectic.

**Comment by jeu8** [comment]
@DavidSagan I did not have the initial px set in the lattice. I was changing it while running using the "set particle_start" command. This should give a final px of around 0.15rad if the particle was not lost.

**Comment by DavidSagan** [comment]
Ultimate problem was default tracking_method = taylor is not suitable for large px tracking. Fix is to go to symp_lie_bmad.
