### ISSUE TITLE
Add anti- versions of atomic nuclei

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#634]
To help with rings that are laid out in the opposite direction to particle motion, it would be helpful to have "anti" versions of atoms/molecules/etc. Probably nobody will be actually pushing around anti-Helium, but you never know I suppose. As discussed, prefixing the name in the current syntax with `anti` should do the trick. Thanks.

**Comment by DavidSagan** [comment]
Implemented.
