### ISSUE TITLE
CesrV seg fault in debug executable only

### ISSUE THREAD

**Issue by JimCrittenden** [bmad-sim/bmad-ecosystem#637]
Hi David,

The production version does not have the problem.
The mpm_utils source code tbt/tbt_mod.f90
is checked in. 

We can zoom if you prefer.

-- Jim

/home/critten/debug/bin/cesrv_cl read tbt 107627

gives

cesrv_jac_debug read tbt 107627
 CORRECTING OFF-BY-ONE PROBLEM...
 Note: Hard wired bpm names for south arc bpms. 
 nonlin_bpm:  Initializing bpm48 lookup table...  using input file
 nonlin_bpm:  Initializing ARC lookup table...  using input file
 nonlin_bpm:  Initializing CHESS-U lookup table...  using input file
 nonlin_bpm: initializing quad offsets
 Reading quad offsets from /nfs/cesr/online/machine_data/meas/orbit/offset.bpm
 nonlin_bpm:  Initializing button calibration
 CORRECTING OFF-BY-ONE PROBLEM...
SHAKER PHASE MISMATCH!    33 :    1020       1******** :    1020       1********
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
cesrv_cl           0000000003FEDDD6  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FE2361F3630  Unknown               Unknown  Unknown
cesrv_cl           00000000019203CC  Unknown               Unknown  Unknown
cesrv_cl           00000000019223E1  cbpm_file_input_m         247  cbpm_fio_accessors.f90
cesrv_cl           0000000000AACF75  tbt_mod_mp_tbt_re         260  tbt_mod.f90
cesrv_cl           00000000006E5B23  read_tbt_                  47  read_tbt.f90
cesrv_cl           00000000005110E7  cesrv_command_           1833  cesrv_command.f90
cesrv_cl           00000000005A4C84  init_init_                128  init_init.f90
cesrv_cl           0000000000407DE2  MAIN__                     51  cesrv_cl.f90
cesrv_cl           000000000040771E  Unknown               Unknown  Unknown
libc-2.17.so       00007FE2341A4555  __libc_start_main     Unknown  Unknown
cesrv_cl           0000000000407629  Unknown               Unknown  Unknown

**Comment by DavidSagan** [comment]
@JimCrittenden The change to tbt_mod.f90 broke the compile:

/home/dcs16/linux_lib/cesr_programs/../production/lib/libmpm_utils.a(tbt_mod.f90.o): In function `tbt_mod_mp_tbt_read_data_file_':
tbt_mod.f90:(.text+0x39c4): undefined reference to `nonlin_orbit_'
gmake[2]: *** [/home/dcs16/linux_lib/production/bin/cbpm_fft_anal] Error 1

I will put in a fix...

**Comment by JimCrittenden** [comment]
I see.  cesrv was fine, but other programs will need nonlin_bpm.

==========================================
James Crittenden                        Tel. (607) 255-4882
Wilson Synchrotron Laboratory
Cornell University
Ithaca, New York 14853-8001
________________________________

**Comment by DavidSagan** [comment]
May be slow but things look like they work.

**Comment by JimCrittenden** [comment]
Did you check something in?

==========================================
James Crittenden                        Tel. (607) 255-4882
Wilson Synchrotron Laboratory
Cornell University
Ithaca, New York 14853-8001
________________________________

**Comment by DavidSagan** [comment]
Yes in cesr_programs. I compiled cesrv and verified that the program did not crash.

**Comment by JimCrittenden** [comment]
Hi David

My  production cesrv also does not crash.
Only the debug version gets a seg fault.

I may be doing something wrong  in mpm_utils/tbt/tbt_mod.f90 here:

    do i_but = 1, 4
      bunch_bpm%gain(i_but) = cbpm_rawfile_gain_factor_f(bpm%name, i_bunch, ix_button(i_but))
      bunch_bpm%pedestal(i_but) = cbpm_rawfile_pedestal_f(bpm%name, i_bunch, ix_button(i_but))
    enddo


  *   Jim
  *

==========================================
James Crittenden                        Tel. (607) 255-4882
Wilson Synchrotron Laboratory
Cornell University
Ithaca, New York 14853-8001
________________________________

**Comment by DavidSagan** [comment]
You can use totalview for this. Do you know how to use it?

**Comment by JimCrittenden** [comment]
Sure.

I am just a little intimidated by it being only the debug version
and unsure about whether I need to use only pointers with  cbpm_rawfile_gain_factor_f

Let me have a look now and get back if I get confused.


  *   Jim

==========================================
James Crittenden                        Tel. (607) 255-4882
Wilson Synchrotron Laboratory
Cornell University
Ithaca, New York 14853-8001
________________________________

**Comment by JimCrittenden** [comment]
Here is the problem. It is not in my stuff.


  *   Jim

==========================================
James Crittenden                        Tel. (607) 255-4882
Wilson Synchrotron Laboratory
Cornell University
Ithaca, New York 14853-8001
________________________________

**Comment by DavidSagan** [comment]
whose stuff is it in?

**Comment by JimCrittenden** [comment]
It looked like cbpmfio.

I am in antoine's meeting right now and will bring it up.

I think I saw in passing that it is getting the gains from the
famously bad 33w processor.

Something needs to get protected.

I think it is always worthwhile to run the debug version
because it reports bugs which the production version missed.


  *   Jim

==========================================
James Crittenden                        Tel. (607) 255-4882
Wilson Synchrotron Laboratory
Cornell University
Ithaca, New York 14853-8001
________________________________

**Comment by JimCrittenden** [comment]
Of course the result of the meeting was that I was
volunteered to fix the problem.


  *   Jim

==========================================
James Crittenden                        Tel. (607) 255-4882
Wilson Synchrotron Laboratory
Cornell University
Ithaca, New York 14853-8001
________________________________
