### ISSUE TITLE
MadX to Bmad translation

### ISSUE THREAD

**Issue by ErisW** [bmad-sim/bmad-ecosystem#640]
Here is an example of one element defined in MadX sequence: 

**_qrfr1: quadrupole,l:=lqrfr1 ,k1:=k1qrfr1 ;
qrfr1.1: qrfr1,k1:= 0.003894633937537,ktap:= -0.000110153548622;_**

However Bmad translate it as:

**_qrfr1: quadrupole, l = lqrfr1, k1 = k1qrfr1
qrfr1.1: qrfr1, k1 = qrfr1.1[k1] * (1 + -0.000110153548622)_**

ignoring the new k1 value given _**k1:= 0.00389**_ but still using the **_k1qrfr1_** as **_qrfr1.1[k1]_**. The attached is a simple case. It would be very helpful if this could be fixed. Thank you so much!
[for_david.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13415777/for_david.zip)

**Comment by DavidSagan** [comment]
@ErisW Fixed. New Release being made now.

**Comment by ErisW** [comment]
Thanks David! But in the new madx_to_bmad.py, there is one line missing between **line 604** and **line 605**

```
if 'ktap' in params: 
    params['k2'] = params['k2'] + ' * (1 + ' + params.pop('ktap') + ')' 
else:
    params['k2'] = ele.name + '[k2] * (1 + ' + params.pop('ktap') + ')'
``` 

should be 

```
if 'ktap' in params: 
    if 'k2' in params:
        params['k2'] = params['k2'] + ' * (1 + ' + params.pop('ktap') + ')' 
    else:
        params['k2'] = ele.name + '[k2] * (1 + ' + params.pop('ktap') + ')'
``` 
Thank you so much!

**Comment by DavidSagan** [comment]
@ErisW Yes. This will be corrected. Thanks for reporting this.
