### ISSUE TITLE
BBU program directory errors

### ISSUE THREAD

**Issue by sadik82** [bmad-sim/bmad-ecosystem#643]
Hi, 

I am trying to run BBU program in Bmad. My Bmad is installed in Ubuntu in WSL. I tried the example under ~/bmad/bmad_dist_2023_0808-0/bsim/bbu. 

The DR SCAN mode ran without errors, but the THRESHOLD mode has directory errors as shown blow:
------------------------------------------------------------------------------------------------------------------------
~/bmad/bmad_dist_2023_0808-0/bsim/bbu$ ./test_run.py 1 1 1
['./test_run.py', '1', '1', '1']
./test_run.py
1700510142.349406
4 or more arguments (including python script) given, threshold (current) mode.
Lattice name: '$DIST_BASE_DIR/bsim/bbu/examples/oneturn_lat.bmad'
Traceback (most recent call last):
  File "/home/sadiq/bmad/bmad_dist_2023_0808-0/bsim/bbu/./test_run.py", line 272, in <module>
    main(sys.argv[1:])
    ^^^^^^^^^^^^^^^^^^
  File "/home/sadiq/bmad/bmad_dist_2023_0808-0/bsim/bbu/./test_run.py", line 132, in main
    os.chdir( py_par['temp_dir'])
FileNotFoundError: [Errno 2] No such file or directory: '1/1/bbu_temp_47pk69wr1'
------------------------------------------------------------------------------------------------------------------------
BBU program is attached.
[bbu.tar.gz](https://github.com/bmad-sim/bmad-ecosystem/files/13419261/bbu.tar.gz)

**Comment by DavidSagan** [comment]
Fixed by @weiyuanlou
