### ISSUE TITLE
RF wavelength in rfcavity is off by 0.42m w.r.t circumference/harmonic number

### ISSUE THREAD

**Issue by BaiMay** [bmad-sim/bmad-ecosystem#644]

**Comment by DavidSagan** [comment]
[AgsBooster.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13432125/AgsBooster.zip)

**Comment by DavidSagan** [comment]
@BaiMay Problem was that harmon was being used to set the rf_frequency and after setting the rf_frequency is the master parameter. This, coupled with a ramper element shifting the energy (and hence the revolution time) after the initial rf_frequency set lead to the problem. I have implemented a `harmon_master` parameter which is set True if harmon is set in the lattice fiel and harmon_master is set False if the rf_frequency is set in the lattice file.

**Comment by BaiMay** [comment]
When use ramp_e: ramper = {*[e_tot]: 3.0234e9+3.9168e4*time/1.2265e-6}, var = {time}, long_term_tracking seems to work. Nevertheless, the assumption of this ramp is not right as for helion acceleration in this non-relativistic region, the time per turn is rapidly changing.

I then uses ramp_e: ramper = {*[e_tot]: 3.0234e9,3.023427e+09,3.023780e+09,3.025346e+09,3.027305e+09,3.042972e+09,
        3.062556e+09,3.219227e+09,3.415066e+09,3.695234e+09}, var = {time}, x_knot ={0.0, 1.817123e-06,
	1.816457e-05,9.067563e-05,1.809863e-04,8.909162e-04,1.749440e-03,7.799527e-03,1.414786e-02,2.202657e-02}, where the total energy per time step is calculated with the proper revolution time per turn. The plot here shows the difference between the two ramp_e. 
![e_tot_time](https://github.com/bmad-sim/bmad-ecosystem/assets/51864141/d8fd874e-c468-446d-808b-9b7871efc569)

Nevertheless, for the 2nd ramp_e, long_term_tracking met error, i.e.TOTAL ENERGY IS LESS THAN REST MASS:   0.00E+00. 

It is not clear to me what the rest mass for #3He++ in Bmad. For my calculation of ramp_e, I used 2.808391482 GeV as the rest mass of Helion.

[AgsBooster.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13446011/AgsBooster.zip)

**Comment by BaiMay** [comment]
> @BaiMay Problem was that harmon was being used to set the rf_frequency and after setting the rf_frequency is the master parameter. This, coupled with a ramper element shifting the energy (and hence the revolution time) after the initial rf_frequency set lead to the problem. I have implemented a `harmon_master` parameter which is set True if harmon is set in the lattice fiel and harmon_master is set False if the rf_frequency is set in the lattice file.


Thanks, David! Should I re-build Bmad? BTW, I figured out what went wrong with the ramp_e. It works now. Remaining question is how to relate the rfcavity voltage and phase with the ramp rate, i.e. Bdot. In addition, it seems the rf_wavelength stays unchanged during the acceleration and n_turn is not recognized by the long_term_tracking.

**Comment by BaiMay** [comment]
Are the source codes in lt_tracking_mode in the bmad_dist? for the long_term_tracking, the ltt%column(1)  = 'n_turn', 'N_turn', 'i7' is empty. would like to check whether n_turn is a valid attribute. The reason for asking is custom.dat with  
  ltt%column(1) = 'n_turn', 'N_turn', 'i5'
  ltt%column(2) = 'cavity[rf_wavelength]', 'rf_w', 'f12.8'
has the N_turn part completely empty and rf_w stays constant despite this is an acceleration of Helion from Ggamma=-4.5 to Ggamma=-5.5, very non-realistic.

**Comment by DavidSagan** [comment]
All source code is in the Distribution. `n_turn` is a valid field name. If you post your input files I can take a look. Also I'm not sure what version of Bmad you have but using the latest cannot hurt.

**Comment by BaiMay** [comment]
Thanks, David. Just submit the issue in github. I downloaded the latest package and rebuilt. Yet the problem persists. In case the zipped file that I uploaded doesn’t work, please find the input file and custom.dat in the attached.

And, Happy Thanksgiving!!!

From: David Sagan ***@***.***>
Date: Thursday, November 23, 2023 at 11:15 AM
To: bmad-sim/bmad-ecosystem ***@***.***>
Cc: Bai, Mei ***@***.***>, Mention ***@***.***>
Subject: Re: [bmad-sim/bmad-ecosystem] RF wavelength in rfcavity is off by 0.42m w.r.t circumference/harmonic number (Issue #644)

All source code is in the Distribution. n_turn is a valid field name. If you post your input files I can take a look. Also I'm not sure what version of Bmad you have but using the latest cannot hurt.

**Comment by BaiMay** [comment]
Hi David

Is this harmon_master an attribute of ltt, ie I set it in the input file as ltt%harmon_master=T?

Best,

Mei

From: David Sagan ***@***.***>
Date: Tuesday, November 21, 2023 at 6:51 PM
To: bmad-sim/bmad-ecosystem ***@***.***>
Cc: Bai, Mei ***@***.***>, Mention ***@***.***>
Subject: Re: [bmad-sim/bmad-ecosystem] RF wavelength in rfcavity is off by 0.42m w.r.t circumference/harmonic number (Issue #644)

@BaiMay<https://github.com/BaiMay> Problem was that harmon was being used to set the rf_frequency and after setting the rf_frequency is the master parameter. This, coupled with a ramper element shifting the energy (and hence the revolution time) after the initial rf_frequency set lead to the problem. I have implemented a harmon_master parameter which is set True if harmon is set in the lattice fiel and harmon_master is set False if the rf_frequency is set in the lattice file.
