### ISSUE TITLE
long_term_tracking for accelerating non relativistic particles

### ISSUE THREAD

**Issue by BaiMay** [bmad-sim/bmad-ecosystem#646]
Updated my bmad package. Yet, n_turn is still empty in the custom.dat and rf_wavelength still stays constant instead of changing with beam energy. Both long_term_tracking.init and custom.dat are in the zip file attached here
[ltt.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13453411/ltt.zip)
.

**Comment by BaiMay** [comment]
Also the rf_wavelength is still too bigger than the circumference/harmonic number.
[AgsBooster.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13453485/AgsBooster.zip)

**Comment by DavidSagan** [comment]
One thing I notice immediately is that the syntax for the ramper is off. What you want is
```
ramp_e: ramper = {*[e_tot]: {3.0234e9,3.023427e+09,3.023780e+09,3.025346e+09,3.027305e+09,3.042972e+09,
        3.062556e+09,3.219227e+09,3.415066e+09,3.695234e+09}}, var = {time}, x_knot ={0.0, 1.817123e-06,
	1.816457e-05,9.067563e-05,1.809863e-04,8.909162e-04,1.749440e-03,7.799527e-03,1.414786e-02,2.202657e-02}

```
Notice the curly brackets after `[e_tot]:`. Bmad should detect this error. I will work on a fix and then look at the other stuff...

**Comment by BaiMay** [comment]
Thanks, David. I fixed it shortly after I sent you the email. I also found out the original of the discrepancy of the RF wavelength w.r.t. average circumference.

**Comment by DavidSagan** [comment]
I fixed the custom output code. One thing I noticed is that your rf_wavelength format width was too small. what you want is something like `f14.8`

Also I do see the RF wavelength varying so I'm not sure why you see otherwise. I am going to close this issue. If you still have any issues, please open another ticket.

**Comment by BaiMay** [comment]
> I fixed the custom output code. One thing I noticed is that your rf_wavelength format width was too small. what you want is something like `f14.8`
> 
> Also I do see the RF wavelength varying so I'm not sure why you see otherwise. I am going to close this issue. If you still have any issues, please open another ticket.

Hi David

I just ran the long_term_tracking with f14.8. Will email you the custom.dat as Github doesn't let me attach it here. In there, you can see the n_turn is all zero, and rf_wavelength is one number, 310.89045363. I must have missed something. The bmad package I have been using is from yesterday Gitbub the latest.

Mei

**Comment by DavidSagan** [comment]
@BaiMay I suspect that the code was not correctly updated or recompiled. We can zoom to sort this out if you want.

Also: Make a zip file to attach a file that has a suffix that GitHub will not accept.

**Comment by BaiMay** [comment]
Am still outside. How about zoom tomorrow morning say 9am PDT?

Thanks a lot!!!

Sent from my iPhone

On Nov 25, 2023, at 3:25 PM, David Sagan ***@***.***> wrote:

﻿

@BaiMay<https://github.com/BaiMay> I suspect that the code was not correctly updated or recompiled. We can zoom to sort this out if you want.

Also: Make a zip file to attach a file that has a suffix that GitHub will not accept.
