### ISSUE TITLE
Symp_Lie_Bmad does not track spin in cartesian maps

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#652]
As the title describes, spin is propagated through Cartesian Maps as though they are drift elements.

Run `tao` in the following directory.
[spin_sympliebmad_example.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13479603/spin_sympliebmad_example.zip)

If you change the `tracking_method` to runge_kutta, you can see the difference.

**Comment by DavidSagan** [comment]
Spin tracking with symp_lie_bmad never implemented. I will work on upgrading the code.

**Comment by DavidSagan** [comment]
Implemented.
