### ISSUE TITLE
NAN in long_term_tracking custom.dat

### ISSUE THREAD

**Issue by BaiMay** [bmad-sim/bmad-ecosystem#654]
[my.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13488476/my.zip)

While n_turn is now functioning properly, cavity##1%rf_wavelength continues to be NAN.

**Comment by DavidSagan** [comment]
@BaiMay It looks like the mpi version is having problems while the single threaded version is fine. I will look further into this.

**Comment by DavidSagan** [comment]
Actually I was wrong about it being an mpi problem. The problem is that the code to write a custom file is not handling averaging over a bunch correctly. I am working on a correction.

**Comment by BaiMay** [comment]
Thanks, David! Am also a bit confused which is the better way, i.e. cavity##1%rf_wavelength or cavity%rf_wavelength. For my case, there is only one rfcavtiy for acceleration.

**Comment by DavidSagan** [comment]
Either cavity##1%rf_wavelength or cavity%rf_wavelength works in your case.

**Comment by DavidSagan** [comment]
And the custom table code has been fixed.
