### ISSUE TITLE
ibs_ring init file trouble

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#659]
I am attempting to get the ibs_ring program working, and have run in to an invalid variable error in my init file on the line "mA_per_bunch = 1." Both this line and the previous line appear to be formatted correctly, so I am not sure where the error is coming from

[IBS.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13516406/IBS.zip)

**Comment by DavidSagan** [comment]
I asked Mike to take a look since he developed the code. The basic problem is that `ma_per_bunch` appears in the documentation but not in the program take a look at `bsim/ibs_ring/ibs_ring.f90 which has documentation  at the top of the file.

**Comment by MichaelEhrlichman** [comment]
The parameter names were cleaned up a while back, but the documentation was not updated.  I will be checking in an update to the .tex file.

[https://github.com/bmad-sim/bmad-ecosystem/commit/c94884459e3f63b669f1376c052734d9c14423dd#diff-8159761beb73b3a09e5e2d[…]789269067434df88859cb2eL285](https://github.com/bmad-sim/bmad-ecosystem/commit/c94884459e3f63b669f1376c052734d9c14423dd#diff-8159761beb73b3a09e5e2de3c32a2498f6fb7700d789269067434df88859cb2eL285)

**Comment by DavidSagan** [comment]
@MichaelEhrlichman Documentation change merged into Repo and the web doc page updated. Much thanks!

@jeu8 Can you take a look and to see if everything is OK?

**Comment by jeu8** [comment]
This appears to have fixed that issue, although now I have a new error for a missing parameter 'initial_blow_up'. I cannot find information on this parameter

**Comment by MichaelEhrlichman** [comment]
Thanks for pointing this out.  I will look into it.  In the mean time, you might want to use `bsim/ibs_ring/test/ibs_ring.in` as a template.

**Comment by MichaelEhrlichman** [comment]
initial_blow_up has been added to the ibs_ring tex documentation and should be available shortly by updating from the main repo.

**Comment by DavidSagan** [comment]
I have merged change into repo main and update the online doc pdf. @jeu8 If everything looks good you can close this issue.

**Comment by jeu8** [comment]
Everything looks good
