### ISSUE TITLE
Emittance data values different from beam initialization file

### ISSUE THREAD

**Issue by wlin6927** [bmad-sim/bmad-ecosystem#660]
The emittance d1 data values (emit.a, emit.b, norm_emit.a, norm_emit.b) at the BEGINNING element are different from the values set by the beam initialization commands (beam_init%a_emit, beam_init%b_emit, beam_init%a_norm_emit, beam_init%b_norm_emit). The values can be checked using 'show beam', 'show data emittance.a', and 'show data emittance.an' etc. 

[ltb_lattice.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13530890/ltb_lattice.zip)

**Comment by DavidSagan** [comment]
@wlin6927 Fixed. Problem was Tao was not including a factor of beta when converting between normalized and unnormalized values.
