### ISSUE TITLE
Tao lattice slicing incorrectly with extra element

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#661]
Attached is the HSR release lattice from Scott's GitHub repo.
[release.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13531711/release.zip)

In the file `ir6-lat.bmad` at `line 32` you'll find the additional snake that I've placed. This causes the issues.
If you comment out that element, then all is good.
Alternatively, if you erase the Tao initialization file, then all is good.

Not sure why this is happening.

**Comment by DavidSagan** [comment]
The problem was the bookkeeping for the longitudinal reversal of a Taylor element (not a slice problem). Fixed.
