### ISSUE TITLE
Ramper elements not working with overlays nor groups

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#667]
[booster.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13549132/booster.zip)

In the above file, the ramper element does not successfully change the group knobs `QUADS_V` and `QUADS_H`.
Even as overlays, the ramper element cannot ramp them.

**Comment by DavidSagan** [comment]
Fixed.
