### ISSUE TITLE
Long term tracking - add flag in init file to use equilibrium emittances

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#669]
It would be really nice if, instead of having to copy and paste the equilibrium emittances from Tao into the long_term_tracking.init for every lattice I'd like to track, if there were some flag I could set so that it just uses by default the equilibrium emittances of the lattice

**Comment by DavidSagan** [comment]
@mattsignorelli Actually that feature already exists. All you do is set a negative value. I have updated the long_term_tracking manual to document this (this was already documented in the Bmad manual). Similarly you can set sig_z or sig_pz negative.
