### ISSUE TITLE
Orbit zero in Tao but plot shows following dispersion

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#671]
[esr-main-unique.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13564368/esr-main-unique.txt)

The orbit is zero everywhere in show lat or show ele, but the plot shows an orbit ~1e-9 following exactly the disperrsion. The orbit should be zero everwhere

**Comment by DavidSagan** [comment]
`show ele` does not display enough digits. Use `show lat -orbit` to see the nonzero orbit which is of order 10^-12m.
And the orbit is non-zero due to differing RF phases between cavities.
