### ISSUE TITLE
No documentation for touschek_background

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#672]
The touschek_background program has no documentation on the bmad website

**Comment by MichaelEhrlichman** [comment]
I can write a document on the touschek_background program.

**Comment by DavidSagan** [comment]
@MichaelEhrlichman Any progress on this?

**Comment by MichaelEhrlichman** [comment]
Not yet.  Probably next week.

**Comment by MichaelEhrlichman** [comment]
Documentation for touschek_background merged into bmad-sim main branch.

**Comment by DavidSagan** [comment]
And the documentation has been posted to the web at https://www.classe.cornell.edu/bmad/other_manuals.html
