### ISSUE TITLE
b_emit set equal to a_emit in long term tracking when beam_init b_emit set negative

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#680]
Negative emittances in the beam_init for ltt should give equilibrum emittances, however the b_emit is set equal to the equilibrium emittance for a_emit

**Comment by mattsignorelli** [comment]
Example files on CLASSE computer at /home/mgs255/mgs255/master/test/test_ltt_b_emit

**Comment by DavidSagan** [comment]
@mattsignorelli Try the latest code and please close this issue if fixed.

**Comment by mattsignorelli** [comment]
@DavidSagan This is the output now:
pered.bmad_40.50
[FATAL | 2023-DEC-08 12:52:27] calc_emit_from_b:
    SETTING BOTH NORM_EMIT AND EMIT IN BEAM_INIT STRUCTURE IS NOT ALLOWED.
 
 !-------------------------------------------------
 ERR_EXIT: WILL BOMB PROGRAM TO GIVE TRACEBACK...

**Comment by DavidSagan** [comment]
I am working on the fix...

**Comment by DavidSagan** [comment]
Fixed.
