### ISSUE TITLE
show spin -ign * and -(x/y/z)_zero * not changing output at all

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#686]
There should atleast be small differences in the output of show spin if using the flags -ignore_ , -x_zero, y_zero, z_zero, but there is no change.
[esr-n2pi_cancel_eta-tapered.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13628081/esr-n2pi_cancel_eta-tapered.txt)

**Comment by DavidSagan** [comment]
Fixed.
