### ISSUE TITLE
tao error message when plotting lattices with lcavities: STARTING ORBIT NOT PROPERLY INITIALIZED!

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#687]
Floor plots in tao recentely started reporting the following error message when the lattice includes lcavities.

Test case at /home/ehrlichm/for_dcs/82

```
[ERROR | 2023-DEC-11 08:06:51] track1:
    STARTING ORBIT NOT PROPERLY INITIALIZED! [NEEDS AN INIT_COORD CALL?]
    TRACKING THROUGH ELEMENT: BUN1B (-2)
[FATAL | 2023-DEC-11 08:06:51] ele_compute_ref_energy_and_time:
    PARTICLE LOST IN TRACKING: BUN1B
    CANNOT COMPUTE REFERENCE TIME & ENERGY.
```

**Comment by MichaelEhrlichman** [comment]
In the test case, if the following line is commented out, then the error message goes away.

`graph%floor_plan_orbit_scale = 1`

**Comment by MichaelEhrlichman** [comment]
Issuing a `scale *` or `x_scale *` also makes the error message appear.

**Comment by DavidSagan** [comment]
Fixed.
