### ISSUE TITLE
Tao: write bmad group elements no old_X

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#690]
write bmad should have some flag so when writing the lattice, the actual state of the group elements is captured and written (with no old_X) parameters so that if I set X = 0 in the lattice after writing, it is equivalent to setting X = 0 in the lattice before writing

**Comment by DavidSagan** [comment]
Put in code so that you can now set `is_on` element parameter for groups. So now you can:
1. Set the group variable to get the right slave parameter values, 
2. set the group is_on = False.
3. set the group variable back to the design value.
4. Save the lattice
