### ISSUE TITLE
Unexpected truncation of lr_wake information when hybridizing a lattice with a cavity assigned with 65 or more wakes

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#695]
A lattice with a lcavity with more than 80 HOMs are assigned, and the lattice can be hybridized to run BBU with no issue.
However, the exported hybridized lattice ( using "write_bmad_lattice_file" function under "bbu_program.f90 " ) bombs Tao since the wake information beyond the 65th wake are missing ( see the instance below, note that after the number 7.908 the HOM information stops being written, and the incomplete syntax bombs Tao.  I suspect that there's a maximum number of lines allowed to be written for the "lr_wake" attribute.

I hope the lattice can hold an assignment of up to 200 HOMs per cavity.

Thanks.

**Comment by DavidSagan** [comment]
@weiyuanlou Can you attach example file?

**Comment by weiyuanlou** [comment]
[bbu_test.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13721236/bbu_test.zip)

Hi Dave, 

  Please unzip the attached folder, run .../bmad-ecosystem/production/bin//bbu  in the directory. The file "hybrid.lat" should be produced. Then run "tao -lat hybrid.lat" , and you will see that Tao bombs. If you look into the produced lattice you will see that the wake information has been truncated. 

Thanks

**Comment by DavidSagan** [comment]
Fixed.
