### ISSUE TITLE
normal.h.<..> "NOT VALID"

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#696]
Tao is saying my datum for the RDT is not valid

[Archive.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13650545/Archive.zip)

**Comment by DavidSagan** [comment]
Fixed. Two problems: 1) Error message was wrong as to what the problem was and 2) Tao needed to turn on the PTC 1-turn map calc with normal form when there was a datum that needed it but was not doing this.
