### ISSUE TITLE
Plotted curves incorrect

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#710]
Sorry for the complicated example, but it's probably necessary. Unpack [231220-bad-plot.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13731850/231220-bad-plot.zip). Change directory into `lo-n/041-05-collision`. Run `tao`. Then do `call 231220-bad-plot.tao`. What I see is a plot with three high but unequal peaks in `beta_b` between 40 and 60 m. But look at the `show lattice` output: all those peaks should be exactly the same. Now do `x_scale * 8.6 180`. Note the peaks are now all the same height. Do `x_scale * 8.5 180`; the peaks are a different height. I'm guessing that plot is mishandling one of the patches at 8.502 m?

**Comment by DavidSagan** [comment]
Looks like plotting is mishandling the bends due to the fact that the lattice is reversed. I'm guessing that slicing reversed elements is where the problem lies. Investigating further...

**Comment by DavidSagan** [comment]
Fixed. Problem turned out to be fringe field bookkeeping for slicing of reversed elements. Literally, just had to change one line.
