### ISSUE TITLE
BeamBeam not working after writing lattice with BeamBeam

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#713]
With attached lattice,
[esr-BB.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13756087/esr-BB.txt)

tao -lat esr-BB.txt
sho uni (see the tunes)
write bmad -form one_file esr-test.bmad
exi
tao -lat esr-test.bmad
sho uni (see the tunes are 0.08, 0.14, which is the bare lattice tunes)

**Comment by mattsignorelli** [comment]
Whoops, use this file instead (group elements removed: 
[esr-BB.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13756131/esr-BB.txt)

**Comment by mattsignorelli** [comment]
It looks like the cause is from n_particle. After writing some negative value (junk?)  is written for that rather than the original value.

**Comment by mattsignorelli** [comment]
Yes its writing int max or int min

**Comment by DavidSagan** [comment]
Fixed. Problem was that n_particle was being treated as an integer and there was integer overflow. Now it is a real.
