### ISSUE TITLE
Calculation of HOM power in BBU simulation

### ISSUE THREAD

**Issue by weiyuanlou** [bmad-sim/bmad-ecosystem#718]
Hi David:

        The current BBU program monitors the voltage of the HOMs over time, and the HOMs are modeled as long-range wakes.
        I wonder if the power associated with EACH HOM can be calculated or exported in a large file(s).
        
   Thanks.

**Comment by DavidSagan** [comment]
Yes this is possible. To implement, needed is exactly what is wanted.

**Comment by DavidSagan** [comment]
Closed due to inactivity. Can reopen when needed.
