### ISSUE TITLE
Orbit plot is wrong, does not match true orbit when using crab cavity

### ISSUE THREAD

**Issue by ColwynGulliford** [bmad-sim/bmad-ecosystem#720]
I have a crab cavity in a more complicated model which was producing a strange orbit plot - the smooth curve does not agree with the value of orbit.x and orbit.px at the lattice elements.  I've stripped things down to just a crab_cavity and a drift:

```
no_digested
    
beginning[e_tot] = 10000000000.0
    
parameter[particle] = electron
parameter[geometry] = open
beginning[beta_a] = 10
beginning[beta_b] = 10
beginning[alpha_a] = 0 
beginning[alpha_b] = 0

kcav: crab_cavity, rf_frequency=80e6, L=3.0, voltage=30e6, phi0=0.25
d1: drift, L=1

MWE: line = (kcav, d1)

use, MWE
```

When I run that with the most recent Tao on conda the kick from the cavity is set up to be positive 3 mrad.  When I do `sho value` I see the expected behavior:

```
Tao> sho value ele::END[orbit.px]
     3.0000000039048674E-03
```

However, the plot is wrong:
<img width="651" alt="Screenshot 2024-01-05 at 7 15 31 PM" src="https://github.com/bmad-sim/bmad-ecosystem/assets/36416205/c1c0fb6b-c553-48ab-bfba-25e2e9e642fa">

Furthermore, setting the smooth_line_curve switch to False seems to correct things:

`Tao> set global disable_smooth_line_calc = T`

<img width="629" alt="Screenshot 2024-01-05 at 7 17 01 PM" src="https://github.com/bmad-sim/bmad-ecosystem/assets/36416205/a9d0001f-86e3-4240-a07c-19f2247955fe">

**Comment by DavidSagan** [comment]
This looks like an element slicing problem with the crab cavity (which is what Tao uses to produce a smooth line plot). I will look into it.

**Comment by DavidSagan** [comment]
Slicing problem fixed.
