### ISSUE TITLE
Linear BeamBeam spin tracking?

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#724]
How is spin tracked through a beambeam element in long_term_tracking 1st order map tracking but the beambeam element by default excluded, and tracking_method = linear?
[bb.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13894104/bb.txt)

**Comment by mattsignorelli** [comment]
It looks like spin tracking is just not implement when doing tracking_method = linear, because the depolarization time I get from long_term_tracking is basically equivalent to what Tao gives when setting the G matrix of the beam-beam element to zero in a show spin

**Comment by DavidSagan** [comment]
Fixed.
