### ISSUE TITLE
Show spin seg fault

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#734]
[esr-main-18GeV-2IP.txt](https://github.com/bmad-sim/bmad-ecosystem/files/13920167/esr-main-18GeV-2IP.txt)

**Comment by mattsignorelli** [comment]
This occurs with the current release and with release 20231106-0, I haven't checked any in between.

**Comment by DavidSagan** [comment]
Fixed. Problem was missing use statement coverage.
