### ISSUE TITLE
error in expression for overlay element

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#738]
I have an overlay element set up with several variables with an expression for each attribute being controlled. The expressions are all similar to 1.56*a/(a+b+c+d+f), with the last addition giving the error
[vwig_new.zip](https://github.com/bmad-sim/bmad-ecosystem/files/13964923/vwig_new.zip)

**Comment by DavidSagan** [comment]
Fixed. Problem was confusion with "+d+" in the expression and that Bmad thought this was a malformed real number (like "1.3d-4").
