### ISSUE TITLE
Unclear in documentation on field maps

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#739]
I am wanting to set up an optimization in Tao using field map attributes of a cartesian field type. The documentation is unclear how this is done

**Comment by DavidSagan** [comment]
See updated Bmad manual section 3.8

**Comment by jeu8** [comment]
@DavidSagan I am able to use the attributes in the manual with no problem. Is there a way to alter the terms within a Cartesian map? (kx, ky, kz etc)

**Comment by DavidSagan** [comment]
I just added this to the code.
