### ISSUE TITLE
show spin seg fault

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#745]
This lattice has a use statement and still gives a segfault.
In Tao with `esr.bmad` do
`read lat var1.out`
`show spin`
[Archive.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14014764/Archive.zip)

**Comment by DavidSagan** [comment]
Missing is file: BAGELS_errors.bmad

**Comment by mattsignorelli** [comment]
[BAGELS_errors.txt](https://github.com/bmad-sim/bmad-ecosystem/files/14028125/BAGELS_errors.txt)

**Comment by mattsignorelli** [comment]
here is another lattice where it is a problem
[esr.txt](https://github.com/bmad-sim/bmad-ecosystem/files/14028298/esr.txt)

**Comment by DavidSagan** [comment]
@mattsignorelli I'm not seeing this with either ifort nor gfortran. Are you able to reproduce this on a lab computer?

**Comment by mattsignorelli** [comment]
For some reason I cannot reproduce this on a lab computer, however it's definitely happening on the office Mac desktop. It might be related to OpenMP. Basically if I call `show spin` without `spin_tracking_on` being explicitly set to true, it seg faults:

```
CLASSE-mc112:Downloads mgs255$ tao -lat esr.txt 
[MESSAGE | 2024-JAN-24 12:12:15] tao_init:
    OpenMP active with number of threads: 24
[MESSAGE | 2024-JAN-24 12:12:16] bmad_parser:
    Lattice parse time(min): 0.00
s
Tao> sho spin

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Could not print backtrace: executable file is not an executable
#0  0x104ac9b07
#1  0x104ac8b53
#2  0x185c49a23
#3  0x101ab3af3
Segmentation fault: 11
CLASSE-mc112:Downloads mgs255$
```

**Comment by DavidSagan** [comment]
@mattsignorelli If you recompile without openmp do you still get the error?

**Comment by mattsignorelli** [comment]
No issues when recompiling everything without openmp

**Comment by DavidSagan** [comment]
And I don't see any problems running on Mac with openmp. Are you sure you have properly updated your mac code?

**Comment by mattsignorelli** [comment]
I've recompiled and am no longer seeing the problem..
