### ISSUE TITLE
problem with inconsistent data from cartesian maps

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#746]
The plotting and data readouts for the end of this lattice do not match up, it seems to be some issue originating in the cartesian map wiggler

[cartesian_map_grad.txt](https://github.com/bmad-sim/bmad-ecosystem/files/14026033/cartesian_map_grad.txt)

**Comment by DavidSagan** [comment]
Two problems: 1) Default tracking_method = taylor is not accurate. Switched to symp_lie_bmad. 2) Step size too large. Got reasonable agreement with ds_step = 0.001
