### ISSUE TITLE
open ring w function

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#747]
I remember you put this feature in last summer, however it doesn't seem I can do it anymore
[BB-match.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14027463/BB-match.zip)

**Comment by DavidSagan** [comment]
Right now dbeta/dpz and dalpha/dpz are automatically set to zero at the beginning of an open branch. And you should be able to define W-function datums. Is this good enough?

**Comment by DavidSagan** [comment]
@mattsignorelli I am closing this for now but please reopen if there is still an issue.
