### ISSUE TITLE
optimization not working with cartesian maps

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#748]
I am attempting to do an optimization of an orbit using a parameter in a cartesian map. If a make a change by hand I see a change in the orbit, however if I run an optimization in Tao it returns the initial value after a few tries. I do not get the error where it says the variable does not change the merit.
[test.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14027992/test.zip)

**Comment by DavidSagan** [comment]
Problem is that the Taylor map is not getting remade. This does not affect the plotting but `show ele 5` shows that the non-plot orbit is not changing. I will work on a fix.

**Comment by jeu8** [comment]
@DavidSagan I saw this problem also appear using symp_lie_bmad tracking as well. Thought I would mention that in case it is a separate fix

**Comment by DavidSagan** [comment]
I put in a fix. I do not see any problem with symp_lie_bmad.

**Comment by jeu8** [comment]
Moved to new issue
