### ISSUE TITLE
cartesian map optimization

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#751]
k values of cartesian maps cannot be altered in Tao during optimization due to consistency issue. They can be altered by hand and the inconsistency is ignored
[map.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14055960/map.zip)

**Comment by DavidSagan** [comment]
This is complicated by the fact that there are three variables here kx, ky, kz with one constraint so how to vary, say, ky and kz when kx is varied is not something that Bmad can figure out. The best way around this is to use an overlay. For example:
```
k: overlay = {wig1[cartesian_map(1)%t(2)%kx]:x, 
 wig1[cartesian_map(1)%t(2)%ky]:sqrt(x^2 + 0.01^2)}, var = {x}, x = 0.69*3.56658
```
