### ISSUE TITLE
losing particle for cartesian map optimization

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#752]
I am running an optimization of the "A" parameter in a cartesian map and keep losing the particle. step size seems small enough it should work.
[Map.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14055970/Map.zip)

**Comment by DavidSagan** [comment]
Problem is that an `unstable_orbit` datum is needed to guide the optimization back to stability (merit otherwise drops to zero when the orbit becomes unstable!).
