### ISSUE TITLE
Tao: changing `beam distribution_type` does nothing

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#769]
In `bmad-doc/tao_examples/optics_matching`, 
```
call plot_bunch.tao 
```
will track the beam and plot as below. However, trying to change the distribution type seems to do nothing:
```
set beam distribution_type      = "ran_gauss"  "ran_gauss"  "ran_gauss"
```
The plot remains the same. 

![image](https://github.com/bmad-sim/bmad-ecosystem/assets/31023527/6bf06918-cb1d-439b-b633-b20b4f78c7bb)

**Comment by DavidSagan** [comment]
There is a message about the parameter (distribution_type) not being recognized. The problem is that the appropriate command is `set beam_init` and not `set beam`.  I will expand the message to be more visible and point the user to `set beam_init`.
