### ISSUE TITLE
fixed_step_time_runge_kutta overriding other tracking methods

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#771]
In the APEX gun benchmark, the solenoid overlaps the gun.
<img width="565" alt="image" src="https://github.com/bmad-sim/bmad-ecosystem/assets/31023527/b2810bec-ecbc-4bf3-bf4d-50ee1506b518">

However, setting the following
```
GUN[tracking_method] = fixed_step_time_runge_kutta
SOL1[tracking_method] = time_runge_kutta
```
makes fixed step seems to override the second part:

```
tao -lat lat.bmad -command "sho lat -at tracking_method"
[MESSAGE | 2024-FEB-06 18:51:31] tao_init:
    OpenMP active with number of threads: 10
[MESSAGE | 2024-FEB-06 18:51:31] bmad_parser:
    Lattice parse time(min): 0.00
# Values shown are for the Exit End of each Element:
# Index  name      key                         s          l  tracking_method
      0  BEGINNING Beginning_Ele        0.000000        ---
      1  GUN#1     E_Gun                0.006530   0.006530  Fixed_Step_Time_Rung
      2  GUN\SOL1  EM_Field             0.175000   0.168470  Fixed_Step_Time_Rung
      3  P1\SOL1   Solenoid             0.486530   0.311530  Fixed_Step_Time_Rung
      4  P1#1      Pipe                 0.500000   0.013470  Bmad_Standard
      5  END       Marker               0.500000   0.000000  Bmad_Standard
Lord Elements:
      6  GUN       E_Gun                0.175000   0.175000  Fixed_Step_Time_Rung
      7  P1        Pipe                 0.500000   0.325000  Bmad_Standard
      8  SOL1      Solenoid             0.486530   0.480000  Fixed_Step_Time_Rung
```

Example files: [example.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14188501/example.zip)

**Comment by DavidSagan** [comment]
@ChristopherMayes Taking a closer look, it turns out that for tracking certain elements like an lcavity, it is important that the super_slaves of the element all have the same tracking method. So this is not a bug.

**Comment by ChristopherMayes** [comment]
The problem I have is the 'chicken and egg' with instability in the gun energy: https://github.com/bmad-sim/bmad-ecosystem/issues/488#issuecomment-1724171714

The above case has three tracking parts. Is there no way to transition the tracking method in the second part?

**Comment by DavidSagan** [comment]
what do you mean by "transition"?

**Comment by ChristopherMayes** [comment]
I want the first part to be fixed tilmestep, the later adaptive.

**Comment by DavidSagan** [comment]
How about use two solenoids instead of one?

**Comment by ChristopherMayes** [comment]
well, this is a single solenoid fieldmap

**Comment by DavidSagan** [comment]
Note: This issue is different from the "chicken and egg" issue of calculating the reference energy for the gun since here the tracking_method through the gun is always fixed_step_time_runge_kutta.

**Comment by DavidSagan** [comment]
You can use the same fieldmap for two solenoid elements. Just make sure the fieldmap is offset for the second element.
