### ISSUE TITLE
Implement Ion cooling

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#773]
- [x] Define lattice elements: pickup (new)  & kicker (slaves), and feedback (control_lord).
- [x] feedback uses parameters `input_from` and `output_to` to point to slaves.
- [x] Implement possibility to define multiple input and output slave elements.
- [ ] Implement appropriate parameters for these elements.
- [ ] Implement tracking code.
- [ ] Document.
- [ ] Testing.
- [ ] Implement regression tests

ecool struct implementation:
- [ ] Ignore in cpp interface
- [ ] read/write digested bmad
- [ ] Instantiate during parsing
- [ ] equal_mod
- [ ] pointer_to_attribute
- [ ] type_ele

**Comment by BhawinDhital** [comment]
@DavidSagan What kind of ion cooling method you are going to implement in Bmad? I am really interested in this topic.
I have used JSPEC which is benchmarked with BETACOOL.

**Comment by DavidSagan** [comment]
[tbt_code_theory.pdf](https://github.com/bmad-sim/bmad-ecosystem/files/14226566/tbt_code_theory.pdf)
This is being done with Will Bergan.

**Comment by DavidSagan** [comment]
@BhawinDhital Bmad manual updated. See the section on the feedback element for details.

**Comment by DavidSagan** [comment]
e_cooling program in development. Currently no work needed for the Bmad library so closing this issue.
