### ISSUE TITLE
long term tracking with simulation mode = "INDIVIDUAL"

### ISSUE THREAD

**Issue by BhawinDhital** [bmad-sim/bmad-ecosystem#774]
Hi David

I am doing a long term tracking using simulation mode = "INDIVIDUAL" in a long term tracking. It is all about a third integer slow resonant extraction. Simulation mode = "SINGLE" gives me a nice unstable triangle plot for the given amplitude (x) of the particle. With the same set up I take many particles and "individual" mode. It should record the particles coordinates at the septum location. But the tracking ends so quickly and the output particles phase space does not look like slowly extracted.
[individual_mode.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14200645/individual_mode.zip)

**Comment by eiad-hamwi** [comment]
@DavidSagan If you run the `long_term_tracking` in _beam_ mode, it runs properly. So the bunches are good, the error is somewhere in _individual_

**Comment by DavidSagan** [comment]
@BhawinDhital @eiad-hamwi Fixed. Problem was individual mode was applying the closed orbit offset to the initial particle position twice in individual mode.
