### ISSUE TITLE
HARMON attribute of Crab_Cavity element ignored

### ISSUE THREAD

**Issue by vsmorozov** [bmad-sim/bmad-ecosystem#778]
The HARMON attribute of a Crab_Cavity element does not seem to work. When RF_FREQUENCY is specified, the resulting bunch tilt is as expected. When using HARMON corresponding to that frequency in a closed lattice, there is no error message but it looks like the cavity does not generate a kick. When HARMON is specified, "show ele" in tao gives RF_FREQUENCY = 0 and, vice versa, when RF_FREQUENCY is set, HARMON = 0.

Thanks,
Vasiliy

**Comment by DavidSagan** [comment]
@vsmorozov I don't see a problem. Can you attach a lattice that I can test?

**Comment by DavidSagan** [comment]
Fixed.
