### ISSUE TITLE
Inconsistent tracking of lcavity with track_all and track_s_to_s different number of slices.

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#784]
Test case at LNS: /home/ehrlichm/for_dcs/85

```
[mpe5@lnx201 85]$ ../production/bin/bug2 one_cav.bmad 
track_all:      1.0377  -3.051163E-05  -3.178162E-05   0.000000E+00   0.000000E+00  -3.141242E-09   1.266024E-09   7.814574E+06
2 slices:       1.0377  -3.050472E-05  -2.020795E-05   0.000000E+00   0.000000E+00  -3.141009E-09   1.265910E-09   7.813941E+06
10 slices:      1.0377   2.793044E-06  -2.020795E-05   0.000000E+00   0.000000E+00  -1.478725E-09   1.045345E-09   7.813941E+06

```

**Comment by MichaelEhrlichman** [comment]
Part of the discrepancy can be attributed to lcavity fringe fields, which is understandable.  However, even after accounting for whether or not the end fringe is tracked through, the more fundamental routine track_from_s_to_s shows a dependency on number of slices.

**Comment by MichaelEhrlichman** [comment]
I have updated the test case at `for_dcs/85` to use `track_from_s_to_s`, rather than `track_s_to_s` from `bsim`'s `slice_mod`.

**Comment by DavidSagan** [comment]
Fixed. Problem was that lcavity tracking was ignoring num_steps and only taking one step. On top of that, the energy gain in this particular lattice was larger than the reference energy which, with one step, made the tracking inaccurate. The fix will be in the Repo shortly.
