### ISSUE TITLE
long_term_tracking cannot set the starting particle time

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#795]
The long_term_tracking program init system is capable of setting the initial phase space variables of a single particle, as well as the ramping_start_time, but not the particle's actual start time. 

In order to concatenate many single-turn tracking results, the particle coordinates at the end of the previous turn that ought to be passed down to the lattice for the next turn include phase space coordinates and particle time. 

Therefore, long_term_tracking should be modified to be able to set the particle's starting time.

**Comment by DavidSagan** [comment]
Can you attach you input file? Thanks.

**Comment by eiad-hamwi** [comment]
Input file attached:

[LTT_init.zip (updated)](https://github.com/bmad-sim/bmad-ecosystem/files/14233655/LTT_init.zip)

**Comment by DavidSagan** [comment]
@eiad-hamwi Looks like there is an undocumented parameter `beam_init%ix_turn` which should do what you want. Just set this to the turn number. I will update the documentation. If this works please close the issue.

**Comment by eiad-hamwi** [comment]
This parameter `beam_init%ix_turn` seems to have no observable effect on the calculations.

**Comment by DavidSagan** [comment]
Fixed. Try is now.

**Comment by eiad-hamwi** [comment]
Test

**Comment by eiad-hamwi** [comment]
Input files: [LTT_init.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14312036/LTT_init.zip)

**Comment by DavidSagan** [comment]
Fixed.
