### ISSUE TITLE
zero beta error in tune_scan

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#800]
I am getting a zero beta error while using the tune_scan program. The lattice on its own has no errors, so it must be getting introduced by something the tune_scan program is doing. I am currently using a phase trombone to alter the tune, so I would not expect to get a change in optics.
[tune_scan.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14237950/tune_scan.zip)

**Comment by DavidSagan** [comment]
Fixed. Problem was that the tune_scan program needed updating when the match element syntax was modified recently.
