### ISSUE TITLE
Possible issue with phase trombone

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#803]
In this lattice I have zero phase phase_trombone, and receive an error about non-positive beta. I also get an error about my setting of recalc, which according to the manual should be on for a phase_trombone. turning recalc off still gives an error   

[phase_trombone.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14245559/phase_trombone.zip)

**Comment by DavidSagan** [comment]
@jeu8 I put in a fix but there is a wrinkle we need to discuss...
