### ISSUE TITLE
Ramp element trhowing error.

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#814]
Not sure if bug or poor lattice writing but the attached file worked with an order version of Bmad (say ~9/1/23) and is now giving a bug.
[MESSAGE | 2024-FEB-16 00:03:52] tao_init:
    OpenMP active with number of threads: 12
ERROR IN bmad_parser: BLANK NAME
      IN FILE: /home/lovelace/BMAD_DIST/lattice_files/rhic/Au21-100GeV_gammat/../Au23-100GeV-e0/rrr/ramp-rrr-gt-120223.bmad
      AT OR BEFORE LINE: 81
     21.880010000000002,
     21.89001,
ERROR IN bmad_parser: MALFORMED CONTROLLER SLAVE NAME:
      IN FILE: /home/lovelace/BMAD_DIST/lattice_files/rhic/Au21-100GeV_gammat/../Au23-100GeV-e0/rrr/ramp-rrr-gt-120223.bmad
      AT OR BEFORE LINE: 81
[ramp_error.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14312025/ramp_error.zip)

     21.880010000000002,
     21.89001,
and so on
Bmad version 12/7/23

**Comment by DavidSagan** [comment]
@henrylovelace3 The syntax is off. Lines like:
  `,},var = {time}, x_knot = {21.85001,`
should not have the first comma. I'm going to be changing Bmad to be more forgiving but for now you can just remove the commas.

**Comment by henrylovelace3** [comment]
Thanks, I was a victim of staring too long!
