### ISSUE TITLE
6D beam tracking with no RF

### ISSUE THREAD

**Issue by wlin6927** [bmad-sim/bmad-ecosystem#815]
I have trouble tracking a beam input file in the LtB line with no RF. The emittance and sigma are not calculated.

[ltb_parmila.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14314559/ltb_parmila.zip)

**Comment by DavidSagan** [comment]
@wlin6927 What happens if you give the particles z-positions using a Gaussian random number generator?

**Comment by DavidSagan** [comment]
And I have put in a fix to avoid the problem altogether.
