### ISSUE TITLE
Tao floor plan scaling doesn't honor shape widths

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#816]
Often a user issues `scale` when the floor plan is in the plot. For example, in `bmad-doc/tao_examples/cbeta_cell`, upon init:
<img width="330" alt="image" src="https://github.com/bmad-sim/bmad-ecosystem/assets/31023527/169ebcf5-b39b-4b4c-b78d-f4bd91effd45">

`Tao> scale`:
<img width="717" alt="image" src="https://github.com/bmad-sim/bmad-ecosystem/assets/31023527/46ed54e8-f6e0-4fee-8c62-aefdd91fd9e5">

Could we make it so that this honors the ele shapes, or have some other method that doesn't distort?

**Comment by DavidSagan** [comment]
@ChristopherMayes Does floor_plan%size_is_absolute do what you want?

**Comment by ChristopherMayes** [comment]
That makes it worse: 
<img width="745" alt="image" src="https://github.com/bmad-sim/bmad-ecosystem/assets/31023527/a829b6ab-7c10-47f7-a639-697985490c12">

**Comment by DavidSagan** [comment]
@ChristopherMayes You need to adjust the width numbers to correspond to the absolute scale.

**Comment by DavidSagan** [comment]
Assuming this is solved I am closing.
