### ISSUE TITLE
Inconsistent spin + giant spin norm with Taylor element

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#821]
[BB-nolin.txt](https://github.com/bmad-sim/bmad-ecosystem/files/14336265/BB-nolin.txt)
The attached lattice has a Taylor element to counteract the linear part of the beambeam.

With attached lattice,  run Tao and do a show spin. Spin norm will be gigantic (not sure why...)

Then set ele rbb is_on = F

Another show spin does not resolve the huge spin norm. 

Now exit Tao and change the element "rbb" to a marker. Reopen Tao and see the spin norm is ok

**Comment by mattsignorelli** [comment]
I realized the large spin norm is my fault. I have q(z0) from the BeamBeam and am just doing q^-1(zf) whereas I also need to invert the coordinates inside so I have q^-1(z0). However the is_on is still a problem with spin

**Comment by DavidSagan** [comment]
Fixed.
