### ISSUE TITLE
chrom.w.a, chrom.w.b not working with open lattice

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#823]
I am doing an optimization with the w-function where it is easier to start with an open lattice. The chrom.w data types should be able to be calculated with an open lattice, but I get an error about the open lattice and the value is not computed. The plotting of the w-function does appear to work properly with an open lattice, so the calculation itself seems fine
[w_function.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14376334/w_function.zip)

**Comment by DavidSagan** [comment]
Fixed.
