### ISSUE TITLE
TAO giving slip factor for momentum_compaction

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#824]
This may have been fixed in a later version. The distribution I am using is from 12/7

Tao> show uni
Universe: 1  Of: 1
Branch:   0  In range: [0, 0]
is_on:                    T
Lattice name:             ""
Machine name:             ""
Used line(s) in lat file: "HSR_LO_N"
Lattice file name:        "/home/lovelace/BMAD_DIST/lattice_files/eic/hsr/hsr_full/EIC-HSR.git/trunk/lo-n/041-05-collision/gammat/16psopti/./lo-n-inj.bmad"
Reference species:        Antiproton
Default tracking species: Ref_Particle (Antiproton)
a_anomalous_moment * gamma     4.54999995E+01
Reference energy:              2.38120550E+10
Reference momentum:            2.37935623E+10
Absolute_Time_Tracking:      T
Geometry:                    Closed
global%rf_on:                F
Elements used in tracking: From 1 through 3560
Lord elements:   3561  through 5136
Lattice branch length:      3832.950
Lattice branch transit time: 1.279528E-05
Lattice branch S-range:     [.000000, 3832.949598]

                              A-Mode         |            B-Mode
                         Model       Design  |       Model       Design
                Q    28.229959    28.228000      29.211875    29.210000  ! Tune
            Chrom     1.927891     2.000000       1.762540     2.000000  ! dQ/(dE/E)
           J_damp     0.785433     0.994767       0.999020     1.000018  ! Damping Partition #
        Emittance  5.02058E-18 -7.87307E-18    2.10741E-19  1.69058E-19  ! Unnormalized
   Emit (photon vert opening angle ignored)    0.00000E+00  0.00000E+00
       Alpha_damp  1.72696E-16  2.18262E-16    2.19658E-16  2.19414E-16  ! Damping per turn
     Damping_time  7.40913E+10  5.86235E+10    5.82509E+10  5.83156E+10  ! Sec

                         Model       Design
          Z_tune:    0.0000000    0.0000000   ! The design value is calculated with RF on
         Sig_E/E: -1.00000E+00  1.11035E-07
           Sig_z: -1.00000E+00  1.38393E-05   ! Only calculated when RF is on
     Emittance_z: -1.00000E+00 -1.00000E+00   ! Only calculated when RF is on
     Energy Loss:  1.04713E-05  1.04492E-05   ! Energy_Loss (eV / Turn)
          J_damp: -4.96672E-16 -4.73560E-18   ! Longitudinal Damping Partition #
      Alpha_damp: -1.09205E-31 -1.03904E-33   ! Longitudinal Damping per turn
       damp_time: -1.17168E+26 -1.23145E+28   ! Longitudinal Damping time (sec)
         **Alpha_p:  1.95882E-03**  0.00000E+00   ! Momentum Compaction
           Eta_p:  4.06207E-04 -1.55262E-03   ! Slip factor
     gamma_trans:  2.25945E+01     Infinity   ! Gamma at transition
            <pz>:  1.00000E-03  0.00000E+00   ! Average closed orbit pz (momentum deviation)

[Note: The emittance, energy loss, etc. calcs have changed. Use "help show universe" for more info.]

**Tao> show value lat::momentum_compaction[end]|design
     4.0529994292707900E-04**

**Comment by DavidSagan** [comment]
Fixed.
