### ISSUE TITLE
Add functionality to set multiple elements to design values.

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#827]
The following command lets me reset the k1 of an individual quad.
```set ele QA01 k1 = ele::QA01[k1]|design```

 However, the following two do not work.  Is their syntax similar to the above that sets all quad k1 to their design k1?
```set ele quad::* k1 = quad::*[k1]|design #errors out```
```set ele ele::Q* k1 = ele::Q*[k1]|design #errors out```

**Comment by DavidSagan** [comment]
Correct syntax is:
`set ele Q* k1 = ele::Q*[k1]|design
`
