### ISSUE TITLE
Problem with multiple universe

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#837]
I have five universes initialized in my init file. All are the same lattice. With just one universe I get no errors, but with additional universes I get a singular one turn matrix error
[universe_problem.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14510402/universe_problem.zip)

**Comment by DavidSagan** [comment]
Fixed. Problem was Tao was getting confused turning off RF in multiple universes that used the same lattice.
