### ISSUE TITLE
error with taylor element

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#838]
I am getting an error with a taylor element about the field_calc parameter. It seems odd that this error would show up with a taylor element

[ags_mat_run22.txt](https://github.com/bmad-sim/bmad-ecosystem/files/14512936/ags_mat_run22.txt)

**Comment by DavidSagan** [comment]
Fixed. Problem was taylor element with finite length was confusing Bmad in the radiation calculation.
