### ISSUE TITLE
Build scripts cannot handle the zsh shell

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#84]
Build scripts cannot handle the zsh shell.
This needs to be fixed.
This is important since zsh is now the default shell on Mac OS. 
Reference:  [CU-CLASSE #56199]

**Comment by attiliodefalco** [comment]
The solution on macOS is to switch back to bash shell:

   chsh -s /bin/bash

Even on macOS 10.16, bash shell is still available.
