### ISSUE TITLE
problem with expressions in defining data in Tao

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#843]
I am having trouble using expressions in defining custom data in Tao. I received an error about setting a reference element. In my case I am not using any data that needs a reference element. I put one in just to see if it fixed the problem, but I get a new error about an unknown data source. I have it set to "data" which should be what I want for expressions. The expression itself is just about the simplest case I could think for troubleshooting. I just pull one previously defined datum, so I could pull the form directly from the manual.

Not sure if this is a bug or a subtlety with expressions I am missing.

[expressions.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14523673/expressions.zip)

**Comment by DavidSagan** [comment]
I will work on the error message which is wrong. The real problem is you need to use "expression:" at the start of the data_type string.

**Comment by DavidSagan** [comment]
And error message fixed.
