### ISSUE TITLE
Extraction simulations in a Long-term tracking gives the same output files at marker elmenets

### ISSUE THREAD

**Issue by BhawinDhital** [bmad-sim/bmad-ecosystem#846]
[new_final.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14547877/new_final.zip)

Hi David,

Tracking many particles with extraction methods = "ON" in a long term tracking with "INDIVIDUAL" simulation mode: All phase space coordinates are the same at the the septum location and at other marker locations downstream the extraction lines.

The files I am using are attached. Please use the long_term_tracking.init file, which has set-up for the long-term tracking.

**Comment by DavidSagan** [comment]
Fixed. Problem was that with an aperture on the upstream end of the extraction septum, the long_term_tracking program was mishandling the tracking.
