### ISSUE TITLE
Bulid busted on LAPACK VERSION 3.12.0

### ISSUE THREAD

**Issue by henrylovelace3** [bmad-sim/bmad-ecosystem#849]
The build breaks when compiling LAPACK version 3.12.0. The error log is attached. The build is with 

ifort: **remark #10448: Intel(R) Fortran Compiler Classic (ifort) is now deprecated and will be discontinued late 2024. Intel recommends that customers transition now to using the LLVM-based Intel(R) Fortran Compiler (ifx) for continued Windows* and Linux* support, new language support, new language features, and optimizations. Use '-diag-disable=10448' to disable this message.**
ifort (IFORT) 2021.11.1 20231117
Copyright (C) 1985-2023 Intel Corporation.  All rights reserved.

The "emphasized" is just a warning. 

[error.log](https://github.com/bmad-sim/bmad-ecosystem/files/14588628/error.log)

**Comment by DavidSagan** [comment]
@henrylovelace3 This looks to be an issue with your computer setup as opposed to LAPACK per se since from the error log:

```
CMake Error at /usr/share/cmake/Modules/FortranCInterface.cmake:383 (message):
  The Fortran compiler:

    /opt/intel/oneapi/compiler/2024.0/bin/ifort

  and the C compiler:

    /usr/bin/cc

  failed to compile a simple test project using both languages.
```
Try talking to @jsberg-bnl If needed.
