### ISSUE TITLE
long_term_tracking taking longer than expected

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#850]
I have a lattice with a few RF elements in the lattice along with a matrix. for 300k turns it takes 40mins, which is longer than expected for a simple lattice
[AGS_merge.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14591395/AGS_merge.zip)

**Comment by DavidSagan** [comment]
Problem is writing to the averages file every turn. When I turn this off the simulation takes about 1/2 minute.
