### ISSUE TITLE
Add support for mad8 lcavity parameter SWAVE to mad8_to_bmad.py

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#854]
The mad8s program at SLAC now supports a logical SWAVE parameter for lcavity elements.

If present, the cavity is treated as a standing wave cavity per Rosenzweig & Serifini.
If present and true, the cavity is treated as a standing wave cavity per Rosenzweig & Serifini.
If not present, the cavity is treated as a traveling wave cavity.
If present and false, the cavity is treated as a traveling wave cavity.

**Comment by DavidSagan** [comment]
@MichaelEhrlichman Question: are there any other versions of MAD8 besides MAD8S that are in use and have an lcavity? If so, any changes must be made to not break the translation of these versions.

**Comment by DavidSagan** [comment]
The problem is that with mad8s the default, if swave is not present, to treat the lcavity as a traveling wave cavity while the current translation translates lcavity elements to standing wave.

**Comment by MichaelEhrlichman** [comment]
The current mad8, only supports traveling wave cavities.  The SLAC mad8s is the only fork I am aware of that supports standing wave cavities.  So, mad8_to_bmad should default to traveling wave.

**Comment by DavidSagan** [comment]
I'm also worried about the people who are not using the latest version of mad8s.

**Comment by MichaelEhrlichman** [comment]
If the current mad8_to_bmad is translating lcavities to standing wave, then that is a mistake.  However, perhaps users are accustomed to that mistake and will be perturbed by the change.

Since mad8s /w standing wave cavities is only in use at SLAC, I could understand if support for SWAVE is left out of mad8_to_bmad.  The adjustment can be made by hand (or script).  mad8s will not be in use too much longer.

**Comment by DavidSagan** [comment]
@ChristopherMayes Do you have a comment?

**Comment by ChristopherMayes** [comment]
Only `mad8s` (Mad-8 SLAC) has LCAVITYs anyway, right? I

**Comment by DavidSagan** [comment]
I believe so @jsberg-bnl may have some knowledge about this.

**Comment by DavidSagan** [comment]
Scott writes:

> MAD8 is solidly dead. You can’t get it from CERN any more, SLAC doesn’t make their version publicly available. There seems to be a group of people at SLAC that insist on working with it (Yunhai Cai is one of them), but they’re an anomaly. It’s probably not (easily) buildable from source any more, since I believe it is dependent on CERNLIB which is broken for 64-bit systems. This may be part of the reason they’re “upgrading” to about-to-be-unsupported RHEL7 at SLAC.
 
So I will work on implementing SWAVE.

**Comment by MichaelEhrlichman** [comment]
@DavidSagan Did you mean "So I will not work on implementing SWAVE."

It is not so difficult for me to manually make the standing wave edits when doing lattice translation, and mad8 will not be around for too much longer.  If it is not easy to add to mad8_to_bmad, then I would rather withdraw this feature request.

*** comment here added after further consideration***
On the other hand, while mad8 may be on its death bed, people probably have old mad8 lattices laying around that they may try to translate to a modern code like Bmad.  In that case, the translation should be done correctly and mad8_to_bmad should convert lcavities to traveling_wave cavities.  Perhaps the best solution would be to have mad8_to_bmad always translate to traveling_wave cavities, and I can manually find-and-replace to standing_wave for SLAC's particular purposes.

**Comment by DavidSagan** [comment]
@MichaelEhrlichman It should be just a few lines add so not much of a problem. Can you provide a simple example?

**Comment by MichaelEhrlichman** [comment]
```
title, "one cav for lcavity model testing"

option, -echo, info, warn, verify, double
assign, echo="one_cav.echo"
assign, print="one_cav.print"

begm: mark
da: drif, l=1.0
db: drif, l=1.0
endm: mark

cav_sc:  lcav, freq=1300, l=1.5,  deltae=2.7, &
      phi0=-0.236, swave

cav_tw:  lcav, freq=1300, l=1.5,  deltae=2.7, &
      phi0=-0.236

one_sc_cav: line=(begm,da,cav_sc,db,endm)
one_tw_cav: line=(begm,da,cav_tw,db,endm)

use, one_sc_cav

tw0: beta0, betx=9.63,alfx=8.00,bety=6.47,alfy=-6.63
beam, particle=electron,energy=0.001261  !GeV
twiss, save, beta0=tw0
archive, table=twiss, filename="one_cav.archive"

stop

```

**Comment by DavidSagan** [comment]
Conversion both ways is fixed.
