### ISSUE TITLE
Possible issue in frequency_map with non-zero longitudinal closed orbit

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#855]
I have a lattice that has a large z coordinate at the beginning of the lattice due to tracking through a cartesian map wiggler.  I put in a patch element to correct the timing with the rf. Running in Tao or the DA program works fine, but in the frequency map program all points fail with a "particle outside of rf bucket" message. My guess is that the frequency map program does not know how to handle my odd lattice.

I have the lattice and frequency_map input/setup files attached
[freq_map.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14624806/freq_map.zip)

**Comment by DavidSagan** [comment]
@jeu8 How do I create the input files for frequency_map?

**Comment by jeu8** [comment]
@DavidSagan I use the python scripts in the frequency_map bmad directory. I have my altered version of make_inputs_DA.py in the attached files. This makes several input files that I submit as jobs with the submit.py script, although I see the error with every input file, so you should only need to look at one of them.

**Comment by DavidSagan** [comment]
Fixed. Problem was that the out of RF bucket test was not taking into account the closed orbit z.
