### ISSUE TITLE
initial longitudinal position of second bunch in long term tracking

### ISSUE THREAD

**Issue by jeu8** [bmad-sim/bmad-ecosystem#860]
I have a cavity set up for my lattice with harmon=12. I then take the frequency of this cavity to calculate the dt for initializing the second bunch in my simulation. this should give a z coordinate of ~67m for the second bunch. The actual number I get in the simulation is ~0.5*10^6m. 
[bunches.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14671144/bunches.zip)

**Comment by DavidSagan** [comment]
Fixed. Calculation was dividing by beta instead of multiplying.
