### ISSUE TITLE
cannot see time of the simulation at the end of a long term tracking.

### ISSUE THREAD

**Issue by choitingwing** [bmad-sim/bmad-ecosystem#870]
When I run 
`mpiexec long_term_tracking_mpi long_term_tracking_beam.init`  

in my 10 cores M1 macOS, this happens at the end of the simulation, what is the reason? I haven’t had it with another macOS which has intel core:

` Cumulative number dead at end of turn 98: 3645
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
 Cumulative number dead at end of turn 98: 3664
 Cumulative number dead at end of turn 98: 3732
 Cumulative number dead at end of turn 99: 3780
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
 Cumulative number dead at end of turn 99: 3696
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
 Cumulative number dead at end of turn 99: 3639
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
 Cumulative number dead at end of turn 99: 3665
 Cumulative number dead at end of turn 99: 3735
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
 Cumulative number dead at end of turn 99: 3639
 Cumulative number dead at end of turn 99: 3639
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG`

One problem is I couldn't see the time of simulation at the end.

I installed openMPI with brew, and Bmad with conda.

These are the files I used
[ring_Beam_tracking.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14760945/ring_Beam_tracking.zip)

**Comment by DavidSagan** [comment]
@choitingwing I could not reproduce this on Linux. Try compiling a Bmad Release to see if the problem persists.

**Comment by DavidSagan** [comment]
Since no response will close this issue.
