### ISSUE TITLE
Error running on tutorial 11.8- Running the Optimization

### ISSUE THREAD

**Issue by sophiayang627** [bmad-sim/bmad-ecosystem#873]
File used: bmad-ecosystem/bmad-doc/tutorial_bmad_tao/lattice_files/lattice_correction/

Input to simulate Correction according to pg 57 on Bmad & Tao tutorial:

Tao > run ! Run the optimizer
Tao> set lattice base = model ! Save the model fit values in the base lattice 
Tao> call create_data.tao ! This will load the "true" values
Tao> set var *|model = *|model + *|design - *|base ! Load the correction.

After input line: call create_data.tao, got the following: 

Tao: set var steering[1]|model = 1.2e-4

Tao: set var steering[2]|model = 0.9e-4

Tao: set var quad_k1[1]|model = 0.9

Tao: set var quad_k1[2]|model = -1.05

Tao: set var quad_tilt[1]|model = 0.1    ! Also include tilt errors

Tao: set var quad_tilt[2]|model = -0.05

Tao: show value 1@orbit.x|model + 5e-5*ran_gauss() -form es12.4  ! Add 10um noise
[ERROR | 2024-MAR-26 13:48:39] tao_param_value_routine:
    CANNOT EVALUATE AS DATUM OR VARIABLE VALUE: formes12.4
[ERROR | 2024-MAR-26 13:48:39] tao_evaluate_expression:
    ERROR IN EXPRESSION: 1@orbit.x|model+5e-5*ran_gauss()-formes12.4
    CANNOT EVALUATE: formes12.4
[WARNING] tao_show_cmd:
    "Note: -format" has been changed to "#format" to avoid confusion with any negative signs.

Tao: show value 1@orbit.y|model + 5e-5*ran_gauss() -form es12.4
[ERROR | 2024-MAR-26 13:48:39] tao_param_value_routine:
    CANNOT EVALUATE AS DATUM OR VARIABLE VALUE: formes12.4
[ERROR | 2024-MAR-26 13:48:39] tao_evaluate_expression:
    ERROR IN EXPRESSION: 1@orbit.y|model+5e-5*ran_gauss()-formes12.4
    CANNOT EVALUATE: formes12.4
[WARNING] tao_show_cmd:
    "Note: -format" has been changed to "#format" to avoid confusion with any negative signs.

Tao: show value 2@orbit.x|model + 5e-5*ran_gauss() -form es12.4
[ERROR | 2024-MAR-26 13:48:39] tao_param_value_routine:
    CANNOT EVALUATE AS DATUM OR VARIABLE VALUE: formes12.4
[ERROR | 2024-MAR-26 13:48:39] tao_evaluate_expression:
    ERROR IN EXPRESSION: 2@orbit.x|model+5e-5*ran_gauss()-formes12.4
    CANNOT EVALUATE: formes12.4
[WARNING] tao_show_cmd:
    "Note: -format" has been changed to "#format" to avoid confusion with any negative signs.

Tao: show value 2@orbit.y|model + 5e-5*ran_gauss() -form es12.4
[ERROR | 2024-MAR-26 13:48:39] tao_param_value_routine:
    CANNOT EVALUATE AS DATUM OR VARIABLE VALUE: formes12.4
[ERROR | 2024-MAR-26 13:48:39] tao_evaluate_expression:
    ERROR IN EXPRESSION: 2@orbit.y|model+5e-5*ran_gauss()-formes12.4
    CANNOT EVALUATE: formes12.4
[WARNING] tao_show_cmd:
    "Note: -format" has been changed to "#format" to avoid confusion with any negative signs.

**Comment by DavidSagan** [comment]
@sophiayang627 Problem was `-form` is now `#form` to avoid confusion with a minus sign in expressions. The tutorial files have been corrected.
