### ISSUE TITLE
Dynamic Aperture program crashing immediately

### ISSUE THREAD

**Issue by Saadi-mughal** [bmad-sim/bmad-ecosystem#876]
[dynamic aperture.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14767054/dynamic.aperture.zip)

Hi,
My dynamic aperture program is crashing as i execute it.  Master file is attached here.
Best Regards

**Comment by DavidSagan** [comment]
@Saadi-mughal Please attach ASCII files instead of PDF. Also please attach all relevant files. In this case the lattice file is missing. To attach files in this case, easiest is to use zip. Thanks.

**Comment by Saadi-mughal** [comment]
I have updated it. please have a look and let me know if needed any other file.

**Comment by DavidSagan** [comment]
I do not see any lattice file.

**Comment by Saadi-mughal** [comment]
sorry, now its there.

**Comment by DavidSagan** [comment]
@Saadi-mughal One issue is that n_angle is set to 0 in your input file. There was another issue that I fixed so please download the latest version.
