### ISSUE TITLE
using beam sigma matrix elements in expressions for defining data 

### ISSUE THREAD

**Issue by vsmorozov** [bmad-sim/bmad-ecosystem#884]
Fitting in Tao does not work if a constraint is specified by an expression containing sigma matrix elements. For example, if a datum in tao_d1_data is defined as
datum(1) = 'expression: 1@lat::sigma.25[0]/1@lat::sigma.55[0]'     ''  ''  ''  'target'    0.           1
fitting will run but will say that the constraint is independent of the optimization variables.

The reason is that sigma matrix calculation is disabled when calculating the data for fitting by default. It is enabled by setting the "u%calc%lat_sigma_for_data" flag to true in tao_init_data_mod.f90 and  tao_run_cmd.f90 if sigma matrix elements are used as constraints. However, if a sigma matrix element is used in an expression, the flag does not get enabled. 

My workaround was to force the flag to always be true in both files: "u%calc%lat_sigma_for_data = .true." There is probably a more elegant way to fix this.

Thanks,
Vasiliy

**Comment by DavidSagan** [comment]
@vsmorozov I did not directly test but the code I put in should fix this.
