### ISSUE TITLE
range constraint on expression datum

### ISSUE THREAD

**Issue by vsmorozov** [bmad-sim/bmad-ecosystem#885]
It looks like a range constraint is ignored if the datum is specified by an expression.  For example,
datum(1) = 'sigma.36'     ''  'beginning'  'end'  'abs_max'    3.e-8           1e8
works fine but if changed to
datum(1) = 'expression: sigma.36'     ''  'beginning'  'end'  'abs_max'    3.e-8           1e8
it seems to no longer affect the fit process. 

Thanks,
Vasiliy

**Comment by DavidSagan** [comment]
Fixed.
