### ISSUE TITLE
Setting b1_gradient on an sbend via an overlay fails silently

### ISSUE THREAD

**Issue by jsberg-bnl** [bmad-sim/bmad-ecosystem#892]
Here's an example:

[240329a.txt](https://github.com/bmad-sim/bmad-ecosystem/files/14805824/240329a.txt)

The overlay attempts to set `b1_gradient` on the `sbend` elements, and fails to do so leaving it at 0. This is expected since `field_master` is false, but there's no error message to inform the user of their screwup.

**Comment by DavidSagan** [comment]
Actually Bmad should do the right thing here and set k1/b1_gradient independent of field_master. This has been fixed.
