### ISSUE TITLE
Strange dependence of standing_wave cavity on num_steps, absolute_time_tracking, and digested file

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#893]
Using nightly from lnx201.

See /home/ehrlichm/for_dcs/88

The following problem only occurs if num_steps is greater than 1.

```
bash> tao -lat test2_a.lat -noplot
Tao> sho ele 1 -xfer_mat
```
Look at R11  (it is 0.9289254)
```
Tao> quit
bash> tao -lat test2_b.lat -noplot
Tao> sho ele 1 -xfer_mat
```
Look at R11 (it is 0.9952205)
```
Tao> quit
```
Edit test2_b.lat and comment out `parameter[absolute_time_tracking]=T`
```
bash> tao -lat test2_b.lat -noplot
Tao> sho ele 1 -xfer_mat
```
Look at R11 (it is 0.9952205)
```
Tao> quit
```
Delete the test2_b.lat digested file.
```
bash> tao -lat test2_b.lat -noplot
Tao> sho ele 1 -xfer_mat
```
Look at R11 (it is 0.9289254)

**Comment by DavidSagan** [comment]
Fixed. Bug was in reading of digested file "contaminated" bmad_com even when digested file was out of date.
