### ISSUE TITLE
BUG: tao_examples/space_charge

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#897]
Something has changed in the space charge calc to cause the following:

```
tao_examples/space_charge]$ tao
[MESSAGE | 2024-APR-01 17:27:57] tao_init:
    OpenMP active with number of threads: 10
[MESSAGE | 2024-APR-01 17:27:57] bmad_parser:
    Lattice parse time(min): 0.00
Using startup file: SC.tao

Tao: set space_charge_com n_bin = 40

Tao: set space_charge_com ds_track_step = 0.01

Tao: set ele * csr_method = off
[INFO] tao_set_elements_cmd:
    Note: 1 elements (out of 3) set.

Tao: set ele * space_charge_method = fft_3d
[INFO] tao_set_elements_cmd:
    Note: 1 elements (out of 3) set.

Tao: set bmad_com csr_and_space_charge_on = T

Tao: set global track_type = beam
[ERROR | 2024-APR-01 17:27:58] track1_bunch:
    WITH SPACE_CHARGE_METHOD SET TO CATHODE_FFT_3D, THE TRACKING_METHOD SHOULD BE SET TO
    TIME_RUNGE_KUTTA OR FIXED_STEP_TIME_RUNGE_KUTTA. FOR LATTICE ELEMENT: P1
    ALL PARTICLES OF THE BUNCH WILL BE MARKED AS LOST.
```

**Comment by DavidSagan** [comment]
@ndwang What do you think?

**Comment by ChristopherMayes** [comment]
@DavidSagan I suspect this message is bogus. See below that the element `space_charge_method= FFT_3D`
```
Tao> set ele * space_charge_method = fft_3d
[INFO] tao_set_elements_cmd:
    Note: 1 elements (out of 3) set.
[ERROR | 2024-APR-01 18:05:02] track1_bunch:
    WITH SPACE_CHARGE_METHOD SET TO CATHODE_FFT_3D, THE TRACKING_METHOD SHOULD BE SET TO
    TIME_RUNGE_KUTTA OR FIXED_STEP_TIME_RUNGE_KUTTA. FOR LATTICE ELEMENT: P1
    ALL PARTICLES OF THE BUNCH WILL BE MARKED AS LOST.
[WARNING] tao_graph_phase_space_setup:
    NO BEAM AT ELEMENT: END
    CANNOT DO PHASE_SPACE PLOTTING FOR CURVE: xphase.x.c1
[WARNING] tao_graph_phase_space_setup:
    NO BEAM AT ELEMENT: END
    CANNOT DO PHASE_SPACE PLOTTING FOR CURVE: zphase.z.c1

Tao> sho lat -at space_charge_method
# Values shown are for the Exit End of each Element:
# Index  name      key                      s       l  space_charge_method
      0  BEGINNING Beginning_Ele        0.000     ---
      1  P1        Pipe                 1.000   1.000  FFT_3D
      2  END       Marker               1.000   0.000
# Index  name      key                      s       l  space_charge_method
```

**Comment by ndwang** [comment]
The issue is the tracking method of P1 isn't set to time_runge_kutta or fixed_step_time_runge_kutta. This error message was changed recently to catch this, because it may lead to undefined behavior. I suppose the error message should change to include FFT_3D now, not just CATHODE_FFT_3D.

**Comment by ChristopherMayes** [comment]
Why do we require `time_runge_kutta` in this case? It should be up to the user to decide when this approximation is not valid.

**Comment by ndwang** [comment]
Because FFT_3D requires that tracking is done using t as the variable, so the tracking method must be time_runge_kutta. Otherwise, track1_bunch doesn't know what to do.

**Comment by ChristopherMayes** [comment]
But this worked previously, stepping in `s` with `space_charge_com ds_track_step = 0.01`. Forcing time tracking is a severe restriction that loses previous functionality.

**Comment by ndwang** [comment]
I don't think that is possible. Either it didn't have space charge or it used time_runge_kutta regardless...

**Comment by ChristopherMayes** [comment]
We have been using this with `s` tracking since 2018: https://epaper.kek.jp/ipac2018/papers/thpak085.pdf

**Comment by ndwang** [comment]
@DavidSagan can speak to what was implemented before I joined. What I wrote was strictly stepping in t.
You can also check the dispatch here to see the current logic in track1_bunch. If an element has `space_charge_method == fft_3d` and `tracking_method != time_runge_kutta .and. tracking_method != fixed_step_time_runge_kutta`, `track1_bunch_csr` is mistakenly called instead.
https://github.com/bmad-sim/bmad-ecosystem/blob/8654bd11f52400b6605566ecc172be94f246a84a/bmad/multiparticle/beam_mod.f90#L255C1-L281C8

**Comment by ChristopherMayes** [comment]
#864  introduced the problem. The CSR routines correctly handle space charge with `s` stepping in https://github.com/bmad-sim/bmad-ecosystem/blob/8654bd11f52400b6605566ecc172be94f246a84a/bmad/space_charge/csr_and_space_charge_mod.f90#L1393.

**Comment by ndwang** [comment]
I see. In that case you are right. Error-checking should not catch this and should revert back to it's previous state.

How tracking_method and space_charge_method combine is not well documented in the Bmad manual. Perhaps we should add something so users understand what they are going into, and which parameters are relevant for their tracking?

I introduced the changes because someone wanted to use track1_bunch_space_charge but in reality used track1_bunch_csr, and the tracking got stuck. I need to go back to it and see why it got stuck...

**Comment by ChristopherMayes** [comment]
All of this if because the CSR calc predates the 3D space charge calc. Part of the original CSR calc was the slice space charge kick, and 3D space charge became an option in there, even without the CSR. 

The logic should probably be simplified. However, in the meantime @ndwang could you make a PR that reverts this change?

**Comment by DavidSagan** [comment]
@ChristopherMayes @ndwang Please look at PR #919 . I have revamped beam_mod.f90 to do Ningdong's error check. I will assume everything is OK unless I hear otherwise.

**Comment by ChristopherMayes** [comment]
I think this work.
