### ISSUE TITLE
Foil element warns about invalid attribute: scatter

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#899]
Using a foil element with most default settings shoots a warning about an invalid attribute:

```
[MESSAGE | 2024-APR-02 21:51:03] bmad_parser:
    Lattice parse time(min): 0.01
[ERROR | 2024-APR-02 21:51:03] pointer_to_attribute:
    INVALID ATTRIBUTE: SCATTER
    FOR THIS ELEMENT: FOO
```

This is the example file: [foil.zip](https://github.com/bmad-sim/bmad-ecosystem/files/14845675/foil.zip)

**Comment by DavidSagan** [comment]
Fixed.
