### ISSUE TITLE
Can't find module file `plplot.mod`

### ISSUE THREAD

**Issue by evvaletov** [bmad-sim/bmad-ecosystem#906]
I am building `bmad` with `bmad-external-deps` on Oracle Linux 8, following the instructions from [https://wiki.classe.cornell.edu/ACC/ACL/OffsiteDoc](url).

The build process started using `dist_build_production` fails with the following messages:

```
/opt/bmad/sim_utils/plot/plplot_interface.f90:39:4:

 use plplot
    1
Fatal Error: Can't open module file ‘plplot.mod’ for reading at (1): No such file or directory
compilation terminated.
gmake[2]: *** [CMakeFiles/sim_utils.dir/build.make:1474: CMakeFiles/sim_utils.dir/plot/plplot_interface.f90.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[ 70%] Building Fortran object CMakeFiles/sim_utils.dir/io/lunget.f90.o
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/sim_utils.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

Error in distribution build.
```

I noticed that the file `plplot.mod` does not exist in the directory `$DIST_BASE_DIR/plplot/bindings/fortran`.

I was able to solve this issue by building `plplot` separately on my system and installing it. As a result, `plplot.mod` was installed into `/usr/local/lib/fortran/modules/plplot`. I then added the line

```
include_directories(/usr/local/lib/fortran/modules/plplot)
```

to `$DIST_BASE_DIR/sim_utils/CMakeLists.txt`. The build process was then completed without errors.

I suppose that a general fix of this issue may be relatively simple, such as revising a build flag in a CMake file.

**Comment by DavidSagan** [comment]
@evvaletov If you go to the plplot directory and in the Release and issue the "mk" command what do you get? plplot should be built when you build everything else.

**Comment by evvaletov** [comment]
Here is a text file with the output of `mk` ran in the `plplot` directory.
[plplot_build.txt](https://github.com/bmad-sim/bmad-ecosystem/files/14900604/plplot_build.txt)

**Comment by DavidSagan** [comment]
@evvaletov Looks like you need to do `mk cleaner` first and then `mk`. What do you get with this?

**Comment by evvaletov** [comment]
It built without errors:

`/opt/bmad/plplot Compile/Link time: 6.00sec`

I see the file `plplot.mod` exists now in `$DIST_BASE_DIR/plplot/production/bindings/fortran`.

**Comment by DavidSagan** [comment]
So the issue was that the plplot directory had been moved which confused cmake. When directories are moved, the intermediate files need to be removed before rebuilding.
