### ISSUE TITLE
Option to terminate beam tracking when too many particles are lost

### ISSUE THREAD

**Issue by ndwang** [bmad-sim/bmad-ecosystem#912]
It would be useful to have the option to terminate a beam tracking when certain number of particles are lost. Users can set a parameter such as dead particle limit and Bmad can check the total alive charge at the end of every element.

**Comment by DavidSagan** [comment]
To clarify: This is for Tao. Long_term_tracking already has this.

**Comment by DavidSagan** [comment]
Added: global%beam_dead_cutoff and updated documentation.
