### ISSUE TITLE
The aperture_by_tracking program is poorly documented and the example input files do not work

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#926]
Given its state, the aperture_by_tracking program is hereby slated for removal unless someone steps up to rectify the situation.

**Comment by DavidSagan** [comment]
Michael has graciously agreed to fix the test example and improve the documentation.

**Comment by MichaelEhrlichman** [comment]
Regarding this error:
```
lnx4200:~/linux_lib/bsim/aperture_by_tracking/test> aperture_by_tracking aperture_by_tracking.in 
 ERROR: no slaves found in cluster.  At least two nodes
 must be available to run this program.
```

I am inclined simply to write a better error message stating that the aperture_by_tracking requires mpi only.

Another possible solution would be to write a single core mode.

**Comment by DavidSagan** [comment]
@MichaelEhrlichman Do what you think best.

**Comment by MichaelEhrlichman** [comment]
Resolved with https://github.com/bmad-sim/bmad-ecosystem/pull/965
