### ISSUE TITLE
The srdt_lsq_soln program in bsim has no documentation and the example bombs

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/bmad-ecosystem#928]
This program is slated for removal unless documentation and example are fixed. 
The example does not work since `var_names` is defined as a character string in the program but in the example srdt_lsq_soln.in `var_names` is an array of strings.

@MichaelEhrlichman Do you want to work on this?

**Comment by MichaelEhrlichman** [comment]
bsim/srdt_lsq_soln would be easy enough to fix.

However, tao supports resonant driving term minimization through both the
normal.* and srdt.* data types.  With that, perhaps removing
bsim/srdt_lsq_soln is the right plan.

Note, if srdt_lsq_soln is removed from bsim, then I'll make a copy of it in
my personal repo at https://github.com/MichaelEhrlichman/mpe_bmad

**Comment by DavidSagan** [comment]
@MichaelEhrlichman OK I will remove it.
