### ISSUE TITLE
Tao runtime error on Brew-installed distro

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#943]
If you open the following lattice file:  
[example.bmad.zip](https://github.com/bmad-sim/bmad-ecosystem/files/15194853/example.bmad.zip)

If you use an element attribute to set the value of an _overlay_ attribute, Tao will crash. For example:

```
show val ele::y_qmain_ps[i]|design
set ele y_qmain_ps i = ele::y_qmain_ps[i]|design
```

This will crash Tao on the Brew install, but not the ACC Linux install. 
I have not been able to reproduce this bug by making a simpler lattice with an overlay.

**Comment by DavidSagan** [comment]
I cannot reproduce this with Ifort GCC and with Macports on my Mac. There is nothing I can do to help.
