### ISSUE TITLE
`show beam` missing items in Tao

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#944]
The Python command has items that are not seen in the regular `show beam` command in Tao:

`'full_6d_coupling_calc', 'ix_turn', 't_offset', 'use_t_coords', 'use_z_as_t'`

https://github.com/bmad-sim/bmad-ecosystem/blob/3b8cf0c34392822c77a80d0c19f3ab08c49b1bea/tao/code/tao_python_cmd.f90#L362

**Comment by DavidSagan** [comment]
Fixed.
