### ISSUE TITLE
written lattice does not equal lattice at time of writing

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#954]
with attached
`tao -lat esr-rad.bmad -init tao-errors.bmad`
```
cut
veto data cbar
run lm
run lm
run lm
cut
run lm
run lm
run lm
write bmad -form one_file out.bmad
```

`out.bmad` will be different from the lattice at the time of `write`

**Comment by mattsignorelli** [comment]
[Archive.zip](https://github.com/bmad-sim/bmad-ecosystem/files/15225618/Archive.zip)

**Comment by DavidSagan** [comment]
@mattsignorelli How much different? A tiny bit or a lot?

**Comment by mattsignorelli** [comment]
It’s a significant amount On May 6, 2024, at 6:59 PM, David Sagan ***@***.***> wrote:﻿
@mattsignorelli How much different? A tiny bit or a lot?

**Comment by mattsignorelli** [comment]
@DavidSagan this may have been related to the cut bug - I'm not seeing it anymore with the latest
