### ISSUE TITLE
cut incorrectly gives NON-POSITIVE BETA DETECTED AT ELEMENT: BEGINNING 

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#955]
with attached lattice esr-rad.bmad, call `cut`. it will error. Then set the geometry to open in the lattice file, it will work.
[Archive.zip](https://github.com/bmad-sim/bmad-ecosystem/files/15226531/Archive.zip)

**Comment by DavidSagan** [comment]
This will be fixed on the next PR.

**Comment by mattsignorelli** [comment]
@DavidSagan I am still seeing this bug with the attached
[Archive 2.zip](https://github.com/bmad-sim/bmad-ecosystem/files/15235949/Archive.2.zip)
