### ISSUE TITLE
optimize orbit when particle lost initially

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#956]
here's some example files (call tao-orbit.init)
[Archive.zip](https://github.com/bmad-sim/bmad-ecosystem/files/15227612/Archive.zip)

**Comment by DavidSagan** [comment]
I'm guessing that the radiation damping calculation is causing problems. I am investigating.

**Comment by DavidSagan** [comment]
@mattsignorelli My guess was wrong. The solution is to set bmad_com%max_aperture_limit = 1 (Or you can set individual element apertures). The problem looks to be that having the large (100 meters) default aperture limit is problematic for the optimizer.

**Comment by mattsignorelli** [comment]
@DavidSagan thank you! This is working very nicely now, using max_aperture_limit=0.100 meters

**Comment by mattsignorelli** [comment]
Would it be reasonable to set the default for max_aperture_limit to say 0.1 ? Then if the particle is "lost" a descriptive warning is printed saying how max_aperture_limit could be increased if that is desired

**Comment by DavidSagan** [comment]
The purpose (at least originally) of max_aperture_limit is to prevent numerical overflow in cases where there is no aperture set. You don't want the default max_aperture_limit to override element apertures. And I am loth to add print statements. I am putting a paragraph in the Tao manual in the documentation on unstable.orbit about this.
