### ISSUE TITLE
Tao's spin resonance strength calculation disagrees with Sprint

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad-ecosystem#964]
Attached is a toy lattice for the AGS and a plot of the horizontal resonance strengths as evaluated on resonant energies from Tao.

Similarly, Vincent extracted the horizontal resonance strengths using SPRINT, and we have disagreement:

[spin_res_a_str_tao_vs_sprint.zip](https://github.com/bmad-sim/bmad-ecosystem/files/15328074/spin_res_a_str_tao_vs_sprint.zip)

**Comment by eiad-hamwi** [comment]
@mattsignorelli

**Comment by eiad-hamwi** [comment]
The spin tunes that Tao spits out do not reflect the lower right-hand corner of the 8x8 spin-orbit transport matrix. 
In particular, if we flip the N0-axis of the frame, the G-matrix is visibly changed (some new minus signs), but the spin tune remains the same whereas it should also be changing sign.

The green points are the values of spin tune calculated by taking arctan2 of the lower-right components of the 8x8 spin-orbit transfer matrix. The purple points are the spin tune values that are outputted and seem to be used in Tao's resonance analysis. 
 
One potential explanation behind this disparity is that it results from the imperfection resonances due to the addition of a partial snake. 
These should create a discontinuity at integer values of Ggamma in both the spin tune and the choice of n0, or neither of them. In Desmond's conventions we usually choose to fix the n0 axis to the upper hemisphere, and make the spin tune jump explicit (as in the purple line). 
However, in Tao it appears that the n0 is smooth, while the spin tune seems to still have the spin tune jump:
 
I've attached the lattice and plots below.
[toy_ags_resonances.zip](https://github.com/user-attachments/files/15997733/toy_ags_resonances.zip)

**Comment by eiad-hamwi** [comment]
Furthermore, by performing the correct analysis on the G-matrix results in choosing all the correct resonance strengths, whereas Tao chooses only half the correct choices of (sum vs difference) resonance strength in this lattice.

**Comment by DavidSagan** [comment]
@eiad-hamwi For the two lattices in the zip file can you show your analysis and which is off?

**Comment by eiad-hamwi** [comment]
Yes, I will write up and upload the analysis by end of day today.

Eiad

**Comment by eiad-hamwi** [comment]
@DavidSagan I've attached a Julia-based Jupyter notebook containing the analysis with some comments to guide the eyes. 
[G-matrix_analysis.zip](https://github.com/user-attachments/files/16036279/G-matrix_analysis.zip)

**Comment by DavidSagan** [comment]
I have put in a fix.
