### ISSUE TITLE
Make tao phase_space plots heed curve%component

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#966]
It appears that phase space plots always use the model lattice, regardless of the setting of curve%component.

Furthermore, in tao_graph_setup_mod.f90, it looks as if the 'twiss'  branch for phase_space plots never sets ele.  The ele that ends up being used it whatever left at the end of an upstream loop that sets graph title_suffix.

At the least, the 'twiss' branch should be explicitly setting ele.  As a feature request, it would be nice if the twiss version of phase_space plots took heed of the curve%component setting.

**Comment by MichaelEhrlichman** [comment]
Adding this code to the `curve%data_source == 'twiss' ` branch of the `tao_graph_phase_space_setup`  subroutine seems to make phase_space plots heed the `curve%component` setting.
```
    ib = tao_branch_index(curve%ix_branch)
    select case (curve%component)
    case('model')
      ele => u%model%lat%branch(ib)%ele(curve%ix_ele_ref_track)
    case('design')
      ele => u%design%lat%branch(ib)%ele(curve%ix_ele_ref_track)
    case('base')
      ele => u%base%lat%branch(ib)%ele(curve%ix_ele_ref_track)
    end select
```

**Comment by DavidSagan** [comment]
Fixed.
