### ISSUE TITLE
Phase Space Coordinates in Dynamic Aperture Simulations

### ISSUE THREAD

**Issue by Saadi-mughal** [bmad-sim/bmad-ecosystem#969]
Hello,

I looked into dynamic_aperture.f90 file which writes output file for DA Simulations. I cannot find any way to write complete set of particle's coordinates on output file. can you please look into it?
Additionally, it is not showing (in output file) at which coordinate particle  lost.

[PTR.zip](https://github.com/bmad-sim/bmad-ecosystem/files/15404723/PTR.zip)

Thanks and Regards
Saad Siddique

**Comment by Saadi-mughal** [comment]
FurtherMore


If no ele_start = "", it works and start simulation from Beginning but if i give any element name like ele_start ="d"  (drift in my bmad file), it doesn't find any element. Further, if i give an marker name, it shows error.
please check it too.

**Comment by DavidSagan** [comment]
@Saadi-mughal I added the init orbit to the output. For the ele_start issue, when I use `ele_strart = "d"` I get the error message:
```
Multiple elements found with ele_start name: d
Will stop here.
```
which is a valid error message. So as far as I know, there are no problems with ele_start. If you are seeing a problem please report it with more detail.
