### ISSUE TITLE
`write bmad` line should have all-caps elements

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/bmad-ecosystem#974]
When I do write bmad, all of the elements named are changed to all caps in the lattice file, except in the "line". The element list in the line should also be all caps

**Comment by mattsignorelli** [comment]
I know I'm being picky but just to keep it all "pretty" and consistent :)

**Comment by DavidSagan** [comment]
@mattsignorelli How about changing the names to lower case?

**Comment by mattsignorelli** [comment]
My point is that it is inconsistent when using "write" - the element names in their definitions are always written full uppercase (even if I define it as lowercase in the initial lattice file), and in line element lists they are always lowercase.

**Comment by DavidSagan** [comment]
Yes I meant changing all element names to lower case.

**Comment by mattsignorelli** [comment]
If you do that, then Tao changes the element names to uppercase, except in the line element lists

**Comment by DavidSagan** [comment]
Tao does not change element names. It is Bmad that internally stores things as upper case.

**Comment by mattsignorelli** [comment]
`write bmad` prints element names in lines (line elements) as lowercase, this is inconsistent with what `write bmad` prints for the element names in their definitions (uppercase). I feel that `write bmad` should then print all uppercase everywhere instead

**Comment by DavidSagan** [comment]
Why not all lower case?

**Comment by mattsignorelli** [comment]
Here's an example. The output of write bmad is 
```
parameter[geometry] = Closed          

parameter[p0c]                      = 1.7846262612447E10
parameter[particle]                 = Electron

beginning[beta_a]    = 30.6276899615611
beginning[alpha_a]   = -2.4028257772189
beginning[eta_x]     = 0.586770946004804
beginning[etap_x]    = 0.0453552950370463
beginning[beta_b]    = 5.54894365028878
beginning[alpha_b]   = 0.476856799032399


!-------------------------------------------------------

QF: Quadrupole, L = 0.5, K1 = 0.312808574467162, DS_STEP = 0.05
D1: Drift, L = 0.609
B: SBend, L = 6.86016190935103, G = 3.46929776000413E-3, E1 = 0.0118999721726886, E2 = 0.0118999721726886
D2: Drift, L = 1.241
QD: Quadrupole, L = 0.5, K1 = -0.312643401293818, DS_STEP = 0.05

!-------------------------------------------------------
! Overlays, groups, rampers, and superimpose


!-------------------------------------------------------
! Lattice lines


FODOAF: line = ( qf, d1, b, d2, qd, d1, b, d2)

use, FODOAF
```

I am saying that `FODOAF: line = ( qf, d1, b, d2, qd, d1, b, d2)` should be `FODOAF: line = (QF, D1, B, D2, QD, D1, B, D2)`

**Comment by mattsignorelli** [comment]
For consistency

**Comment by DavidSagan** [comment]
If all the element names are lower case *everywhere* that is consistent.

**Comment by mattsignorelli** [comment]
But they're not lowercase ?

**Comment by DavidSagan** [comment]
Bmad does not care.

**Comment by mattsignorelli** [comment]
In the same lattice file you have `d1` in the line and `D1` defined above it, they should both be `D1`. I know Bmad doesn't care I am just being picky about consistency

**Comment by DavidSagan** [comment]
But if `d1` is used everywhere that is consistent.

**Comment by mattsignorelli** [comment]
You have `D1: Drift, L = 0.609` and then `d1` in the line, it is not the same everywhere

**Comment by DavidSagan** [comment]
Correct. I'm asking if `D1` is changed to `d1` would that satisfy you?

**Comment by mattsignorelli** [comment]
I would prefer all uppercase so 1-to-1 with Bmad internally

**Comment by DavidSagan** [comment]
OK I will make the line upper case...

**Comment by DavidSagan** [comment]
And will be in next PR
