### ISSUE TITLE
Inconsistent quadrupole b1_gradient when cavity phasing is adjusted.

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#982]
Test case at /home/ehrlichm/for_dcs/91/MWE_tao

I realize that field_master for Q1 should be set to true before setting its b1_gradient.  But the following sequence suggests there is a bug somewhere.

```
set global lattice_calc_on = F
set ele CAV1 phi0 = -0.1
set ele Q1 b1_gradient = 10.0
set global lattice_calc_on = T
```
```
Tao> sho value ele::q1[b1_gradient]
     8.1782336820807675E+00
```

**Comment by DavidSagan** [comment]
`field_master` does not have to be set before setting `b1_gradient`. The confusion here is that the reference energy is getting shifted at `Q1` when the last command is executed which is *after* the set to `b1_gradient`.

**Comment by DavidSagan** [comment]
The Bmad `cookbook` under development will have a section on this.
