### ISSUE TITLE
h5 files parsed with timeOffsets parsed inconsistently

### ISSUE THREAD

**Issue by MichaelEhrlichman** [bmad-sim/bmad-ecosystem#983]
Test case at /home/ehrlichm/for_dcs/92.

The two distributions beam_1.hdf5 and test_beam_1.hdf5 should have identical particles.  beam_1.hdf5 has a timeOffset, whereas in test_beam_1.hdf5 time has been replaced by time+timeOffset.

Tao parses beam_1 with a z centroid of -1.35e-5 and test_beam_1 with a z centroid of -9.44e0.

```
tao -lat simple.lat -noplot
set beam_init position_file=beam_1.hdf5 
set global track_type=beam
show beam end
```
Have a look at z Centroid.
```
set beam_init position_file=test_beam_1.hdf5 
sho beam end
```
Have a look at z Centroid

**Comment by DavidSagan** [comment]
@MichaelEhrlichman I'm confused. There needs to be more details here.

**Comment by ChristopherMayes** [comment]
I see the problem as well. Using `bmad-doc/tao_examples/optics_matching`, I made two files at element `B1` using `write beam - at B1 B1.h5`:
- `B1.h5` is the file written by Tao
- `B1_zerotimeOffset` is a file I manipulated by summing `time + timeOffset`, storing in `time`, and zeroing out `timeOffset` (see code below)

With the first file:
```
Tao> set beam_init position_file = B1.h5
Tao> set beam track_start = B1
Tao> set global track_type=beam;set global track_type=single
Tao> set global track_type=beam
Tao> set global track_type=single
Tao> sho beam B1
  Centroid:     -1.15797402E-06 -1.84789667E-07  1.34218948E-06  2.43812853E-06 -3.46076658E-07  2.47459219E-21  4.00800657E-09
```

However, using the second file, we see a huge z:
```
Tao> set beam_init position_file = B1.h5
...
  Centroid:     -1.15797402E-06 -1.84789667E-07  1.34218948E-06  2.43812853E-06 -1.20000003E+00  2.47459219E-21  4.00800657E-09
```
This is the same regardless of absolute_time_tracking. So, it seems that Bmad is relying on timeOffset, which it shouldn't.


This shows that the total `time + timeOffset` is the same in both files
```python
from h5py import File
h1 = File('B1.h5')
h2 = File('B1_zerotimeOffset.h5')

t1 = h1['data/00001/particles/positron/time'][:] + h1['data/00001/particles/positron/timeOffset'][:]
t2 = h2['data/00001/particles/positron/time'][:] + h2['data/00001/particles/positron/timeOffset'][:]

all(t1 - t2 == 0)
```

Manipulation code:
```python
with File('B1_zerotimeOffset.h5', 'a') as h5:
    time = h5['data/00001/particles/positron/time'][:]
    timeOffset = h5['data/00001/particles/positron/timeOffset'][:]
    print(set(timeOffset))
    
    h5['data/00001/particles/positron/time'][:] = time + timeOffset
    h5['data/00001/particles/positron/timeOffset'][:] = 0
    print(set(timeOffset))
```

[B1_files.zip](https://github.com/user-attachments/files/15523185/B1_files.zip)

**Comment by DavidSagan** [comment]
See the `HDF5` chapter in the Bmad manual. `time` gives phase space `z` / c*beta and ` time + timeOffset` the time. So what you are doing does shift phase space `z`.

**Comment by ChristopherMayes** [comment]
But @DavidSagan we want to use the absolute time to place the particles. Is that not possible?

**Comment by DavidSagan** [comment]
There is some confusion here. Absolute time tracking vs relative time does not shift a particle's phase space. Only how RF phases are calculated. Do you want to zoom?

**Comment by ChristopherMayes** [comment]
Yes let's zoom.

**Comment by ChristopherMayes** [comment]
Okay, I see. In both cases the particle time = `4.00800657E-09`. This is what's used when `absolute_time_tracking= T`, which is what I usually do, and in that case `%vec(5)` is irrelevant. 

@MichaelEhrlichman check your example for `absolute_time_tracking = T`

**Comment by MichaelEhrlichman** [comment]
I redid the test with the same two h5 files after setting `parameter[absolute_time_tracking]=T` in the lattice file, but there was no effect.  The 2nd file still give a z centroid of -9.449 meters.

**Comment by DavidSagan** [comment]
@MichaelEhrlichman This is expected. See the Bmad manual on how particle positions are stored with HDF5. Also conversion between bmad structures and HDF5 does not depend on the setting of `parameter[absolute_time_tracking]`
