### ISSUE TITLE
Tracking Particles Starting from a Region With Nonzero Orbit

### ISSUE THREAD

**Issue by electronsandstuff** [bmad-sim/bmad-ecosystem#984]
The beam's orbit appears to be wrong when tracking is started inside a bend with nonzero orbit and the values reported by `show orbit <ele>` are used for the particles' initial coordinates.

I am running into an issue where I need to track particles from a region where the beam has some orbit which then gets zeroed out by a patch element later on. I observe that when I start particles at the element I want with the orbit reported by tao that the orbit at the end is no longer correctly zeroed out. I was able to reproduce the issue in a minimum working example which I can share here.

In this example, the beam starts with an initial orbit, goes through a bend, then goes through a patch element to remove the orbit. 
![image](https://github.com/bmad-sim/bmad-ecosystem/assets/61094787/9b23edf9-6d4d-40f3-8e4b-303e9311f5d7)
I have a script which generates a beam using values of the orbit from tao and then tracks it through the lattice starting at the end of the bend element. I end up with the following orbits.
![image](https://github.com/bmad-sim/bmad-ecosystem/assets/61094787/6aa16a90-6452-422d-99a0-6e00b6cc462c)
![image](https://github.com/bmad-sim/bmad-ecosystem/assets/61094787/78c80f62-96ee-4048-87a6-8774846cfc33)
It seems that the `px` component of the orbit reported by tao is different from the one which is expected for beam tracking from that location.

The following zip file has my example lattice and a script to generate the beam, track it, and make the plots I show.
[bmad_orbit_debugging.zip](https://github.com/user-attachments/files/15517657/bmad_orbit_debugging.zip)

**Comment by DavidSagan** [comment]
@electronsandstuff I'm having a problem running the Python file. Simplest is for you to post the beam file and and the commands you use to track it without any Python.

**Comment by electronsandstuff** [comment]
Sure thing. The particles are attached below and the commands I ran were the following.
```
set bmad_com csr_and_space_charge_on = False
set bmad_com radiation_fluctuations_on = F
set beam_init track_start = BEN01
set beam_init track_end = end
set beam_init bunch_charge = 1e-09
set beam_init n_particle = 32
set beam_init always_reinit = T
set beam_init beam_saved_at = MARKER::*
set beam_init renorm_center = F
set beam_init use_t_coords = F
set beam_init use_z_as_t = F
set beam_init position_file = debug_particles.h5
set global track_type = beam
set global track_type = single
```

Github doesn't like the h5 file for some reason, so here it is zipped.
[debug_particles.h5.zip](https://github.com/user-attachments/files/15537293/debug_particles.h5.zip)

**Comment by DavidSagan** [comment]
@electronsandstuff When I look at the beam at the starting element BEND01 I see:
```
Tao> show beam 2
Bunch parameters at: BEN01 (2)
                        x               px               y              py                z               pz          time
  Centroid:      3.15341971E-04  1.00372402E-01  0.00000000E+00  0.00000000E+00 -1.00131847E+00  5.02468583E-03  3.34003890E-09
```

And the particle orbit is:
```
Tao> show lat -orb
# Values shown are for the Downstream End of each Element:
# Index  name      key                          s         orbit         orbit         orbit         orbit         orbit         orbit
#                                                             x            px             y            py             z            pz
      0  BEGINNING Beginning_Ele         0.000000 -1.000000E-01  1.000000E-01  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00
      1  PIP01     Pipe                  0.500000 -4.974811E-02  1.000000E-01  0.000000E+00  0.000000E+00 -2.518908E-03  0.000000E+00
      2  BEN01     SBend                 1.000000  3.153420E-04  1.003724E-01  0.000000E+00  0.000000E+00 -1.318472E-03  0.000000E+00
      3  PAT01     Patch                 1.000032 -1.369983E-17 -1.387779E-17  0.000000E+00  0.000000E+00 -1.286820E-03  0.000000E+00
      4  PIP02     Pipe                  2.000032 -2.757762E-17 -1.387779E-17  0.000000E+00  0.000000E+00 -1.286820E-03  0.000000E+00
      5  END       Marker                2.000032 -2.757762E-17 -1.387779E-17  0.000000E+00  0.000000E+00 -1.286820E-03  0.000000E+00
# Index  name      key                          s         orbit         orbit         orbit         orbit         orbit         orbit
#                                                             x            px             y            py             z            pz
# Values shown are for the Downstream End of each Element:
```

So the problem is that the beam pz is off. (also z is off but if you are using absolute time tracking this is not a problem).

**Comment by electronsandstuff** [comment]
Thanks! I discussed it with Chris and it ended up being a subtle issue with coordinate conventions in bmad/openPMD.
