### ISSUE TITLE
Tao: `sp h5dump end.h5` h5dump error: unable to open file "end.h5"

### ISSUE THREAD

**Issue by ChristopherMayes** [bmad-sim/bmad-ecosystem#987]
Trying to call `h5dump` within Tao that has written an h5 file causes an error. However, after quitting tao, the file can be dumped. 

Perhaps Tao is not closing the file?

In `bmad-doc/tao_examples/optics_matching`:

```
Tao: set global track_type=beam;set global track_type=single

Tao: write beam -at end end.h5
[INFO] tao_write_cmd:
    Written: end.h5

Tao: sp ls -ahl end.h5
-rw-r--r--  1 chrisonian  staff    54K Jun  1 12:59 end.h5

Tao: sp h5dump end.h5
h5dump error: unable to open file "end.h5"
```

**Comment by DavidSagan** [comment]
I tried to reproduce with ifort and gfortran but could not. Note: I am *not* using the PR #971 code.

**Comment by ChristopherMayes** [comment]
Oh sorry, this is using that code.

**Comment by DavidSagan** [comment]
Added group close to write beam code.
