### ISSUE TITLE
DA Simulations Irregular Output

### ISSUE THREAD

**Issue by Saadi-mughal** [bmad-sim/bmad-ecosystem#993]
Dear David Sagan,

With DA Simulations, change in number of turns in input file, doesn't change DA but changes particle's survival turns. Please have a look  at it.
Moreover, it is not showing in output file that at which coordinate (x/y) particle is lost.

Thanks
[temp.zip](https://github.com/user-attachments/files/15566509/temp.zip)

**Comment by DavidSagan** [comment]
The turn lost, when a particle is started near the dynamic aperture, is highly variable and is dependent upon how the program searches for the aperture boundary. So you cannot relate that to the maximum number of turns set in the input file. Also when you are doing 1-turn map tracking as in the example here, the partcle is always going to be lost at the beginning element. and the final coordinates are not helpful in understanding the dynamic aperture.
